### ISSUE TITLE
Version 2.0.29 is installing on python 3.8, but not working

### ISSUE THREAD

**Issue by Krukosz** [O365/python-o365#1004]
Hello,

Today new version has released, I use `O365` on my databricks cluster with python 3.8 ("legacy" scripts). 
New version uses `zoneinfo` package which requires Python 3.9, but cluster automatically installed new version of `O365` and returned a lot of errors (can't find module zoneinfo).

Could you add system version requirement in setup.py and information on Readme.md, that Python 3.9 is required?

**Comment by janscas** [comment]
Completely true. This should have come in the PR.

I’ll fix this asap

**Comment by janscas** [comment]
2.0.30 released

**Comment by rafmagns-skepa-dreag** [comment]
glad to see that 2.0.30 is fixed. however, 2.0.29 is still a problem because dependency resolvers will still find it. 2.0.29 needs to be yanked or updated in place on PyPI so that this issue doesn't keep coming up

**Comment by janscas** [comment]
Yep. yanked!
