### ISSUE TITLE
Upload session Error

### ISSUE THREAD

**Issue by thierryjmartin** [O365/python-o365#1027]
Good morning,

Since yesterday I have had a problem adding attachments to emails with upload sessions.

(I use auth_flow_type='credentials').

The Graph API returns an upload url like this:
https://outlook.office365.com/api/gv1.0/users('xxx')/AttachmentSessions('vvv')

which doesn't seem to work because I get this:
The audience claim value is invalid for current resource. Audience claim is 'https://outlook.office.com/api/', request url is 'https://outlook.office365.com' and resource type is 'Exchange'.

It worked perfectly until yesterday.
I don't understand how if it's a temporary problem from Microsoft or if I have things to specify in my request, or authorizations to add for my application.

Thanks in advance to anyone who has information on this problem.

**Comment by alejcas** [comment]
I don't know what's changing in the microsoft side.

Do you find out?

**Comment by thierryjmartin** [comment]
Yes thank you for your reply.
The problem lasted a few days and disappeared on its own.
