### ISSUE TITLE
2.0.33 : 'MSGraphProtocol' object has no attribute 'keyword_data_store'

### ISSUE THREAD

**Issue by stezz** [O365/python-o365#1053]
Testing the new release and I am getting this error:

```
    self.protocol = MSGraphProtocol()
                    ^^^^^^^^^^^^^^^^^^^
  File "development/python-o365/O365/connection.py", line 242, in __init__
    super().__init__(
  File "development/python-o365/O365/connection.py", line 114, in __init__
    self.timezone = timezone or get_localzone()
    ^^^^^^^^^^^^^
  File "development/python-o365/O365/connection.py", line 261, in timezone
    self.keyword_data_store['prefer_timezone_header'] = f'outlook.timezone="{get_windows_tz(self._timezone)}"'
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MSGraphProtocol' object has no attribute 'keyword_data_store'
```

the problem seems to be here:

```
class MSGraphProtocol(Protocol):
....
        self.keyword_data_store['prefer_timezone_header'] = f'outlook.timezone="{get_windows_tz(self._timezone)}"'
        self.max_top_value = 999  # Max $top parameter value

    @Protocol.timezone.setter
    def timezone(self, timezone: Union[str, ZoneInfo]):
        super()._update_timezone(timezone)
        >>> self.keyword_data_store['prefer_timezone_header'] = f'outlook.timezone="{get_windows_tz(self._timezone)}"' <<<
```

**Comment by stezz** [comment]
Maybe @Invincibear might have some insight into this?

**Comment by Invincibear** [comment]
I haven't touched that part of the codebase, but sounds like https://github.com/O365/python-o365/issues/1051 would fix it, eventually. I would look at the `Protocol` class to see if it defines `keyword_data_store`, it looks like the code is assigning that dict a value but was the dict ever created before adding an item to it?

**Comment by alejcas** [comment]
That is probably my fault… I have to look into it a bit. I’ve run some test and all worked, let me see. I’ll report back

**Comment by stezz** [comment]
Thanks @alejcas. No worries and no rush, I’ll hold back the update in the meantime ;)

**Comment by stezz** [comment]
Ps. Probably worth to mention that I’m not using the “user” account but the `auth_flow_type=‘credentials’`

**Comment by alejcas** [comment]
Fixed!

Can you try again? I'll release a new version if all works

**Comment by stezz** [comment]
Almost there:

`Python 3.12.1 (main, Dec  7 2023, 20:45:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.21.0 -- An enhanced Interactive Python. Type '?' for help.

   ...: from O365 import Account, MSGraphProtocol
   ...: protocol = MSGraphProtocol(api_version="beta")
Europe/Helsinki
<class 'pytz_deprecation_shim._impl._PytzShimTimezone'>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[1], line 5
----> 5 protocol = MSGraphProtocol(api_version="beta")  # MSGraphProtocol defaults to v1.0 api version

File ~/development/python-o365/O365/connection.py:249, in MSGraphProtocol.__init__(self, api_version, default_resource, **kwargs)
    238 def __init__(self, api_version="v1.0", default_resource=None, **kwargs):
    239     """Create a new Microsoft Graph protocol object
    240
    241     _protocol_url = 'https://graph.microsoft.com/'
   (...)
    247      nothing explicitly specified during the requests
    248     """
--> 249     super().__init__(
    250         protocol_url=self._protocol_url,
    251         api_version=api_version,
    252         default_resource=default_resource,
    253         casing_function=camelcase,
    254         protocol_scope_prefix=self._oauth_scope_prefix,
    255         **kwargs
    256     )
    258     self.keyword_data_store['message_type'] = 'microsoft.graph.message'
    259     self.keyword_data_store['event_message_type'] = 'microsoft.graph.eventMessage'

File ~/development/python-o365/O365/connection.py:114, in Protocol.__init__(self, protocol_url, api_version, default_resource, casing_function, protocol_scope_prefix, timezone, **kwargs)
    112     timezone = dt.timezone(timezone)
    113 try:
--> 114     self.timezone = timezone or get_localzone()
    115 except ZoneInfoNotFoundError as e:
    116     log.debug('Timezone not provided and the local timezone could not be found. Default to UTC.')

File ~/development/python-o365/O365/connection.py:267, in MSGraphProtocol.timezone(self, timezone)
    265 @Protocol.timezone.setter
    266 def timezone(self, timezone: Union[str, ZoneInfo]):
--> 267     super()._update_timezone(timezone)
    268     self.keyword_data_store['prefer_timezone_header'] = f'outlook.timezone="{get_windows_tz(self._timezone)}"'

File ~/development/python-o365/O365/connection.py:152, in Protocol._update_timezone(self, timezone)
    150 else:
    151     if not isinstance(timezone, ZoneInfo):
--> 152         raise ValueError(f'The timezone parameter must be either a string or a valid ZoneInfo instance.')
    153 self._timezone = timezone

ValueError: The timezone parameter must be either a string or a valid ZoneInfo instance.`

python-o365 is using `tzlocal` methods here

```
        try:
            self.timezone = timezone or get_localzone()
```
which is using the (now deprecated) `pytz` which returns a `<class 'pytz_deprecation_shim._impl._PytzShimTimezone'>` while you are expecting either a `str` or a `ZoneInfo` class, neither of which is true in the case above.

You might want to take that into account here:

```
    def _update_timezone(self, timezone: Union[str, ZoneInfo]):
        """Sets the timezone. This is not done in the setter as you can't call super from a overriden setter """
        print(timezone)
        print(type(timezone))
        if isinstance(timezone, str):
            # convert string to ZoneInfo
            try:
                timezone = ZoneInfo(timezone)
            except ZoneInfoNotFoundError as e:
                log.error(f'Timezone {timezone} could not be found.')
                raise e
        else:
            if not isinstance(timezone, ZoneInfo):
                raise ValueError(f'The timezone parameter must be either a string or a valid ZoneInfo instance.')
        self._timezone = timezone
 ```
 
 But really inches away ;)

**Comment by stezz** [comment]
Ok if I you use `time.localtime().tm_zone` this is what happens later on:

```
File ~/development/python-o365/O365/drive.py:1609, in Drive._update_data(self, data)
   1607 local_tz = self.protocol.timezone
   1608 print(local_tz)
-> 1609 self.created = parse(created).astimezone(local_tz) if created else None
   1610 self.modified = parse(modified).astimezone(local_tz) if modified else None

TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
```

Any chance you can get away without using this `get_windows_tz` function if you use that tm_zone on Windows ?

**Comment by stezz** [comment]
Oh actually this works:

```
self._timezone: ZoneInfo = ZoneInfo(time.localtime().tm_zone)
```

And get_windows_tz complies with it:

```
from O365 import Account, MSGraphProtocol
protocol = MSGraphProtocol(api_version="beta")
from O365.utils import get_windows_tz
get_windows_tz(protocol.timezone)

'GTB Standard Time'
```
So that is your fix apparently ;)

**Comment by alejcas** [comment]
> So that is your fix apparently ;)

I don't see the fix...


> self._timezone: ZoneInfo = ZoneInfo(time.localtime().tm_zone)

Where and why are you using this?

In protocol class we do:

```python
self._timezone: ZoneInfo = get_localzone()
```

get_localzone() from tzlocal already returns a `ZoneInfo` instance.

We don't use the time module.
Maybe you are referring to your own code.

Guess it's all working as it is.

Thanks

**Comment by stezz** [comment]
@alejcas apologies for lack of clarity. 

`tzlocal.get_localzone` is still using `pytz` under the hood: 

```
import pytz_deprecation_shim as pds
...
def get_localzone():
    """Returns the zoneinfo-based tzinfo object that matches the Windows-configured timezone."""

    global _cache_tz
    if _cache_tz is None:
        _cache_tz = pds.timezone(get_localzone_name())

    if not utils._tz_name_from_env():
        # If the timezone does NOT come from a TZ environment variable,
        # verify that it's correct. If it's from the environment,
        # we accept it, this is so you can run tests with different timezones.
        utils.assert_tz_offset(_cache_tz)

    return _cache_tz
```

So you might have dropped `pytz` everywhere else in your code, but you are using it through `tzlocal.get_localzone`

The fix is in the `connection.patch` patchfile attached to [this comment](https://github.com/O365/python-o365/issues/1053#issuecomment-1970833698)

**Comment by alejcas** [comment]
tzlocal dropped pytz completely.

I think you are using an old version

We now enforce tzlocal >=5.0

https://github.com/regebro/tzlocal?tab=readme-ov-file#api-change

**Comment by stezz** [comment]
Ah I see! As I am testing from git, I didn't update the deps.

Let me test again

**Comment by stezz** [comment]
Awesome! 

Tested with 

```
  • Updating tzdata (2023.4 -> 2024.1)
  • Updating tzlocal (5.0 -> 5.2)
```

And it all works like a charm. Thanks ;)

**Comment by alejcas** [comment]
ok, closing this and will release next version soon
