### ISSUE TITLE
Message.forward() incorrect error handling

### ISSUE THREAD

**Issue by pungys97** [O365/python-o365#1070]
I am trying to forward message and am getting the following error when calling it. In the screenshot you can see I am calling the `.forward()` method on Message object a I get the error `.get() not a method on str`.

<img width="1042" alt="Screenshot 2024-05-07 at 10 04 09 AM" src="https://github.com/O365/python-o365/assets/128874891/fd3c7367-26a7-4102-87d6-c5790316fd6b">

**Comment by RogerSelwyn** [comment]
Please just copy and paste the whole error using the <> in the GitHub toolbar, don't do a screen shot.

**Comment by alejcas** [comment]
What version are you using. 

I think this was fixed.
Last version is 2.0.34

**Comment by pungys97** [comment]
We are using 2.0.27

**Comment by alejcas** [comment]
well then upgrade
