### ISSUE TITLE
Question about the refresh process of a token

### ISSUE THREAD

**Issue by Bakura01** [O365/python-o365#1096]
Hello,

I have a question about the refresh process of the refresh token. I’ve already implemented connection.refresh_token() in my program. However, I’m unsure whether it automatically refreshes the token before the 90-day expiration period. If it doesn’t, can I manually call a function to handle this, or do I need to write one myself?

**Comment by alejcas** [comment]
The token is refreshed automatically every hour using the “refresh token”. Every token refresh will request a new “refresh token” that will last for 90 days. So as long as you connect once in the 90 day period you will refresh the “refresh token” for another 90 days.

So, in order for you to never have to reconnect again just connect once every 89 days.

**Comment by Bakura01** [comment]
Ok thank you!
