### ISSUE TITLE
Return limitation shared items 

### ISSUE THREAD

**Issue by SaadAmien20** [O365/python-o365#1098]
I was Using the library and It was working fine, but I faced an issue because of that all of files shared in teams and the library list only 500 item, but the actual folders I need, I can't get it.
I want if I am able to get only shared folders in OneDrive, not all thing shared in Microsoft teams, SharePoint 
or get all shared items and after that I can condition on what folder I need exactly.
I use ` my_drive = storage.get_default_drive('OneDrive')` 

So how to  solve this issue?

Thanks

**Comment by alejcas** [comment]
We use MS Graph under the hood. If it's possible to do what you want there it should be possible to do it in O365.

Can you check MS Graph to see if this is possible?
