### ISSUE TITLE
How do you mark an email as read

### ISSUE THREAD

**Issue by HeadJar** [O365/python-o365#112]
I want to get all the unread emails in my inbox then I want to set them as read, how do I do that?

**Comment by HeadJar** [comment]
Nevermind I got it

**Comment by rasjani** [comment]
@HeadJar  How did you actually archive this ? I tried to read the code but didn't find any clues. Actual code has tracker and setting is_read for message marks the message as read and informs the tracker what property has changed but i havent really found a way how to sync this status back into server ...

**Comment by rasjani** [comment]
Doesnt seem to work (for me atleast):

`(venv) jani.mikkonen@siilim180809 ~/src/work/robotframework-rfo365 (master *)$ pip freeze|grep O365
O365==1.0.0
`
So, i do have the latest installed.

I then have a code like this:

`    @keyword
    def fetch_attachment_from_unread_emails(self):
        for message in self.inbox.get_messages(download_attachments=True):
            print(message.is_read)
            if message.has_attachments:
                for attachment in message.attachments:
                    attachment.save(custom_name=attachment.name)
                    print(message.object_id)
                    message.is_read = True`

So, im just essentially trying to mark the all the emails i've downloaded attachments from as read, which works but is_read is not synced to cloud so everytime i run the same piece of code,  same object_id gets printed out.

**Comment by janscas** [comment]
First of all, message attachments are not downloaded by default. To iterate over attachments you first need to download them.

do:
```
if message.has_attachments:
    message.attachments.download_attachments()
    for attachment in message.attachments:
```

Second, ... my fault. Its not message.is_read = True. It's:

`message.mark_as_read()`

**Comment by rasjani** [comment]
Thank oyu @janscas - works, dunno why i missed `mark_as_read`.

About attachment downloads, as unrelated but it did work just fine, maybe due to download_attachments=True given to get_messages() ? :D anyway as said, no issues with it.

**Comment by janscas** [comment]
> About attachment downloads, as unrelated but it did work just fine, maybe due to download_attachments=True given to get_messages()

Oh! yes! I didn't see that. That works also so you don't need the call to message.attachments.download_attachments().
