### ISSUE TITLE
filter email by domain?

### ISSUE THREAD

**Issue by ajwillo** [O365/python-o365#113]
Hi,

is it possible to get email by sender domain?

for example
```
    i = Inbox((credentials.username, credentials.password),getNow=False)
    # filter sample (IsRead eq false) and (Subject eq 'who')
    i.setFilter("(Sender contains '@domain.com')")
```

Thanks

**Comment by Narcolapser** [comment]
No, unfortunately "contains" is only available for search and not filters: https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/complex-types-for-mail-contacts-calendar#Search

However fluent inbox supports search at this time. You should be able to use that to accomplish what you are trying to do.

**Comment by roycem90** [comment]
closing this as this feature is available on 'FluentInbox'
