### ISSUE TITLE
Import to Odoo

### ISSUE THREAD

**Issue by doanhuybinh90** [O365/python-o365#115]
Hi all,

Please help me how can use it in odoo V11 ?

Thanks !

**Comment by Narcolapser** [comment]
Sorry, I am unfamiliar with Odoo. I'll try to help you how I can. I asked their website and they pointed me towards [this](https://www.odoo.com/forum/help-1/question/how-can-i-execute-a-sql-statement-on-module-update-and-installation-6131) post suggesting that running arbitrary python is possible. I googled a little and found [this tutorial](https://www.odoo.yenthevg.com/). But your best bet isn't seeking help here. You should seek help on the Odoo forums.
