### ISSUE TITLE
Can't create calendar meetings. Getting error while setting subject for meeting.

### ISSUE THREAD

**Issue by dannybritto96** [O365/python-o365#116]
Replicated the steps in README.md
and got to this.

Using Python 3 on Mac OS.

>> e.setSubject('Sample')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/O365/event.py", line 226, in setSubject
    self.json['Subject'] = val
TypeError: 'tuple' object does not support item assignment

**Comment by dannybritto96** [comment]
Getting the same for setStart and setEnd functions as well.

>>> e.setStart(time.gmtime(time.time()+3600))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/O365/event.py", line 255, in setStart
    self.json['Start'] = time.strftime(self.time_string,val)
TypeError: 'tuple' object does not support item assignment

**Comment by Narcolapser** [comment]
The problem is in the ordering of the arguments (The tutorial IS wrong). Try doing this instead:

    e = Event(auth=yoauthtuple)

Sorry for the delay. Let me know if that works for you.

**Comment by dannybritto96** [comment]
Do we need to specify the calendar name in the cal argument?

**Comment by Narcolapser** [comment]
It is not needed at instantiation, this is done in case you are planning on putting it into multiple calendars for example. But you will need to specify the calendar before you can save it.
