### ISSUE TITLE
Fluent inbox getBody: No body content

### ISSUE THREAD

**Issue by SergeySerj** [O365/python-o365#117]
I'm getting the empty email body from the next fluent_message.py method:
```
	def getBody(self):
		'''get email body.'''
		try:
			return self.json['Body']['Content']
		except KeyError as e:
			log.debug("Fluent inbox getBody: No body content.")
			return ""
```
This [source code line](https://github.com/O365/python-o365/blob/master/O365/fluent_message.py#L192) `self.json['Body']['Content']` raise the KeyError as there is no ['Content'] key in json Body. I found there is ['content'] key in json Body instead.

So to fix the problem we can use
```
self.json['Body']['content']
```

Not sure why we can access the body via both `self.json['Body']` and `self.json['body']` ways, but can't access the content with `self.json['Body']['Content']` code.

**Comment by Narcolapser** [comment]
This issue has come up before. @roycem90 you mind looking into this? You know fluent better than I do.

**Comment by roycem90** [comment]
@Narcolapser which branch has the latest?

**Comment by roycem90** [comment]
@SergeySerj outlook api sends 'content' and most of them are only in camel case, we have added flexible dict to handle both 'Content', 'content' - (apparently we didn't handle well)

This issue is fixed now

**Comment by SergeySerj** [comment]
> @SergeySerj outlook api sends 'content' and most of them are only in camel case, we have added flexible dict to handle both 'Content', 'content' - (apparently we didn't handle well)
> 
> This issue is fixed now

Thanks guys!
