### ISSUE TITLE
OAuth2 Calendar support?

### ISSUE THREAD

**Issue by Nmasood** [O365/python-o365#120]
Is there calendar support for OAuth2? I'm not seeing a way to action the connection object to access calendars and getting 401 Unauthorized with connection.get_response()

**Comment by Narcolapser** [comment]
There is not currently, but there is hopes to provide said functionality in the future. One of the developers was working on it but he seems to have gotten busy with other projects. I'll give it a hack, but I can't guarantee any time line.

**Comment by roycem90** [comment]
@Nmasood while we build a Calendar class with OAuth2 support you can access it using connection.get_response(url, method='GET')

but before running getting the response u have to add the calendar related scopes to the connection, this can be done by assigning the scopes
Connection.scopes.append('https://graph.microsoft.com/Calendars.ReadWrite')

Also make sure u have enabled the Calendar readwrite permission for your registerd application

**Comment by roycem90** [comment]
Calendar support is now available on v1.0
