### ISSUE TITLE
Attached files have full filepath

### ISSUE THREAD

**Issue by diamondplated** [O365/python-o365#121]
Not sure if this is really an issue or if there is something i'm missing.  But when I attach a file by providing a full file path as "file".  The email that comes across has the full file path, instead of just the file name.

att = Attachment(file)
resp.attachments.append(att)

**Comment by diamondplated** [comment]
I can definitely see where it could be a security concern.  Yes, running on windows for this application.

**Comment by janscas** [comment]
Closing this issue as this is no longer an issue in the new api.
