### ISSUE TITLE
Date filter

### ISSUE THREAD

**Issue by vishaldesai** [O365/python-o365#122]
I'm using date filter but its not returning any messages.

i = Inbox(authenticiation, getNow=False)
i.setFilter("CreatedDateTime ge 2017-01-01")

inbox = FluentInbox()
for message in inbox.filter('ReceivedDateTime ge 2017-01-01').fetch(count=20):

Could not find a property named 'ReceivedDateTime' on type 'Microsoft.OutlookServices.Message'."

**Comment by vishaldesai** [comment]
Yes tried full format and its not working either.

**Comment by roycem90** [comment]
it is throwing error for Inbox or FluentInbox

i just tried with 'FluentInbox' and worked fine for me, can you try again once

**Comment by roycem90** [comment]
Can you try DateTimeReceived
instead of receivedDateTime

If you are not using oauth, the connection use v1. 0 of api and that parameter has been changed between 1.0 and 2.0

**Comment by vishaldesai** [comment]
Getting below error:

"Could not find a property named 'receivedDateTime' on type 'Microsoft.OutlookServices.Message"

python code
=========================================================
from O365 import Message
from O365 import Inbox
from bs4 import BeautifulSoup
from O365 import Connection, FluentInbox
Connection.login('email@email.com', 'password')
# # Create an inbox reference
inbox = FluentInbox()
#for message in inbox.filter('ReceivedDateTime ge 2018-01-01').fetch(count=20):
#for message in inbox.filter('ReceivedDateTime ge 2018-01-01T00:00:00Z').fetch(count=20):
for message in inbox.filter('receivedDateTime ge 2018-01-01').fetch(count=20):
#for message in inbox.fetch_first(count=2):
    # Just print the message subject
    print("================================================================")
    print(message.getSenderEmail())
    print(message.getSubject())
    rawtext = BeautifulSoup(message.getBody(), features="html.parser")
    text = rawtext.get_text() 
    print(text)

**Comment by vishaldesai** [comment]
As I was using username and password it was using v1.0. With v1.0 DateTimeReceived filter worked.

for message in inbox.filter('DateTimeReceived ge 2018-01-01').fetch(count=20)

Thanks roycem90 for pointing that out.

**Comment by roycem90** [comment]
@vishaldesai i recommedn you move to oauth authentication as the v1.0 basic authentication will be removed by microsoft on Nov 1, 2018
