### ISSUE TITLE
Change Mailbox when using fluent inbox?

### ISSUE THREAD

**Issue by diamondplated** [O365/python-o365#137]
I have a situation where I need to connect to a shared mailbox (doesn't have direct username/password).  The account I'm using has access, but I can't seem to find a method of logging into a different mailbox other than the default for the credentials?

**Comment by janscas** [comment]
Check the new api on the master branch (not published on pypi for the time being).

With the new api you can:

```python
account = Account(credentials, main_resource='your_shared_mailbox@example.com')

# working with this account instance will always use the shared mailbox provided you have access and 
# you request the required permissions with the oauth scope (for example: Mail.Send.Shared to send
# emails)
```

**Comment by diamondplated** [comment]
Is there a way to use the fluent inbox searching? For example, i'm using a line like this in my code:

inbox.from_folder(args.sfolder).search(str(CreateSearchFilter())).fetch(count=50)

Where i'm building a dynamic search filter to the criteria, and passing it through.

**Comment by janscas** [comment]
you can for example do this:

```python
maibox = account.mailbox()

folder = mailbox.get_folder(folder_name='folder_name')

my_query = folder.q('created_date_time').greater_equal(datetime(2018, 1, 1))  # chain as many queries as you want

for msg in folder.get_messages(limit=5000, query=my_query, batch=25)
    # the library will request 25 items each time up to 5000
    print(msg)
    # break as soon as you want...
```
It is not the same. The new version is still in early development so maybe in the future there will be something like the 'fluent search'.

**Comment by diamondplated** [comment]
@janscas  Got it, appreciate your guidance.

**Comment by roycem90** [comment]
lol looks like there are fans for my api :)

@janscas worth adding that fluent api/search on our todo project list

**Comment by janscas** [comment]
> @janscas worth adding that fluent api/search on our todo project list

I'm adding it
