### ISSUE TITLE
Remove strict versioning from requirements.txt

### ISSUE THREAD

**Issue by SergeySerj** [O365/python-o365#138]
Hi,

I noticed I'm unable to add this library to my project via pipenv due to 'incompatible versions in the resolved dependencies' pipenv error.
This happens because some library vendors sticks to strict versions in their requirements.txt file like this:
```
requests==2.20.0
requests-oauthlib==1.0.0
```
Therefore if one library needs `requests==2.20.0` while another library needs `requests==2.12.4` then pipenv would be unable to satisfy those conditions.

Could we have a more relaxed versions specification, like the next example?
```
requests>=2.12.4
requests-oauthlib>=1.0.0
```

**Comment by roycem90** [comment]
i have already updated them on the documentation branch, just wait for it be finished :)

**Comment by roycem90** [comment]
i just copied over from setup.py to requirements.txt (its on #140 )

**Comment by janscas** [comment]
Great!

**Comment by SergeySerj** [comment]
Thanks!
