### ISSUE TITLE
Cannot install pyo365 in anaconda

### ISSUE THREAD

**Issue by zimws** [O365/python-o365#139]
Hi, 

I tried to install pyo365 to anaconda by using pip install pyo365 but I got the following message:

Could not fetch URL https://pypi.org/simple/pyo365/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pyo365/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1051)'))) - skipping
  Could not find a version that satisfies the requirement pyo365 (from versions: )
No matching distribution found for pyo365

I searched online and updated the python version to 3.7.1 and pip to 18.1 but the error still occurred. Could anyone help me and advise what I could do?

Many thanks,
Wen

**Comment by Narcolapser** [comment]
Sorry for the confusion but pyo365 is a kind of fork of python-o365. As Roycem90 suggested try installing O365 not pyo365.

Note the difference between:
https://pypi.org/simple/pyo365/
and
https://pypi.org/simple/o365/

**Comment by zimws** [comment]
Thanks everyone the issue has now been resolved.
