### ISSUE TITLE
InvalidClientIdError on Refreshtoken

### ISSUE THREAD

**Issue by speckone** [O365/python-o365#143]
Hello,

I'm running the following code which works (sends my email), but I get an error about the refresh_token method. I've included some debug. Any advice? Thanks!
```
from O365 import Account, Connection, MSGraphProtocol, MSOffice365Protocol, Message

credentials = ('client_id', 'client_secret')
#protocol = MSGraphProtocol ()
protocol = MSOffice365Protocol ()

scopes = protocol.get_scopes_for('message_all')

account = Account(credentials=credentials, protocol=protocol)
#account.authenticate(scopes=scopes)
m = account.new_message()
m.to.add('bob@example')
#m.sender.address='noreply@example.com'
#m.sender.name='Nope'
m.subject = 'Testing! 2'
m.body = "George Best quote: I've stopped drinking, but only while I'm asleep."
m.send()
account.connection.refresh_token()
```

DEBUG:requests_oauthlib.oauth2_session:Adding auto refresh key word arguments {}.
DEBUG:requests_oauthlib.oauth2_session:Prepared refresh token request body grant_type=refresh_token
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://login.microsoftonline.com/common/oauth2/v2.0/token using method POST.
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'refresh_token'}
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'json': None, 'auth': ('client_id', 'client_secret'), 'timeout': None, 'verify': True, 'proxies': None}.
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /common/oauth2/v2.0/token HTTP/1.1" 400 440
DEBUG:requests_oauthlib.oauth2_session:Request to refresh token completed with status 400.
DEBUG:requests_oauthlib.oauth2_session:Response headers were {'Cache-Control': 'no-cache, no-store', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'x-ms-request-id': '0ff54191-29d7-40c2-b91b-36ac4f802e00', 'P3P': 'CP="DSP CUR OTPi IND OTRi ONL FIN"', 'Set-Cookie': 'fpc=AQQUAcODli1DllijTvAS1Y4; expires=Thu, 20-Dec-2018 21:17:07 GMT; path=/; secure; HttpOnly, x-ms-gateway-slice=011; path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly', 'Date': 'Tue, 20 Nov 2018 21:17:06 GMT', 'Content-Length': '440'} and content {"error":"invalid_request","error_description":"AADSTS900144: The request body must contain the following parameter: 'refresh_token'.\r\nTrace ID: 0ff54191-29d7-40c2-b91b-36ac4f802e00\r\nCorrelation ID: 71d318ef-248f-42c5-8acc-8fb857ff09cf\r\nTimestamp: 2018-11-20 21:17:07Z","error_codes":[900144],"timestamp":"2018-11-20 21:17:07Z","trace_id":"0ff54191-29d7-40c2-b91b-36ac4f802e00","correlation_id":"71d318ef-248f-42c5-8acc-8fb857ff09cf"}.
DEBUG:requests_oauthlib.oauth2_session:Invoking 0 token response hooks.

The request body must contain the following parameter: 'refresh_token'

**Comment by janscas** [comment]
Yes, you are not passing the 'basic' scope helper. This scope helper will add the 'offline_access' scope.
This scope is the one you need to acquire the refresh token (since refresh tokens are all about having offline access).

the 'basic' scope helper will provide additionally a User.Read scope. Make sure you configure your app at the ms app registration portal to grant this permissions to your app.

If you prefer not to give access to User.Read, then you can configure a Connection manually and then pass it over to the account instance.

**Comment by speckone** [comment]
That fixed it! Thanks!

**Comment by roycem90** [comment]
as basic is important, i think we should add it in code irrespective of what the user passes @janscas (i can make the changes if you agree)

**Comment by janscas** [comment]
@roycem90 we can’t add it by default because it will fail if the user didn’t add the permission User.Read and offline_access on the app registration portal.
