### ISSUE TITLE
ImportError: cannot import name 'Account' from 'pyo365'

### ISSUE THREAD

**Issue by YoloSwag4Jesus420** [O365/python-o365#144]
When I try to use the new library I get this error message:

ImportError: cannot import name 'Account' from 'pyo365'

I have tried importing Connections and that fails to import as well with the same error message, I also tried
from pyo365.account import Account and that doesn't work either.

running in windows 10 and also tried on server 2012. tried uninstalling pyo365 and reinstalling it and still get the same message. Is this a local issue or widespread. 

<s>I can still use the old import:
from O365 import Message
But I want to upgrade my code to the latest version of the library to save me having to do it in the future</s>

EDIT: Just realised the above is a separate library and is a fork of yours, still not sure why I can't import your library though

**Comment by janscas** [comment]
install this library using `pip install O365`

Then report back

**Comment by YoloSwag4Jesus420** [comment]
I already have that library installed on both systems I tried testing on

**Comment by janscas** [comment]
Then `from O365 import Account` should work. Is this working for you?

**Comment by YoloSwag4Jesus420** [comment]
tried uninstalling both, and reinstalled and upgraded both, still no luck. will try loading the library at home which is linux to see if I have any luck

Will also try on a clean vm next week

**Comment by YoloSwag4Jesus420** [comment]
So have uninstalled and reinstalled python and the relevant modules and is all working fine (think there was an issue were I had old versions of O365 installed) 

I saw you put that as of 1st Nov that basic auth would be depreciated, however I was still able to use basic auth as of last week before uninstalling python. do we have a definitive date as to when this will no longer work?

I only ask as my project requires it to be run unattended and I haven't figured out how I can achieve this using Oauth yet. (in fact im having issues with oauth as a whole, but that could be proxy issues)

**Comment by roycem90** [comment]
@YoloSwag4Jesus420 as per microsoft's announcement they said it will be Nov 1st, so we can't be sure of why it may be working or when it will suddenly stop

And as per your unattended question, once you setup OAuth it should be fine running unattended

**Comment by TerranceDeJesus** [comment]
I am currently having this issue where the O365 library does not contain "Account" class for me. Have uninstalled and re-installed O365 via pip, but not luck. I have also tried to upgrade the library but again no luck. Not sure what the issue is.

**Comment by Narcolapser** [comment]
@TerranceDeJesus if you keep having problems open an new issue explaining your problem and the results of this command:

    pip show O365

**Comment by Xkdash** [comment]
I had the same issue. Then I changed my file name. It was email.py. After changing that problem is gone!!!

**Comment by KriKu-coder** [comment]
It is too late but below command can help to extract the Message sub Module:

**from O365.message import Message**
