### ISSUE TITLE
Saving contacts fails

### ISSUE THREAD

**Issue by thomas-schulze-entwicklerschmiede** [O365/python-o365#147]
Hi there,

the saving of a newly created contact fails,
cf. the examples given in the (old) documentation:

```Python
new_contact = address_book.new_contact()
new_contact.save()
```

... gives the error:

> [...]/lib/python3.6/site-packages/O365/address_book.py", line 124, in to_api_data
    'emailAddresses': self.emails.to_api_data(),
AttributeError: 'Recipients' object has no attribute 'to_api_data'

There appears to be a bug present in this part of the code.

Also I saw, that the documentation for the address-book seems missing!?

Kind regards

**Comment by janscas** [comment]
Yes, this bug was fixed in 3615076a8b66431156db8b608753fd5e2750f14a but it is not included yet as a pypi release.

Expect a new release very soon.

**Comment by janscas** [comment]
There is version 1.0.1 on pypi with all the bug fixes up to date.

**Comment by thomas-schulze-entwicklerschmiede** [comment]
Thanks a lot!!

Mit freundlichen Grüßen


—
Ihr Ansprechpartner:
Dipl.-Ing.
Thomas Schulze
Chief Executive Officer
Tel.: +49 9391 6905
thomas.schulze@entwicklerschmiede.com<mailto:thomas.schulze@entwicklerschmiede.com>

Es unterstützt Sie
Die Entwicklerschmiede GmbH & Co. KG
Würzburger Strasse 5
97828 Marktheidenfeld

www.entwicklerschmiede.com
info@entwicklerschmiede.com

USt-IdNr.: DE305944872

CONFIDENTIALITY NOTICE
This email is for the use of the intended recipient only. It may contain information that is legally privileged or confidential.
If you are not the intended recipient, any disclosure, distribution or copying of this email is strictly prohibited and may be unlawful.
If received in error, please reply to the sender confirming this, then delete the email.
Der Inhalt dieser E-Mail ist ausschliesslich für den bezeichneten Adressaten bestimmt.
Wenn Sie nicht der vorgesehene Adressat dieser E-Mail oder dessen Vertreter sein sollten, so benachrichtigen Sie uns bitte und beachten Sie,
dass jede Form der Kenntnisnahme, Veröffentlichung, Vervielfältigung oder Weitergabe des Inhalts dieser E-Mail unzulässig ist.

Am 28.11.2018 um 11:03 schrieb Alejandro Casanovas <notifications@github.com<mailto:notifications@github.com>>:


There is version 1.0.1 on pypi with all the bug fixes up to date.
