### ISSUE TITLE
Saving contacts failes

### ISSUE THREAD

**Issue by thomas-schulze-entwicklerschmiede** [O365/python-o365#148]
Hi,

I tried a code-example, but unfortunately that failed: (version 1.01 from PyPi):

```Python
    new_contact = address_book.new_contact()
    new_contact.display_name = "George"
    new_contact.emails.add('george@best.com')
    new_contact.save()
```

gives the error:

> requests.exceptions.HTTPError: 405 Client Error: Method Not Allowed for url: https://graph.microsoft.com/v1.0/me/contacts/...

What am I doing wrong?

I also tried to save a contact into a contact-folder like this:
```Python
        contactbooks = address_book.get_folders()
        new_contact = contactbooks[0].new_contact()
        new_contact.display_name = "George"
        new_contact.emails.add('george@best.com')
        new_contact.save()
```

This gives another internal error:

> .../lib/python3.6/site-packages/O365/address_book.py", line 211, in save
    self._endpoints.get('child_contact').format(self.folder_id))
KeyError: 'id'

Any ideas?

Best regards and many thanks!

**Comment by janscas** [comment]
Fixed now. This change is not yet available on Pypi. Will be in the next release.

**Comment by janscas** [comment]
This is available now on pypi under version 1.0.2

**Comment by thomas-schulze-entwicklerschmiede** [comment]
Hi,

yes but now we get a bad request:

```Python
        contactbooks = address_book.get_folders()
        new_contact = contactbooks[0].new_contact()
        new_contact.display_name = "George"
        new_contact.emails.add('george@best.com')
        new_contact.save()
```

gives:

> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/contacts

Same error on the following usage:
```Python
        new_contact = address_book.new_contact()
        new_contact.display_name = "George"
        new_contact.emails.add('george@best.com')
        new_contact.save()
```

Any ideas?

**Comment by janscas** [comment]
Fixed now, It appears that the api needed the contact givenName all the time, even if it's not set.

Now it works.

**Comment by thomas-schulze-entwicklerschmiede** [comment]
Perfect - I tested it, now it runs as expected!
