### ISSUE TITLE
calendar search under MSGraph returns error 400

### ISSUE THREAD

**Issue by uriba107** [O365/python-o365#149]
I'm trying the very basic search a decribed in the README calender example, however, error 400 pops up on query execution.

the syntax stated in the docs is wrong, but I had corrected it.

Original (sort of):
``` q = self.calendar.new_query('start').ge(dt.datetime(2018, 5, 20)).chain('and').on_attribute('end').le(dt.datetime(2018, 5, 24))```

Corrected for current syntax:
``` q = self.calendar.new_query('start').greater_equal(dt.datetime(2018, 5, 20)).chain('and').on_attribute('end').less(dt.datetime(2018, 5, 24))```

I expect to get nothing in response, as the calendar has nothing at that date (which is arbitrary from the example), Obviously I started by trying dates which are relevant to the project. However, I switched to using the example, just in case I've done something wrong.

print(q) output:
```  
Filter: start/dateTime ge 2018-05-19T21:00:00+00:00 and end/dateTime lt 2018-05-23T21:00:00+00:00
Order: None
Select: None
```

error on the Exception:
```
400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/calendars/<TOKEN_WAS_HERE>/events?%24top=25&%24filter=start%2FdateTime+ge+2018-05-19T21%3A00%3A00%2B00%3A00+and+end%2FdateTime+lt+2018-05-23T21%3A00%3A00%2B00%3A00
```
please note that "normal" ```calendar.get_events()``` work, and I can add, modify and delete meetings in the calendar, I just can't filter... :-/
And just for completion, the init of the class contains all the auth stuff..
```
        self.account = Account(credentials=(FlightCalendar.k,FlightCalendar.s))
        self.schedule = self.account.schedule()
        self.calendar = self.schedule.get_calendar(calendar_name='test_calendar')
```

Thanks,
Uri

**Comment by janscas** [comment]
You are right, the readme is not updated. I'll change that.

The query you used is correct. And it should work... However I've just found that if you request for messages, then enclosing the date with single quotes works. If you don't enclose the date with single quotes it won't work. It's a bad request.

For example sending a $filter like `receivedDateTime ge '2018-10-28T23:00:00+00:00'` works.

On the other hand if you request for calendar events, then enclosing the date with single quotes won't work.
For example this won't work: `start/dateTime ge '2018-11-19T23:00:00+00:00'`
But this will: `start/dateTime ge 2018-11-19T23:00:00+00:00`

This seems very odd to me... I'll try to see if I can solve this.

**Comment by janscas** [comment]
I've just find out that:

receivedDateTime is of type DateTimeOffset, and that's why the quotes are needed. On the other hand start/dateTime is of type string.

@Narcolapser and @roycem90 I will commit a change that will fix this, but it's kind of a botched job what I did. Maybe you find out how to fix this in a more elegant way.

**Comment by janscas** [comment]
@uriba107 Your query should work now with the last commit

**Comment by janscas** [comment]
We've just roll out 1.02 on pypi as well.
