### ISSUE TITLE
App request new tokens

### ISSUE THREAD

**Issue by RobertoEsteve** [O365/python-o365#150]
Hello,
I test this package for send an email and it works but only 60 minutes I don't understand how to the app can automatically request new tokens to 90 dias and how to implement a periodic call to "Connection.refresh_token" before the 90 days have passed. The code is:

from pyo365 import Account
from pyo365 import oauth_authentication_flow

account = Account(credentials=(id, secret)
scopes=['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send']

url = account.connection.get_authorization_url(scopes)

result=input(url)
account.connection.request_token(result)

 and send email with:
from pyo365 import Account, oauth_authentication_flow

account = Account(credentials=(id, secret))
m.to.add(email)
m.subject = 'Testing'
m.body = "body"
m.send()

Error: TokenExpiredError()

**Comment by janscas** [comment]
For the automatic refresh token to work you have to grant the “offline_access” permission to the app and then pass it as another scope. Then it will work.

**Comment by RobertoEsteve** [comment]
Yes. it works. and I suppose the next code allows to work for more than 90 days without user interaction and without interacting with the API, right?. Thank you!

from pyo365 import Connection
credentials = (id, secret)
scopes = ['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send', 'offline_access']
con = Connection(credentials, scopes=scopes)
con.refresh_token

**Comment by janscas** [comment]
Copied from the readme:

The access token only lasts 60 minutes, but the app will automatically request new tokens through the refresh tokens, but note that a refresh token only lasts for 90 days. So you must use it before or you will need to request a new access token again (no new consent needed by the user, just a login).

If your application needs to work for more than 90 days without user interaction and without interacting with the API, then you must implement a periodic call to Connection.refresh_token before the 90 days have passed.

**Comment by saulcruz** [comment]
@RobertoEsteve so, did you find a solution , was your code above your solution?
