### ISSUE TITLE
#Newbie How to set up the repository locally and contribute?

### ISSUE THREAD

**Issue by AnoojNair** [O365/python-o365#154]
Hi Guys,

I am a newbie to python , i am looking forward to help out with SharePoint and Graph API. Just wanted to check if there any instructions on how to set up the repository locally and build the application. 

Thanks in advance.
Anooj.

**Comment by Narcolapser** [comment]
Hello AnoojNair. Glad to hear you are interested in helping. What you'll want to be looking for first is a guide to getting started with github, such as [this one](https://guides.github.com/activities/hello-world/). That should guide you through the process of getting the repository locally on your machine. After that the project builds in the standard python way, which is:

    python setup.py install

That will install the library locally on your machine. If you have any more questions feel free to ask them in this thread. Usually questions like the one you have asked here are better asked on a community forum like [r/learnprogramming](reddit.com/r/learnprogramming) or [r/learnpython](reddit.com/r/learnpython/). That being said it also looks like you got it working based off of #155. Glad to have you!
