### ISSUE TITLE
sharepoint-get_items not working

### ISSUE THREAD

**Issue by AnoojNair** [O365/python-o365#157]
Hi,

I am trying to get the items from a sharepoint list using the below code snippet.

`acc = Account(credentials)
sp = acc.sharepoint()
root = sp.get_root_site()
print(root.display_name)
print(root.get_lists()[0].get_items())`

and i get an Resource not found exception. Looks like it's a issue with the Resource Url(it's missing a / before lists)

**https://graph.microsoft.com/v1.0/sites/myappsdomain.sharepoint.com,f40a831f-cb44-4c3f-838c-56d37ed2ef57,a7e461a1-cb4c-43f9-9877-e92530dfe584lists/53ae8a11-e5f2-4a5b-b635-617b3a79cc4a/items**

**Comment by janscas** [comment]
Just as an advice, the sharepoint part is not finished yet.

Feel free to contribute
