### ISSUE TITLE
Unable to fetch auth token. Error: (mismatching_state) CSRF Warning! State not equal in request and response.

### ISSUE THREAD

**Issue by davres1** [O365/python-o365#160]
mport getpass
from O365 import MSOffice365Protocol,MSGraphProtocol,Account,oauth_authentication_flow
from requests_oauthlib import OAuth2Session
from pyo365 import Connection

# try the api version beta of the Microsoft Graph endpoint.
#protocol = MSGraphProtocol(api_version='beta')
#scopes = protocol.get_scopes_for('message all')
#protocol = MSGraphProtocol(api_version='beta')
credentials = ('c2e9f47a-b15c-4ea8-b36c-58e8391377e3', '<CLIENT_SECRET>')
scopes = ['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send']

con = Connection(credentials, scopes=scopes)

redirect_uri='https://outlook.office365.com/owa/'

url=con.get_authorization_url()
print (url)

#result_url = input('Paste the result url here...').strip()
#result = oauth_authentication_flow('c2e9f47a-b15c-4ea8-b36c-58e8391377e3', '<CLIENT_SECRET>' , scopes)
#result_url = input(url)
#print (result_url)
url1='https://outlook.office365.com/owa/?code=RESULTCODE'

con.request_token(url1)

result = oauth_authentication_flow('c2e9f47a-b15c-4ea8-b36c-58e8391377e3', '<CLIENT_SECRET>', scopes )

**Comment by roycem90** [comment]
please don't put your client secret information out 

Try once by clearing your cookies and re-authenticating

**Comment by mitliucak** [comment]
> please don't put your client secret information out
> 
> Try once by clearing your cookies and re-authenticating

I clear the cookies and authenticating , but the same error

**Comment by roycem90** [comment]
Can you try using the account instead of connection
https://o365.github.io/python-o365/latest/html/usage/account.html#authenticating-your-account

**Comment by roycem90** [comment]
add 'offline_access' to the list of scopes, if not refresh_token won't work (you may have to authenticate again as u will be changing the scopes)

**Comment by mitliucak** [comment]
> add 'offline_access' to the list of scopes, if not refresh_token won't work (you may have to authenticate again as u will be changing the scopes)

Thank you ,I add offline_access to the list : 
scopes = ['https://graph.microsoft.com/Mail.ReadWrite', 'https://graph.microsoft.com/Mail.Send',"offline_access"]
and change the "offline_access" to the delegated permissions 
but the error occur:

AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope https://graph.microsoft.com/offline_access https://graph.microsoft.com/Mail.Send https://graph.microsoft.com/Mail.ReadWrite is not valid. The resources must specify a known valid scope..

**Comment by janscas** [comment]
There's a little bit of confusion on when to use protocol defined 'scopes' or ['scope helpers'](https://github.com/O365/python-o365/blob/master/O365/connection.py#L33).

If you use the `account.authenticate` you will have to use [scope helpers](https://github.com/O365/python-o365/blob/master/O365/connection.py#L33) because the scopes will be prefixed with the chosen account protocol (MSGRAPH by default).

If you prefer to use protocol defined scopes (like 'https://graph.microsoft.com/Mail.ReadWrite') then you can not use the authentication methods and you should use the following Connection methods:

- `get_authorization_url`
- `request_token`

**Comment by mitliucak** [comment]
> try 'basic' instead of 'offline_access', this may be a minor bug (it should not have added the graph prefix to offline)

Great！Thanks a lot！ It works.

**Comment by derrix060** [comment]
@davres1 can you make sure that it works now? If so, please close the issue.

**Comment by davres1** [comment]
Pls close

Thanks
Sumit Davre

On Jan 11, 2019, at 11:01 PM, Mario Apra <notifications@github.com<mailto:notifications@github.com>> wrote:

CAUTION: This email originated from outside the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.



@davres1<https://github.com/davres1> can you make sure that it works now? If so, please close the issue.
