### ISSUE TITLE
Insufficient privileges to complete the operation.

### ISSUE THREAD

**Issue by Ooverandout** [O365/python-o365#163]
Hi,

I am trying to add the app to connect to O365 as suggested in the tutorial, however clicking CREATE on https://apps.dev.microsoft.com/portal/register-app leaves me with "Insufficient privileges to complete the operation." notification.

What should be done in this kind of situation?

**Comment by roycem90** [comment]
probably you do not have privileges for some of the permissions u added, what permissions did you give to the app?

**Comment by Ooverandout** [comment]
I did not set any permissions, as this page only lets me “Add App”. This is the first step from the link basically.
Is there some other place I should look into to get these permissions?

Adam Mrozik

Customer Integration Team
Schenker Technology Center (Warsaw) Sp. z o.o.
Ul. Żwirki i Wigury 16c,
02-092 Warszawa, Polska
www.dbschenker.pl<http://www.dbschenker.pl/>
Mobile: +48 665 650 976
[IPMA-PPEA-2018-zwycięzcy-Stopka-2]

**Comment by roycem90** [comment]
can you post screenshot on which page you are getting error?

**Comment by Ooverandout** [comment]
Hi,

Of course:
[cid:image001.png@01D4A791.2128B740]

Adam Mrozik

Customer Integration Team
Schenker Technology Center (Warsaw) Sp. z o.o.
Ul. Żwirki i Wigury 16c,
02-092 Warszawa, Polska
www.dbschenker.pl<http://www.dbschenker.pl/>
Mobile: +48 665 650 976
[IPMA-PPEA-2018-zwycięzcy-Stopka-2]

**Comment by roycem90** [comment]
i can't see any screenshot here, can you forward that to royce@outlook.in

**Comment by roycem90** [comment]
as this seems to be limited by the organization from creating apps, i am closing this issue
