### ISSUE TITLE
Getting email only newer than

### ISSUE THREAD

**Issue by jwhugheskp** [O365/python-o365#165]
I just updated from pyo365 to O365 and while reading the documentation I found the query section.  This is what I’m reading

`
query = mailbox.new_query()
query = query.on_attribute('subject').contains('george best').chain('or').startswith('quotes')
query = query.chain('and').on_attribute('created_date_time').greater(datetime(2018, 3, 21))
print(query)
`

I use this to try and only get mail after a date

`
account = Account(credentials = CREDENTIALS)
mailbox = account.mailbox()
inbox = mailbox.inbox_folder()
query = inbox.new_query()
my_query = query.on_attribute(‘created_date_time’).greater(datetime(2018, 12, 31))
print(my_query) 
`

I get a TypeError: ‘module’ object is not callable.  I was able to use a query in pyo365 using the above first three lines and this

`
query = inbox.new_query(‘is_read’).equals(False)
`

It is probably something obvious, but if so I don’t get it.  Also can you use datetime(Year, Monthy, Day, Hour, Minute, Second)?  If so is time on a 24 hour clock or AM/PM?

TIA,
Joe

**Comment by derrix060** [comment]
please use triple '`' to ensure your code formatted correctly.

Example:

\```python
your code here
\```

**Comment by derrix060** [comment]
Where `datetime` is defined?

If it's

```python
import datetime
...
datetime(2018, 12, 31)
```
you will have a problem because you are trying to call a module. If that's the case, change to

```python
import datetime
...
datetime.datetime(2018, 12, 31)
```

**Comment by jwhugheskp** [comment]
Hi Mario,

Thanks for the information.  I just used the code link in the form.  Also GIT has gone strange on me if I try to use it on a computer and not a tablet.  Strange formatting.

Regards,
Joe
--------
Joe Hughes
Cyber Risk Defense Senior Analyst

Kaiser Permanente
Technology Risk Office
Cyber Security, Data and Platform Support

360-731-3487 (mobile)
tro.kp.org<http://tro.kp.org/>
---------
kp.org/thrive<http://kp.org/thrive>
Service Now Group: TRO Splunk – TRO Splunk issues only
Service Now Group: Tripwire Reporting – Tripwire Report issues only
Upcoming PTO Days:

**Comment by jwhugheskp** [comment]
Hi Mario,

Thanks.  That resolved the problem.  I was looking in the wrong place.

Regards,
Joe
--------
Joe Hughes
Cyber Risk Defense Senior Analyst

Kaiser Permanente
Technology Risk Office
Cyber Security, Data and Platform Support

360-731-3487 (mobile)
tro.kp.org<http://tro.kp.org/>
---------
kp.org/thrive<http://kp.org/thrive>
Service Now Group: TRO Splunk – TRO Splunk issues only
Service Now Group: Tripwire Reporting – Tripwire Report issues only
Upcoming PTO Days:
