### ISSUE TITLE
Unable to save token to custom path

### ISSUE THREAD

**Issue by anish1106** [O365/python-o365#166]
Hi,
I am having trouble with saving token file to a custom file path. I also tried to save the token file in the current directory with a custom name. I get the same error for both: **"token_path must be a valid Path from pathlib".**
Per my understanding, under "_save_token" function in connections.py, the else part of following lines should be removed:
```
def _save_token(self, token, token_path=None):
        if not token_path:
            token_path = self.token_path or self._default_token_path
        else:
            if not isinstance(token_path, Path):
                raise ValueError('token_path must be a valid Path from pathlib')

       with token_path.open('w') as token_file:
            json.dump(token, token_file, indent=True)

        return True
```

Since the token file is not saved at this point in execution, this part of the code will always raise an error. 

I think this was copied from load_token or delete_token function, but missed out to be removed. 

In case I am doing something wrong, could you please guide me how to save the token to a custom path or a custom file name?
Thanks

**Comment by janscas** [comment]
As you see `_save_token` is an internal method, not meant to be used by the users of the library (as any method that begins with an underscore).

By now, you can't change the token path easily. You can only change the token file name (by passing `token_file_name='Your_token_file_name' to the `Connection` or `Account` class).

If you need to change the token path, you will have to:

a) When authenticating use the raw methods:  using the `Connection` `get_authorization_url` and `request_token` methods. 

b) When using the library: overwrite the `Connection.token_path` attribute or maybe subclass the Connection and change the implementation of the methods that use the `self.token_path` attribute.

**Maybe you can explain why this is important so we can think about how to include this in future versions**.

**Comment by anish1106** [comment]
> As you see `_save_token` is an internal method, not meant to be used by the users of the library (as any method that begins with an underscore).

I apologize. My explanation was incomplete. I should have included my code for better understanding. Here is the code that I am using:
```
#Get Office365 tokens
def get_token(credentials=o365_credentials,scopes=o365_scopes,tokenName='o365_token.txt'):
    connection = Connection(credentials=credentials, scopes=scopes)
    redirect_url = 'http://localhost:8080/office365_code'
    if not os.path.isfile(tokenName):
        connection = Connection(credentials=credentials, scopes=scopes)
        webserver.link = connection.get_authorization_url(redirect_uri=redirect_url)
        web_server = webserver.startServer()
        authorization_response = webserver.address
        
        token = connection.request_token(authorization_response,token_path=tokenName)
        
        connection.get_session()
    return True
```

webserver(.py) is based on http.server library that I am using for authorizing Office365 account using localhost.

> By now, you can't change the token path easily. You can only change the token file name (by passing token_file_name='Your_token_file_name' to the Connection or Account class).

I am trying to figure this out. Thanks for your guidance.

> Maybe you can explain why this is important so we can think about how to include this in future versions.

I am trying to download attachments from multiple accounts (currently two account, may increase in future). So i believe I have to save separate token files for each account. I have successfully implemented this for a single Office365 account as I did not have to worry about token file name. Now I am trying to work this out for multiple accounts. I think this is the way to do it. Let me know what you think.

I could create separate copies of python file and token files for each Office365 account, but that would be very inefficient to manage in future.

**Comment by janscas** [comment]
> I am trying to download attachments from multiple accounts (currently two account, may increase in future). So i believe I have to save separate token files for each account.

You can easily do this. Just authenticate with your two accounts using a different token_file_name (as I show you before).
Then instantiate two Accounts (pass the appropriate credentials and token_file_name to each one) and start operating with both as you prefer.

**Comment by anish1106** [comment]
Thank you. I changed my connection and account functions to include my custom path.

`connection = Connection(credentials=credentials, scopes=scopes,token_file_name=tokenPath)`

`account = Account((client_id,client_secret),token_file_name=tokenPath)`

**Comment by janscas** [comment]
Great, I close the issue then.
