### ISSUE TITLE
Unable to fetch auth token. Error: (invalid_client)

### ISSUE THREAD

**Issue by eikenb** [O365/python-o365#168]
Updating a calendar syncing tool I wrote for the new auth system I can't seem to get it to work. I've gone through the app registration steps, I have the app-id and app secret/password  with the redirect URL and appropriate graph delegate permissions (superset of scopes list).

I run the script, cut-n-paste the login url into my browser and login. It then redirects me to an outlook.office365.com/owa/ URL which I cut-n-paste back into the terminal at the prompt and I get an error. Script and session copied below.

This is with a freshly created venv using python3.5 (Debian stable) using `--system-site-packages` and pip installing o365, icalendar and pylint.
 
Thanks.

```
import O365 as o365
creds = ('<snip>', '<snip>')
acct = o365.Account(credentials=creds)
scopes = [
    'https://graph.microsoft.com/Calendars.Read',
    'https://graph.microsoft.com/Calendars.Read.Shared',
]
result = acct.authenticate(scopes=scopes)
```
Running this I get (snipped out anything auth/id related)...
```
(venv) [~]./test.py
Visit the following url to give consent:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=<snip>&redirect_uri=https%3A%2F%2Foutlook.office365.com%2Fowa%2F&scope=https%3A%2F%2Fgraph.microsoft.com%2FUser.Read+https%3A%2F%2Fgraph.microsoft.com%2FCalendars.Read.Shared+offline_access+https%3A%2F%2Fgraph.microsoft.com%2FCalendars.Read&state=5tUXfvP<snip>&access_type=offline
Paste the authenticated url here: https://outlook.office365.com/owa/?code=OAQABAAIAAACEf<snip>&state=5tUXf<snip>&session_state=f7178db7-<snip>
Unable to fetch auth token. Error: (invalid_client) AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.
Trace ID: 6452564a-<snip>
Correlation ID: eaa6da0c-<snip>
Timestamp: 2019-01-14 20:34:12Z
Something go wrong. Please try again.
```

**Comment by eikenb** [comment]
After reading #160, I tried adding `offline_access` to the graph delegate permissions and adding `basic` to the scope list. Same results.

**Comment by janscas** [comment]
> scopes = [ 'https://graph.microsoft.com/Calendars.Read', 'https://graph.microsoft.com/Calendars.Read.Shared', ] result = acct.authenticate(scopes=scopes)

The scopes you have to pass to `account.authenticate` are not those. You have to pass ["scope helpers"](https://github.com/O365/python-o365/blob/master/O365/connection.py#L33).

So you have to pass the scope helpers like this.:

```python
# ...
result = acct.authenticate(scopes=['basic', 'address_book', 'address_book_shared'])
```

I you don't want to authenticate on every run, add the basic scope helper (adds User.Read and offline_access. Add this persmissions to you app.

Hope this helps.

**Comment by janscas** [comment]
Note that if you don't want to work with the scope helpers, then you have to authenticate the "hard" way.
Like this:

```python
con = Connection(credentials, scopes=['https://graph.microsoft.com/Calendars.Read', 'https://graph.microsoft.com/Calendars.Read.Shared'])

visit_url = con.get_authorization_url()

# follow the url and give consent, and then copy the result url and paste it there:

authenticated_url = input()  # paste url
result = con.request_token(authenticated_url)
```

**Comment by eikenb** [comment]
Thanks for the quick response. I changed my script to this..

```
mport O365 as o365
creds = ('<snip>', '<snip>')
acct = o365.Account(credentials=creds)
scopes = [
    'calendar',
    'basic',
]
result = acct.authenticate(scopes=scopes)
```
And re-tried the same test. The error is now different.
```
Unable to fetch auth token. Error: (missing_code) Missing code parameter in response.
Something go wrong. Please try again.
```
I didn't include the URLs as they looked pretty much like they did before.
The pasted auth-url did have the same "#code=..." bit in it if that is relevant to the 'Missing code parameter' mentioned.

**Comment by janscas** [comment]
What scopes did you add on the app registration portal?

**Comment by eikenb** [comment]
Under the "Microsoft Graph Permssions/Delegate Permissions" I have the following listed...
Calendars.ReadWrite, offline_access, User.Read

**Comment by eikenb** [comment]
After pasting the first URL into the browser and going through the auth steps, it redirects me to the o365 outlook page. It is the URL from that final step that I paste back into the terminal.

**Comment by janscas** [comment]
> After pasting the first URL into the browser and going through the auth steps, it redirects me to the o365 outlook page. It is the URL from that final step that I paste back into the terminal.

Maybe you are not pasting the whole string? ... I don't know.

What you can do to further see If I we can help you is set the logging to DEBUG and paste the output here (**PLEASE REMOVE THE SENSITIVE INFO**).

```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by eikenb** [comment]
I started getting the invalid_client error again so I tried a few things. After a few checks with different browsers and such I was able to get back to the missing_code error after re-creating the venv. I re-created the virtual-env without system-site-packages and made sure to include wheel/cffi (without them I still got invalid_client errors). I used an incognito browser session to hit the URL and login to make sure no plugins or old state were affecting things.

The logging output when I get the missing_code output is short (compared to with the invalid_client output). So I'll include both. First, here is the session with the missing_code error.
```
(venv) [~]./test.py
DEBUG:requests_oauthlib.oauth2_session:Generated new state idyS7W21yR9EicSLuohTVfbURKwByP.
Visit the following url to give consent:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=<snip>&redirect_uri=https%3A%2F%2Foutlook.office365.com%2Fowa%2F&scope=https%3A%2F%2Fgraph.microsoft.com%2FCalendars.ReadWrite+offline_access+https%3A%2F%2Fgraph.microsoft.com%2FUser.Read&state=idyS7W21yR9EicSLuohTVfbURKwByP&access_type=offline
Paste the authenticated url here: https://outlook.office365.com/owa/#code=<snip>&state=idyS7W21yR9EicSLuohTVfbURKwByP&session_state=93203573-a957-42ca-9e1f-e08ad3bb1969
ERROR:O365.connection:Unable to fetch auth token. Error: (missing_code) Missing code parameter in response.
Something go wrong. Please try again.
```
And here is the session with the invalid_client error.
```
(venv) [~]./test.py
DEBUG:requests_oauthlib.oauth2_session:Generated new state yzHplHxKd2cEv4EYN8rt2PCbf9yLSc.
Visit the following url to give consent:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=<snip>&redirect_uri=https%3A%2F%2Foutlook.office365.com%2Fowa%2F&scope=https%3A%2F%2Fgraph.microsoft.com%2FCalendars.ReadWrite+https%3A%2F%2Fgraph.microsoft.com%2FUser.Read+offline_access&state=yzHplHxKd2cEv4EYN8rt2PCbf9yLSc&access_type=offline
Paste the authenticated url here: https://outlook.office365.com/owa/?code=<snip>&state=yzHplHxKd2cEv4EYN8rt2PCbf9yLSc&session_state=0191b273-5bdf-4843-9399-fdfb6fd8f60b
DEBUG:requests_oauthlib.oauth2_session:Encoding `client_id` "<snip>" with `client_secret` as Basic auth credentials.
DEBUG:requests_oauthlib.oauth2_session:Requesting url https://login.microsoftonline.com/common/oauth2/v2.0/token using method POST.
DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Accept': 'application/json'} and data {'code': '<snip>', 'redirect_uri': 'https://outlook.office365.com/owa/', 'grant_type': 'authorization_code'}
DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'auth': <requests.auth.HTTPBasicAuth object at 0x7f4fb1ea9978>, 'proxies': None, 'timeout': None, 'json': None, 'verify': True}.
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /common/oauth2/v2.0/token HTTP/1.1" 401 449
DEBUG:requests_oauthlib.oauth2_session:Prepared fetch token request body grant_type=authorization_code&code=<snip>&redirect_uri=https%3A%2F%2Foutlook.office365.com%2Fowa%2F
DEBUG:requests_oauthlib.oauth2_session:Request to fetch token completed with status 401.
DEBUG:requests_oauthlib.oauth2_session:Request headers were {'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Accept': 'application/json', 'Content-Length': '897', 'Connection': 'keep-alive', 'User-Agent': 'python-requests/2.21.0', 'Authorization': 'Basic <snip>', 'Accept-Encoding': 'gzip, deflate'}
DEBUG:requests_oauthlib.oauth2_session:Request body was code=<snip>&redirect_uri=https%3A%2F%2Foutlook.office365.com%2Fowa%2F&grant_type=authorization_code
DEBUG:requests_oauthlib.oauth2_session:Response headers were {'x-ms-request-id': '8b3dca77-befa-4c79-bb6a-f2b4bc102500', 'X-Content-Type-Options': 'nosniff', 'Content-Type': 'application/json; charset=utf-8', 'Date': 'Tue, 15 Jan 2019 18:05:12 GMT', 'Expires': '-1', 'P3P': 'CP="DSP CUR OTPi IND OTRi ONL FIN"', 'Pragma': 'no-cache', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'Cache-Control': 'no-cache, no-store', 'Content-Length': '449', 'Set-Cookie': 'fpc=<snip>; expires=Thu, 14-Feb-2019 18:05:13 GMT; path=/; secure; HttpOnly, x-ms-gateway-slice=002; path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly'} and content {"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: 8b3dca77-befa-4c79-bb6a-f2b4bc102500\r\nCorrelation ID: 051fd362-50d2-42c4-b5c9-57d67a0e5e57\r\nTimestamp: 2019-01-15 18:05:13Z","error_codes":[70002,50012],"timestamp":"2019-01-15 18:05:13Z","trace_id":"8b3dca77-befa-4c79-bb6a-f2b4bc102500","correlation_id":"051fd362-50d2-42c4-b5c9-57d67a0e5e57"}.
DEBUG:requests_oauthlib.oauth2_session:Invoking 0 token response hooks.
ERROR:O365.connection:Unable to fetch auth token. Error: (invalid_client) AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.
Trace ID: 8b3dca77-befa-4c79-bb6a-f2b4bc102500
Correlation ID: 051fd362-50d2-42c4-b5c9-57d67a0e5e57
Timestamp: 2019-01-15 18:05:13Z
Something go wrong. Please try again.
```

**Comment by derrix060** [comment]
`Invalid client secret is provided.` Make sure the client secret is correct.

**Comment by eikenb** [comment]
I generated a new secret/password on the apps.dev MS site, under 'Application Secrets' I selected 'Generate New Password' and saved that into my script (above). Same issue.

I've re-installed the venv again and am back to invalid_client each time. I think the missing_code error is likely to be be unrelated.

Another possibly relevant detail... I'm logging into office365 with my company account creds which use Okta based single sign with 2-factor auth (google totp/auth).

**Comment by eikenb** [comment]
And I'm about as sure as I can be that I'm copy-pasting the whole string. Just using standard X-windows primary selection copy/paste and haven't had an issue with partial pasting before.

**Comment by eikenb** [comment]
I also used the same Office365 account to login to the apps.dev site and create the Application. I mention it in case having it and the Office365 account using the same auth is somehow an issue.

**Comment by janscas** [comment]
The error is returned by requests oauthlib (not this library itself). If it says `Invalid client secret is provided.` it's probably true.
What you can try is the [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) to see if you can login and test some endpoints... but I think I can't help you beyond this point, because the error is unrelated to this library. 

Just to review the whole process, try all from the beginng:

1. Set `logging.basicConfig(level=logging.DEBUG)`
1. Register a new app following the indications on the docs.
1. Authenticate using the `account.authenticate` method providing all the scope helpers you need (and you add as delegated permissions to the app). (when pasting the result url be careful... sometimes the terminal can span the string into multiple lines and if you hit enter on the middle only a part of the string is returned to the function)
1. Check the logs

> Another possibly relevant detail... I'm logging into office365 with my company account creds which use Okta based single sign with 2-factor auth (google totp/auth).

This is not relevant. The authentication flow for the Api's uses Oauth2.

**Comment by janscas** [comment]
Check: [https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L160](https://github.com/requests/requests-oauthlib/blob/master/requests_oauthlib/oauth2_session.py#L160)

**Comment by janscas** [comment]
@eikenb Some news. This could be related to #169. It is related to a [recent change](https://github.com/requests/requests-oauthlib/pull/331) within request-oauthlib 1.2.0

Let's hope it's this because it's easy to fix.

**Comment by janscas** [comment]
@eikenb hi, we have just released a new version
`pip install --upgrade O365`
And try again

**Comment by eikenb** [comment]
`Authentication Flow Completed. Oauth Access Token Stored. You can now use the API.`

That got it. Thanks!
