### ISSUE TITLE
Unable to fetch auth token. Error: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'client_id'.

### ISSUE THREAD

**Issue by jixster** [O365/python-o365#169]
after pasting the authenticated url i receive Unable to fetch auth token. Error: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'client_id'. which prevents me from successfully getting a token.

**Comment by janscas** [comment]
> after pasting the authenticated url i receive Unable to fetch auth token. Error: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'client_id'. which prevents me from successfully getting a token.

That's odd. The client_id is in fact passed to the request fetching the token.

**Comment by jixster** [comment]
2019-01-15 13:43:27,062: DEBUG   - Requesting url https://login.microsoftonline.com/common/oauth2/v2.0/token using method POST.
2019-01-15 13:43:27,063: DEBUG   - Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'authorization_code', 'code': 'my code here', 'redirect_uri': 'https://outlook.office365.com/owa/'}
2019-01-15 13:43:27,063: DEBUG   - Passing through key word arguments {'json': None, 'timeout': None, 'auth': <requests.auth.HTTPBasicAuth object at 0x7f66f3dc5e10>, 'verify': True, 'proxies': None}.
2019-01-15 13:43:27,068: DEBUG   - Starting new HTTPS connection (1): login.microsoftonline.com:443
2019-01-15 13:43:33,262: DEBUG   - https://login.microsoftonline.com:443 "POST /common/oauth2/v2.0/token HTTP/1.1" 400 436
2019-01-15 13:43:33,264: DEBUG   - Prepared fetch token request body grant_type=authorization_code&code=my code here
2019-01-15 13:43:33,264: DEBUG   - Request to fetch token completed with status 400.
2019-01-15 13:43:33,266: DEBUG   - Invoking 0 token response hooks.
2019-01-15 13:43:33,266: ERROR   - Unable to fetch auth token. Error: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'client_id'.

I truncated that first token request body message because the only thing after that was the authorization_code which would not be smart to send via email.  I was attempting to code it just like the documentation:

account = Account(authentication)
res = account.authenticate(scopes=['basic', 'message_all'])

I was hoping that I just was missing something on my end and that documentation just needed to be updated, today I guess I will dive deeper into the code unless you have some sort of quick fix.  I do appreciate the fast response as my email system is down thanks to Microsoft and my missing the notification that the old interface was going away.

thanks

On 1/15/19 3:11 PM, Alejandro Casanovas wrote:

after pasting the authenticated url i receive Unable to fetch auth token. Error: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'client_id'. which prevents me from successfully getting a token.

That's odd. The client_id is in fact passed to the request fetching the token.

**Comment by janscas** [comment]
Can u try something? 

I think this is an issue with a [recent change](https://github.com/requests/requests-oauthlib/pull/331) to the request_oauthlib library regarding the fecth_token method.

First off all, ensure you have requests_oauthlib 1.2.0 by `pip install --upgrade requests-oauthlib`

Just do the following and try to authenticate again:
(I'm just subclassing the Connection to change the request_token method so we pass `include_client_id=True` to the `fetch_token` method of requests_oauthlib)

```python
import os
import logging
from O365 import Connection as OldConnection
from O365 import Account as OldAccount
from O365 import MSGraphProtocol
from O365.utils import ME_RESOURCE


log = logging.getLogger(__name__)

class Connection(OldConnection):
    def request_token(self, authorization_url, store_token=True,
                      token_path=None):
        if self.session is None:
            raise RuntimeError("Fist call 'get_authorization_url' to "
                               "generate a valid oauth object")

        client_id, client_secret = self.auth

        # Allow token scope to not match requested scope.
        # (Other auth libraries allow this, but Requests-OAuthlib
        # raises exception on scope mismatch by default.)
        os.environ['OAUTHLIB_RELAX_TOKEN_SCOPE'] = '1'
        os.environ['OAUTHLIB_IGNORE_SCOPE_CHANGE'] = '1'

        try:
            self.token = self.session.fetch_token(
                token_url=self._oauth2_token_url,
                authorization_response=authorization_url,
                include_client_id=True,
                client_secret=client_secret)
        except Exception as e:
            log.error('Unable to fetch auth token. Error: {}'.format(str(e)))
            return False

        if token_path:
            self.token_path = token_path
        self.store_token = store_token
        if self.store_token:
            self._save_token(self.token, self.token_path)

        return True

class Account(OldAccount):
    def __init__(self, credentials, *, protocol=None, main_resource=ME_RESOURCE,
                 **kwargs):
        protocol = protocol or MSGraphProtocol  # Defaults to Graph protocol
        self.protocol = protocol(default_resource=main_resource,
                                 **kwargs) if isinstance(protocol,
                                                         type) else protocol

        if not isinstance(self.protocol, Protocol):
            raise ValueError("'protocol' must be a subclass of Protocol")

        self.con = Connection(credentials, **kwargs)
        self.main_resource = main_resource
```

With the previous code you have changed the key part. Now use it. Don't use the O365 Account here, but the one we created previoulsy.

```python
credentials = ('id', 'secret')
scope_helpers = ['...']
account = Account(credentials)

account.authenticate(scopes=scope_helpers)
```

This should work. Can you tell me?

Thanks

**Comment by janscas** [comment]
Once you got the token don’t use account.authenticate anymore ... that will stop the prompt.

So, can you confirm that you can use the library with the token you got?

**Comment by jixster** [comment]
yep, it works now.  I guess I miss understood that the authentication call was only needed once and only to get the consent and initial token.  Thanks for all of the prompt and valuable help.

**Comment by janscas** [comment]
Good!!! So at the end that was a breaking change introduced by requests-oauthlib.

I’ll commit this change and push a new version to github that will enforce requests-oauthlib >= 1.2.0.

Thanks

**Comment by jixster** [comment]
currently the 2.7 version of o365 is as 0.9.16 any chances that the 2.7 version will be caught up the python3 version?  Also I am assuming you will close this with your commit.

**Comment by janscas** [comment]
The new version completely substitutes the old one and is python 3 only. We stopped development of the old api.

**Comment by jixster** [comment]
I figured as much, I just need to get my s together and migrate my code.  This just moves the project to the top of the list.

**Comment by janscas** [comment]
Version 1.0.5 released on Pypi.
