### ISSUE TITLE
How to fetch attachments when mailbox.get_messages in batches?  

### ISSUE THREAD

**Issue by VFS** [O365/python-o365#173]
* Library version: `O365==1.0.5`
* Python version: `3.7.0`

Related Issues:
* [Attachments download problem #58](https://github.com/O365/python-o365/issues/58
)
* [fluent_message.fetchAttachment not working? #114](https://github.com/O365/python-o365/issues/114)

I'm trying to use the .get_messages() method as a iterator to run through a list of messages, and save some of the attachments.

```python3
mailbox = account.mailbox()
test_mailbox = mailbox.get_folder(folder_name="ParentFolder").get_folder(folder_name="subfolder")
query = test_mailbox.new_query().on_attribute('subject').contains("my_subject")
```

When I mailbox.get_messages() **without specifying the number of batch jobs**, but specifying the `download_attachments` as True, everything works as expected:
```python3
msgs =test_mailbox.get_messages(limit=2, query=query, download_attachments=True)
```
`list(msgs[0].attachments)`:  `[Attachment: A.txt, Attachment: B.txt, Attachment: C.txt]`

But If I specify that I want to fetch the messages in batches, then I can't find a way to get it`s message attachments:
```python3
msgs = test_mailbox.get_messages(limit=2,batch=1, query=query, download_attachments=True)
```
(The side effect of passing the batch parameter is that it sets download_attachments to False [mailbox.py#L176](https://github.com/O365/python-o365/blob/master/O365/mailbox.py#L176))

Then msgs will be an iterator. `m = next(msgs)`, as expected:
* `m.has_attachments`: `True`
* `list(m.attachments)`; `[]`
* `m.fetchAttachments()`: AttributeError: 'Message' object has no attribute 'fetchAttachments', contrary to what is recommended on issue #58 .

It seems this bug was fixed on pull requests #127 or #130, but none of those have been merged. Is there any other way to fetch the attachments of a message? 

Thanks!

**Comment by janscas** [comment]
Hi, first of all this library was completely changed on version 1.0. This means that the old tickets that refer to the old api (< 1.0) are no longer valid as none of the former methods work (for example `message.fetchAttachments` is from the old api and no longer exists).

Second, and as you correctly notice, when using the batch the download_attachments is set to False.
However when iterating over the messages you can also download it's attachements:

```python
for message in msgs:  # msgs is an iterator
    if message.has_attachments:
        message.attachments.donwload_attachments()
        # now you can iterate over the message.attachments
```

**Comment by janscas** [comment]
I was looking at the actual implementation, and I'ts really an easy change so I will change the api so the donwload_attachments is passed to the Paginator to allow for batches to work the same way.
Thanks

**Comment by VFS** [comment]
Awesome. Thank you!

**Comment by brody-langille** [comment]
message.attachments.download_attachments(). Not donwload.
