### ISSUE TITLE
Is it possible to determine font in messages?

### ISSUE THREAD

**Issue by BenchmarkDC** [O365/python-o365#175]
I'm trying to send automate emails with a specific font from Outlook. Is it possible to determine what font the email uses via a method?

Thanks!

**Comment by janscas** [comment]
Of course. Just use plain css inside style tags.

Like
```html
<span style="font-family: Helvetica, sans-serif;">My Text</span>
```

**Comment by BenchmarkDC** [comment]
Ah! Sorry very new to this.

Thank you for the quick response.

Andrew Held, LEED Green Associate
Energy Program Specialist
Data & Benchmarking Division
Department of Energy & Environment
1200 First Street NE, 5th Floor
Washington, DC 20002
Desk: (202) 727-8950
Cell: (202) 740-6757
Andrew.Held@DC.Gov
http://doee.dc.gov/

**Comment by derrix060** [comment]
@janscas close it?
