### ISSUE TITLE
Always be prompted for auth.url -- token is written

### ISSUE THREAD

**Issue by dfv-ms** [O365/python-o365#177]
I guess I miss something really simple. But my code always prompts me to paste in the authenticated url. The token_file is written to disk, but it is not used.

My code is

   from O365 import Account
 
   account = Account(credentials=('xxxx', 'yyy'))
   result = account.authenticate(scopes=['onedrive'])

So how do I reuse the written token?

**Comment by janscas** [comment]
You only have to call `account.authenticate once`. Then you will have the token file and you no longer need to call `authenticate`.

Just implement two script: 1 for authenticating when necessary and the other to operate with the library.

We will make this more straightforward on the following library updates.

**Comment by dfv-ms** [comment]
@janscas Thanks, in combination with #172 I could solve my problem.
