### ISSUE TITLE
 The request body must contain the following parameter: 'refresh_token' or 'NoneType' object has no attribute 'refresh_token'

### ISSUE THREAD

**Issue by ajwillo** [O365/python-o365#178]
Hi,

I have followed the instructions to setup the oflow authentication and have a successful token in my directory.

```
>>> mailbox = account.mailbox()
>>> query = mailbox.new_query().on_attribute('from').contains('@bob.com')
>>> query = query.chain('and').on_attribute('is_read').equals(False)
>>> messages = mailbox.get_messages(limit=25, query=query)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/O365/connection.py", line 539, in _internal_request
    **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests_oauthlib/oauth2_session.py", line 395, in request
    http_method=method, body=data, headers=headers)
  File "/usr/local/lib/python3.6/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)
...
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'refresh_token'.
Trace ID: 78ae8c45-f51e-4dfe-a46a-....
Correlation ID: 46063da9-0a05-495a-8d32-...
Timestamp: 2019-01-23 14:47:03Z
>>>
```

However when I run a script I get the missing authentication token error if I use just account, looking at other issues and documentation I assumed I must need to create a con each time also

so ive added the below:

```
    scopes = ['calendar','message_all','offline_access']
    con = Connection((credentials.username, credentials.password), scopes=scopes)
    con.refresh_token()

    account = Account((credentials.username, credentials.password))
    mailbox = account.mailbox()
    query = mailbox.new_query().on_attribute('from').contains('@kcom.com')
    query = query.chain('and').on_attribute('is_read').equals(False)
    messages = mailbox.get_messages(limit=25, query=query)
```

and now I get the error 

```
>>> con.refresh_token()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/O365/connection.py", line 484, in refresh_token
    self.token = token = (self.session
AttributeError: 'NoneType' object has no attribute 'refresh_token'
```

Thanks for any help

**Comment by janscas** [comment]
What vesion of O365 are you running on?

Male sure you have the last one and try again. It should work

**Comment by janscas** [comment]
`pip install --upgrade O365`

**Comment by ajwillo** [comment]
root@d2a57bda3e9c:/itapp/itapp# pip install --upgrade O365
Requirement already up-to-date: O365 in /usr/local/lib/python3.6/site-packages (1.0.5)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7 in /usr/local/lib/python3.6/site-packages (from O365) (2.7.3)
Requirement already satisfied, skipping upgrade: requests>=2.0.0 in /usr/local/lib/python3.6/site-packages (from O365) (2.19.1)
Requirement already satisfied, skipping upgrade: requests-oauthlib>=1.2.0 in /usr/local/lib/python3.6/site-packages (from O365) (1.2.0)
Requirement already satisfied, skipping upgrade: pytz>=2018.5 in /usr/local/lib/python3.6/site-packages (from O365) (2018.5)
Requirement already satisfied, skipping upgrade: stringcase>=1.2.0 in /usr/local/lib/python3.6/site-packages (from O365) (1.2.0)
Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.0.0 in /usr/local/lib/python3.6/site-packages (from O365) (4.6.3)
Requirement already satisfied, skipping upgrade: tzlocal>=1.5.0 in /usr/local/lib/python3.6/site-packages (from O365) (1.5.1)
Requirement already satisfied, skipping upgrade: six>=1.5 in /usr/local/lib/python3.6/site-packages (from python-dateutil>=2.7->O365) (1.11.0)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/site-packages (from requests>=2.0.0->O365) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python3.6/site-packages (from requests>=2.0.0->O365) (2018.8.24)
Requirement already satisfied, skipping upgrade: urllib3<1.24,>=1.21.1 in /usr/local/lib/python3.6/site-packages (from requests>=2.0.0->O365) (1.23)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python3.6/site-packages (from requests>=2.0.0->O365) (2.7)
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in /usr/local/lib/python3.6/site-packages (from requests-oauthlib>=1.2.0->O365) (3.0.0)

root@d2a57bda3e9c:/itapp/itapp# pip freeze | grep 365
O365==1.0.5
root@d2a57bda3e9c:/itapp/itapp#

**Comment by janscas** [comment]
mmmm it seems you didn’t add the `offline_access` scope.

When using `account.authenticate` include ‘basic’ in the scopes list.

**Comment by ajwillo** [comment]
I have already followed the authentication flow tutorial and I have a token, but I cannot access that token again it seems, I can authorise it one time and the script works, but I would like to be able to refresh the existing token as this is a automated script that runs on a cron and needs to be run without input

have I missed anything in the code?

**Comment by mkrishnamurthy013** [comment]
Hi,

I think I have a very similar issue. I could successfully retrieve the auth token but unable to refresh the token could you please advice. 

```
>>> protocol = MSGraphProtocol()
>>> scopes = protocol.get_scopes_for('message_all')
>>> credentials = (client_id, secret_key)
>>> account = Account(credentials=credentials, protocol=protocol, scopes=scopes)
>>> url = account.connection.get_authorization_url()
```
```
>>> account.connection.request_token(result_url)
True
>>> m = account.new_message()
>>> m.to.add(sending_address)
>>> m.subject = 'Testing!'
>>> m.body = "George Best quote: I've stopped drinking, but only while I'm asleep."
>>> m.send()
True
>>> account.connection.refresh_token()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\O365\connection.py", line 487, in refresh_token
    client_secret=client_secret))
  File "C:\Program Files\Python37\lib\site-packages\requests_oauthlib\oauth2_session.py", line 374, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "C:\Program Files\Python37\lib\site-packages\oauthlib\oauth2\rfc6749\clients\base.py", line 415, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "C:\Program Files\Python37\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "C:\Program Files\Python37\lib\site-packages\oauthlib\oauth2\rfc6749\parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "C:\Program Files\Python37\lib\site-packages\oauthlib\oauth2\rfc6749\errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) AADSTS900144: The request body must contain the following parameter: 'refresh_token'.
```

Thanks for the help in advance.

**Comment by janscas** [comment]
> I have already followed the authentication flow tutorial and I have a token, but I cannot access that token again it seems, I can authorise it one time and the script works, but I would like to be able to refresh the existing token as this is a automated script that runs on a cron and needs to be run without input
> 
> have I missed anything in the code?

Do you have the 'refresh_token' in the token file?

**Comment by ajwillo** [comment]
the txt file has the below in, which looked good to me? how does the code find the text file? the text file is in a different directory to my script. also how do I call the token in code?

```
{
 "token_type": "Bearer",
 "scope": [
  "profile",
  "openid",
  "email",
  "https://graph.microsoft.com/Calendars.ReadWrite",
  "https://graph.microsoft.com/Contacts.ReadWrite",
  "https://graph.microsoft.com/Mail.ReadWrite",
  "https://graph.microsoft.com/Mail.Send"
 ],
 "expires_in": 3599,
 "ext_expires_in": 3599,
 "access_token": "eyJ0eXAiOiJ...",
 "expires_at": 1548093515.7867677
}
```

**Comment by janscas** [comment]
You do not have the refresh_token.
That's why you are getting the error.

If you don't ask the offline_access scope basically you only receive a "1 time, 1 hour" access token.
After this 1 hour you will have to re-authenticate again.
To avoid this just include the offline_access scope.

Do the following in order:

1. Make sure you have this permissions included in the app registration portal: 
    - User.Read
    - offline_access
1. Perform the authentication flow with this library. Just do this:
    ```python
    credentials = ('my_client_id', 'my_secret')
    my_desired_scopes =['basic', 'calendar', 'address_book_all', 'message_all']
    account = Account(credentials)
    account.authenticate(scopes=my_desired_scopes)
    # follow authentication flow. You should retrieve the token. 
    ```
    I've just added the scopes you have pasted on your token definition above. Check [scope helpers](https://github.com/O365/python-o365/blob/master/O365/connection.py#L33) for more options.

1. Then (without calling `account.authenticate` again), just use the library... you don't have to call `refresh_token`. The token is refreshed automatically.

**Comment by ajwillo** [comment]
I tried adding offline access but get an error:

```
    credentials = get_credentials('oncall mailbox 365 api')
    # Setup connection object
    scopes = [
        'https://graph.microsoft.com/Mail.ReadWrite', 
        'https://graph.microsoft.com/Mail.Send',
        'https://graph.microsoft.com/Calendars.ReadWrite',
        'https://graph.microsoft.com/Contacts.ReadWrite',
        'https://graph.microsoft.com/User.Read',
        'https://graph.microsoft.com/offline_access',
        ]
    con = Connection((credentials.username, credentials.password), scopes=scopes)
    auth_url = con.get_authorization_url()
```

I think ive put the offline access url in, incorrectly?

`AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://graph.microsoft.com/Mail.ReadWrite https://graph.microsoft.com/Mail.Send https://graph.microsoft.com/Calendars.ReadWrite https://graph.microsoft.com/Contacts.ReadWrite https://graph.microsoft.com/User.Read https://graph.microsoft.com/offline_access is not valid. The resources must specify a known valid scope. `

**Comment by janscas** [comment]
The offline scope does not have the prefix pass just 'offline_access'

**Comment by janscas** [comment]
you just have to read the three steps I wrote above. There you have the scope helpers and even a link to all the available ones...

You will know that you have the offline_access scope applied because you will have a “refresh_token” key in the token file.

**Comment by ajwillo** [comment]
finally got it working! I used what you had said above. what threw me off was the step 1, I assumed I needed to use the manual scopes as a step before I could use the helper, I then realised I add them manually to the app in the 365 portal, then use step 2.

thanks for your assistance and your patience

**Comment by janscas** [comment]
Great!!
