### ISSUE TITLE
Authentication Token expiry

### ISSUE THREAD

**Issue by hassanalinali** [O365/python-o365#182]
The authentication token that I generated earlier today expired already, I receive an (invalid_request)

`The request body must contain the following parameter: 'refresh_token'.`

If I calculate the `expires_at` time it's set to expire after 1 hour, can you help me figure out what's going wrong here?

**Comment by hassanalinali** [comment]
While checking #178 I've seen that you recommended including 'basic' scope, that did it for me, now I also have refresh_token in 0365_token.txt

**Comment by janscas** [comment]
'basic' scope helper will add the scopes: User.Read and offline_access. The later adds the refresh_token so you can stay "logged in" for more than 1 hour.

You did it right.

**Comment by janscas** [comment]
Can we close this issue?
