### ISSUE TITLE
Specify tenant-specific (directory) endpoint

### ISSUE THREAD

**Issue by frennkie** [O365/python-o365#184]
I'm pretty new to this O365, Microsoft Graph, OAuth2 stuff. I registered an application and created a secret. Then I ran the following: 

```
from O365 import Connection, MSGraphProtocol, MSOffice365Protocol
from O365.account import Account
credentials = ("<client_id>", "<secret>")
scopes = ['https://graph.microsoft.com/User.Read']
protocol_graph = MSGraphProtocol()
scopes_graph  = protocol_graph.get_scopes_for(scopes)
con = Connection(credentials, scopes=scopes_graph)
con.get_authorization_url()
```

The result is an URL that points to `https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=<client_id>...redirect=...scope=...access_type=offline`. I opened that URL in a browser, successfully authenticated an account and got the following error from Microsoft:

> AADSTS50194: Application '<client_id>' is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

I do not want to switch to multi-tenant. So I manually changed the URL and replaced `common` with the <directory_id> (also labeled `Directory (tenant) ID`). Then I no longer get the AADSTS50194 error.

Is there a parameter in `python-o365` to set the `direcory_id` value? If not and it makes sense then I could look into sending a PR.

**Comment by frennkie** [comment]
Basically I would change Connection to include `directory_id` like so:

```
con = Connection(credentials, scopes=scopes_graph, directory_id="abcdefgh-xxxx-yyyy-zzzz-abcdefghijkl")
```

Makes sense?

**Comment by janscas** [comment]
For the moment you can change:

```python
Connection._oauth2_authorize_url
# defaults to: https://login.microsoftonline.com/common/oauth2/v2.0/authorize


Connection._oauth2_token_url
# defaults to: https://login.microsoftonline.com/common/oauth2/v2.0/token
```

But PR are welcome.
You can change the `_oauth2_authorize_url` and `_oauth2_token_url` to be instance attributes instead of class attributes and then set those with a diretory_id as you said. It should default to 'common'.
