### ISSUE TITLE
error while generating access token

### ISSUE THREAD

**Issue by rehanalam1** [O365/python-o365#186]
Hi Janscas,

You have provided great stuff here. I was using it but recently got an error. 

The error is when I try to authenticate my app and generate auth token.

```
from O365 import Account
account = Account(credentials=("client id", "client cred"))
result = account.authenticate(scopes=['basic',   'message_all'])
```

This is the code I had to authenticate. It returned with a URL to click and authenticate. I did the same. Authenticated my app to send email etc and then it redirected to URL: "https://outlook.office.com/mail/inbox"

When I entered the same URL in the input box present in python, it returned with the error 

> "Unable to fetch auth token. Error: (missing_code) Missing code parameter in response."

Please correct me what I'm doing wrong.

**Comment by janscas** [comment]
after login and give consent you will be redirected to outlook.office.com.
The full url should contain a query parameter called "code". You have to copy the full url and paste it on the prompt.

**Comment by rehanalam1** [comment]
Thanks. I noticed an URL just before "https://outlook.office.com/mail/inbox". The URL is structured as below:

`https://outlook.office365.com/mail/#code=[random_string] state [string present in the auth request] sessions_state[some_random_string]`

I input the above URL but still getting the error. Tried with multiple Azure apps and machine. 

> oauthlib.oauth2.rfc6749.errors.MissingCodeError: (missing_code) Missing code parameter in response.


Last time I generated token was in the month of Nov'18.

**Comment by rehanalam1** [comment]
**Resolved**

The issue was with the response URI from office365 API. As I stated above the response URL structure was:

`https://outlook.office365.com/mail/#code=[string].........`

The "urlparse" library was unable to parse above URL because it contained `#` after _https://outlook.office365.com/mail/_. I changed `#` with `?` and it worked.
