### ISSUE TITLE
Inbox 'Message' objects returning with body_type 'html', not 'HTML', causing a bug in Message.get_body_soup()

### ISSUE THREAD

**Issue by matthewgdv** [O365/python-o365#188]
Honestly, the issue isn't so much what the body_type returns as, as it is the implementation of Message.get_body_text() and Message.get_body_soup().

The following lines in these methods:
    if self.body_type != 'HTML':

Should actually be:
    if self.body_type.upper() != 'HTML':

Because right now some messages are returning with body_type 'html' for me, which itself isn't a problem, but is causing these two methods not to work (Message.get_body_soup() falls back on None, and Message.get_body_text() falls back on its body attribute).

It may be worth taking a look at any other checks like this in the project's code that are case-sensitive but shouldn't be.

**Comment by janscas** [comment]
Thanks! I’ll commit a fix!
