### ISSUE TITLE
This project is not PEP 519 compliant (does not accept all os.PathLike objects anywhere a path is expected)

### ISSUE THREAD

**Issue by matthewgdv** [O365/python-o365#190]
As the title says, if I declare my own class that inherits from os.PathLike and implements \_\_fspath__ I can't actually use it with this library as-is (without first calling os.fspath() on it in my own code). I've tried it with, for example, the add() method of the BaseAttachments class.

A quick skim-through of the O365 api seems to show that system paths are only handled in 4 places: connection.py, attachment.py, drive.py, and token.py. And there pretty much only seems to be 1-2 places in each of these modules where they're handled (usually with if-elif-else blocks using isinstance() checks).

It doesn't seem like making the adjustments would be much work. The only things that would have to change are little things like:
    
    isinstance(hopefully_a_path, Path)
would become:

    isintance(hopefully_a_path, os.PathLike)

and

    isinstance(hopefully_a_path, (str, Path))
would become:

    isinstance(hopefully_a_path, (str, os.PathLike))

And then before actually using the values for anything you'd have to call os.fspath() on them. That's about it.

I could open a pull request for this and give it a shot. I've never yet really contributed to an open-source project so I might need a little help around some of the technical things like how you guys handle unit tests, or whether you have any kind of continuous integration set up, but if anyone would be willing to chat me through some of that I'd be super grateful.

If that's too much hassle that's fair. Hopefully the report at least helps.

Cheers!

**Comment by matthewgdv** [comment]
Whooops, I should have checked before posting this, but I just noticed that O365 supports Python 3.4 and up, and the functions I mentioned are 3.6+.

I've got no idea if there's a clean way to still integrate this functionality without breaking it for people running 3.4-3.5 but I'm guessing probably not. 

Feel free to close this issue.

**Comment by janscas** [comment]
As you said that's not posible for the moment as we are targeting python >= 3.4.
