### ISSUE TITLE
SFB/Teams user status? i.e.: Available/busy/away/out of office

### ISSUE THREAD

**Issue by idesignstuff** [O365/python-o365#191]
Is this functionality in the API, and if so, could it be exposed in Python-o365? 
Ideally, this could stay on the local machine to get the local user's status, as well as online to get other users' status.

If [local_user.status] is away
  lock computer

etc...

**Comment by janscas** [comment]
This is what graph allows: https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

You can check what's implemented in python-o365 by looking at the readme.

**Comment by idesignstuff** [comment]
Thanks for that link.

Looks like the MS dev may implement in 2019...
https://officespdev.uservoice.com/forums/224641-feature-requests-and-feedback/suggestions/17788489-provide-freebusy-functionality-in-microsoft-graph
