### ISSUE TITLE
ContactFolder class constructor is hardcoded

### ISSUE THREAD

**Issue by matthewgdv** [O365/python-o365#192]
Hi, I've been writing my own wrapper around this library for personal use and I just want to say thank you for exposing the various class constructors for child objects as class attributes on parent objects to make inheriting from your classes nice and painless.

However, the ContactFolder class seems to be an exception here. While it has the message_constructor and contact_constructor class attributes that it inherits from BaseContactFolder, when using methods like 'get_folder()' or 'get_folders()' it always instanciates new ContactFolder objects.

By contrast, the Folder class uses a 'self_class' constructor that it gets by introspecting its parent's folder_constructor (and falling back on type(self) otherwise).

Is there any chance you could you implement the same thing for ContactFolder objects too?

Cheers!

**Comment by janscas** [comment]
Fixed on commit 0a530ff3031c159082b2bbc89341fbbbd9d4539a

Thanks!
