### ISSUE TITLE
mark a message as read by object_id

### ISSUE THREAD

**Issue by ajwillo** [O365/python-o365#194]
Hi,

is it possible to mark a message as read by the messages ID?

I have obtained the ID as the below but am unable to use it to mark a message as read it seems?

message obtained by message.object_id

```
account = Account((credentials.username, credentials.password))
mailbox = account.mailbox()
query = mailbox.new_query().on_attribute('id').contains(message_id)
messages = mailbox.get_messages(limit=1, query=query)

...| Error Message: The property 'Id' does not support filtering.

```

I assumed I would filter the mailbox then mark that message as read, is there another way?

**Comment by janscas** [comment]
We don't have a method to retrieve a message by id, but you can do the following:

```python
# ...
from O365 import Message

m = Message(parent=account, is_draft=False)  # the parent can be any ApiComponent subclass
m.object_id = 'the_object_id_you_want'

m.mark_as_read()  # this message id will be mark as read
```

**Comment by ajwillo** [comment]
thank you for this, is it also possible to mark an email as unread? I can't see it in the API anywhere but wondering if there was any way?

Thanks

**Comment by janscas** [comment]
just change is_read property and save

**Comment by ajwillo** [comment]
I tried the below but got the error "'NoneType' object is not callable" for the m.is_read line

```
    credentials = get_credentials('oncall mailbox 365 api')
    account = Account((credentials.username, credentials.password))
    m = Message(parent=account, is_draft=False) 
    m.object_id = message_id
    m.is_read(False) 
```

**Comment by janscas** [comment]
is_read is a property, not a method

**Comment by ajwillo** [comment]
sorry updated the question, but its not being marked as read currently

**Comment by janscas** [comment]
I've commited 970e03375b92021b790ae911629794ccd4e9550d to incorporate some changes and the ability to change the message read status.

Now you can:

- pass the object_id into the Message constructor: `m = Message(parent=account, object_id='my_id', is_draft=False)`
- update the message read status: `message.save_message()` (also updates any other non draft dependent property: categories, etc.). If you call `message.save_message` on a draft or new message it will fallback to `message.save_draft`.
- get a message directly by it's id: `inbox.get_message(object_id='my_id')` However if you don't need the message data, you can build the message with the object_id to avoid a request.

This is already on pypi with version 1.1.1.

**Comment by ajwillo** [comment]
This is great!

I think there may be an issue?

code:
```
    from O365 import Account, Message
    # get account credentials
    credentials = get_credentials('oncall mailbox 365 api')
    account = Account((credentials.username, credentials.password))
    m = Message(parent=account, object_id=message_id, is_draft=False) 
    m.is_read = False
    m.save_message()
```

error:

File "/itapp/itapp/home/views.py" in inbox_mark_unread
  1616.     m.save_message()

File "/usr/local/lib/python3.6/site-packages/O365/message.py" in save_message
  799.             data = self.to_api_data(restrict_keys=changes)

File "/usr/local/lib/python3.6/site-packages/O365/message.py" in to_api_data
  568.             message[cc('createdDateTime')] = self.created.astimezone(

Exception Type: AttributeError at /inbox_mark_unread/A....../
Exception Value: 'NoneType' object has no attribute 'astimezone'

**Comment by janscas** [comment]
ok, it's fixed in cbfb9b4.

We also added the ability for Messages to handle flags.

**Comment by ajwillo** [comment]
awesome! thank you so much for the features!

**Comment by OttomanZ** [comment]
## Latest Solution Working 25/11/22

```python
full_message_object=self.sales_folder.get_message(object_id=message.object_id, download_attachments=True)
```


If you already have a message object like from `.get_messages(limit=1000)` and you want to only download attachment's for certain messages and not all for speed or whatever reason you might have the best solution in that case is using the above code to get attachment, as follows,

```python
if message.has_attachments:
     # fetch the message with message.object_id and download_attachmets=True
```


I hope you understand.

**Comment by hrvacadaIM** [comment]
Hi.

This mark as unread functionality on existing messages seems not to work at all or I am doing something wrong here:

If I try this:

```python
message.is_read = True
result = message.save_message()
```

The result is `True`, but the message is not set as `Read` when I login into the inbox on O365 webmail interface.

If I try this:

```python
message.mark_as_read()
```

I get his error:

```sh
Traceback (most recent call last):
  File "/myscript.py", line 132, in <module>
    mark_message_as_read(message)
  File "/myscript.py", line 88, in mark_message_as_read
    result = message.mark_as_read()
  File "/Users/JohnDoe/Library/Python/3.9/lib/python/site-packages/O365/message.py", line 795, in mark_as_read
    raise RuntimeError('Attempting to mark as read an unsaved Message')
RuntimeError: Attempting to mark as read an unsaved Message
```

**Comment by hrvacadaIM** [comment]
Hi.

I found other way to patch the message. After investigating further MS Graph I found there are 4 endpoints for patching the message: https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/api/message-update.md#http-request. For me this one worked: `PATCH /users/{id | userPrincipalName}/mailFolders/{id}/messages/{id}`. So at the end I ended up using `requests` module and send PATCH request to the MS Graph. Something like:

```python
def mark_message_as_read(message):
    # Not working
    # msg = Message(parent=account, object_id=message.object_id, is_draft=False)
    # msg.mark_as_read()

    # Other way to update emails to read
    access_token = get_access_token()

    url = f'https://graph.microsoft.com/v1.0/users/{ACCOUNT}/mailFolders/Inbox/messages/{message.object_id}'
    body = {
        'isRead': True
    }
    headers = {
        'Authorization': f'Bearer {access_token}',
        'Content-Type': 'application/json;charset=UTF-8'
    }

    try:
        response = requests.patch(url, json=body, headers=headers)
        response.raise_for_status()
        return True
    except requests.exceptions.HTTPError as ex:
        pprint.pprint(ex)
        return False
```
