### ISSUE TITLE
EventMessage - handle meeting invites

### ISSUE THREAD

**Issue by frennkie** [O365/python-o365#197]
I am currently working on migrating a "Bot" that handles several tasks from our on-Prem Exchange (using the Exchange Web Service EWS) to Exchange Online/O365. For EWS I had been using https://github.com/ecederstrand/exchangelib - which is great.. but it appears that Microsoft is phasing out EWS.

I have been able to successfully authenticate using `python-o365` and I can get messages from the mailbox and also calendar entries from the calendar. What I am missing is a dedicated `EventMessage`. Meeting invitations (or rejections) that are in the inbox have the same type as emails in python-o365.

I am currently working with the `MSGraphProtocol` and also there `EventMessage` is a separate Type: https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/complex-types-for-mail-contacts-calendar#eventmessage.

Am I'm doing something wrong or is this simply not implemented (yet?!)?

**Comment by frennkie** [comment]
I looked into the raw API response and the following two fields need to be evaluated:

* `@odata.type` (e.g. `#microsoft.graph.eventMessage`)
* `meetingMessageType` (e.g. `meetingRequest`)

How can I access this in `python-o365`?

**Comment by janscas** [comment]
We have this as a 'ToDo':

https://github.com/O365/python-o365/projects/2#card-14588162

This should be easy to implement:

- add the message type property
- add the meetingMessageType property
- add a method to retrieve the related event.

**Comment by frennkie** [comment]
@janscas The `ToDo` is pretty brief.. Do you also consider [accepting](https://docs.microsoft.com/en-us/graph/api/event-accept?view=graph-rest-1.0)/[declining](https://docs.microsoft.com/en-us/graph/api/event-decline?view=graph-rest-1.0) a meeting request in scope? Those are the things I am currently using through EWS.

**Comment by janscas** [comment]
That’s already implemented. Check the calendar.py code.

**Comment by frennkie** [comment]
@janscas Great! :-D I didn't see that. Would it help if I start/send a PR?

**Comment by frennkie** [comment]
I was able to retrieve the related event of a Event Message like so: 
`https://graph.microsoft.com/v1.0/me/messages/A...A=?$expand=microsoft.graph.eventMessage/event`

I noticed that some query key words are implement in utils.py - but not `expand`. So I assume it should be added there, right?

**Comment by frennkie** [comment]
@janscas I have to admit that I'm struggling a bit with finding my way around the code base and getting the integration to "get_event" right. Do you guys by any change have a communication channel (IRC, Slack..) for dev..? :-D

These changes to `message.py` do work:

```
    def get_event(self):
        """ Returns the related meeting event from a meeting message """

        from O365.calendar import Event

        if not self.meeting_message_type:
            return None

        url = self.build_url(
            self._endpoints.get('get_message').format(id=self.object_id))

        url += "?$expand=microsoft.graph.eventMessage/event"

        response = self.con.get(url)
        if not response:
            return None

        data = response.json()
        return Event(parent=self, **{self._cloud_data_key: data.get('event')})
```

So what I don't like/am trying to fix is:
1. Failed import
2. expand is not reusable
3. manually "crafting" of url and call for con.get(url)



1. Failed import

```
  File "...\python-o365\O365\calendar.py", line 11, in <module>
    from .message import HandleRecipientsMixin
```

Would it hurt to move `Recipient`, `Recipients` and `HandleRecipientsMixin` into a new `recipient.py` to avoid this import issue?

2. expand

$expand should go into utils.py, right? A if possible also be `fluent`, right?

3. URl + con.get

I would rather call e.g. `Mailbox.get_message()` (or `Mailbox.get_messages()`) with my object_id and the query containing the `$expand` statement. But there is line explicitly blocking this:

```
        if object_id is not None and query is not None:
            raise ValueError('Must provide object id or query but not both.')
```

What is the reason for this? The API is completly fine with specifying query parameter when getting a specific message. E.g.: https://graph.microsoft.com/v1.0/me/messages/A[...]=?$select=body.

Should I open a "working-in-progress" PR for this discussion?

**Comment by janscas** [comment]
Hi! usually non core developers communicate with PR and issues.

My idea to handle EventMessage is to have the Message class detect when the data is in fact a EventMessage. Then Message should expose a simple `get_event` method that will return None when a Message is not a EventMessage and the related Event (from calendar.py) when it's a EventMessage.

This Event should be retrieved with the $expand property. $expand can be easily be implemented in the Query object from utils.py. I can do that in the next week.



> What is the reason for this?

You can call `get_messages` without any params, but `get_message` (singular) needs at least a object_id or a query. It can not work without that parameters.

> Should I open a "working-in-progress" PR for this discussion?

Let me work on the expand on the Query and I'll report back.

**Comment by frennkie** [comment]
> Hi! usually non core developers communicate with PR and issues.

Completely understandable.. I just thought I'd ask.

> My idea to handle EventMessage is to have the Message class detect when the data is in fact a EventMessage. Then Message should expose a simple get_event method that will return None when a Message is not a EventMessage and the related Event (from calendar.py) when it's a EventMessage.

How exactly would you do this? 

 1. Always (or at least by default) request the Event data (which will be empty if message is not a `EventMessage`)
 2. Do not immediately request the Event data.. only after the data is fetched once, make another request to the API and get the event data for the detected `EventMessage`

IMHO the first option might fetch some additional data that might often not be needed and the second option adds (significant?!) delay as one (or multiple) request(s) to the API will need to be made.

**Comment by janscas** [comment]
> 1. Always (or at least by default) request the Event data (which will be empty if message is not a `EventMessage`)

If the message is not an EventMessage then we return none.



> 2\. Do not immediately request the Event data.. only after the data is fetched once, make another request to the API and get the event data for the detected `EventMessage`

The `get_event` will request the message with a 'select' with only 1 dummy field (ej. subject) and with expand=event. This should be fast,

**Comment by frennkie** [comment]
> The get_event will request the message with a 'select' with only 1 dummy field (ej. subject) and with expand=event. This should be fast,

For the default behavior I agree. 

But I think it would be nice to give the user to choice to override this (similar to `download_attachments`). Let's assume you are fetching your 400 message in the inbox of which 250 are EventMessage.. that would be 250 separate Calls for the Events.. instead of one (per paginated page) - Yes... this is made up and not a common szenario.. but I guess you get my point.

**Comment by janscas** [comment]
This is implemented in commit 290b7c6

**Comment by frennkie** [comment]
@janscas Great work, thanks! (also for already pushing this to PyPI).

I migrated from my implementation to yours and I think I found a bug. When I call `message.get_event()`  the data is incomplete. Only the subject is requested.. this comes from this [line](https://github.com/O365/python-o365/blob/master/O365/message.py#L908):

```
        # select a dummy field (eg. subject) to avoid pull unneccesary data
        query = self.q().select('subject').expand('event')
```

Why the limitation to `subject`? How should this be able to construct a full `Event` object (`return Event(parent=self, **{self._cloud_data_key: event_data})`)?

**Comment by janscas** [comment]
Lets recap:

First you get a message that turns out to be an EventMessage. This message will have all the data (if you requested all).

Next, you want to get the related event. To get it the docs state that you have to get the same message again but with an $expand=event paramenter. Therefore as we already have the message data we do not want to download the same data again. 

That’s why I only select the subject from the message.

**Comment by frennkie** [comment]
@janscas Sorry.. please disregard! **I had a broken test message in my inbox..** With regular messages this works fine!

**Comment by frennkie** [comment]
@janscas Oh... just so you are aware of this.. my "broken message" is actually a perfectly fine meeting request that I created with the Thunderbird Calendar. So this appears to be incompatible. My use case only includes "native" clients (Office, O365 Web) - so this is fine for me.

**Comment by janscas** [comment]
So, can we close this?
