### ISSUE TITLE
O365 Multi-factor authentication

### ISSUE THREAD

**Issue by skvsree** [O365/python-o365#20]
I am not sure yet how we accommodate this, but O365 supports Multifactor Auth https://technet.microsoft.com/en-us/library/dn383636.aspx.  But this would be really required feature in future

**Comment by Narcolapser** [comment]
It may be a possibility. This may need to be implemented in the same way that OAuth in issue 16 is. I'm envisioning a seperate authentication class that manages any of a number of authentication types. For multi-factor authentication for this library it would fall under the category of non-browser client so it would use an application password. Not to much more difficult but would mean storing passwords which means encryption. If you are interested in fiddling around in that area at all, have at, send me some pull requests and we'll hammer something out.

**Comment by janscas** [comment]
Closing this because by using the Oauth authentication protocol you can no longer use username and password and also it's not posible to use the 2FA.
