### ISSUE TITLE
API currently has typo for tentatively

### ISSUE THREAD

**Issue by frennkie** [O365/python-o365#203]
The MSGraph API currently has a typo in the word `tentatively`. More details: microsoftgraph/microsoft-graph-docs#4069

Therefore this enum currently won't match: https://github.com/O365/python-o365/blob/master/O365/message.py#L21

**Comment by janscas** [comment]
So accross api v1 is “tenatively”. Beta is “tentatively”.

This will require a horrible patch. I’ll fix it later!

C
