### ISSUE TITLE
How can I add online meeting (Skype For Business)?

### ISSUE THREAD

**Issue by bj32161** [O365/python-o365#204]
Hi,
How can I add online meeting (Skype For Business)?
I can only add an event on my calendar but I need to edit and enable online meeting (Skype). Just wonder how can I add more parameter on this code below.
Thanks
===============================
from O365 import Account, FileSystemTokenBackend
from O365 import MSGraphProtocol
import datetime as dt
protocol = MSGraphProtocol(api_version='beta')  # MSGraphProtocol defaults to v1.0 api version

credentials = ('xxxx', 'xxxx)

token_backend = FileSystemTokenBackend(token_path='/Users/panya/Documents/Projects/XXX/O365', token_filename='o365_token.txt')
account = Account(credentials, token_backend=token_backend)

schedule = account.schedule()

calendar = schedule.get_default_calendar()
new_event = calendar.new_event()  # creates a new unsaved event
new_event.subject = 'Testing'
new_event.location = 'Conf TH Room 01'

new_event.start = dt.datetime(2019, 3, 7, 15, 40)
new_event.end = dt.datetime(2019, 3, 7, 16, 5)
new_event.attendees.add('panya@xxx.com')
new_event.remind_before_minutes = 45
new_event.save()

------------------
![outlook-calendar-skype](https://user-images.githubusercontent.com/7337058/53943409-9ef92400-40ef-11e9-8e4d-777af888a75b.jpg)

**Comment by janscas** [comment]
I don't think this is available in Microsoft Graph.

https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-beta
