### ISSUE TITLE
cannot import name 'Account' ImportError

### ISSUE THREAD

**Issue by nkgiovannivl** [O365/python-o365#205]
I'm trying to start my project with this library but i'm having problems to use it, below some information:

Code:
from O365 import Account
account = Account(credentials=('xxxxxxx', 'yyyyyyy')) 
account.authenticate(scopes=['files.read', 'user.read', 'offline_access'])

Error:
ImportError: cannot import name 'Account' from 'O365' (C:\Python\Python37\lib\site-packages\O365\__init__.py)

Some commands:

py -3.7 -m pip install --upgrade O365
Requirement already up-to-date: O365 in c:\python\python37\lib\site-packages (1.1.3)
Requirement already satisfied, skipping upgrade: pytz>=2018.5 in c:\python\python37\lib\site-packages (from O365) (2018.9)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7 in c:\python\python37\lib\site-packages (from O365) (2.8.0)
Requirement already satisfied, skipping upgrade: stringcase>=1.2.0 in c:\python\python37\lib\site-packages (from O365) (1.2.0)
Requirement already satisfied, skipping upgrade: tzlocal>=1.5.0 in c:\python\python37\lib\site-packages (from O365) (1.5.1)
Requirement already satisfied, skipping upgrade: beautifulsoup4>=4.0.0 in c:\python\python37\lib\site-packages (from O365) (4.7.1)
Requirement already satisfied, skipping upgrade: requests>=2.0.0 in c:\python\python37\lib\site-packages (from O365) (2.21.0)
Requirement already satisfied, skipping upgrade: requests-oauthlib>=1.2.0 in c:\python\python37\lib\site-packages (from O365) (1.2.0)
Requirement already satisfied, skipping upgrade: six>=1.5 in c:\python\python37\lib\site-packages (from python-dateutil>=2.7->O365) (1.12.0)
Requirement already satisfied, skipping upgrade: soupsieve>=1.2 in c:\python\python37\lib\site-packages (from beautifulsoup4>=4.0.0->O365) (1.8)
Requirement already satisfied, skipping upgrade: urllib3<1.25,>=1.21.1 in c:\python\python37\lib\site-packages (from requests>=2.0.0->O365) (1.24.1)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in c:\python\python37\lib\site-packages (from requests>=2.0.0->O365) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in c:\python\python37\lib\site-packages (from requests>=2.0.0->O365) (2018.11.29)
Requirement already satisfied, skipping upgrade: idna<2.9,>=2.5 in c:\python\python37\lib\site-packages (from requests>=2.0.0->O365) (2.8)
Requirement already satisfied, skipping upgrade: oauthlib>=3.0.0 in c:\python\python37\lib\site-packages (from requests-oauthlib>=1.2.0->O365) (3.0.1)

py -3.7 -m pip show O365
Name: O365
Version: 1.1.3
Summary: Microsoft Graph and Office 365 API made easy
Home-page: https://github.com/O365/python-o365
Author: Janscas, Roycem90, Narcolapser
Author-email: janscas@users.noreply.github.com
License: Apache License 2.0
Location: c:\python\python37\lib\site-packages
Requires: stringcase, tzlocal, python-dateutil, requests, requests-oauthlib, beautifulsoup4, pytz
Required-by:

So, i can not find more information for troubleshooting, thanks!

**Comment by janscas** [comment]
try re-install it.

better if you use virtualenvs

**Comment by nkgiovannivl** [comment]
> try re-install it.
> 
> better if you use virtualenvs

Hi Janscas, i don't know how to use virtualenvs, but i tried uninstall and reinstall, but it does not work as expected, below the procedure:

C:\Users\FAVERNET_PC>py -3.7 -m pip uninstall  O365
Uninstalling O365-1.1.3:
  Would remove:
    c:\python\python37\lib\site-packages\o365-1.1.3.dist-info\*
    c:\python\python37\lib\site-packages\o365\*
Proceed (y/n)? y
  Successfully uninstalled O365-1.1.3

C:\Users\FAVERNET_PC>py -3.7 -m pip install  O365
Collecting O365
  Using cached https://files.pythonhosted.org/packages/d8/41/d610bb7dea3ebdef0b8019856318eb167bee9630f257f3a04117cf18d82d/O365-1.1.3-py3-none-any.whl
Requirement already satisfied: pytz>=2018.5 in c:\python\python37\lib\site-packages (from O365) (2018.9)
Requirement already satisfied: beautifulsoup4>=4.0.0 in c:\python\python37\lib\site-packages (from O365) (4.7.1)
Requirement already satisfied: requests>=2.0.0 in c:\python\python37\lib\site-packages (from O365) (2.21.0)
Requirement already satisfied: stringcase>=1.2.0 in c:\python\python37\lib\site-packages (from O365) (1.2.0)
Requirement already satisfied: tzlocal>=1.5.0 in c:\python\python37\lib\site-packages (from O365) (1.5.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\python\python37\lib\site-packages (from O365) (2.8.0)
Requirement already satisfied: requests-oauthlib>=1.2.0 in c:\python\python37\lib\site-packages (from O365) (1.2.0)
Requirement already satisfied: soupsieve>=1.2 in c:\python\python37\lib\site-packages (from beautifulsoup4>=4.0.0->O365) (1.8)
Requirement already satisfied: idna<2.9,>=2.5 in c:\python\python37\lib\site-packages (from requests>=2.0.0->O365) (2.8)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\python\python37\lib\site-packages (from requests>=2.0.0->O365) (1.24.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\python37\lib\site-packages (from requests>=2.0.0->O365) (2018.11.29)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\python\python37\lib\site-packages (from requests>=2.0.0->O365) (3.0.4)
Requirement already satisfied: six>=1.5 in c:\python\python37\lib\site-packages (from python-dateutil>=2.7->O365) (1.12.0)
Requirement already satisfied: oauthlib>=3.0.0 in c:\python\python37\lib\site-packages (from requests-oauthlib>=1.2.0->O365) (3.0.1)
Installing collected packages: O365
Successfully installed O365-1.1.3
You are using pip version 18.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\FAVERNET_PC>py -3.7 Y:\RO_RFID_Srv\email.py
Traceback (most recent call last):
  File "Y:\RO_RFID_Srv\email.py", line 7, in <module>
    from O365 import Account
  File "C:\Python\Python37\lib\site-packages\O365\__init__.py", line 4, in <module>
    from .__version__ import __version__
  File "C:\Python\Python37\lib\site-packages\O365\__version__.py", line 1, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "C:\Python\Python37\lib\site-packages\pkg_resources\__init__.py", line 36, in <module>
    import email.parser
  File "Y:\RO_RFID_Srv\email.py", line 7, in <module>
    from O365 import Account
ImportError: cannot import name 'Account' from 'O365' (C:\Python\Python37\lib\site-packages\O365\__init__.py)

**Comment by nkgiovannivl** [comment]
Update: 

My py file name is email.py, so in line 36 a module has the same name, after change my py name, the problem was solved.

Sorry for my inexperience, thanks

**Comment by sindreka** [comment]
You're a goddamn hero, nkgiovannivl!

**Comment by salihzett** [comment]
Hey, I have got the same issue. Tried everthing like update, upgrade, etc. nothing.
So when i try with ptython3 I got:
```
Traceback (most recent call last):
  File "test_account.py", line 1, in <module>
    from O365 import Account
ImportError: No module named 'O365'
```

When I try with python2:
```
Traceback (most recent call last):
  File "test_account.py", line 1, in <module>
    from O365 import Account
ImportError: cannot import name Account
```

I tried the test_account.py but also others, are not working.
Any suggestions?

**Comment by janscas** [comment]
not python 2 compatible

**Comment by ChandlerChin** [comment]
I use conda to create env and I only install O365 through 
 
`pip install O365`

my python is 3.6.13. I found the following problem:

(paper) C:\Users\Administrator>python
Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import O365
>>> from O365 import Account
>>> exit()

(paper) C:\Users\Administrator>cd Desktop\paper

(paper) C:\Users\Administrator\Desktop\paper>python
Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import O365
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\paper\lib\site-packages\O365\__init__.py", line 8, in <module>
    from .account import Account
  File "C:\ProgramData\Anaconda3\envs\paper\lib\site-packages\O365\account.py", line 1, in <module>
    from .connection import Connection, Protocol, MSGraphProtocol, MSOffice365Protocol
  File "C:\ProgramData\Anaconda3\envs\paper\lib\site-packages\O365\connection.py", line 7, in <module>
    from requests import Session
  File "C:\ProgramData\Anaconda3\envs\paper\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\ProgramData\Anaconda3\envs\paper\lib\site-packages\urllib3\__init__.py", line 11, in <module>
    from . import exceptions
  File "C:\ProgramData\Anaconda3\envs\paper\lib\site-packages\urllib3\exceptions.py", line 3, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
  File "C:\ProgramData\Anaconda3\envs\paper\lib\site-packages\urllib3\packages\six.py", line 234, in create_module
    return self.load_module(spec.name)
  File "C:\ProgramData\Anaconda3\envs\paper\lib\site-packages\urllib3\packages\six.py", line 209, in load_module
    mod = mod._resolve()
  File "C:\ProgramData\Anaconda3\envs\paper\lib\site-packages\urllib3\packages\six.py", line 118, in _resolve
    return _import_module(self.mod)
  File "C:\ProgramData\Anaconda3\envs\paper\lib\site-packages\urllib3\packages\six.py", line 87, in _import_module
    __import__(name)
  File "C:\ProgramData\Anaconda3\envs\paper\lib\http\client.py", line 71, in <module>
    import email.parser
  File "C:\Users\Administrator\Desktop\paper\email.py", line 1, in <module>
    from O365 import Account
ImportError: cannot import name 'Account'
