### ISSUE TITLE
Syntax Error on Python 3.4

### ISSUE THREAD

**Issue by frennkie** [O365/python-o365#206]
Using python-o365 on Python 3.4 (default for Cent OS 7) I get a syntax error:

```
  File "/opt/scripts/roster/venv/lib/python3.4/site-packages/O365/utils/utils.py", line 518
    self._cloud_data_key: value}, **self.extra_args) for value in data]
                                ^
SyntaxError: invalid syntax
```

The reason this works on Python3.5+ seems to be this: https://docs.python.org/3/whatsnew/3.5.html#whatsnew-pep-448.

**Comment by janscas** [comment]
That's true!

I'll make it python 3.4 compliant again.

Thanks!

**Comment by frennkie** [comment]
Can you do a new PyPI release including this?

**Comment by janscas** [comment]
Yes, but I have to accumulate some more fixes.
It will be released in a few days
