### ISSUE TITLE
Sharepoint connector

### ISSUE THREAD

**Issue by acasa87** [O365/python-o365#207]
Hi, 
I am developing a remote sharepoint connector for a third party company to connect to sharepoint with personal O365 credentials.
Is it possible to use O365 library to connect to sharepoint using url, user and password, to explore folders, 
to upload/download/delete files and to get the last modified time of files?
Thank you in advance
Best regards
a.c.

**Comment by janscas** [comment]
To use O365 you will need to use oauth for authentication (not username and password). This is a requirement set by Microsoft.

You can connect to sharepoint sites and retrieve some info by url and some other methods. The actions allowed are limited by the microsoft graph api:

https://docs.microsoft.com/en-us/graph/api/resources/sharepoint?view=graph-rest-1.0

**Comment by janscas** [comment]
closing this as there is no response
