### ISSUE TITLE
ERR: sharepoint.py Site.get_list_by_name always returning an empty list

### ISSUE THREAD

**Issue by jtweeder** [O365/python-o365#209]
I am happy to PR this fix, but as I am new to sharepoint, and O365 I wanted to submit as an issue first.  

Able to authenticate, and connect to sharepoint site as expected (already got a token in this example)
```python
from O365 import account
acct = Account((app_id, app_pw))
spSite = acct.sharepoint().get_site('root','pathtosite')
spList = spSite.get_list_by_name('listName')
```

If I provide a gibberish name in listName it fails with a client error that it cannot find it as I would expect.   But when I use a real list name it only returns [].

Looking at the returns for Site.get_list_by_name and Site.get_lists they are identical 
```python
return 
[self.list_constructor(parent=self, **{self._cloud_data_key: lst}) for 
     lst in data.get('value', [])]
```

The response from `self.con.get(url)` is not the same in both cases.  Site.get_list_by_name only has a return of a single dictionary containing the list parameters, and does not contain the 'value' key.

In my local copy I have simple changed the return of Site.get_list_by_name to not use the list iteration and pass the `data` object directly to the list_constructor as follows:

(line 394 of sharepoint.py)
```python
return self.list_constructor(parent=self, **{self._cloud_data_key: data})
```

Again happy to submit as a PR if you would prefer to review the code in context, but I wanted to make sure I was not causing the issue first.

**Comment by janscas** [comment]
That's true!

Do you want to submit the PR with this fix? or should I fix it?

Thanks!

**Comment by jtweeder** [comment]
I will submit it.  Just wanted to verify I was on the right track before I started firing off PRs.
