### ISSUE TITLE
Query >> Flagged Messages Mapping

### ISSUE THREAD

**Issue by TheSanjo** [O365/python-o365#215]
Hi 

The search below is not possible due to a missing mapping. 

https://graph.microsoft.com/v1.0/me/mailFolders/inbox/messages?$filter=flag/flagStatus eq 'flagged'

This could simply be fixed by adding the flag to the mappings in the query class. 

```
class Query:
    """ Helper to conform OData filters """
    _mapping = {
        'from': 'from/emailAddress/address',
        'to': 'toRecipients/emailAddress/address',
        'start': 'start/DateTime',
        'end': 'end/DateTime',
        'flag': 'flag/flagStatus'
    }

```

**Comment by janscas** [comment]
Done! Thanks
