### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by TheSanjo** [O365/python-o365#216]
Do you have any plans for adding functionality for Notes?  These are Outlook Notes and not OneNote notes.  

Thanks 
Sanjo

**Comment by janscas** [comment]
If ms graph or office 365 rest api offers this functionality maybe in the future...

Check this:

https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

**Comment by janscas** [comment]
Closing this as it's not available neither in ms graph or office 365 api

**Comment by AnishDe12020** [comment]
So I found out that an OneNote REST API exists now [here](https://docs.microsoft.com/en-us/graph/api/resources/onenote-api-overview?view=graph-rest-1.0). So can we get it implemented with the library now? Also if it is gonna take a lot of time or not going to happen, can you let me know if I can use some workaround to use the REST API with using auth from this library?

**Comment by janscas** [comment]
Not planned but PR are welcome.

**Comment by Feelixe-tin** [comment]
I've created a [PR](https://github.com/O365/python-o365/pull/688), please consider contributing to fork if you would like this functionality.
