### ISSUE TITLE
Readme docs - ApiComponent

### ISSUE THREAD

**Issue by asishm** [O365/python-o365#219]
Is the README out of date for ApiComponent?

The doc states

```py
class CustomClass(ApiComponent):
    _endpoints = {'my_url_key': '/customendpoint'}
    
    def __init__(self, *, parent=None, con=None, **kwargs):
        super().__init__(parent=parent, con=con, **kwargs)
```
but when running the `do_some_stuff` method which uses `self.con`, there seems to be no attribute called `con`. I look at the source code for `ApiComponent` and there is no required keyword arg called `con`. Is the documentation out of date?

**Comment by janscas** [comment]
Yep you are right.

An ApiComponent only needs a "protocol" and a "main_resource". The connection is (maybe or maybe not) needed by your CustomClass.

I'll change this.
