### ISSUE TITLE
Excel

### ISSUE THREAD

**Issue by mattarderne** [O365/python-o365#220]
Any chance for supporting Excel Online (or a quick nudge in the right direction if it is currently possible)

I've tried using [this](https://github.com/O365/python-o365/blob/master/examples/storageDownloadFile) but can't seem to get it working. I'm able to Oauth and send emails, but can't get any further.

For what its worth, the [graph-explorer](https://developer.microsoft.com/en-us/graph/graph-explorer) indicates that a GET to following endpoint should return results:
```shell
https://graph.microsoft.com/v1.0/me/drive/items/{workbook-id}/workbook/worksheets/{00000000-0001-0000-0000-000000000000}/range(address='A1:C5')
```

**Comment by janscas** [comment]
Yes, we can add this in the near future.

**Comment by mattarderne** [comment]
Great, I think it will drive some significant usage as there is currently not really an effective way of getting data out of Excel Online, and your API seems to be really user friendly compared to the alternatives. 
Thanks!

**Comment by janscas** [comment]
I'm beginning this.

Note however that excel manipulation through ms graph is only supported for business accounts.

**Comment by mattarderne** [comment]
Thanks for the update

**Comment by janscas** [comment]
Closing this as the api is almost complete.

**Comment by mattarderne** [comment]
@janscas thanks let me know if I can be of help to test
