### ISSUE TITLE
Getting messageID 

### ISSUE THREAD

**Issue by ChrisMellor68** [O365/python-o365#225]
Hi

Is it possible to get the message ID of a message? I read from previous threads that this is an SMTP thing and folks are wanting to set it...

But I want to read it. 

Also the headers, is it possible to get at these? 

Thank you

**Comment by janscas** [comment]
For the moment you can access the message id with: `message.object_id`

In the next release (1.1.6) you will have access to:

1. Message Internet Message ID: The message ID in the format specified by RFC2822.
1. The message headers: only when selecting them through `query.select('internet_message_headers')`

**Comment by janscas** [comment]
v.1.1.6 is available on pypi

**Comment by StevenMapes** [comment]
How does this work with sending? It looks like you still can't set or retrieve the header after sending and have to then go back to the mailbox, check sent items and then try to find the message you just sent based on "to" and rough sent dates.

**Comment by janscas** [comment]
If the underlying api allows that then it can be implemented in O365. Is this somehow available in MS Graph?

**Comment by StevenMapes** [comment]
So the [Send Mail page](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http) says they support the Internet Message Headers and the [RFC it links](https://datatracker.ietf.org/doc/html/rfc2076#section-3.12) to to includes the Message-ID header on page 10 referencing RFC's 822 and 1036 but setting them does not appear to work when sending. Or at least it appears that setting message.internetMessageHeaders before sending doesn't actual set them and I couldn't find examples of setting headers on send that work
