### ISSUE TITLE
Drive method - get_root_folder returns root of OneDrive and not SharePoint?

### ISSUE THREAD

**Issue by slash5k1** [O365/python-o365#228]
Hi, 

Following the example I have created some code as follows:

```
class O365Account():
    def __init__(self, client_id=client_id,
                 client_secret=client_secret, scopes=scopes):
        self.client_id = client_id
        self.client_secret = client_secret
        self.account = Account(credentials=(client_id, client_secret))
        self.account.is_authenticated ## we have a saved token to work with

        self.sharepoint = self.account.sharepoint()
        self.site = self.sharepoint.get_site('xxxxxxxxxxxxx.sharepoint.com','/sites/PlayPen')

account = O365Account()
playpen = account.site

print (playpen.get_default_document_library().get_root_folder().get_items())
```

I would have assumed I would get a listing of the files at the root of the default document library however I actually get a listing of my Onedrive?

Bug or have I misunderstood the intent of your methods ?

**Comment by slash5k1** [comment]
As a workaround, making use of the method list_document_libraries and then calling get_root_folder on the default "Documents" library achieves what I thought the above code snippet would do.

```
for library in playpen.list_document_libraries():
    if library.name == "Documents":
        print (library.get_root_folder().get_items())
```

**Comment by janscas** [comment]
Yep, you catch a bug.

For the moment, just add `request_drive=True` to the call to `get_default_document_library()`

I'll commit a fix.

Thanks

**Comment by janscas** [comment]
This bug is fixed in the last release on pypi (v.1.1.6)

**Comment by janscas** [comment]
Just for clarification: in v1.1.6 there's no need to add the `request_drive=True` to work.
