### ISSUE TITLE
Mailbox - can't query message "body"

### ISSUE THREAD

**Issue by KirbyFears** [O365/python-o365#230]
Though subject is easy to query, I don't see any documented way to query the message body. The obvious approach using mailbox queries does not work. I've tried many attributes names for the body, for example:
```
query = mailbox.new_query('body').contains('word')
query = mailbox.new_query('body_html').contains('word')
query = mailbox.new_query('body_content').contains('word')
query = mailbox.new_query('body/content').contains('word')
```

All of these attempts return 400 Client Error.

`messages  = mailbox.get_messages(limit=25, query=query)`
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/users/(omitted@company.com)?%24top=25&%24filter=contains%28body%2C+%27change%27%29 | Error Message: Invalid filter clause

Is there a different attribute to query, or is this a bug?

**Comment by janscas** [comment]
user search.

```python 
query = mailbox.q().search('word')  # search in subject, from and body.
query = mailbox.q().search('body:word')  # just search body
```

**Comment by KirbyFears** [comment]
Ah, very helpful. The only downside of search is that I can't use additional filters. E.g. "mail within the last 5 days with "word" in the body".

Is there any plan to enable filter queries against the body text, which would enable query chaining?

Thanks!

**Comment by janscas** [comment]
Yep, that's something imposed by Microsoft:

https://docs.microsoft.com/en-us/graph/query-parameters?toc=./ref/toc.json&view=graph-rest-1.0#search-parameter

Filters on body text are not allowed by Microsoft.

It's nonsense I know ... But Microsoft sets the game rules.

**Comment by KirbyFears** [comment]
Okay this works. I can actually make complex search criteria using AND, OR, NOT, etc.

`mailbox.new_query().search('body:word AND received>=2019-04-05')`

Thank you!

**Comment by janscas** [comment]
> mailbox.new_query().search('body:word AND received>=2019-04-05')

Didn't know this! the microsoft docs said received is not searchable... 

Thanks

**Comment by KirbyFears** [comment]
[Examples for combining queries in searches](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#using-multiple-property-restrictions-within-a-kql-query)

I'm unfortunately not able to get full timestamps working despite the docs saying it should work:  `received>=2019-04-05Thh:mm:ss`

[date formats](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference#date-or-time-values-for-properties)

**Comment by janscas** [comment]
You're looking at the Sharepoint REST Api docs,  which do not apply for this library.
We actually use Microsoft Graph.

**Comment by KirbyFears** [comment]
Yep, sorry. The graph search example on "received" field only shows a time-less date. And the format is nonstandard. Seems out of sync with the other microsoft APIs.

**Comment by janscas** [comment]
> Yep, sorry. The graph search example on "received" field only shows a time-less date. And the format is nonstandard. Seems out of sync with the other microsoft APIs.

Well, you can always filter by code.
