### ISSUE TITLE
problem with message.save_message

### ISSUE THREAD

**Issue by cccmir** [O365/python-o365#232]
Hi,

When trying save message after changing is_read property, nothing happens.
when searched I've found the following issue #194 and after looking at the code
I believe the problem is with the allowed_changes set that values there are not cased by the casing function.

see the below example, when i use it on an read message it doesn't change to unread
```
acc = Account(credentials, token_backend=token_backend, protocol=protocol_office)
mailbox = acc.mailbox()
msg = inbox.get_message()
msg.is_read = False
msg.save_message()
```

**Comment by janscas** [comment]
> I believe the problem is with the allowed_changes set that values there are not cased by the casing function.

Yep, that was the problem.
Fixed now. Will be on pypi on the next version release.

**Comment by cccmir** [comment]
Thanks for the quick response.

may I ask when is the next scheduled release?

**Comment by janscas** [comment]
Don't know. Maybe a week or so.

**Comment by janscas** [comment]
But the change is straighforward, meanwhile patch your version.
