### ISSUE TITLE
Update documentation examples

### ISSUE THREAD

**Issue by MartyMacGyver** [O365/python-o365#235]
As I've gone through the documentation and tried examples, I've found that there are some typos in the code that should be corrected. The following is what I've happened upon so far, but it's not comprehensive.

- Typos:

    versiones = file.get_versions()

Ought to be `versions`

    print(item.dimensione)  # print the image dimensions

Ought to be `dimensions`

- Generally, it'd be useful for the variables used to be consistent throughout the document (e.g., `protocol` vs `my_protocol`, `drive` vs `my_drive`, etc.)

- It would be useful to show the required (or typical) scopes for the various examples (e.g., `onedrive` for OneDrive).

**Comment by janscas** [comment]
Done.

> * It would be useful to show the required (or typical) scopes for the various examples (e.g., `onedrive` for OneDrive).

This is indeed a very good enhance.


Thanks!
