### ISSUE TITLE
Move email to another folder?

### ISSUE THREAD

**Issue by chinguetti** [O365/python-o365#236]
Is there any way to move an email to a different folder?

It is supported by Microsofts API:
https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/mail-rest-operations#MoveMessage

OST https://outlook.office.com/api/v2.0/me/messages/{message_id}/move

**Comment by janscas** [comment]
Yes 
I think it’s message_instance.move().

But check the api: help(message_instance)

**Comment by janscas** [comment]
Solved?

**Comment by Naveen0217** [comment]
Issue is still exists, their is no endpoint /method for move single email to specific folder.
