### ISSUE TITLE
Error on Authentication

### ISSUE THREAD

**Issue by KPxto** [O365/python-o365#237]
<img width="731" alt="error" src="https://user-images.githubusercontent.com/42779734/56866333-3a02d180-69ae-11e9-902f-724eefdfb1e8.png">

On authentication phase, when I have to visit the URL and give consent to the app, please note what happens to me. Any idea on how I can solve this?

Thanks!!

**Comment by janscas** [comment]
Don’t prefix “offline_access”

**Comment by KPxto** [comment]
![code](https://user-images.githubusercontent.com/42779734/56866473-ea250a00-69af-11e9-84eb-8e6497534f14.jpg)

This is the script I tried...something wrong?

I am new to python and may be missing basic steps. Thanks!

**Comment by janscas** [comment]
Instead of “https://graph..../offline_access” pass just “offline_access”.

Just for the offline acces one

**Comment by KPxto** [comment]
<img width="719" alt="lbherror" src="https://user-images.githubusercontent.com/42779734/56866561-ea71d500-69b0-11e9-81ce-52b7d1933702.png">

Now I got this. I am trying to access the e-mail of my company in order to automate some messages.

**Comment by janscas** [comment]
I can see that you are passing your email as the client_id in credentials.

You don't have to pass your email. Read the instructions carefully and try again.

**Comment by KPxto** [comment]
Thanks!

**Comment by Ehigie** [comment]
Hey I am getting a similar error 

what is the proper  documentation to be following here ? 

https://github.com/O365/python-o365#authentication
or https://o365.github.io/python-o365/latest/html/index.html?

either one of these gave me a different uri link to use and I quite confused ...

![image](https://user-images.githubusercontent.com/45437761/57188118-d7826780-6ebe-11e9-8986-0591001eaa8a.png)

**Comment by janscas** [comment]
I'm sorry, the readme of the project is the most up-to-date info,

So, just check this: https://github.com/O365/python-o365#authentication

**Comment by Ehigie** [comment]
This helped. I was able to authenticate last night.

Thank you
