### ISSUE TITLE
Problems with Timezones

### ISSUE THREAD

**Issue by gmaron** [O365/python-o365#238]
When I try to iterate the generator object after ```get_events()``` method, it throws me the next error: 

```
File "./lib/python3.7/site-packages/O365/calendar.py", line 1652, in <genexpr>
    for event in data.get('value', []))

File "./lib/python3.7/site-packages/O365/calendar.py", line 868, in __init__
    cc('recurrence'), None))

File "./lib/python3.7/site-packages/O365/calendar.py", line 124, in __init__
    get_windows_tz(self.protocol.timezone))

File "./lib/python3.7/site-packages/O365/utils/windows_tz.py", line 510, in get_windows_tz
    "Can't find Iana TimeZone " + iana_tz.zone)

pytz.exceptions.UnknownTimeZoneError: "Can't find Iana TimeZone America/Argentina/Buenos_Aires"
```

And I fixed adding `America/Argentina/Buenos_Aires` in the ```IANA_TO_WIN``` array`/site-packages/O365/utils/windows_tz.py`

**Comment by gmaron** [comment]
Here is the dateTimeTimeZone resource type
* https://docs.microsoft.com/en-us/graph/api/resources/datetimetimezone?view=graph-rest-1.0

And Buenos Aires appears as `America/Argentina/Buenos_Aires`

**Comment by janscas** [comment]
Ok, I’ll add these timezone and double check all the others.

Thanks!

**Comment by janscas** [comment]
ok, I've found this timezones that where not included in the library.

Thanks

```
America/Indiana/Indianapolis
America/Argentina/Buenos_Aires
Europe/Kyiv (Kiev)
Asia/Toshkent (Tashkent)
Asia/Kathmandu
Asia/Astana (Almaty)
Asia/Yangon (Rangoon)
```

**Comment by aufbakanleitung** [comment]
When I run a Python program with O365 on IBM Cloud Functions I get the error _"pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'"_

I don't really know what to do about this as this is in the cloud. Though it is running in an OpenWhisk Docker container, so I guess technically I do have a lot of options. But I don't see how I could do anything about the timezone. The IBM Cloud servers are situated in London, if that helps.

Does anyone have any idea?

The entire error:
_account = Account(credentials)  # Access to mailbox connected to credentials: hveer@cokeccep.com",
File \"/usr/local/lib/python3.6/site-packages/O365/account.py\", line 32, in __init__",
type) else protocol",
File \"/usr/local/lib/python3.6/site-packages/O365/connection.py\", line 204, in __init__",
**kwargs)",
File \"/usr/local/lib/python3.6/site-packages/O365/connection.py\", line 90, in __init__",
self.timezone = timezone or get_localzone()  # pytz timezone",
File \"/usr/local/lib/python3.6/site-packages/tzlocal/unix.py\", line 131, in get_localzone",
_cache_tz = _get_localzone()",
File \"/usr/local/lib/python3.6/site-packages/tzlocal/unix.py\", line 125, in _get_localzone",
raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')",
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'"_
