### ISSUE TITLE
Is it possible to integrate sending mail with a MUA

### ISSUE THREAD

**Issue by maitra** [O365/python-o365#240]

**Comment by maitra** [comment]
Trying to get ideas on how to integrate the sending of e-mail using O365 and my MUA. For instance, how can I integrate it with thunderbird or sylpheed (which is what i use)?

**Comment by janscas** [comment]
No idea... sorry

**Comment by maitra** [comment]
I apologize but how do the authors recommend using this package to send mail? Do they use a MUA? Is there an example that can be mimicked?

**Comment by janscas** [comment]
I don’t get it. Use python. Just that.

**Comment by maitra** [comment]
For writing and keeping copies of sent and received e-mails, it  is useful to have a MUA such as mutt, thunderbird or sylpheed or claws-mail. It also provides for a more manageable and user-friendly interface. Therefore, I am wondering how to integrate that with python. So, how does one read and the write the e-mail after getting it down from python or before sending to python?

**Comment by janscas** [comment]
This is completely out of the scope of this project. I can’t help you.

**Comment by maitra** [comment]
Don't see why it is at least indirectly not within the scope of this project, but I very much appreciate your trying to help. Thanks again!
