### ISSUE TITLE
Is it possible to get all the reference & reply message id of the current mail?

### ISSUE THREAD

**Issue by nishanttayal** [O365/python-o365#243]
There is a requirement to track the entire conversation and I observed in outlook properties that there is a tag called References which contains the message id of all the previous emails which are typically present as text below your current mail. Just wondering if we can get the reference and reply internet message id while reading messages.

**Comment by janscas** [comment]
In each message instance you have a `message.conversation_id` property.
You can filter messages with this property like so:

```python
q = mailbox.q('conversation_id').equals('my_conversation_id')
messages_in_conversation = mailbox.get_messages(limit=10, query=q)
```

**Comment by nishanttayal** [comment]
@janscas - Thank You, it works perfectly in my use case.

**Comment by RandomNameUser** [comment]
Unfortunately this doesn't include the conversation order, so it's not quite enough to reconstruct the conversation flow.  Looking at the docs (https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0) there is a conversationIndex property that seems like it would help, but looking at it with the GraphExplorer it's not just an index but something different, not sure how to interpret it. The whole conversation concept seems pretty complex, as it mixes lots of different things where people reply to each other, not just emails...

Unfortunately I need this for my app. :( Any other hints on how to reconstruct the order and which message replies to which other message? Thanks!

**Comment by janscas** [comment]
Did you try to sort on conversationIndex?
It seems you should achieve this by sorting on that field

**Comment by RandomNameUser** [comment]
That will give you a set of all the messages in a conversation, but I don't see how it will give you the order within the conversation. 

I ended up solving it through using the In-Reply-To internet message header, which gives a reference to the message that is being replied to. Given that I'm keeping track of all the messages I've seen already anyway that works ok for me.

Thanks!
