### ISSUE TITLE
A problem with scopes?

### ISSUE THREAD

**Issue by tarikaltuncu** [O365/python-o365#244]
Hi!

I'm exploring  the API using this module.
I can get mailbox folders but I cannot get_messages because of the error below

```
ERROR:O365.connection:Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/mailFolders/Inbox/messages?%24top=25 | Error Message: Access is denied. Check credentials and try again.
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-20-26cf27c8af8a> in <module>()
----> 1 ib.get_messages()

```

I have ` 'Mail.ReadWrite', 'Mail.ReadWrite.Shared' ` scopes.

What could be a problem?

**Comment by janscas** [comment]
It should work.

Can you paste the code used?

**Comment by tarikaltuncu** [comment]
Hi!

Here it is:

```
credentials = (client, secret, )
from O365 import Account

scopes = [
    'Mail.ReadWrite', 'Mail.ReadWrite.Shared', 
]

account = Account(credentials)
account.connection.token_backend.delete_token()

if not account.is_authenticated:  # will check if there is a token and has not expired
    # ask for a login
    account.authenticate(scopes=scopes)
```
> Visit the following url to give consent:
> https://login.microsoftonline.com/common/oauth2/v2.0/authorize?blabla..
> Input the response url and return
> Authentication Flow Completed. Oauth Access Token Stored. You can now use the API.
> 
```
for folder in mb.get_folders():
    print(folder)
    
```
> Archive from resource: me
> Conversation History from resource: me
> Deleted Items from resource: me
> Drafts from resource: me
> Inbox from resource: me
> Junk Email from resource: me
> Outbox from resource: me
> Sent Items from resource: me

```
mailbox = account.mailbox()

for folder in mailbox.get_folders():
    print(folder)
    for message in folder.get_messages():
        print(message.subject)
        break
```

> Archive from resource: me

> Client Error: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/mailFolders/blabla=/messages?%24top=25 | Error Message: Access is denied. Check credentials and try again.
> ---------------------------------------------------------------------------
> HTTPError                                 Traceback (most recent call last)
> <ipython-input-6-a7360c2b9d7c> in <module>()
>       3 for folder in mailbox.get_folders():
>       4     print(folder)
> ----> 5     for message in folder.get_messages():
>       6         print(message.subject)
>       7         break
> 
> ~/.pyenv/versions/3.6.3/envs/general_3/lib/python3.6/site-packages/O365/mailbox.py in get_messages(self, limit, query, order_by, batch, download_attachments)
>     202                 params.update(query.as_params())
>     203 
> --> 204         response = self.con.get(url, params=params)
>     205         if not response:
>     206             return iter(())
> 
> ~/.pyenv/versions/3.6.3/envs/general_3/lib/python3.6/site-packages/O365/connection.py in get(self, url, params, **kwargs)
>     667         :rtype: requests.Response
>     668         """
> --> 669         return self.oauth_request(url, 'get', params=params, **kwargs)
>     670 
>     671     def post(self, url, data=None, **kwargs):
> 
> ~/.pyenv/versions/3.6.3/envs/general_3/lib/python3.6/site-packages/O365/connection.py in oauth_request(self, url, method, **kwargs)
>     656             self.session = self.get_session()
>     657 
> --> 658         return self._internal_request(self.session, url, method, **kwargs)
>     659 
>     660     def get(self, url, params=None, **kwargs):
> 
> ~/.pyenv/versions/3.6.3/envs/general_3/lib/python3.6/site-packages/O365/connection.py in _internal_request(self, request_obj, url, method, **kwargs)
>     621                 if self.raise_http_errors:
>     622                     if error_message:
> --> 623                         raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
>     624                     else:
>     625                         raise e
> 
> HTTPError: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/me/mailFolders/blabla=/messages?%24top=25 | Error Message: Access is denied. Check credentials and try again.

Thanks

**Comment by janscas** [comment]
**First:**
I've run the same code you did from scratch and It worked for me.

Are you using a corporate account? Maybe the administrator of your account does enforce some restrictions on the ability to read emails. Check it with IT.

**Second:**

> scopes = [
>     'Mail.ReadWrite', 'Mail.ReadWrite.Shared', 
> ]
First of all, if you don't use the scope helpers (see [Permissions and Scopes](https://github.com/O365/python-o365#permissions-and-scopes)), you have to provide the protocol used in the scopes.

It works if you don't but It can stop working anytime (microsoft requires the 'https://graph.microsoft.com/' part in scopes)

Like this:

```python
scopes = [
    'https://graph.microsoft.com/Mail.ReadWrite', 
    'https://graph.microsoft.com/Mail.ReadWrite.Shared'
]
```

**Third:**
If you don't want to re-authenticate every hour, add the 'offline_access' scope both in the app registration and in the authentication process.

See [Authentication Flow](https://github.com/O365/python-o365#authentication-flow)

**Comment by tarikaltuncu** [comment]
Hi,

Thanks for all the three.

It's strange because I give access to my own API using [the guide](https://login.microsoftonline.com/common/oauth2/nativeclient?code=OAQABAAIAAADCoMpjJXrxTq9VG9te-7FXEUENrrREJ_5Gkqv86Zx_5OIBK8c7vXnpSepwsKhl2UD1eYI3NuPqf2hOclflL2o-Q2J_EyVgT4kl1z142Jm5LD0e92atIHXPjD78y9iJvTKuF20Mfw28t7FboqeNCA7kFNDVInfPfxZUNA44syEacdnlcLqA5CM2UdwOPPgT1YLSk3howN1aTD0WDjmkxZbrUYTb2wYrEm4nXTtgModVgsg-YaFHBNwapShnNen-rcmirjiKfv95N5MATQi4-pz_gPS5irPMLNB17O2pGmm8GkDd28f-gTtVQYeryYwGxb9hP4gS9Qd9-U3tJdpkGmraTQqJAa-Siojpv5w7c9tcu40Vu7GO4Pa-HYnW_XBo45iUmTbfIMwdKLcaPOfJsLht9lnkg9jNtuxmsaNFxuF9h2hDfRXv77nLCxebrG8sCNJ23o4tN5AQOh3V6JfRBXf31FoXvl6ob005IwYlUYW3ndCSSCdT7iI72bL8psXFw0Gktw06-nIWsw0YpXlBCFoDpQyiV2fdsJJur0DtKHwm86VZgiQOSQ8W9jJfrdtBVc1eS1dYqN2CGYsD8fK8PgffkCuAaspN_hS0AW8u9NG9zrT7IXw_Fc3WJ9pd_G24RVg3eHGsKcfQwtnb1PGummmAvf9qI-xsoGBZWld9JOEECgeZodi988eF__kWPL7pYqsH_jztV9hG6FxcvtEVo2lInVhzg8g4EjRgbYynEeumW8ogA2Z78VxSSFDQI6IjjcTaGXv8N74S-81sMm6i88KNAPMuItCHKzUwLF-7hbaFXNDuViFNK1kwxt6YddK3c5HvvRYhealCqhtmleVEYBXViiyoVyB04tLCA5mBdPeJ0RhyX2laB45BQpZdriI8_bwKRtDA82X-n8LF3n5ziEHMIAA&state=TVygmJUgOOS0794OVa2bya9qN2s84B&session_state=4d907b11-d028-4e07-9602-b7234996cb0a) for all endpoints including all Mail.* api types and Granted Admin consent for all users as well..

Is there a way to debug this to understand where the problem is?

Best,

**Comment by janscas** [comment]
Men you pasted a link with your access token. I've removed it. For security reasons, clear the secret and generate a new one.

**Comment by janscas** [comment]
> Is there a way to debug this to understand where the problem is?

Well, the Microsoft servers are responding with a 403 (forbidden), so I don't know.

- ¿Did you add the correct permissions on the app registration process?
- ¿Did you register your app exactly as described in the Authentication section of the Readme?
- ¿Can you try for example to access the calendar and try to read calendars and events?
- ¿Are you using a corporate account, personal or educational?

**Comment by tarikaltuncu** [comment]
Thanks!

* I added all permissions actually to the app and granted admin consent to all.
* Yes, I was trying to paste the readme [section](https://github.com/O365/python-o365#authentication) 
* I successfully can get calendar event. Btw, the scopes you put in [Calendar section in readme ](https://github.com/O365/python-o365#calendar) says has scope_helper `calendar_shared_all' but if I use it in scores I get error saying I didn't provide correct scopes. Thus, I used `calendar' scope helper code from the [docs site](https://o365.github.io/python-o365/latest/html/usage/account.html?highlight=scope#setting-scopes). I think it's not up-to-date on the readme.
* How can I check that? I guess it's corporate. The owner registered it though GoDaddy domain registration.

**Comment by tarikaltuncu** [comment]
I'm not sure what's different now, but I regenerated another app and it worked this time.

Thanks for your help and sorry for the fuss,
Tarik

**Comment by janscas** [comment]
> * I successfully can get calendar event. Btw, the scopes you put in [Calendar section in readme ](https://github.com/O365/python-o365#calendar) says has scope_helper `calendar_shared_all' but if I use it in scores I get error saying I didn't provide correct scopes. Thus, I used `calendar' scope helper code from the [docs site](https://o365.github.io/python-o365/latest/html/usage/account.html?highlight=scope#setting-scopes). I think it's not up-to-date on the readme.

This is because maybe you're not using the last version of the library (1.1.9 at this time).

**Comment by tarikaltuncu** [comment]
What's more interesting is, I didn't add delegated permissions for Calendar access on the app registration page this time. (because I only needed Mail)

But I had already added 'calendar' to the scopes while authenticating. It could bring calendar events in this settings as well.

This means, it's not must to add delegated permission at the time of app creation.
Best,
Tarik

**Comment by janscas** [comment]
> This means, it's not must to add delegated permission at the time of app creation.

??? First time I've heard of this. It should be imposible.

Maybe that's because you already previously consent access to calendars with the same app_id?

Don't know, but will try that.
