### ISSUE TITLE
Slow import time

### ISSUE THREAD

**Issue by janscas** [O365/python-o365#245]
**The current state of the library (v. 1.1.9) has a slow import time.**

This is due to some facts:
1. The library is currently importing all the sub-modules at once inside "\_\_init__". Even if the user only wants to send an email, all the sub-modules (calendar, excel, etc) will be loaded.
1. The library requires to install BeautifulSoup4. Even if its only needed when parsing emails body text.
1. The O365.utils subpackage also imports all inside the "\_\_init__".

We plan to change this in library version 2.0 by:

1. Only import Account, Connection, MsGraphProtocol and some minor things in the library "\_\_init__". The rest will be imported dynamically inside the Account method calls. Any other library object should be imported manually from the sub-modules.
1. We will remove BeautifulSoup4 from the requirements. The current methods that return soup objects will return strings. Maybe, the library will try to import it when using the methods that requires a html parser. 
1. Remove almost all from O365.utils.\_\_init__. All should be imported internally by referencing to the sub-module inside utils.

This means there will be some backward breaking changes... but those are needed.

**Comment by jtweeder** [comment]
Happy to help anyway I can that would help your effort.  I am much more familiar with the sharepoint sub-module, but I am sure I can read through the others to help with the enhancements.

I can also do any validation and testing if needed as you get changes pushed.

**Comment by janscas** [comment]
@jtweeder Thanks! sure you can help with a lot of things. You can check the [Project](https://github.com/O365/python-o365/projects/2) to see the "In Progress", "To do" and "Ideas".

Also there are many things to improve.

Tell me if you need any guidance!

**Comment by janscas** [comment]
Another thing that slows the library is the usage of `pkg_resources`.

We will remove this also

**Comment by janscas** [comment]
Update: 

1. The imports are now optimised on account.py.
1. I can't remove BeautifulSoup4 from the dependencies as it's used for inserting the replies at the top of the message when replying emails.
1. the imports on O365.utils will not be changed as those are minor.

**Comment by janscas** [comment]
Fixed on 2a92dda8d7735e53793e7d07e122c52776f78156
