### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by Legaia77** [O365/python-o365#249]
Hi team, 
i'm having auth error. Any idea?
my code:
![image](https://user-images.githubusercontent.com/47090314/57808472-d01e5200-7739-11e9-8ae3-38011113b502.png)

i got the following error
![image](https://user-images.githubusercontent.com/47090314/57808534-f17f3e00-7739-11e9-9eee-2004a85a57df.png)

thank you

**Comment by softsan** [comment]
@Legaia77 - Have you set up your reply (Redirect URL) in Azure -> App registration?

**Comment by janscas** [comment]
As @softsan said, it's saying that you didn't set any redirect url:

Follow [the guide](https://github.com/O365/python-o365#authentication-flow) and try again.

Please report back

**Comment by Legaia77** [comment]
Done! Sorry for not having noticed
Thank you!! both of you :)
