### ISSUE TITLE
ValueError: Protocol not provided to Api Component

### ISSUE THREAD

**Issue by softsan** [O365/python-o365#250]
Hi,
I've trouble initializing `Calendar` or `Schedule` object.
It throws me an error: `ValueError: Protocol not provided to Api Component
`

I follow your documentation and example but it uses Account for authentication and account.schedule to get schedule data. but problem with Account is that it print the url and then user needs to paste it in browser and copy the resultant url to console. So it is not suitable for what i am trying to achive.
I am trying to achive it through the web based authentication. I already have one web app where i want to integrate the calendar and events. So  i am using `Flask` and want to do it web based. So There are two end points:
1) /api/O365api - For authentication and redirecting to my other end point (2)  if success
2) /api/GetCode - This method is where i want to get the appropriate calender/schedule object and further getting events etc.

Below is my code:

```
from O365 import Connection
from O365 import Calendar, Schedule, MSGraphProtocol
from O365.utils import ApiComponent
import datetime as dt
from O365 import oauth_authentication_flow
from flask import Blueprint
from flask import redirect, request 
 

outlookApi = Blueprint('outlook_api', __name__)

appid = 'MYAPPID'
clientSecret = 'MYAPPSECRET'

credentials = (appid, clientSecret)
scopes = ['https://graph.microsoft.com/Calendars.Read']

def redirectToMs(url):
    return redirect(url, code=302)


@outlookApi.route("/api/O365api")
def O365Api():
    global con
    con = Connection(credentials, scopes=scopes)
    url = con.get_authorization_url(scopes, redirect_uri="http://localhost:31544/api/GetCode")
    return redirectToMs(url)

@outlookApi.route("/api/GetCode")
def GetCode():
    val = request.url
    result = con.request_token(val)
    if result:
        print('Authentication Flow Completed. Oauth Access Token Stored. '
              'You can now use the API.')

        # s = Schedule() ## Even this is also not working and trhwoing same exception
        c = Calendar() ## This line throws the exception
        q = c.new_query('start').greater_equal(dt.datetime(2018, 5, 20))
        q.chain('and').on_attribute('end').less_equal(dt.datetime(2018, 5, 24))

        birthdays = c.get_events(query=q,
                                 include_recurring=True)   
        for event in birthdays:
            print(event.subject)
    else:
        print('Something go wrong. Please try again.')

    return 'Success'
```

**Comment by janscas** [comment]
First of all I recommend you to include the 'offline_access' scope. If not, the token will only be valid for an hour. After an hour you will need the user to re-authenticate.

The error you are facing is because every `ApiComponent` (like Schedule, Calendar, Message, Event, etc.) needs an explicit `Protocol`. Also the `Schedule` needs a `Connection` instance.

If you want to use the `Schedule` object alone you will need to initialise the instance with what is called a "parent" or a "connection" object. The parent can be any other already initialised `ApiComponent` that has a `Connection` instance. If you provide a parent, then the instance will get the protocol and the connection from it. If you provide a connection, then you will also need to provide the protocol.

So, the `Schedule` instance no matter what, will need a connection.
```python
# instead of just Calendar()
con = Connection(credentials)  # no need to pass the scopes here because the user is already authenticated at this point.
schedule = Schedule(con=con, protocol=MSGraphProtocol)
# ...
```

Nevertheless I strongly recommend to always start with an Account instance:
```python
account = Account(credentials)  # this will create a connection for you
schedule = account.schedule()
# ...
```

Also, to use this library in a web environment I recommend to use a custom [TokenBackend](https://github.com/O365/python-o365#token-storage)

With a custom token backend you can store the token inside your database instead in the file system.

**Comment by softsan** [comment]
Hi,

Thanks for the quick reply and tips.

So, the Schedule instance no matter what, will need a connection.

#instead of just Calendar()
con = Connection(credentials)  # no need to pass the scopes here because the user is already authenticated at this point.
schedule = Schedule(con=con, protocol=MSGraphProtocol)
# ...

I tried that but then it gives me following error:
`RuntimeError: Fist call 'get_authorization_url' to generate a valid oauth object
`

I took a Global `con` object as i am using it in web based scenario so first endpoint will handle the authentication and second endpoint will get perform schedule event operation. In my case, it is just one time hit from other web page, get events details and finish. 
so finally i am able to achive with this:

```
protocol = MSGraphProtocol()
schedule = Schedule(con=con, protocol=protocol)
```

**Comment by janscas** [comment]
> Nevertheless I strongly recommend to always start with an Account instance:
> But problem with me is that i am using web based scenario, AFAIK, the account instance is used in console app.

You can use the connection inside account using `account.con`. Don’t call account.authenticate as it’s console based.



> I tried that but then it gives me following error:
> RuntimeError: Fist call 'get_authorization_url' to generate a valid oauth object

This only triggers if you call the method request_token. You don’t have to called once you are authenticated and the token remains valid.

**Comment by softsan** [comment]
Okay so i changed my implementation according to your advise.

so in my first endpoint i used account(global):
```
@outlookApi.route("/api/O365api")
def O365Api():
    global account
    account = Account(credentials,scopes=scopes)
    url = account.con.get_authorization_url(scopes, redirect_uri="http://localhost:31544/api/GetCode")
    return redirectToMs(url)
```

and in another endpoint (redirect url or call back url):
```
@outlookApi.route("/api/GetCode")
def GetCode():
    s = account.schedule() # This throws exception
    # s = Schedule(con=account.con, protocol=MSGraphProtocol) Even this also failed
    birthdays = s.get_events(include_recurring=False)   
    for event in birthdays:
           print(event.Subject)
```

but then it throws following error on `s=account.schedule()`:

`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/me/calendar/events?%24top=25 | Error Message: Access token is empty.`

**Comment by janscas** [comment]
> s = account.schedule()

This does not make any requests, It's imposible this could throw the error you said.





> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/me/calendar/events?%24top=25 | Error Message: Access token is empty.

This is thrown by `schedule.get_events`

The error tells that you don't have the access token.

**Comment by softsan** [comment]
Thanks for quick reply. Yeh sorry my mistake, it throws error by `schedule.get_events` 
so how do i get the access token from that point?

Sorry to bother you.

**Comment by janscas** [comment]
If you didn't set any TokenBackend, then when you complete the authentication,  a file is stored in the file_system next to the calling script called o365_token.txt (by default).

This file should contain the token.

That's why I told you before, that you have to implement a TokenBackend to store and retrieve the token from the database as web servers usually can't rely on file systems (as there could be multiple machines).

**Comment by janscas** [comment]
Just note that implementing your own TokenBackend is straightforward:

To implement a new TokenBackend:

1. Subclass BaseTokenBackend

2. Implement the following methods:
    - __init__ (don't forget to call super().__init__)
    - get_token: this should set self.token and return a Token instance or None
    - save_token: this should store the self.token in the desired backend.
    - Optionally you can implement: check_token and delete_token

**Comment by softsan** [comment]
okay i have implemented `FileSystemTokenBackend` (to quickly see if it creates file) as per the [link](https://github.com/O365/python-o365#token-storage) your provided:

`UPLOAD_FOLDER = '/Users/myuser/projects/api/uploads'`

then use the UPLOAD_FOLDER as token_path but it didnt create any file in specified folder.
```
def O365Api():
    global account
    token_backend = FileSystemTokenBackend(token_path=UPLOAD_FOLDER, token_filename='my_token.txt')
    account = Account(credentials,token_backend=token_backend)
    url = account.con.get_authorization_url(scopes, redirect_uri="http://localhost:31544/api/GetCode")
    return redirectToMs(url)
```

**Comment by janscas** [comment]
Check the logs of the return value on `connection.request_token` If it return True, then the authentication process was successfully completed and the token should be stored. If returns False something failed.

Set the logs level to DEBUG to see the whole process.

Anyway I think you are not doing it right:

In a web environment It is posible that a request may go to a server and hit the first endpoint (Where you set the global account object. But the next request maybe hits another server (you will have multiple workers), then the second request does not have the account object initialised.

It is better to avoid global variables in web development. Just re-create the account object in each method.

**Comment by softsan** [comment]
Sorry but i m new to python. 
I tried using `connection.request_token ` then it works.
 
I have two endpoints 
1.Login - to login and ask user consent 
2.Authorize - Call back/redirect url to get the token and perform the task.

I am doing a python rest api and this api will be consumed by another web app in angular.

Please see blow revised code:

```
def redirectToMs(url):
    return redirect(url, code=302)


@outlookApi.route("/api/Login")
def Login():
    global account
    token_backend = FileSystemTokenBackend(token_path=UPLOAD_FOLDER, token_filename='my_token.txt')
    account = Account(credentials,token_backend=token_backend)
    url = account.con.get_authorization_url(scopes, redirect_uri="http://localhost:31544/api/Authorize")
    return redirectToMs(url)


@outlookApi.route("/api/Authorize")
def Authorize():
     val = request.url
    result = account.con.request_token(val)
   ## Question is if account is not global then how can i get access token here. also how to use token_backend here?
```

now if i define third function to which can be called by the angular web client and then i need to check whether user is authenticated, if so get the token and get the calendar events and dump it into my database. if user is not authenticated then do the authentication flow.

so question is which method i should use to passed the stored token at later stage and get the relevant events of user's calendar?

Thanks.

**Comment by janscas** [comment]
Do you have a database?

If yes:
- Subclass a new BaseTokenBackend that will implement the logic to save and retrieve the token from the database as I told you early.

If no:
- If your web app uses multiple instances then you pretty much need a database.

The O365 library will obtain a token:

1. When the user authenticates:
    - This will be a fresh new token so It will be cached in the instance and stored in the TokenBackend for later use.
1. When the user makes the first request (like getting events):
    - Whenever a new instances of the O365 library makes the first request will check if there is a token cached. If not, it will retrieve it from the TokenBackend and then cache it for later use.
1. When the token is expired:
    - The library will then request a new token, cache it and store it in the TokenBackend.

All this works automatically. You just have to define the TokenBackend.

You can check if there is a token stored in the TokenBackend and if this token is valid with `account.is_authenticated` property.

```python
account = Account(credentials)
if account.is_authenticated:
    events = account.schedule().get_events(limit=25)
    # ...
else:
   return redirect('O365 authentication endpoint')
```

I think this is the most I can help you.

**Comment by janscas** [comment]
Can we close this?

**Comment by softsan** [comment]
Yes sorry for delayed reply but everything works as expected. Thanks a lot for your help so far and the great library.

**Comment by janscas** [comment]
@softsan Check [Different Authentication Flows](https://github.com/O365/python-o365#different-authentication-flows)
