### ISSUE TITLE
Precedence grouping in queries

### ISSUE THREAD

**Issue by matthewgdv** [O365/python-o365#251]
In the docs (https://docs.microsoft.com/en-us/onedrive/developer/rest-api/concepts/filtering-results?view=odsp-graph-online) it seems to be implied that the REST api this library is wrapped around supports precedence grouping in queries, but as far as I've been able to see, the fluent Query class provided in this library doesn't seem to offer a way to build up queries of this type.

For example, just to get my point accross:

    From.contains("John") and (not From.contains("Doe") or not IsRead)

The query this pseudo-code represents is not simply read left to right, but rather would give precence to the 'or' operator. It should return all unread messages sent by someone with "John" in their address, but only return read messages if that person's address doesn't also contain "Doe".

If I've overlooked some method that allows the user to specify precedence grouping in the query filter could someone let me know? Otherwise, could I suggest this as a possible enhancement if anyone thinks it might be valuable?

Thanks in advance.

**Comment by janscas** [comment]
Hi, thanks.

This is not implemented yet. I'll add it.
