### ISSUE TITLE
Certificate based authentication instead of client_id and secret

### ISSUE THREAD

**Issue by gitsreerao** [O365/python-o365#252]
Hi,
Does the module support certificate based auth in addition to the client_id and secret method? If so, do you have an pointers on how to go about it?

**Comment by janscas** [comment]
Can you provide the url to the docs web of this authentication method?

**Comment by gitsreerao** [comment]
https://docs.microsoft.com/en-us/graph/auth/auth-concepts

... the section below mentions public/private key...
Application Secret: A password or a public/private key pair that your app uses to authenticate with the Microsoft identity platform.

**Comment by janscas** [comment]
We don't have this option for the moment and we don't have plans to implement it.

However PR are welcome.
