### ISSUE TITLE
Location property doesn't work correctly

### ISSUE THREAD

**Issue by gmaron** [O365/python-o365#253]
I am trying to put the 'location' property in the event but it doesn't show correctly in the calendar.
It looks like this

![It looks like this](https://user-images.githubusercontent.com/5501354/58431788-cc69c400-8085-11e9-9bb5-fcd1c61c3362.png)

I just set the property and call the __save()__ method. 

Could you help me whit this ?

Thanks!

**Comment by janscas** [comment]
What do you expect?

**Comment by gmaron** [comment]
I want to prepare the location to be indicated. In that way, it's just the street, number and state but I want to see something like this...

<img width="367" alt="image" src="https://user-images.githubusercontent.com/5501354/58565253-c6e6b800-8204-11e9-8144-84fc3434df0a.png">

**Comment by janscas** [comment]
True

I've run some test and the problem is that the location was not correctly implemented. It was set only the display name of the location.

I'll commit a fix, release to pypi and report back.

**Comment by janscas** [comment]
Update the library to version 1.1.10.

To set the location just:

```python
event.location = {
     'address': {
          'street': 'Avenida 1 750',
          'state': 'La plata',
          'postalCode': '1900',
          'city': 'Buenos Aires',
          'countryOrRegion': 'Argentina',
     }
}
```

If you are using Graph protocol this should work.
If you are using Outlook Rest Api then the keys of the dict should be "PascalCased".

To check what 'location' accepts check [this](https://docs.microsoft.com/en-us/graph/api/resources/location?view=graph-rest-1.0)

**Comment by gmaron** [comment]
Thanks @janscas! 
I'll update the lib and try it again.
