### ISSUE TITLE
Is it possible to store downloaded e-mail and store in MAILDIR or MH folders?

### ISSUE THREAD

**Issue by maitra** [O365/python-o365#254]
Hello, I want to download my e-mail using the REST or GRAPH API and store it in folders locally. I prefer the Maildir or MH format. Is it possible? How Thanks!

**Comment by janscas** [comment]
You can download your email.
But you will have to transform the data from the `Message` class to whatever format you want.

The format used is out of the scope of this library. You will have to implemented on your own or use another packages.

**Comment by maitra** [comment]
Thanks! Is there an example on how to use this library with other packages? It does not have to be in the MAILDIR or MH formats. I am just trying to see how to get started. Thanks!

**Comment by janscas** [comment]
Not that I know

**Comment by maitra** [comment]
Thank you. So there is no example of this library, being used anywhere and for anything? I find this very puzzling. Maybe I  am not understanding something. Thanks!

**Comment by janscas** [comment]
I don’t know any blog or anywhere where you may find a complete example. 

But, the readme have all the pieces you need. 

You can also check projects with this library as a dependency.

**Comment by maitra** [comment]
> I do have scripts and apps running with O365 at work, but I can’t share them.
> 
> But, the readme have all the pieces you need.

Thanks!
 
> You can also check projects with this library as a dependency.

Do you know how I can figure out the projects with this library as a dependency?

**Comment by janscas** [comment]
Using github. Can’t tell you right now the exact place.
