### ISSUE TITLE
generator' object has no attribute 'get_messages'

### ISSUE THREAD

**Issue by ajwillo** [O365/python-o365#255]
Hello,

version 1.1.9

I am receiving the below error when querying for messages. its odd because the first time I run this code I got the messages, now subsequent times I do not. even If I quit and restart shell it now fails every time, any ideas?

Thanks

```
>>> account = Account((credentials.username, credentials.password))
>>> mailbox = account.mailbox()
>>> query = mailbox.new_query().on_attribute('subject').contains('Bobby B').chain('and').on_attribute('is_read').equals(False)
>>> messages = mailbox.get_messages(query=query)
>>> # check if we have any messages
>>> unread_count = 0
>>> for message in messages.get_messages():
...  message
...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
AttributeError: 'generator' object has no attribute 'get_messages'
>>>
>>> messages
<generator object Folder.get_messages.<locals>.<genexpr> at 0x7fc971c9b570>
>>>
```

**Comment by janscas** [comment]
???

You are trying to exectute `get_messages` on a collection of messages. You are calling get_messages twice.

```python
for message in mailbox.get_messages(query=query):
   print(message)
```

**Comment by ajwillo** [comment]
apologies, that was a typo:

see below, I cannot index messages, but I can loop through them once, the second time I try to loop through them, empty

>>> credentials = get_credentials('oncall mailbox 365 api')
>>> # Setup connection object
>>> account = Account((credentials.username, credentials.password))
>>> mailbox = account.mailbox()
>>> query = mailbox.new_query().on_attribute('subject').contains('Bobby B').chain('and').on_attribute('is_read').equals(False)
>>> messages = mailbox.get_messages(query=query)
>>> message=messages[0]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
TypeError: 'generator' object is not subscriptable
>>> messages
<generator object Folder.get_messages.<locals>.<genexpr> at 0x7fda393ef3b8>
>>> for i in messages:
...  i
...
Subject: Accepted: Bobby B
Subject: Accepted: Bobby B
>>> for i in messages:
...  i
...
>>>

**Comment by janscas** [comment]
I know. That was a breaking change introduced....

The fact is that the methods that potentially return a large of items now return generators instead of lists.

You can call `list(generator)` to be able to iterate more than once.

**Comment by ajwillo** [comment]
I see, thank you!
