### ISSUE TITLE
I keep getting Number of Attachments unknown

### ISSUE THREAD

**Issue by mash2k3** [O365/python-o365#256]
When i check an email with no attachments the number of attachments are 0
But with 1 attachment or more it always returns Unknown

My goal is to download the attachments on a local folder but i cant get past that error

im using the script below
message.attachments.download_attachments

Can someone shed some light please

Thank you

**Comment by janscas** [comment]
It is not an error.

When downloading a message you just get the property `has_attachments` which will tell you if this message has attachments or not. The number of attachments is still unknown.

You then have to download them to see them.
```python
print(len(message.attachments))  #  cero!
message.attachments.download_attachments()
print(len(message.attachments))  #  != 0

for att in message.attachments:
    print(att)
```

If you want all the attachments in advance you can:
```python
messages = message.get_messages(limit=250, download_attachments=True):
# now all the downloaded messages will have the attachments downloaded as well
```

**Comment by mash2k3** [comment]
Thank you that helped alot, one last question. i am trying to save the attachments to a folder on windows computer. I have the following code below, it runs with out error but i dont see the attachment saved in the folder.  Am i missing anything?

`path = os.path.expanduser("~\Desktop\Attachments")
for message in inbox.get_messages(10):
    if message.subject == 'test':
        message.attachments.download_attachments()
        for att in message.attachments:
            att.save(os.path.join(path,str(att)))
`

**Comment by mash2k3** [comment]
> It is not an error.
> 
> When downloading a message you just get the property `has_attachments` which will tell you if this message has attachments or not. The number of attachments is still unknown.
> 
> You then have to download them to see them.
> 
> ```python
> print(len(message.attachments))  #  cero!
> message.attachments.download_attachments()
> print(len(message.attachments))  #  != 0
> 
> for att in message.attachments:
>     print(att)
> ```
> 
> If you want all the attachments in advance you can:
> 
> ```python
> messages = message.get_messages(limit=250, download_attachments=True):
> # now all the downloaded messages will have the attachments downloaded as well
> ```

Thank you that helped alot, one last question. i am trying to save the attachments to a folder on windows computer. I have the following code below, it runs with out error but i dont see the attachment saved in the folder.  Am i missing anything?

```
path = os.path.expanduser("~\Desktop\Attachments")
for message in inbox.get_messages(10):
    if message.subject == 'test':
        message.attachments.download_attachments()
        for att in message.attachments:
            att.save(os.path.join(path,str(att)))
```

**Comment by mash2k3** [comment]
Never mind i got it working

**Comment by DevNitish** [comment]
> Never mind i got it working

I am also getting the "Number of Attachments: unknown". Could you please share your solution ?

**Comment by DevNitish** [comment]
Never mind I got it working. And this is how:

You need to provide `download_attachments=True` in code.

messages = mailbox.get_messages(limit=23,   download_attachments=True)

**Comment by janscas** [comment]
Attchments are not downloaded by default and the api does not provide any method to know the number lf attachments without downloading them
