### ISSUE TITLE
Timezone issues on IBM Cloud Functions

### ISSUE THREAD

**Issue by aufbakanleitung** [O365/python-o365#257]
This issue is similar to: https://github.com/O365/python-o365/issues/238 

When I run a Python program with O365 on IBM Cloud Functions I get the error "pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'"

I don't really know what to do about this as this is in the cloud. Though it is running in an OpenWhisk Docker container, so I guess technically I do have a lot of options. But I don't see how I could do anything about the timezone. The IBM Cloud servers are situated in London, if that helps.

Does anyone have any idea?

The entire error:
__account = Account(credentials)  # Access to mailbox connected to credentials",_
_File \"/usr/local/lib/python3.6/site-packages/O365/account.py\", line 32, in __init__",
type) else protocol",_
_File \"/usr/local/lib/python3.6/site-packages/O365/connection.py\", line 204, in __init__",
**kwargs)",_
_File \"/usr/local/lib/python3.6/site-packages/O365/connection.py\", line 90, in __init__",_
_self.timezone = timezone or get_localzone()  # pytz timezone",_
_File \"/usr/local/lib/python3.6/site-packages/tzlocal/unix.py\", line 131, in get_localzone",_
__cache_tz = _get_localzone()",_
_File \"/usr/local/lib/python3.6/site-packages/tzlocal/unix.py\", line 125, in get_localzone",_
_raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')",_
_pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'"_

**Comment by janscas** [comment]
Pass the timezone you want to use to the protocol:

```python
protocol = MSGraphProtocol(timezone='Europe/Paris')
account = Account(credentials, protocol=protocol)
```

**Comment by aufbakanleitung** [comment]
Thanks! But it doesn't accept those settings.
```
# IBM Cloud Functions doesn't have a timezone so it needs to be set explicitly
protocol = MSGraphProtocol(timezone='Europe/Paris')
account = Account(credentials=credentials, protocol=protocol, main_resource='some@ema.il')
```
Returns:
```
  File "/Users/hermanvanderveer/anaconda3/lib/python3.6/site-packages/O365/mailbox.py", line 215, in <genexpr>
    for message in data.get('value', []))
  File "/Users/hermanvanderveer/anaconda3/lib/python3.6/site-packages/O365/message.py", line 220, in __init__
    local_tz) if self.__created else None
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'str'
```

**Comment by janscas** [comment]
I’m sorry, my fault. You don’t have to pass a string to timezone but an actual timezone.

So pass pytz.timezone('Europe/Paris')

**Comment by aufbakanleitung** [comment]
Mmh sadly I'm still getting the error on Cloud Functions:
```
# IBM Cloud Functions doesn't have a timezone so it needs to be set explicitly
protocol = MSGraphProtocol(timezone=pytz.timezone('Europe/Paris'))
account = Account(credentials=credentials, protocol=protocol, main_resource='some@email.nl')
```
Gives:
```
File \"/usr/local/lib/python3.6/site-packages/O365/connection.py\", line 204, in __init__",
**kwargs)",
File \"/usr/local/lib/python3.6/site-packages/O365/connection.py\", line 90, in __init__",
self.timezone = timezone or get_localzone()  # pytz timezone",
File \"/usr/local/lib/python3.6/site-packages/tzlocal/unix.py\", line 131, in get_localzone",
_cache_tz = _get_localzone()",
File \"/usr/local/lib/python3.6/site-packages/tzlocal/unix.py\", line 125, in _get_localzone",
raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')",
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'",
```

**Comment by aufbakanleitung** [comment]
If I try debugging locally to the _timezone/get_localzone_ decision moment on line 90 in O365/connection.py I can clearly see it working. But somehow its behavior is different in the cloud.
![debugging O365](https://user-images.githubusercontent.com/9026889/58920849-4a883380-8734-11e9-877d-ac094d2992a6.png)

**Comment by aufbakanleitung** [comment]
LOL, I just ran the same thing again and now it works. Classic!

Anyways, thanks for your help man! Cheers!
