### ISSUE TITLE
Error: (mismatching_state) CSRF Warning! State not equal in request and response

### ISSUE THREAD

**Issue by Zolous** [O365/python-o365#258]
I've been receiving the following error since updating to 1.1.9 (and now 1.1.10).

_Unable to fetch auth token. Error: (mismatching_state) CSRF Warning! State not equal in request and response._

``from O365 import Account``
``credentials = (<app_id>,<app secret>)``
``account = Account(credentials)  ``
``account.authenticate(scopes=['basic', 'message_all'])``

I receive a URL, past it into the browser and receive a blank page with a URL formatted like the following

_https://login.microsoftonline.com/common/oauth2/nativeclient?code=< code>_

and pasting that in yields the aforementioned error.

My API permissions (for testing) are the same from the help docs.
![image](https://user-images.githubusercontent.com/8576684/58917955-666ce480-86f6-11e9-9557-98dd0bf407c6.png)

Any help, or guidance would be greatly appreciated!

Most of my experience using this was before the move to Azure, so I'm still completely new when it comes to how OAUTH2/Azure in general need to be setup.

**Comment by janscas** [comment]
This does not happen to me.

Can you paste the dependencies versions you are using?

**Comment by Zolous** [comment]
No problem:

O365==1.1.10
  - beautifulsoup4 [required: >=4.0.0, installed: 4.7.1]
    - soupsieve [required: >=1.2, installed: 1.7.3]
  - python-dateutil [required: >=2.7, installed: 2.7.5]
    - six [required: >=1.5, installed: 1.12.0]
  - pytz [required: >=2018.5, installed: 2018.9]
  - requests [required: >=2.0.0, installed: 2.21.0]
    - certifi [required: >=2017.4.17, installed: 2018.11.29]
    - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
    - idna [required: >=2.5,<2.9, installed: 2.8]
    - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.1]
  - requests-oauthlib [required: >=1.2.0, installed: 1.2.0]
    - oauthlib [required: >=3.0.0, installed: 3.0.1]
    - requests [required: >=2.0.0, installed: 2.21.0]
      - certifi [required: >=2017.4.17, installed: 2018.11.29]
      - chardet [required: >=3.0.2,<3.1.0, installed: 3.0.4]
      - idna [required: >=2.5,<2.9, installed: 2.8]
      - urllib3 [required: >=1.21.1,<1.25, installed: 1.24.1]
  - stringcase [required: >=1.2.0, installed: 1.2.0]
  - tzlocal [required: >=1.5.0, installed: 1.5.1]
    - pytz [required: Any, installed: 2018.9]

**Comment by janscas** [comment]
I wasn't able to reproduce this.

Please make sure the surl pasted to the console is complete.
That's the only think I can tell you right now.

**Comment by janscas** [comment]
Are you between authentication steps recreating the Connection object (or the Account)?

Thanks

**Comment by janscas** [comment]
closing this as there's no response
