### ISSUE TITLE
Filter attachments on size

### ISSUE THREAD

**Issue by aufbakanleitung** [O365/python-o365#259]
Hi, thanks for making this great library. 

I working on making ServiceNow tickets from e-mails, and I want to add the attachments too. However I don't want to add logo images. I was planning to filter these based on file size, say only add 'size > 10kB', but in debugging it seems there is no 'size' value. Is there a way to do this? If not, I would like to request it as a feature.

_An example were I only want to add attachment 1:_
```
message.attachments = {MessageAttachments} Number of Attachments: 2
  _BaseAttachments__attachments = {list} <class 'list'>: [Attachment: image001.jpg, Attachment: Alta SAP Bartosz.tif]
    0 = {MessageAttachment} Attachment: image001.jpg
    1 = {MessageAttachment} Attachment: Alta SAP Bartosz.tif
```

**Comment by janscas** [comment]
I'll add this.

**Comment by aufbakanleitung** [comment]
Great, thanks!

**Comment by aufbakanleitung** [comment]
I saw someone use the following:
```python
    message.attachments.add('https://www.image.com/email_banner.png')
    att = message.attachments[0]  # get the attachment object
    att.is_inline = True
```
This `att.is_inline` variable would also be useful when trying to filter for company logo's, but it seems it's not available for retrieved attachments.

**Comment by janscas** [comment]
> but it seems it's not available for retrieved attachments.

It is available.
