### ISSUE TITLE
Example of TokenBackend

### ISSUE THREAD

**Issue by TheSanjo** [O365/python-o365#264]
Hi 

Apologies if this is the wrong place to ask this.  Unfortunately, I am really struggling to get my head around creating a **TokenBackend** that stores the token in a database for a User. I have a flask website using the Peewee as an ORM.

I would be very grateful if there were any examples of these that I could use as a template.  

Thank  you for the fantastic module!

**Comment by janscas** [comment]
Assuming this token is stored for each user using your web, and showing the example using sqlite3

## ** IMPORTANT: As the token are private credentials you must store them in a secure way. I don't do this here **

### Also note this was done as an example and it's not optimised.

```python
import sqlite3

class SqliteTokenBackend(BaseTokenBackend):

    def __init__(self, db=None, table=None, column=None, user_id=None):
        super().__init__()  # must call it

        # this can be done in multiple ways ....
        self.db = db
        self.user_id = user_id
        self.get_statement = "SELECT {} FROM {} WHERE user_id = ?".format(column, table)
        self.update_statement = "UPDATE {} SET {} = ? WHERE user_id = ?".format(table, column)
        # etc ...

    def __repr__(self):
        return "{} for user: {}".format(self.__class__.__name__, self.user_id)

    def get_token(self):
        token = None
        con = sqlite3.connect(db)
        cursor = con.cursor()
        cursor.execute(self.get_statement, (self.user_id, ))
        token_str = cursor.fetchone()
        if token_str:
            self token = self.token_constructor(self.serializer.loads(token_str))
        return token

    def save_token(self):
        # same logic as get... Set or update the token info for this user.
        # return true (success) or false (failure)
        return True

    def delete_token(self):
        # optional
        pass

    def check_token(self):
        # optional
        pass
```

**Comment by TheSanjo** [comment]
Excellent, Thank you so much Alejandro!

**Comment by janscas** [comment]
Also check the code for the tokens:

https://github.com/O365/python-o365/blob/master/O365/utils/token.py

**Comment by agn-7** [comment]
@janscas 
I think there are two little issues with your code:

> `import sqlite3

class SqliteTokenBackend(BaseTokenBackend):

    def __init__(self, db=None, table=None, column=None, user_id=None):
        super().__init__()  # must call it

        # this can be done in multiple ways ....
        self.db = db
        self.user_id = user_id
        self.get_statement = "SELECT {} FROM {} WHERE user_id = ?".format(column, table)
        self.update_statement = "UPDATE {} SET {} = ? WHERE user_id = ?".format(table, column)
        # etc ...

    def __repr__(self):
        return "{} for user: {}".format(self.__class__.__name__, self.user_id)

    def get_token(self):
        token = None
        con = sqlite3.connect(db)
        cursor = con.cursor()
        cursor.execute(self.get_statement, (self.user_id, ))
        token_str = cursor.fetchone()
        if token_str:
            self token = self.token_constructor(self.serializer.loads(token_str))
        return token

    def save_token(self):
        # same logic as get... Set or update the token info for this user.
        # return true (success) or false (failure)
        return True

    def delete_token(self):
        # optional
        pass

    def check_token(self):
        # optional
        pass`

 1. It's needed to override the `load_token()` method as it is and `@abstractmethod` in the `BaseToken` class
 2. in the `get_token()` method there is a typo at the end: it should be `self.token = self.token_constructor(self.serializer.loads(token_str))` and `return self.token`

**Comment by janscas** [comment]
> @janscas I think there are two little issues with your code:

I think I wrote that in an early stage of the development of token backends. The methods changed after that. 

But anyway what you mention is correct. Thanks

**Comment by pkstacey** [comment]
Hi. This is brilliant. But, 

(a) don't we need to handle race conditions (as mentioned elsewhere) and introduce a lock flag or timestamp into the schema? ie if a token has been alive for < 60mins (its lifetime as i understand) then just load the existing token... 

(b) user_id also seems redundant as the token is per app rather than per user, as i understand from other posts.

Best and thanks.
