### ISSUE TITLE
Is it possible to change the subject of received e-mails?

### ISSUE THREAD

**Issue by aufbakanleitung** [O365/python-o365#265]
I would like to edit the subject line of received e-mails to add a ticketnumber. I've tried the following options:
```python
message.setSubject("hi")  # AttributeError: 'Message' object has no attribute 'setSubject'  
message.set_subject('hi') # AttributeError: 'Message' object has no attribute 'set_subject'  
message.subject = "hi" # Nothing happens
```
In de [Microsoft Graph documentation](https://docs.microsoft.com/en-us/graph/api/message-update?view=graph-rest-1.0&tabs=cs) regarding Subject I see _"The subject of the message. Updatable only if isDraft = true."_ 

This is clearly a bad sign, but I wanted to check anyways.

**Comment by janscas** [comment]
First of all to know the property and method names of any object type: `help(message)` for example.

Or check the library code. 

Second you can't modify the subject of received messages.

**Comment by aufbakanleitung** [comment]
Oooh, I didn't know that trick! Thanks! ^^
