### ISSUE TITLE
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) using refresh token

### ISSUE THREAD

**Issue by rena2damas** [O365/python-o365#266]
I am running into the error: oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

My token settings are:

```json
{
 "token_type": "Bearer",
...
 "expires_in": 3600,
 "ext_expires_in": 3600,
 "access_token": "xxx",
 "refresh_token": "xxx",
 "expires_at": 1561845080.052145
}
```

Now: 2019-06-30 14:09:04
Expires at: 2019-06-29 21:51:20 (1561845080.052145)

According to the datetimes above, the token is considered to be expired, yet its ```is_expired``` property returns ```False```. For some reason, property ```expiration_datetime``` is adding 90 days to the ```expires_at``` attribute, if ```refresh_token``` attribute is present. This does not seem correct and is causing the token expired error.

**Comment by janscas** [comment]
> I am running into the error: oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired)

In theory you should never hit this error. Because the library will try to refresh the token when is expired.
So each time a TokenExpiredError is raised the library capture this exception and gets another new token using the refresh token.

The `is_expired` property is in fact giving misleading information... on purpose. In the example provided by you, the token is in fact expired. But as long as you have a refresh token in the token you can exchange this for a new token. 

So when `is_expired` property is True the meaning is: 

### This token *and the refresh token* is expired.

So... why is the library adding 90 days to the expired_at info? Because the refresh token lasts 90 days. And therefore you can "use a token" as long as the expiration time + 90 days are within the actual time.

**Comment by rena2damas** [comment]
Hi @janscas 

Thanks a lot for the answer. You are right. After looking at it again, I captured the logic you mentioned. I have to investigate it further to trace where is the refresh token process failing.

**Comment by rena2damas** [comment]
Hi @janscas 

The problem was that was creating an ```Account``` incorrectly. Adding the ```tenant_id``` to the ```Account``` and not the ```authenticate``` method solved the issue.

However, on the way, I found another thing:

```python
protocol = MSOffice365Protocol(default_resource='abc@email.com')
account = Account(credentials, protocol=protocol)
```

Basically the ```default_resource``` attribute is ignored when you create a new Account providing a customized ```protocol```. In the end, the value for ```main_resource``` always prevails. I was expecting Account to inherit the value from Protocol and it does not. Something like:

```python
self.main_resource = protocol.default_resource or main_resource
```

Is this behavior purposely intended?

**Comment by janscas** [comment]
Hi, the resource (it's not the tenant), is defined when creating any instance of the `Account` object or in any other object of the library.

This is on purpose so you can define any different resource at any point. If it's not specified it will inherit the parent resource. For the Account object the resource defaults to 'me'.

Although it's true that the default resource per protocol is not used. 
I'll make the Account object inherit the protocol default_resource if no other resource is provided.

For further info see [Resources](https://github.com/O365/python-o365#resources)

Thanks

**Comment by rena2damas** [comment]
I understood that, it was my mistake and I had that clear. I was just addressing other independent topic: ```default_resource``` of protocol is ignored and ```main_resource``` always defines the type of resource to be used. But you already answered to that:
> I'll make the Account object inherit the protocol default_resource if no other resource is provided.
Hopefully it is considered in the next version

Thank you

**Comment by janscas** [comment]
> Hopefully it is considered in the next version.

It will! Thanks
