### ISSUE TITLE
PushNotification and StreamingSubscription

### ISSUE THREAD

**Issue by rena2damas** [O365/python-o365#267]
Plans for supporting [PushNotification ](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/beta/notify-rest-operations-beta)and [StreamingSubscription](https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/beta/notify-streaming-rest-operations)?

**Comment by janscas** [comment]
No, and no.
