### ISSUE TITLE
oauth_authentication_flow : limit in the number of characters accepted in terminal input() on macos

### ISSUE THREAD

**Issue by llange** [O365/python-o365#268]
When using macos, it seems that the field for the input() prompt (`Paste the authenticated url here:`) is limited to 1024 characters.
This happens when you have a certain number of scopes, the URL that you must paste back may exceed those 1024 characters (in my example: 1087 characters). 

It appears macos specific (cf https://superuser.com/questions/219225/command-limits-when-pasting-into-tcsh-mac-os-x )

I found a workaround [here](https://stackoverflow.com/a/53871077), and indeed when you add `import readline` at the beginning of [connection.py](https://github.com/O365/python-o365/blob/master/O365/connection.py) it did the trick and the limitation vanished.
However, it also works when you `import readline`not in O365, but in your end-user program (be it before, or after, the O365-related imports)

Now there must be an explanation but I did not search for it yet :-)

Any chance you could consider this, either for inclusion in a future version, or in the documentation somewhere for fellow macos users ?

**Comment by janscas** [comment]
Definitively in the docs. Not so sure about adding it to connection.py.

Thanks a lot!

**Comment by janscas** [comment]
Done
