### ISSUE TITLE
Issue while moving email

### ISSUE THREAD

**Issue by johankuy** [O365/python-o365#269]
Hi, I'll start with saying that your library is great. I did find some minor thing that required a fix on for my app.

While moving an Message object to a new folder (Message.move(folder)), the object seems to get detached from the actual email. My guess is that the id of the email changes while the object id seems to remain the same, making any generated url obsolete.  Is there a particular reason you don't update the object id when moving folders?

I'm using graph api btw

**Comment by janscas** [comment]
Thanks a lot! That's a bug.

I'll commit a change that changes the object_id (the id of the message) on the moved message.

**Comment by janscas** [comment]
These is in fact on the Microsoft Graph Api Reference:
https://docs.microsoft.com/en-us/graph/api/message-move?view=graph-rest-1.0&tabs=http

> Move a message to a folder. This creates a new copy of the message in the destination folder and removes the original message.
