### ISSUE TITLE
[feature?] cannot query on collection like Event.categories

### ISSUE THREAD

**Issue by toyg** [O365/python-o365#271]
When I want to retrieve all Event instances with a specific category, I must use a filter like this:
```
categories/any(a:a eq 'Billable')
```

There seems to be no way to express this in a Query. `.iterable()` and `.any()` force me to specify an attribute, which ends up in the filter (e.g. `categories/any(a:a/someattribute eq 'Billable')`), breaking the query.

Is there a different way to specify a filter like this? Maybe the attribute should be made optional...? I tried looking through utils.py but the filter mechanics look pretty obscure.

Edit: I see that I can pass a literal string instead of a Query object to `get_events`, so I guess I can use that. Still, it would be nice if Query could handle this case properly.

**Comment by janscas** [comment]
Yes, you can use the filter parameter instead of using a query instance.

However I agree this should be added to the Query.

Thanks

**Comment by janscas** [comment]
This will be released on version 2.0
