### ISSUE TITLE
mark_as_unread() ?

### ISSUE THREAD

**Issue by jessepink** [O365/python-o365#275]
I know there is a message.mark_as_read() method, but I was wondering how difficult it would be to add a mark_as_unread() method as well?

My use case is that it seems as though when forwarding messages it marks the forwarded messages as read (which is I'm sure the normally desired behavior).

Here is an example of my forwarding code...

    forward_message = message.forward()
    forward_message.to.add('EMAILS_RECIPIENTS')
    forward_message.body = email_html
    new_subject = f'[FORWARDED] {message.subject}'
    forward_message.subject = new_subject
    forward_message.reply_to.add(message.sender.address)
    forward_message.save_draft()
    forward_message.send()

**Comment by janscas** [comment]
the `mark_as_read` it's just an alias for :

```python
message.is_read = False
message.save()
```

I'll add a `mark_as_unread` method but it's completely unnecessary, because you can do the opposite:

```python
message.is_read = True
message.save()
```
