### ISSUE TITLE
Sending Inline Images - Not visible for .png

### ISSUE THREAD

**Issue by sbi-rviot** [O365/python-o365#276]
Hello,
I am using this package to send automated status email.
I am trying to send a status as an image embedded in the body of the email.
I have tried the sample provided (https://pypi.org/project/O365/ - Chapter: Sending Inline Images) but in return I get an email with the image as an attachement, the text but the image in the body of the email is **invisible**. It is there, because I can copy it manually for instance or click on it, but it is not visible :)

Below is my code:

```
    m = account.new_message()
    m.to.add('email@gmail.com')
    m.subject = 'status'
    
    m.attachments.add('status.png')
    att = m.attachments[0]
    att.is_inline = True
    att.content_id = 'status'

    body = """
    <html>
        <body>
            <strong>There should be an image here:</strong></br>
            <p>
                <img src="cid:status">
            </p></br>
            <strong>Or not :)</strong>
        </body>
    </html>
    """
    m.body = body    
    m.send()
```

Any idea what am I doing wrong?
Thank you,
R

**Comment by janscas** [comment]
This works for me:

```python
# ...
msg = account.new_message()
msg.to.add('email@email.com')
msg.attachments.add('myimage.png')
att = msg.attachments[0]
att.content_id = 'myimage'
att.is_inline = True
body = """
<html>
    <body>
        <strong>There should be an image here:</strong>
        <p>
            <img src="cid:myimage">
        </p>
    </body>
</html>
"""
msg.body = body
msg.send()
```

Maybe this depends on the email client used?

I test the above code on gmail and on outlook 2016 and it works as expected.

**Comment by sbi-rviot** [comment]
Interesting.
I am sending it with Outlook and the recipient is Gmail.
I worked my way around it by building a package that convert my pd.df into a very pretty html table that I can then insert as a table to the email.
Thanks!
Renaud

**Comment by alimcmaster1** [comment]
> This works for me:
> 
> ```python
> # ...
> msg = account.new_message()
> msg.to.add('email@email.com')
> msg.attachments.add('myimage.png')
> att = msg.attachments[0]
> att.content_id = 'myimage'
> att.is_inline = True
> body = """
> <html>
>     <body>
>         <strong>There should be an image here:</strong>
>         <p>
>             <img src="cid:myimage">
>         </p>
>     </body>
> </html>
> """
> msg.body = body
> msg.send()
> ```
> 
> Maybe this depends on the email client used?
> 
> I test the above code on gmail and on outlook 2016 and it works as expected.

Interesting this exact same code doesn't seem to work for me using `O365==2.0.15`. Errors before any email is sent with `Error Message: Required property is missing.`. 
Only reference is I'm setting a resource on the message instance. `msg = account.new_message(resource=my_email)`

Any ideas @janscas ?

Ref: https://github.com/O365/python-o365/issues/262

**Comment by janscas** [comment]
It works for me...

the image must be an actual image on your disk or memory.
