### ISSUE TITLE
Bug in 'get_contact_by_email'

### ISSUE THREAD

**Issue by matthewgdv** [O365/python-o365#281]
Heya, I've noticed that on line 712 of address_book.py:

`contacts[0] if contacts else None`

a generator is being tested for truthiness (will always return `True`) and having item access attempted on it (will always raise `TypeError`).

The fix should be as easy as wrapping the previous line in `list()`, like so:

`contacts = list(self.get_contacts(limit=1, query=query))`

where currently it looks like:
`contacts = self.get_contacts(limit=1, query=query)`

Cheers!

**Comment by janscas** [comment]
Thanks a lot!
