### ISSUE TITLE
Inline images not recognized as attachment

### ISSUE THREAD

**Issue by aufbakanleitung** [O365/python-o365#282]
My code basically looks like this:
```python
    for att in message.attachments:
            att.save(att_path)
```
This recognizes all attachments, including inline images, and adds them to a folder. But this only works if the e-mail has actual separate attachments (i.e. you see the paperclip). If the email ónly contains inline image (pasted images, company logo's) it won't add any attachments.

If I had a `if message.has_attachment()` in my code this would make sense, but I don't. 
How do I fix this?

**Comment by aufbakanleitung** [comment]
In the debugger I also see 0 attachments for e-mails with only inline images. This looks like it might be a difficult one.

**Comment by aufbakanleitung** [comment]
Could it have to do with this if-statement in _**message.py**_?
```python
self.__attachments = MessageAttachments(parent=self, attachments=[])
        self.has_attachments = cloud_data.get(cc('hasAttachments'), False)
        if self.has_attachments and download_attachments:
            self.attachments.download_attachments()
```

**Comment by janscas** [comment]
This is not related to this library.

It seems that Microsoft Outlook does not account inline message as attachments.
But... I can't see where the attachment itself is located!!!
It's not on the message hearders and the img tag source is just the cid name.

**Comment by aufbakanleitung** [comment]
The thing is though, as soon as it has one separate attachment it does grab all the inline images as well. So then it does account inline images as attachments.

**Comment by aufbakanleitung** [comment]
Here is an e-mail with just 3 inline images:
![just inline images](https://user-images.githubusercontent.com/9026889/62039383-e3e53a80-b1f7-11e9-83f7-dbc752df14f4.png)

Here is that same e-mail with one more image (hackerman.png) added as an attachment:
![inline and attachment](https://user-images.githubusercontent.com/9026889/62039431-fe1f1880-b1f7-11e9-86a5-9695bb5a5539.png)

So now it suddenly recognizes all attachments, incl inline images. So it really seems to me that there is some kind of check for attachments in _Python O365_ that is causing this behavior. Unless of course _Azure O365_ is handling e-mails with attachments differently than those without.

**Comment by janscas** [comment]
Ok, I've found the issue.

The Graph docs says that the property 'hasAttachments':

> Indicates whether the message has attachments. This property doesn't include inline attachments, so if a message contains only inline attachments, this property is false. To verify the existence of inline attachments, parse the body property to look for a src attribute, such as <IMG src="cid:image001.jpg@01D26CD8.6C05F070">.


Ok. so:

1. When creating the message instance, if the 'hasAttachments' property informed by the server is False, the O365 library will have to inspect the body (in case it's html) and check if there are img tags with source that starts with 'cid:'.
1. If there's something then change the 'hasAttachments' to True.

With these steps It should work.

**Comment by janscas** [comment]
Thanks a lot @aufbakanleitung

**Comment by aufbakanleitung** [comment]
Okay, but now what? Can I just change the value of the `has_attachment` variable to get that behavior? I assume it's already too late at the moment that I receive the `message` object.

**Comment by janscas** [comment]
Grab the latest code from github or wait until the next release... (maybe a week or so)

**Comment by aufbakanleitung** [comment]
Oh, is this the variable you're talking about?
<img width="626" alt="image" src="https://user-images.githubusercontent.com/9026889/62052774-7eed0d00-b216-11e9-8cbb-6705ba40bcd8.png">

**Comment by aufbakanleitung** [comment]
Oh what?! You already fixed it?! Damn, alright I'll grab the latest code from github then ^^

**Comment by janscas** [comment]
> Oh what?! You already fixed it?! Damn, alright I'll grab the latest code from github then ^^

Yeah!
check f5298ba7f395b48ce19ba74973bf7e16ba25bfc9

**Comment by aufbakanleitung** [comment]
Ah, live and learn.

I've just tested your fix, and it totally works!

**Comment by aufbakanleitung** [comment]
How can I see when there is a new release?

**Comment by aufbakanleitung** [comment]
> Grab the latest code from github or wait until the next release... (maybe a week or so)

How can I see when there is a new release.

**Comment by janscas** [comment]
You can check it pypi

**Comment by aufbakanleitung** [comment]
Ah I see. Thanks
https://pypi.org/project/O365/#history
