### ISSUE TITLE
Email retieved with a lot of extra newlines

### ISSUE THREAD

**Issue by aufbakanleitung** [O365/python-o365#284]
When I retrieve an e-mail it adds a lot of extra newlines in the message body. I can simply remove them, but it would perhaps be cleaner to fix this on the library side.

Removal function
```python
def clean_body_text(message):
    try:
        body = message.get_body_text()
    except AttributeError:
        body = ""

    # remove sequential \n symbols
    clean_body = body.replace('\n\n\n\xa0', '').replace('\n\n', '').replace('n\xa0', '')
    return clean_body
```

Example of email body with lots of sequential \n in it: [example_mail_body.log](https://github.com/O365/python-o365/files/3457257/example_mail_body.log)

**Comment by janscas** [comment]
I prefer to leave this out of the library. Because this opens the door to a lot of extra methods to change the content of messages.

Thanks a lot anyway
