### ISSUE TITLE
Get inline image dimensions

### ISSUE THREAD

**Issue by aufbakanleitung** [O365/python-o365#288]
Hi, 

I have a feature request, similar to https://github.com/O365/python-o365/issues/259. For inline images I would like to be able to see the dimensions, so I can filter out signature images based on them.

Thanks again for making this great library ^^

**Comment by janscas** [comment]
If the driveitem it's an image you can access height and width

**Comment by janscas** [comment]
I you get the file and the file is an image then you will have available the properties width and height

**Comment by janscas** [comment]
Closing this as it seems solved
