### ISSUE TITLE
Issue with sharepoint resource syntax

### ISSUE THREAD

**Issue by matt43121** [O365/python-o365#290]
Hi,

I am having some problems understand how the sharepoint resource works. I know vaguely how the requests are setup from a rest point of view with the graph explorer. I am trying to access a folder on a certain sharepoint site. So at the moment I am doing:

`my_protocol = MSGraphProtocol(‘sharepoint:{tenent}.sharepoint.com,80939eb7-90d9-4100-b860-a0a9f340bd1c,344b8dad-ed41-416c-bc8f-2f9f6b751632’)

account = Account(credential=('<client_id>', '<client_secret>', protocol=my_protocol))`

However this is returning the query incorrectly I am wondering if my syntax is incorrect because I know I can use the same site id in the graph explorer and it works fine.

Thanks,

**Comment by janscas** [comment]
You usually get sites using the `get_site` method:

https://github.com/O365/python-o365/blob/master/O365/sharepoint.py#L548

**Comment by matt43121** [comment]
Even when trying to upload a file to one drive for business?

**Comment by janscas** [comment]
No, to use one drive use Storage object

**Comment by matt43121** [comment]
This is what I'm trying to do. I'm trying to access a Sharepoint site's one drive for business.
