### ISSUE TITLE
Did azure change and python-0356 got deprecated? (Autentication/Authorization)

### ISSUE THREAD

**Issue by brunoschroeder** [O365/python-o365#291]
Hello guys.

I am having trouble authenticating to Outlook when using IHOL. I have thoroughly described the issue in an issue in IHOL. Please help!
https://github.com/eikenb/ihol/issues/1

Thank you in advance!

Kind regards,

Bruno

**Comment by MaxWinterstein** [comment]
To get the reference here also, i am pretty sure you are missing your `tenant_id`.

Working example for me, as of right now:
```python
from O365 import Account
from O365 import MSOffice365Protocol

my_protocol = MSOffice365Protocol(api_version='v2.0')
credentials = ('XXX', 'XXX')
emailAcc = Account(credentials=credentials, protocol=my_protocol, tenant_id="XXXX")

if not emailAcc.is_authenticated:
    emailAcc.authenticate(scopes=['basic', 'Mail.Send'], tenant_id="98644696-e673-4999-9c61-543f95a8ca01")

m = emailAcc.new_message()

m.to.add('winterstein@m2p.net')
m.subject = 'Testing auto email!'
m.body = 'Email Test'
m.send()
```

**Comment by janscas** [comment]
@MaxWinterstein is right. did this solve it @brunoschroeder ?

**Comment by brunoschroeder** [comment]
Yes! Authentication with IHOL is working now!

New version of IHOL rocks!

Thank you very much! Cheers!
