### ISSUE TITLE
Connection.request_token: missing_code-error despite single tenant application

### ISSUE THREAD

**Issue by sean2dre** [O365/python-o365#294]
Hi there! I'm trying to deal with microsoft graph api via O365. As far as I understand the usage of an Authorization Code is not necessary when dealing with single tenant applications. My code is the following:

```
credentials = ('client_id', 'client_secret')
scopes = ['http://graph.microsoft.com/Mail.Read']
protocol_graph = MSGraphProtocol()
scopes_graph = protocol_graph.get_scopes_for(scopes)
con = Connection(credentials, scopes=scopes_graph, tenant_id='tenant_id')
url, state = con.get_authorization_url()
con.request_token(url)
```

request_token gives me: 
_Unable to fetch auth token. Error: (missing_code) Missing code parameter in response._
despite there's no need of a code since dealing with single tenant application. 

I'm able to get a token via:
```
payload = {'client_id': 'client_id',
           'client_secret': 'client_secret',
           'grant_type': 'client_credentials',
           'scope': 'Mail.Read'}

r = requests.get('https://login.microsoftonline.com/tenant_id/oauth2/token',
                 data=payload, headers={'Content-Type': 'application/x-www-form-urlencoded'})
token = json.loads(r.content)['access_token']
```

Is there a workaround to set the token manually without usage of request_token? Many thanks!

**Comment by teamoo** [comment]
This is what works for me:

`
client_id = config['msgraph']['client_id']
client_secret = config['msgraph']['client_secret']
auth_token_url = 'https://login.microsoftonline.com/'+config['msgraph']['tenant_id']+'/oauth2/v2.0/token'
resource_uri = config['msgraph']['resource_uri']
scopes = ['https://graph.microsoft.com/.default']

credentials = (client_id, client_secret)
msgraph_payload={
                        'client_id' : client_id,
                        'client_secret' : client_secret,
                        'scope' : 'https://graph.microsoft.com/.default',
                        'grant_type' : 'client_credentials'
                    }

token_backend = FileSystemTokenBackend(token_path='', token_filename='msgraph.token')

account = Account(credentials, token_backend=token_backend, tenant_id=config['msgraph']['tenant_id'],scopes=scopes,main_resource='')

account.protocol.default_resource = ''
account.main_resource = ''

if not account.is_authenticated:
    r = account.connection.get_session().post(url=auth_token_url,data=msgraph_payload)

    token = r.json()
    
    if 'access_token' in token:
        account.connection.token_backend.token['access_token'] = token['access_token']
        account.connection.token_backend.token['expires_at'] = int(time.time() + token['expires_in'])
        account.connection.token_backend.save_token()  `

**Comment by janscas** [comment]
I've just implement a Client Credential Flow on the library: 96140da0fc15eb08aa6e74a509a9d7a870cf2d4f

**... But I can't test it, can either of you test if it works?**

Example:

```python
credentials = ('cli_id', 'cli_secret')
token_backend = FileSystemTokenBackend(token_filename="msgraph.token")
scopes = ["https://graph.microsoft.com/.default"]
account = Account(credentials, token_backend=token_backend, tenant_id='my_tenant_id', scopes=scopes, main_resource="")

account.protocol.default_resource = ""
account.main_resource = ""

if not account.is_authenticated:
    account.authenticate(auth_flow_type='backend')
    # same as using 'account.con.request_token_client_credentials_flow()'

# use the library... 
```

Thanks!

**Comment by teamoo** [comment]
1. the `Account.authenticate` method still needs a scope argument according to your code (`TypeError: authenticate() missing 1 required keyword-only argument: 'scopes'`). So I changed it to `account.authenticate(auth_flow_type='backend',scopes=scopes)`. I think you should provide a default value (`=None`) in the `authenticate` Method?
2. Unfortunately it is not working:
`Unable to fetch auth token. Error: (invalid_request) AADSTS90014: The required field 'scope' is missing.` Problem is that the oauth2_session has no scope set. This could be fixed by adding the `scope=scopes[0]` parameter to the `fetch_token` method call called by `request_token_client_credentials_flow`.
**But I think this is wrong.**  I think the right way would be to create the `BackendApplicationClient` with the `scope` parameter.

**Comment by teamoo** [comment]
Another question: The tokens for this flow always last one hour, and there is no refresh token mechanism. Would the module automatically request a new token if the old one is expired?

**Comment by janscas** [comment]
> 1\. the `Account.authenticate` method still needs a scope argument according to your code (`TypeError: authenticate() missing 1 required keyword-only argument: 'scopes'`). So I changed it to `account.authenticate(auth_flow_type='backend',scopes=scopes)`. I think you should provide a default value (`=None`) in the `authenticate` Method?

That's true because if you pass None to the authenticate scopes parameter, the authenticate method will still use the scopes provided on the Account init




> 2\. Unfortunately it is not working:
>     `Unable to fetch auth token. Error: (invalid_request) AADSTS90014: The required field 'scope' is missing.` Problem is that the oauth2_session has no scope set. This could be fixed by adding the `scope=scopes[0]` parameter to the `fetch_token` method call called by `request_token_client_credentials_flow`.

I don't understand this error. The [scopes are passed to the Oauth2Session object on in the get_session method](https://github.com/O365/python-o365/blob/master/O365/connection.py#L493) (same for the web flow... that works).

Anyway.. passing the scope parameter to fetch token solves this.



> 2\. **But I think this is wrong.**  I think the right way would be to create the `BackendApplicationClient` with the `scope` parameter, which is currently not supplied.

No, not needed.



> Another question: The tokens for this flow always last one hour, and there is no refresh token mechanism. Would the module automatically request a new token if the old one is expired?

Yes, It should ask for another access token. I'll see how to do it.

**Comment by janscas** [comment]
I changed the code: 58bba12aefcca6268d2615a196e808720e18a08a.
Also now scopes is optional when using `account.authenticate`: be3280c29d008d86189e44ffb956280bc8e4209a

Now the flow is different:

You just indicate to the account (or Connection if you prefer) object that the grant flow is of type 'backend' and this will instruct everything to work as expected.

```python
credentials = ('cli_id', 'cli_secret')
token_backend = FileSystemTokenBackend(token_filename="msgraph.token")
scopes = ["https://graph.microsoft.com/.default"]
account = Account(credentials,
                  token_backend=token_backend,
                  tenant_id='my_tenant_id',
                  scopes=scopes,
                  main_resource="",
                  auth_flow_type='backend')  # this is the only change!

account.protocol.default_resource = ""
account.main_resource = ""

if not account.is_authenticated:
    # if you don't pass scopes here they will be inherinted from the ones provided on the Account init.
    if account.authenticate():
        print('Authenticated!!')
    else:
        raise RuntimeError('Error when authenticating')

# use the library...
```


Can you check if it works? 

Thank you a lot.

I've yet to implement the auto-refresh feature.

**Comment by janscas** [comment]
Auto-refresh is now implemented: a685e38ad04b827fb4fb23662af2d543cd70a445

Also if you specify `auth_flow_type='backend'` to an Account instance the scope ('.default') is automatically set for you.

**Comment by teamoo** [comment]
Wow, thanks a lot!

**Comment by janscas** [comment]
Let me know if it works please!

**Comment by teamoo** [comment]
The authentication works, couldn't test the auto-refresh yet.

Now the call got very simple:

```credentials = (client_id, client_secret)

o365_account = Account(credentials,tenant_id=config['msgraph']['tenant_id'],auth_flow_type='backend')

if not o365_account.is_authenticated:
    o365_account.authenticate()```

**Comment by janscas** [comment]
ok! great!

I will upload a version to pypi soon.

Thanks

**Comment by teamoo** [comment]
Thanks a lot. If you would like to update the README, the methods are described here:

- `[auth_flow_type='backend']`(https://docs.microsoft.com/en-us/graph/auth-v2-service)
- `[auth_flow_type='web']`(https://docs.microsoft.com/en-us/graph/auth-v2-user)

**Comment by teamoo** [comment]
Seems like the refresh does not work:

```Unable to fetch auth token. Error: local variable 'scopes' referenced before assignment
Refresh for Client Credentials Grant Flow failed.
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.5/site-packages/O365/connection.py", line 611, in _internal_request
    **kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 395, in request
    http_method=method, body=data, headers=headers)
  File "/home/xxx/.local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/xxx/myscript.py", line 932, in <module>
    for ad_person in global_address_list.get_contacts(limit=1, query=q):
  File "/home/xxx/.local/lib/python3.5/site-packages/O365/address_book.py", line 678, in get_contacts
    response = self.con.get(url, params=params)
  File "/home/xxx/.local/lib/python3.5/site-packages/O365/connection.py", line 703, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/O365/connection.py", line 692, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/O365/connection.py", line 623, in _internal_request
    raise RuntimeError('Token Refresh Operation not working')
RuntimeError: Token Refresh Operation not workin```

**Comment by teamoo** [comment]
I just happended to run into auto refresh and it seems like it is not working (double-checked that I had the latest commit from master):

```
Unable to fetch auth token. Error: local variable 'scopes' referenced before assignment
Refresh for Client Credentials Grant Flow failed.
Traceback (most recent call last):
  File "/home/xxx/.local/lib/python3.5/site-packages/O365/connection.py", line 611, in _internal_request
    **kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 395, in request
    http_method=method, body=data, headers=headers)
  File "/home/xxx/.local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 
  File "/home/xxx/.local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/xxx/myscript.py", line 932, in <module>
    for ad_person in global_address_list.get_contacts(limit=1, query=q):
  File "/home/xxx/.local/lib/python3.5/site-packages/O365/address_book.py", line 678, in get_contacts
    response = self.con.get(url, params=params)
  File "/home/xxx/.local/lib/python3.5/site-packages/O365/connection.py", line 703, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/O365/connection.py", line 692, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/home/xxx/.local/lib/python3.5/site-packages/O365/connection.py", line 623, in _internal_request
    raise RuntimeError('Token Refresh Operation not working')
RuntimeError: Token Refresh Operation not working
```

**Comment by janscas** [comment]
Can you paste de code you execute to run into this error?

Thanks!

**Comment by janscas** [comment]
> Thanks a lot. If you would like to update the README, the methods are described here:
> 
> * `[auth_flow_type='backend']`(https://docs.microsoft.com/en-us/graph/auth-v2-service)
> * `[auth_flow_type='web']`(https://docs.microsoft.com/en-us/graph/auth-v2-user)

Sure!

**Comment by teamoo** [comment]
Hi @janscas,

I am doing repeated calls to the address_book:

```
for ad_person in global_address_list.get_contacts(limit=1, query=q):
```

This is the code I execute to run this error. I set up the object like this:

```
credentials = (client_id, client_secret)

account = Account(credentials,tenant_id=config['msgraph']['tenant_id'],auth_flow_type='backend')

if not account.is_authenticated:
    account.authenticate()
global_address_list = account.address_book(address_book='gal')
q = global_address_list.new_query('display_name')
q.equals(person_harvest['name'])
```

**Comment by janscas** [comment]
Can you check now?

The fix I've just introduced should work

**Comment by janscas** [comment]
I think it is working now.

**Comment by teamoo** [comment]
I think so, too. Did not see that error since running the script again

**Comment by janscas** [comment]
There is a minor change to be aware of:

The default `auth_flow_type` will be called 'authorization' instead of 'web'.
And the client credentials grant flow is now called 'credentials' instead of 'backend'.

`auth_flow_type='authorization'`
or
`auth_flow_type='credentials'`

This will be released finally on the next version (v2.0.2) on pypi.

**Comment by janscas** [comment]
> Thanks a lot. If you would like to update the README, the methods are described here:
> 
> * `[auth_flow_type='backend']`(https://docs.microsoft.com/en-us/graph/auth-v2-service)
> * `[auth_flow_type='web']`(https://docs.microsoft.com/en-us/graph/auth-v2-user)

Readme updated!

**Comment by janscas** [comment]
@teamoo @sean2dre Are you able to work with the library withe the auth_flow_type=credentials?

I can't check it because I can't get application permissions assign to my apps on my company.

Are you able to send emails?
To check the inbox?

What are the code do you use to achieve that?

Some people using the library are not able to make it work with auth_flow_type=credentials.

**Comment by teamoo** [comment]
Yes, I am able to use it and yes, I can send emails.

```
client_id = config['msgraph']['client_id']
client_secret = config['msgraph']['client_secret']
scopes = ['https://graph.microsoft.com/.default']
credentials = (client_id, client_secret)

o365_account = Account(credentials, tenant_id=config['msgraph']['tenant_id'], auth_flow_type='credentials',scopes=scopes)

if not o365_account.is_authenticated:
    o365_account.authenticate()

m = o365_account.new_message(resource='users/' + sender_account.object_id)
m.to.add(xxx@yyy.zz)
m.subject = "Test"
m.sender = "xxx@yyy.zz"
m.attachments.add(ABC)
m.body = "<html><body>Test</body></html>"
m.send()
```

**Comment by janscas** [comment]
ok, I can see that the other users having problems are not setting the tenant_id so it defaults to 'common'

Maybe this is the cause of the errors?

I don't know because I can not test it...

If you have any clue...

Thanks

**Comment by teamoo** [comment]
Yeah sure you have to set the tenant_id. I don't think it should work without it...

**Comment by teamoo** [comment]
With tenant = 'common' I get the following exception:

`Unable to fetch auth token. Error: (unauthorized_client) AADSTS700016: Application with identifier 'XXXX-XXXX-XXXXX-XXXXXX' was not found in the directory 'microsoft.com'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
`

So it is clear that the tenant id is definitely needed.

**Comment by janscas** [comment]
Thank you very much @teamoo
