### ISSUE TITLE
How to work with not default SharePoint format URL?

### ISSUE THREAD

**Issue by hectorcmx** [O365/python-o365#295]
Hello,

The default SharePoint URL in the company I work for is  companyprod.shrepoint.com but there are some SharePoint sites that are using the URL https://sharepoint.company.com/sites for those ones I cannot figure out what I need to modify to reach them using the library. 

If I run `site = sharepoint.get_root_site()` I got:
_base_url ='https://graph.microsoft.com/v1.0/sites/companyprod.sharepoint.com,be8a8312-6161-4c52-88c9-8bb4e69ef69d,5f79d4fe-12e1-4256-9bff-xxxxxxxxxxxx'
object_id = 'companyprod.sharepoint.com,be8a8312-6161-4c52-88c9-8bb4e69ef69d,5f79d4fe-12e1-4256-9bff-xxxxxxxxxxxx'

I tried using the other format as input,
`site= sharepoint.get_site('sharepoint.honeywell.com')`

But it didn't work
```
HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/sites/sharepoint.company.com | Error Message: Invalid hostname for this tenancy
```
Do you have any suggestion?
Thanks in advance

**Comment by janscas** [comment]
> https://sharepoint.company.com/sites

This is a url from your company. Not from microsoft so it is not reachable by the api.
