### ISSUE TITLE
Getting e-mails from multiple folders

### ISSUE THREAD

**Issue by aufbakanleitung** [O365/python-o365#297]
Hi! 

Currently I'm reading my e-mails from a folder using this function.
```python
def get_new_email(amount):
    mailbox = account.mailbox().get_folder(folder_name='SD Brno').get_folder(folder_name='English').get_folder(folder_name='To be handled')
    query = mailbox.new_query().on_attribute('is_read').equals(False)  # Get only unread mail
    messages = mailbox.get_messages(limit=amount, query=query, order_by='receivedDateTime', download_attachments=True)  # FiFo
    return messages
```

How can I make it read 2 different folders as well? Preferable still returning a messages object, just with more messages in there. I've tried reading multiple folders into the mailbox or messages function using the += but that didn't work. `TypeError: unsupported operand type(s) for +=: 'generator' and 'generator'`

**Comment by aufbakanleitung** [comment]
I've currently solved it like this:
```python
def run(amount=1):
    language_folders = ['English', 'Portuguese', 'Spanish']
    for language_folder in language_folders:
        print(f"Reading {language_folder} folder")
        for message in get_new_email(amount, language_folder):

def get_new_email(amount, language_folder):
    mailbox = account.mailbox().get_folder(folder_name='SD Brno').get_folder(folder_name=language_folder).get_folder(folder_name='To be handled')
    query = mailbox.new_query().on_attribute('is_read').equals(False)  # Get only unread mail
    messages = mailbox.get_messages(limit=amount, query=query, order_by='receivedDateTime', download_attachments=True)  # FiFo
    return messages
```
This works just fine. Still wondering if it is possible though.

**Comment by janscas** [comment]
> ```python
> order_by='receivedDateTime'
> ```

You can order in the query and also shorten the instruction:

```python
query = mailbox.q('is_read').equals(False).order_by('received_date_time', ascending=True)
```




> How can I make it read 2 different folders as well? Preferable still returning a messages object, just with more messages in there. I've tried reading multiple folders into the mailbox or messages function using the += but that didn't work. `TypeError: unsupported operand type(s) for +=: 'generator' and 'generator'`

Convert the generator to a list and append them all together

**Comment by aufbakanleitung** [comment]
Hey janscas,

Your refactoring didn't work. 

```
  File "/Users/hermanvanderveer/Code/RPA/Python/Coca cola/main/office365_connector.py", line 51, in get_new_email
    messages = mailbox.get_messages(limit=amount, query=query, download_attachments=True)  # apply query
  File "/Users/hermanvanderveer/anaconda3/lib/python3.6/site-packages/O365/mailbox.py", line 204, in get_messages
    response = self.con.get(url, params=params)
  File "/Users/hermanvanderveer/anaconda3/lib/python3.6/site-packages/O365/connection.py", line 654, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/Users/hermanvanderveer/anaconda3/lib/python3.6/site-packages/O365/connection.py", line 643, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/Users/hermanvanderveer/anaconda3/lib/python3.6/site-packages/O365/connection.py", line 605, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/users/bptservicedeskquality@cokecce.com/mailFolders/AAMkADkzMzhkOTQyLThjOTItNDRjOC1iODBhLTMxZmQ4NzJkMTMyOQAuAAAAAABvitAiUmqoSbfxKGx3xoK7AQDM_gQDaJ4SRbiVHjJ0TRO_AADSNz6cAAA=/messages?%24top=50&%24filter=isRead+eq+false&%24orderby=isRead%2CreceivedDateTime | Error Message: The property can not be used for sorting or grouping results.
```
But anyways it's a moot point, because you already solved my issue. Thank!!

**Comment by janscas** [comment]
> our refactoring didn't work. `The property can not be used for sorting or grouping results.`

That's odd. This is what the graph docs states:

> When you specify $filter the server will infer a sort order for the results. If you use both $orderby and $filter, because the server always infers a sort order for the results of a $filter, the properties in the $filter must be listed first in the $orderby before any other properties, and they must be listed in the order that they appear in the $filter parameter.
