### ISSUE TITLE
Different attributes for "user" and "contact" ressource are not properly supported

### ISSUE THREAD

**Issue by teamoo** [O365/python-o365#298]
A [user](https://docs.microsoft.com/de-de/graph/api/resources/user?view=graph-rest-1.0#properties) resource has different attributes that a [contact](https://docs.microsoft.com/de-de/graph/api/resources/contact?view=graph-rest-1.0#properties) resource. When using the Users API (Global Address List), the Object Model should support slightly different attributes, e.g. a `Contact` has a `businessAddress ` property, whereas a `User` object does not have a `businessAddress` property, but a `streetAddress`,`postalCode`,`state`, etc.

I would consider this a feature request.

**Comment by teamoo** [comment]
My idea would be: instead of creating all the getters and setters manually, why don't we do something like this:

In the constructor
```
        # store all properties
        self.__cloud_data__ = cloud_data
```

And define a new method (see [Customizing attribute access)](https://docs.python.org/3/reference/datamodel.html#customizing-attribute-access)        
```
    #dynamic getter for all other properties that are in cloud_data
    def __getattr__(self, name):
        try:
            return self.__cloud_data__[name]
        except KeyError:
            msg = "'{0}' object has no attribute '{1}'"
            raise AttributeError(msg.format(type(self).__name__, name))
```

**Comment by teamoo** [comment]
I created a comparison of the attributes, maybe this helps when looking at this feature request.

User Ressource Attributes | Contract Ressource Attributes
-- | --
  | assistantName
aboutMe |  
accountEnabled |  
ageGroup |  
assignedLicenses |  
assignedPlans |  
birthday | birthday
  | businessAddress
  | businessHomePage
businessPhones | businessPhones
city |  
  | categories
  | changeKey
  | children
companyName | companyName
consentProvidedForMinor |  
country |  
createdDateTime | createdDateTime
department | department
displayName | displayName
employeeId |  
faxNumber |  
givenName | givenName
hireDate |  
id |  
mail* | emailAddresses*
  | fileAs
  | generation
  | homeAddress
  | homePhones
  | id
imAddresses | imAddresses
interests |  
  | initials
isResourceAccount |  
jobTitle | jobTitle
legalAgeGroupClassification |  
  | lastModifiedDateTime
licenseAssignmentStates |  
  | manager
  | middleName
mailboxSettings |  
mailNickname |  
mobilePhone | mobilePhone
mySite |  
  | nickName
officeLocation | officeLocation
onPremisesDistinguishedName |  
onPremisesDomainName |  
onPremisesExtensionAttributes |  
onPremisesImmutableId |  
onPremisesLastSyncDateTime |  
onPremisesProvisioningErrors |  
onPremisesSamAccountName |  
onPremisesSecurityIdentifier |  
onPremisesSyncEnabled |  
onPremisesUserPrincipalName |  
  | otherAddress
  | parentFolderId
  | personalNotes
  | profession
  | spouseName
otherMails |  
passwordPolicies |  
passwordProfile |  
pastProjects |  
postalCode |  
preferredDataLocation |  
preferredLanguage |  
preferredName |  
provisionedPlans |  
proxyAddresses |  
responsibilities |  
schools |  
showInAddressList |  
skills |  
signInSessionsValidFromDateTime |  
state |  
streetAddress |  
surname | surname
usageLocation |  
userPrincipalName |  
userType |  
  | title
  | yomiCompanyName
  | yomiGivenName
  | yomiSurname

*`mail` attribute is of type `String`, whereas `emailAddresses` is of type `EmailAddress` collection

**Comment by janscas** [comment]
Great! that helps a lot

**Comment by janscas** [comment]
I have been analysing this and I have come to the conclusion that the Contact and the User must be different objects with similar methods and properties

**Comment by janscas** [comment]
This basically means that a User object must be created in address_book.py. The GlobalAddressList should then return Users instead of Contacts.
This requires a lot of effort at the moment: creating the User, implementing the different methods (save method that knows what to update). Etc.

Basically we must replicate the Contact object with the properties, endpoints, etc from Users.

**Comment by teamoo** [comment]
Yes, I would agree that this would be the cleanest solution.

**Comment by teamoo** [comment]
As the User object is a specific Directory object that is neither stored in the personal, nor in the company address book, maybe it would make sense to put it in a new module?

**Comment by janscas** [comment]
> As the User object is a specific Directory object that is neither stored in the personal, nor in the company address book, maybe it would make sense to put it in a new module?

I'm not sure if it's worth it just for one object.

**Comment by janscas** [comment]
See 11560d0
