### ISSUE TITLE
Custom TokenBackend >> get_token >>always returns None for token

### ISSUE THREAD

**Issue by TheSanjo** [O365/python-o365#303]
Hi, 

I have created a custom Token Backend to work with Flask and have successfully managed to save the token in my database for the current user.  

However, for the get_token method, token is always returned as None by the token contructor. 

```python
def get_token(self):
    token = None
    token_str = User.select().where(User.id == str(self.user_id)).first().o365_token_str
    if token_str:
        self.token = self.token_constructor(self.serializer.loads(token_str))
    return token
```
token_str is what is stored in the database but the constructor seems to not return a Token object.  

Any help is greatly appreciated.

**Comment by janscas** [comment]
`self.serializer.load` (without the S) instead of "loads"

**Comment by janscas** [comment]
Closing this as there's no response
