### ISSUE TITLE
bug in share_with_invite to stop send emails

### ISSUE THREAD

**Issue by weasteam** [O365/python-o365#314]
I am trying to create permission without sending out emails, but it still sends with send_email=False:

```
file.share_with_invite(recipients=editors, send_email=False, share_type='edit')
```

Is it a bug? If not, how to stop stending the email?

**Comment by janscas** [comment]
I've checked the code and it's correct.
Maybe it's a microsoft issue.

**Comment by janscas** [comment]
Closing this as there's no follow up
