### ISSUE TITLE
Unable to authentication using app id and secret

### ISSUE THREAD

**Issue by mrvaghani** [O365/python-o365#315]
Instead of using delegated authentication, I have a registered app with application permissions assigned to it.

The app has admin consent already applied it's permissions.

This is the sample code that I am using that is causing the below two problems:
```
from O365 import Account

credentials = ('my_client_id', 'my_client_secret')

# the default protocol will be Microsoft Graph

account = Account(credentials, auth_flow_type='credentials')
if account.authenticate():
   print('Authenticated!')
```

When I try to use `Account` class to get a token, I run into two problems.

1. When using application permissions, the documentation mentions I don't need to specify any scopes. If I don't specify any scopes, I get this error:
```
Traceback (most recent call last):
  File "/Users/****/Documents/office_365/token_manager.py", line 51, in generate_app_token
    if account.authenticate():
TypeError: authenticate() missing 1 required keyword-only argument: 'scopes'
```

2. In order to bypass the issue#1, I passed in default scope. This time, the method `account.authenticate` print's a URL that I have to visit in order to give consent. If I understand this correctly, the URL for consent should only be needed when using "on behalf of the user" authentication method.

**Comment by janscas** [comment]
It seems you are not using the last version of the library. What version are you using?

**Comment by mrvaghani** [comment]
> It seems you are not using the last version of the library. What version are you using?

O365==2.0.1

**Comment by janscas** [comment]
pip install --upgrade O365

**Comment by mrvaghani** [comment]
> pip install --upgrade O365
> 
> Current version is 2.0.2 and it comes with client credentials grant flow
Thanks for the prompt response, I really appreciate it.
Upgraded to 2.0.2. Get a new error

```Traceback (most recent call last):
  File "/Users/****/Documents/office_365/token_manager.py", line 61, in <module>
    generate_app_token()
  File "/Users/****/Documents/office_365/token_manager.py", line 50, in generate_app_token
    account = Account(credentials, token_backend=token_backend, auth_flow_type='credentials')
  File "/Users/****/Documents/venv/lib/python3.7/site-packages/O365/account.py", line 40, in __init__
    scopes.append(self.protocol.prefix_scope('.default'))
AttributeError: 'NoneType' object has no attribute 'append'

Process finished with exit code 1
```

**Comment by janscas** [comment]
Ok! Let me see! Thanks

**Comment by janscas** [comment]
Can you check now?
version 2.0.3 is on pypi with the fix

**Comment by mrvaghani** [comment]
> Can you check now?
> version 2.0.3 is on pypi with the fix

It seems to work now!
I won't be able to fully verify it until I figure out how to change the AD tenant. Will get back once I have it tested.

**Comment by mrvaghani** [comment]
Verified 2.0.3 works with application ID and application secret along with a custom tenant. Thanks again @janscas  :)
