### ISSUE TITLE
How to save attachments to disk?

### ISSUE THREAD

**Issue by thilles** [O365/python-o365#316]
Hi,

May be I'm asking the obvious, but can't seem to save (get) the file attachments (.csv) from email messages. Can see that the method `get_messages` has the boolean parameter `download_attachments`, which I naively though would do exactly that. But can't find any results from that on disk afterwards. 
Am I missing something?

**Comment by thilles** [comment]
Update: So I discovered the `save` method which gives me almost success. 
From the four email it finds in the testfolder only three attachments are downloaded (all have exactly one attachment each). Any ideas why? 

```
from O365 import Account
  
account = Account(('cllient_id', 'secret'))
mailbox = account.mailbox()

# Get folder where emails are
test_folder = mailbox.inbox_folder().get_folder(folder_name='Testfolder')

for message in test_folder.get_messages(limit=5, download_attachments=True):
    print(message)
    message.attachments[0].save()
```

**Comment by janscas** [comment]
Maybe two of them have the same name? so one is overwrite.

**Comment by thilles** [comment]
Unfortunetly no. All four have distinct names, and are of the same-ish filetype (3 csv, 1 xls). 
Adding a `print(message.attachments[0])` yields the following, indicating that Testmail1.csv (the faulty) also is registered.
```
Subject: Testmail1
Attachment: Testmail1.csv
Subject: Testmail2
Attachment: Testmail2.XLS
Subject: Testmail3
Attachment: Testmail3.CSV
Subject: Testmail4
Attachment: Testmail4.CSV
```

**Comment by thilles** [comment]
Okay, truly an obvious error on my part. The testmail1.csv file had no content, hence it wasn't downloaded. Case closed.

**Comment by rahuliet** [comment]
Found this buried here . I missed to set `download_attachments as True` while `get_messages` and was clueless why msg.attachments is showing as 'Unknown'

**Comment by janscas** [comment]
Hi @rahuliet thanks! Feel free to send a PR. For the moment I don’t have time for this.
