### ISSUE TITLE
Authorization error

### ISSUE THREAD

**Issue by basilgeorge** [O365/python-o365#317]
Hi,

I went through other related issues for this repo but none seems to solve my problem. 

I am unable to authenticate and get access token.

These are the steps I followed in command-line:

```
from O365 import Account
credentials = (XXXX, YYYY)
scopes=['basic', 'message_all']
account = Account(credentials)
account.authenticate(scopes=scopes)
```

Visit the following url to give consent:
`https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=XXXX&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fnativeclient&scope=https%3A%2F%2Fgraph.microsoft.com%2FMail.ReadWrite+https%3A%2F%2Fgraph.microsoft.com%2FUser.Read+https%3A%2F%2Fgraph.microsoft.com%2FMail.Send&state=8uYYgVKgZVdyAAB9wJYo4dCcPte2N6&access_type=offline`

Paste the authenticated url here:
`https://login.microsoftonline.com/common/oauth2/nativeclient?code=Xxxx&state=xxx&session_state=Xxx

The pasted URL was received after logging into the account. But I receive the following error:

```
ERROR:O365.connection:Unable to fetch auth token. Error: (invalid_client) AADSTS700025: Client is public so neither 'client_assertion' nor 'client_secret' should be presented.
Trace ID: a3c24393-576f-4884-980a-32ef582d1a00
Correlation ID: 2ef0ceaf-6968-4884-9d75-5ac4151be4eb
Timestamp: 2019-09-19 10:51:30Z
Something go wrong. Please try again.
```

The following are some screenshots of my Azure App Registration portal:

![azure_app_1](https://user-images.githubusercontent.com/38415715/65238842-4291ab00-dafb-11e9-9e15-4aaa7474070b.jpg)

![azure_app_2](https://user-images.githubusercontent.com/38415715/65238850-4ae9e600-dafb-11e9-9877-eec66ebe3124.jpg)

![azure_app_3](https://user-images.githubusercontent.com/38415715/65238858-50dfc700-dafb-11e9-8c71-3f05e97cf762.jpg)

Please help.

Thanks.

**Comment by janscas** [comment]
You haven't set the redirect uri.
You must add it to the Redirect Uri text field on the first screenshot

**Comment by basilgeorge** [comment]
Thanks @janscas. I was under the impression that the tick mark would set the redirect uri. 

Auth tokens were scrambled before pasting.

Thanks!

**Comment by fartwhif** [comment]
what the hell
