### ISSUE TITLE
Question about authentication

### ISSUE THREAD

**Issue by NathanTech7713** [O365/python-o365#318]
Hi there,
Just a quick question about authentication:
Using the example for web service in the documentation, I am able to, happily, authenticate.
My problem comes thus:
I need to save the token amongst other program data, and then restore it from that.
Something like:
access_token=account.connection.token
# code for saving here.

Then in the def main:
# load our data
if(token!=0):
account.connection.access_token=token
if(account.expired())
account.refresh_token()

i'm not entire sure how I'd go about this though, and that's why I'm asking for a little help?

**Comment by janscas** [comment]
Don’t do that. 

You can use a TokenBackend. See the readme about them. 

This allows you to store a retrieve the token from the place you want (a database, a file, memcache, etc)

However for the momento there are only two token backends implemented: FileSystemTokenBackend (stores token as files) and FirebaseTokenBackend (stores tokens in a google firebase database).

You may have to implement your own. But it’s really easy

**Comment by janscas** [comment]
Also, the library refreshes the token automatically for you
