### ISSUE TITLE
Question: read my inbox returns "Error Message: Resource not found for the segment 'mailFolders'."

### ISSUE THREAD

**Issue by lia-cha-avalara** [O365/python-o365#319]
I registered an azure app, gave it user.profile and mail.read permissions (application access). Granted admin consent for the permissions  Ran the following code:

CLIENT_ID = os.environ['CLIENT_ID']
CLIENT_SECRET = os.environ['CLIENT_SECRET']
credentials = (CLIENT_ID, CLIENT_SECRET)
account = Account(credentials, auth_flow_type='credentials')
if account.authenticate():
   print('Authenticated!')
   mailbox = account.mailbox()
   inbox = mailbox.inbox_folder()
   for message in inbox.get_messages():
       print(message)

It authenticates fine but when it tries to get the messages it fails. I even tried by using the MSGraphProtocol class and defining the api_version arg as 'beta' and the default_resource arg as my own email address but doing that says the token doesn't have the right permissions..

Should add that if i went the delegated permissions route and using the console authentication method, everything works fine.

**Comment by janscas** [comment]
I'll suggest to use the authorization auth_flow_type, as there are some problems that need to be addressed now with the credentials flow type.

But please try:
```python
mailbox = account.mailbox(resource='YOUR_EMAIL')
# ...
```

**Comment by lia-cha-avalara** [comment]
The authorization auth_flow_type is the one that requires console authorization correct? I made the suggested change and it's providing me the URL. I'm looking for a way to pull everything programmatically because the UI method via a content search and export is too slow and exports way more data than I need.

**Comment by janscas** [comment]
> he authorization auth_flow_type is the one that requires console authorization correct

It requires an authorization from the user. But the use of the console is not enforced. You can get this authorization done in a lot of ways.

> I'm looking for a way to pull everything programmatically because the UI method via a content search and export is too slow and exports way more data than I need.

I don't know what you mean...

**Comment by janscas** [comment]
@lia-cha-avalara when using the credentials auth flow type, try to:

- First set the tenant_id: `Account(credentials, tenant_id='your tenant id')`
- Second, when using the credentials auth flow type you MUST specify a resource:
 For example: mailbox = account.mailbox('my_user@my-company.com')
 The mailbox object will now retrieve the data from the my_user mailbox.

**Comment by lia-cha-avalara** [comment]
@janscas looks like adding the tenant_id and specifying the resource works!

**Comment by janscas** [comment]
That's great!

**Comment by BGeigerHOL** [comment]
Hi, unfortunately that didnt work for me. I get authenticated and specified a resource with 
mailbox = account.mailbox(resource='anotheruser@my-company.com') but still get 
"Error Message: Access is denied. Check credentials and try again".
Any help would be very much appreciated!
Thanks
Bernd

**Comment by janscas** [comment]
> Hi, unfortunately that didnt work for me. I get authenticated and specified a resource with
> mailbox = account.mailbox(resource='[anotheruser@my-company.com](mailto:anotheruser@my-company.com)') but still get
> "Error Message: Access is denied. Check credentials and try again".
> Any help would be very much appreciated!
> Thanks
> Bernd

The app needs to have that permission if you are connecting with client credentials. If you are connecting with authorization grant code then your user (or the user logging in) needs to have access to that account.

**Comment by murlock** [comment]
I confirm that it works on my side:

```
credentials = (application_id, secret)
account = Account(credentials, auth_flow_type="credentials", tenant_id=tenant_id)
account.authenticate()
mail = account.mailbox(resource="my-secret-email@mycompany.com)
inbox = mail.inbox_folder()
for message in inbox.get_messages():
    print(message)
```

My application has "mail.read"
