### ISSUE TITLE
error when accessing onedrive for business

### ISSUE THREAD

**Issue by veribus** [O365/python-o365#320]
Hello,

I'm using the "with your own identity" method and I have registered an app with Application Permissions in AAD. I can authenticate without issue, but I cannot access onedrive. 

When I execute the pictured script below, I keep getting the error "HTTPError: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/drives?%24top=999 | Error Message: Either scp or roles claim need to be present in the token."

I'm trying to create a script that runs periodically on a VM and uploads a file to onedrive.

Thank you for any help you can provide.
![issue_od](https://user-images.githubusercontent.com/55036524/65910729-4645ed00-e399-11e9-8c06-9c1f53350f87.PNG)

**Comment by janscas** [comment]
It is better if you do:

```python
# ...
if not account.is_authenticated:
    account.authenticate()
# ...
```

This way you don't force an authentication if it's not required.

About the error... it seems you added delegated permissions instead application permissions.

can you check that?

**Comment by veribus** [comment]
Thank you for the tip. I will make that change.

It's application permissions. There is one delegated "User.Read", but I did not add that one. It pre-populates when you select "Application Permissions" when adding permissions to the API.

![app_permissions](https://user-images.githubusercontent.com/55036524/65916753-e739a580-e3a3-11e9-91ee-11b5b09f591a.PNG)

**Comment by veribus** [comment]
Also, I tried to send a message to see if my issue was only related to onedrive, but I received this error:
`storage = account.storage()  
mailbox = account.mailbox()
m = mailbox.new_message()
m.to.add('name@example.com')
m.subject = 'hello'
m.body = 'world'
m.sender.address = 'person@example.com'
m.send()
`
HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/sendMail | Error Message: Resource not found for the segment 'sendMail'.

**Comment by janscas** [comment]
Ok, two questions:

1.  Are you under a Microsoft personal account?
1.  Can you try:

Change the YOUR-EMAIL to your email: like 'name@example.com'

```python
mailbox = account.mailbox(resource='YOUR-EMAIL')
m = mailbox.new_message()
m.to.add('name@example.com')
m.subject = 'hello'
m.body = 'world'
m.sender.address = 'person@example.com'
m.send()
```

**Comment by janscas** [comment]
OK, just more questions:

1. Did you grant the admin consent through the button?

1. If you authenticate before the admin consent was given, then the token may be incomplete (lacking the scopes allowed). Can you delete the token file to force a re-authentication?

**Comment by veribus** [comment]
> Ok, two questions:
> 
> 1. Are you under a Microsoft personal account? **No, it's a work account. I am the only user in the tenant veribusanalytics**
> 2. Can you try the following?: **Yes. See error code below**
> 
> Change the YOUR-EMAIL to your email: like '[name@example.com](mailto:name@example.com)'
> **HTTPError: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/users/myemail@veribusanalytics.com/sendMail | Error Message: The token contains no permissions, or permissions can not be understood.**
>

**Comment by veribus** [comment]
> OK, just more questions:
> 
> 1. Did you grant the admin consent through the button? **Yes. See image above with the dark background and green checkmarks beside "granted for veribus"**
> 2. If you authenticate before the admin consent was given, then the token may be incomplete (lacking the scopes allowed). Can you delete the token file to force a re-authentication? **I granted admin consent, then consented to the permissions for the first time by going to "Enterprise Apps" in my Azure AD and clicking "grant admin consent" and going through the one-time process to accept the app permission through microsoft website, then accessed the API from python in my spyder IDE **

**Comment by janscas** [comment]
> **I'm happy to try. How do I locate the token file? I'm unsure where this is or how to access it.**

It's on your project folder. By default it's called o365_token.txt

**Comment by veribus** [comment]
I don't see that file on my project folder? Strange. I have a sample app that I was using to learn and it does have the o365_token.txt file, but it is not related to the app I'm currently troubleshooting.

Any ideas?

**Comment by janscas** [comment]
It must be somewhere... if there is not token file then you can't connect.

Try:

```python
account = Account(#...)
print(account.con.token_backend.token_path.absolute())
```
This should print the absolute path to where the library is currently loading the token file.

**Comment by veribus** [comment]
I was able to find the token finally. Indeed, it does not contain any permissions...

![image](https://user-images.githubusercontent.com/55036524/66273065-87794980-e83e-11e9-8a2e-9e0b5d2b9df8.png)

**Comment by janscas** [comment]
Then you should try the authentication AFTER the app admin has given consent.
Did you try?

**Comment by veribus** [comment]
Yes that's the only way I've done it. Always give admin consent before authentication. Are you able to create a new app a get it to work?

**Comment by janscas** [comment]
I can't because i don't have access on my company to the application permissions.

**Comment by janscas** [comment]
hi @veribus I've found what happend.

You MUST provide a tenant_id. With version 2.0.4 this is now enforced and will raise an exception if the tenant_id is not set.

please report back

**Comment by janscas** [comment]
Closing this as there's no answer
