### ISSUE TITLE
Refreshed Token doesn't work

### ISSUE THREAD

**Issue by seevoid** [O365/python-o365#323]
Hi,

I have an issue with the refreshed token. 

Explanations :

My app is on my dedicated server, run with wsgi and is served by nginx through my domain name. In my app.py I log to O365 like this : 
`token_backend = FileSystemTokenBackend(token_path='./', token_filename='o365_token.txt')`
`account = Account(o365_credentials, token_backend=token_backend)`

Before using my app, I collected a auth token with another script "auth.py" that I launched to follow the auth process (visit the URL and paste back the new auth URL). Here is my code in "auth.py":
`client_id = "PRIVATE"`
`client_secret = "PRIVATE"`
`credentials = (client_id, client_secret)`
`token_backend = FileSystemTokenBackend(token_path='./', token_filename='o365_token.txt')`
`account = Account(credentials, token_backend=token_backend)`
`token = account.authenticate(scopes=['offline_access', 'Calendars.Read', 'Calendars.Read.Shared', 'Calendars.ReadWrite', 'Calendars.ReadWrite.Shared'])`

When I follow the auth step, I see that a file called "o365_token.txt" appears and when I read it I see there is a "refresh token" line.
However, the token expires after 60minutes and after that I can't use the API. I can't figure out why...

Thanks for helping. I tried a lot of differents things to get a refreshed token, without success.

Seevoid

**Comment by janscas** [comment]
It works for me... the only thing I can tell is that you shouldn't use FileSystemTokenBackend on a server unless you are 100% sure the server will be just 1 instance and have a persistent drive.

**Comment by janscas** [comment]
Also, If you enable logging, the library will log the refresh attempt. Can you paste the logs?

Thanks

**Comment by seevoid** [comment]
There is no problem with the storage on my server I think. I already used some google credentials files or token like that and I never had issues.

How can I enable logging in the O365 lib ?

**Comment by janscas** [comment]
Import logging

logging.basicConfig(level=logging.DEBUG)

**Comment by seevoid** [comment]
Thanks, here are my logs :

oct. 02 11:20:11 vps673855 uwsgi[1801]: INFO:O365.connection:Requesting (GET) URL: https://graph.microsoft.com/v1.0/me/calendars
oct. 02 11:20:11 vps673855 uwsgi[1801]: INFO:O365.connection:Request parameters: {'params': {'$filter': "name eq 'Calendrier'", '$top': 1}, 'allow_redirects': True}
oct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:requests_oauthlib.oauth2_session:Invoking 0 protected resource request hooks.
oct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:requests_oauthlib.oauth2_session:Adding token {'token_type': 'Bearer', 'scope': ['Calendars.Read', 'Calendars.Read.Shared', 'Calendars.ReadWrite', 'Calendars.ReadWrioct. 02 11:20:11 vps673855 uwsgi[1801]: INFO:O365.connection:Oauth Token is expired, fetching a new token
oct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:requests_oauthlib.oauth2_session:Adding auto refresh key word arguments {}.
oct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:requests_oauthlib.oauth2_session:Prepared refresh token request body grant_type=refresh_token&client_id=PRIVATE&client_secret=PRIVATE
oct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:requests_oauthlib.oauth2_session:Requesting url https://login.microsoftonline.com/common/oauth2/v2.0/token using method POST.
oct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grantoct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'json': None, 'auth': None, 'timeout': None, 'verify': True, 'proxies': None}.
oct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
oct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /common/oauth2/v2.0/token HTTP/1.1" 401 471
oct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:requests_oauthlib.oauth2_session:Request to refresh token completed with status 401.
oct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:requests_oauthlib.oauth2_session:Response headers were {'Cache-Control': 'no-cache, no-store', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8oct. 02 11:20:11 vps673855 uwsgi[1801]: DEBUG:requests_oauthlib.oauth2_session:Invoking 0 token response hooks.

**Comment by janscas** [comment]
It returns a 401 unauthorized. I don't know why...

Do you have the permission offline_access registered on the app right?

**Comment by janscas** [comment]
ohh I see... the scopes are wrong

Maybe it's this. when authenticating with O365, you either pass scope helpers or complete formatted scopes.

So you can pass: 

scopes=['calendar_all', 'etc..']

OR

scopes=['https://graph.microsoft.com/Calendars.ReadWrite']

But you can't pass scopes=['Calendar.Read']

try again (you need to get a completely new token so you have to re-authenticate.

**Comment by seevoid** [comment]
OK thanks for your support. I tried with thoses scopes : ['basic', 'calendar_all']

I'll try to use the API in one hour to check if it's ok. I'll give you my feedback.

**Comment by seevoid** [comment]
Damn, the same issue with same logs...
I tried to refresh the token by sending a POST request to "https://login.microsoftonline.com/common/oauth2/v2.0/token". I followed the Microsoft's doc to fill the header and body properly. 
There is the responses I received : 
{'error': 'invalid_grant', 'error_description': "AADSTS65001: The user or administrator has not consented to use the application with ID 'PRIVATE' named 'PRIVATE'. Send an interactive authorization request for this user and resource.\r\nTrace ID: ff335f08-ba8c-4aa9-ac56-a710a11a3e00\r\nCorrelation ID: d66d6c77-ff41-4798-8a29-15eca1307043\r\nTimestamp: 2019-10-02 10:26:15Z", 'error_codes': [65001], 'timestamp': '2019-10-02 10:26:15Z', 'trace_id': 'ff335f08-ba8c-4aa9-ac56-a710a11a3e00', 'correlation_id': 'd66d6c77-ff41-4798-8a29-15eca1307043', 'suberror': 'consent_required'}

It seems I (Administrator) have not consented to use the applcation with the given id. I searched on google what caused this error but I can't understand what to exactly do. Could you help me ?

**Comment by janscas** [comment]
you have just to call account.authenticate(scopes=my_scopes). then copy the link, visit it and then consent the permissions. Then copy the link the page has redirected to and paste it back to the console.

the authenticate process should return True if is successful.

Check:

```python
if account.authenticate(scopes=my_scopes) is True:
    pass
```

**Comment by seevoid** [comment]
Yeah I know that but my problem is with the refreshed token, after 60minutes I can't have access to the API anymore. Like I told you in my previous comment, it seems there is an error when I request a new token with my refresh_token. The error is this one : AADSTS65001.

I will try with a new office 365 account to see if it works because I currently use a scholar one so it may cause this kind of difficulties. I'll keep you in touch ;)

**Comment by seevoid** [comment]
OK everything works well now, I can refresh the token properly. This cause was because I created my previous app under a school organization in Azure so I didn't have the good permissions...

Thanks a lot for your help :)
