### ISSUE TITLE
Reading 'UniqueBody' field

### ISSUE THREAD

**Issue by rena2damas** [O365/python-o365#325]
How can I read the 'UniqueBody' property of the message?
Let's say I get a certain message ```message = folder.get_message(query=Query(...).select('UniqueBody'))```. How do access ```UniqueBody``` of ```message```? All I have is the ```body``` attribute which is not exactly what I want.

**Comment by rena2damas** [comment]
Waiting for the 2.0.4 to be released for this feature to take effect.

**Comment by janscas** [comment]
Soon. You will have to use select, because it’s not included by default.

**Comment by rena2damas** [comment]
> Soon. You will have to use select, because it’s not included by default.

I know, the query is done. Just waiting the 2.0.4 for it to take effect.

**Comment by janscas** [comment]
@rena2damas  v2.0.4 is released

**Comment by rena2damas** [comment]
> @rena2damas v2.0.4 is released

Would be great to have a release.md file to easily keep track on what has changed

**Comment by janscas** [comment]
Don’t hace time right now to do that

**Comment by rena2damas** [comment]
I understand, no problem. Is just a suggestion to help developers that are using your lib

**Comment by janscas** [comment]
@rena2damas there is now a CHANGES.md
