### ISSUE TITLE
Question on filtering events

### ISSUE THREAD

**Issue by NathanTech7713** [O365/python-o365#327]
Hi, I wondered if someone could help me.
I'm trying to filter events, like so:
1. get the master list of events, (already done that)
2. Now, get only events that have been modified since x date.
Any help greatly appreciated.

**Comment by janscas** [comment]
If you query all events (including the recurring ones you can't because it seems it's not a valid query for microsoft.

If you disable getting the recurring events then you can:

```python
import datetime as dt

schedule = account.schedule()
calendar = schedule.get_default_calendar()
q = calendar.new_query()
q = q.on_attribute('last_modified_date_time').greater_equal(dt.datetime(2019, 10, 5))
for event in calendar.get_events(limit=50, query=q, include_recurring=False):
    print(event)
```

**Comment by janscas** [comment]
Closing this as there is no answer
