### ISSUE TITLE
client credentials auth flow authentication problem

### ISSUE THREAD

**Issue by davidlpotter59** [O365/python-o365#330]
I am having issues with the 0365 module. I authenticate perfectly. The errors comes into play at the account objects.

The message I get is: Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/sendMail | Error Message: Resource not found for the segment 'sendMail'.
Traceback (most recent call last):
File "mail5.py", line 18, in
message.send()
File "/home/davep/.local/share/virtualenvs/completed-88qwCt9r/lib/python3.7/site-packages/O365/message.py", line 654, in send
response = self.con.post(url, data=data)
File "/home/davep/.local/share/virtualenvs/completed-88qwCt9r/lib/python3.7/site-packages/O365/connection.py", line 718, in post
return self.oauth_request(url, 'post', data=data, **kwargs)
File "/home/davep/.local/share/virtualenvs/completed-88qwCt9r/lib/python3.7/site-packages/O365/connection.py", line 696, in oauth_request
return self._internal_request(self.session, url, method, **kwargs)
File "/home/davep/.local/share/virtualenvs/completed-88qwCt9r/lib/python3.7/site-packages/O365/connection.py", line 658, in _internal_request
raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/sendMail | Error Message: Resource not found for the segment 'sendMail'.

Code is:
from O365 import Account

credentials = ('ID', 'secret')

account = Account(credentials, auth_flow_type='credentials')
if account.authenticate():
    print('Authenticated!') # this prints

# note no errors if the following lines are commented out.
mailbox = account.mailbox()
message = mailbox.new_message()
message.subject = 'Hello Test'
message.to.add(['user@somedomain.com'])
message.body = "You have documents"
message.send()

Thank you for anyone that can help me.
Versions: python 3.6.8, O365 2.0.3

**Comment by janscas** [comment]
The client credentials auth flow is lacking some funcionallity. 

If you authenticate the other way it should work

**Comment by janscas** [comment]
You have to set a resource when using the credentials auth flow:

For example:

`mailbox = account.mailbox('my_user@my-company.com)`

**Comment by janscas** [comment]
You also need to set the tenant_id:

`Account(credentials, tenant_id='my_tenant_id')`

**Comment by janscas** [comment]
Closing this as there's no answer
