### ISSUE TITLE
Timeout Settings

### ISSUE THREAD

**Issue by hcallen** [O365/python-o365#336]
Hello,

I was wondering if there was an easy way to set a connection/query timeout. I have a script that polls a mailbox every 10 secs. It will work great for ~2 weeks, then unexpectedly hang when attempting to connect.

I poked around a bit and didn't see a straight forward way to implement a timeout. I want to check if there is something I'm missing before I dug deeper.

**Comment by janscas** [comment]
will be released under v2.0.5
