### ISSUE TITLE
[Question] Able to just pull attachment names w/o download?

### ISSUE THREAD

**Issue by lia-cha-avalara** [O365/python-o365#338]
I did some testing and it looks like I'm only able to retrieve the attachment names when i use the download_attachments=True parameter (which makes sense). The problem I see with this is script execution time when there's massive amounts of emails with attachments.

I've been testing this module to pull a report from shared mailboxes and it's been working great but found that on an inbox with 2300 emails, it took roughly 17mins to complete. We have others that have 15-17k emails in there and I'm just curious if there's a way to speed this up.

**Comment by janscas** [comment]
I did not test this, but it should work:

```python
q = inbox.q().expand('attachments').select('name')
messages = inbox.get_messages(query=q)
```

Let me know if it works

**Comment by lia-cha-avalara** [comment]
hmm i must not be doing it right. How would you access/print the value from that?

**Comment by janscas** [comment]
yeah right!

There was a missing piece.

I've added this on 0b776fe8570a66a1760511be2a201328a023117d

**Comment by janscas** [comment]
With this commit and the code I gave to you it will work.

**Comment by lia-cha-avalara** [comment]
so with "q = inbox.q().expand('attachments').select('name')" and passing that into the query parameter of get messages will return all emails and their attachment names? I think when I tested with my existing code of "attachments = [att.name for att in message.attachments]" it was returning an empty list.

**Comment by janscas** [comment]
Yes!

there is a new release v2.0.5. Update and you will see this working

**Comment by lia-cha-avalara** [comment]
working! Thanks for the quick feature update! Tested this against the same 2300 emails...went from 17mins to 50secs.
