### ISSUE TITLE
after copy operation, the function operation.get_item() produce errors

### ISSUE THREAD

**Issue by sidkang** [O365/python-o365#340]
The code is from the document example
```python
# copy a file to the documents special folder

documents_folder = my_drive.get_special_folder('documents')

files = my_drive.search('george best quotes', limit=1)

if files:
    george_best_quotes = files[0]
    operation = george_best_quotes.copy(target=documents_folder)  # operation here is an instance of CopyOperation

    # to check for the result just loop over check_status.
    # check_status is a generator that will yield a new status and progress until the file is finally copied
    for status, progress in operation.check_status():  # if it's an async operations, this will request to the api for the status in every loop
        print('{} - {}'.format(status, progress))  # prints 'in progress - 77.3' until finally completed: 'completed - 100.0'
    copied_item = operation.get_item()  # the copy operation is completed so you can get the item.
    if copied_item:
        copied_item.delete()  # ... oops!
```
Below is the error message
```
Client Error: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/me/drives/*****/items/93aa1d5b-9b55-4c3e-92b4-******* | Error Message: The resource could not be found.
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-33-e75e04569d02> in <module>
---->  copied_item = copy_operation.get_item()
```
The error produces every time after I copy the original file and want to get the item using the get_item. Some id part of the error url is replaced. Am I misunderstanding the func?

**Comment by janscas** [comment]
Do you see the file copied in the documents folder?

**Comment by sidkang** [comment]
> Do you see the file copied in the documents folder?

Yes, I can find the copied file in the target folder. Now I am using the compare method to locate the copied in the target folder by exact name, but sometimes if the name is too complicated, the compare mehod may not work.

**Comment by janscas** [comment]
@sidkang what is the approximate file size of the file you are seeing this error?

**Comment by sidkang** [comment]
> @sidkang what is the approximate file size of the file you are seeing this error?

I tried a lot of files doing the copy action, and there's no one success. filesizes vary from KBs to 5xx MB.
I will try to add more info to help demonstrate the issue later.

**Comment by janscas** [comment]
I tried following the same example posted and It succeed every time. But that's because the server respond witha 'synchronous' operation every time (even with a 1GB file) . I don't know why the server is not responding with an 'Async operation'... As I think this is what is failing.

**Comment by sidkang** [comment]
@janscas That's a little weird, and below is the complete code with the error message.

```python
from O365 import Account, MSGraphProtocol, FileSystemTokenBackend
import time, os

local_dir = os.getcwd()
credentials = ('*****, '***')
token_backend = FileSystemTokenBackend(token_path='', token_filename='o365_token.txt')

account = Account(credentials, token_backend=token_backend)

if account.is_authenticated:
    print('Already authenticated!')
else:
    if account.authenticate(scopes=['basic', 'message_all', 'onedrive_all']):
        print('Authenticated!')
```
> Already authenticated!
```python
filename = 'steam.dmg'

# Onedrive
storage = account.storage()
drives = storage.get_drives()
my_drive = storage.get_default_drive('')  # or get_drive('drive-id')

template_folder = my_drive.get_item_by_path('/TEST/template')
work_folder = my_drive.get_item_by_path('/TEST')

# select the target file
for file in template_folder.get_items():
    if file.name == filename:
        break
print('Found the file.')
print(file.name)
```
>Found the file.
>steam.dmg
```python
copy_operation = file.copy(target=work_folder)
time.sleep(3)
copy_operation.completion_percentage
```
>100.0
```python
copied = copy_operation.get_item()
```
Error Msg:
Client Error: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/me/drives/b!gzb6I-VpTEieig1QIaHTchPQgR9rdsFLuhvEd1OisVjzfp0FehRTTbmKhLJfkKzO/items/e5047bda-51cf-4784-bdc7-c32c14cef36a | Error Message: The resource could not be found.
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-16-e1695da6600d> in <module>
----> 1 copied = copy_operation.get_item()

~/dev/venv/lib/python3.7/site-packages/O365/drive.py in get_item(self)
    198         """
    199         return self.parent.get_item(
--> 200             self.item_id) if self.item_id is not None else None
    201 
    202 

~/dev/venv/lib/python3.7/site-packages/O365/drive.py in get_item(self, item_id)
   1477                 self._endpoints.get('get_item_default').format(item_id=item_id))
   1478 
-> 1479         response = self.con.get(url)
   1480         if not response:
   1481             return None

~/dev/venv/lib/python3.7/site-packages/O365/connection.py in get(self, url, params, **kwargs)
    712         :rtype: requests.Response
    713         """
--> 714         return self.oauth_request(url, 'get', params=params, **kwargs)
    715 
    716     def post(self, url, data=None, **kwargs):

~/dev/venv/lib/python3.7/site-packages/O365/connection.py in oauth_request(self, url, method, **kwargs)
    701             self.session = self.get_session(load_token=True)
    702 
--> 703         return self._internal_request(self.session, url, method, **kwargs)
    704 
    705     def get(self, url, params=None, **kwargs):

~/dev/venv/lib/python3.7/site-packages/O365/connection.py in _internal_request(self, request_obj, url, method, **kwargs)
    663                 if self.raise_http_errors:
    664                     if error_message:
--> 665                         raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
    666                     else:
    667                         raise e

HTTPError: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/me/drives/b!gzb6I-VpTEieig1QIaHTchPQgR9rdsFLuhvEd1OisVjzfp0FehRTTbmKhLJfkKzO/items/e5047bda-51cf-4784-bdc7-c32c14cef36a | Error Message: The resource could not be found.

**Comment by janscas** [comment]
> ```python
> copy_operation = file.copy(target=work_folder)
> time.sleep(3)
> copy_operation.completion_percentage
> ```

Instead of this, try this:

```python
for status, progress in operation.check_status():  # if it's an async operations, this will request to the api for the status in every loop
    print('{} - {}'.format(status, progress))  # prints 'in progress - 77.3' until finally completed: 'completed - 100.0'
copied_item = operation.get_item()
```

**Comment by janscas** [comment]
Closing this as there's no answer
