### ISSUE TITLE
Token Naming for multiple Account instances

### ISSUE THREAD

**Issue by teamoo** [O365/python-o365#341]
I have a situation where different Azure Apps use different `Account` objects. In this case, the `is_authenticated` method does not seem to work correctly. The different `Account` objects cannot distinguish which `Account` is authenticated and which Token belongs to which `Account`. I guess if we changed the naming of the token file to include a ID specific to the client_id (?), it would be possible to differentiate the different `Account` instances.

**Comment by janscas** [comment]
You hace to configure each Account instance using the Token Backend like this (using FileSystemTokenBackend as an example):

```python
account_one = Account(credentials_one, FileSystemTokenBackend(token_filename='token1.txt'))

account_two = Account(credentials_two, FileSystemTokenBackend(token_filename='token2.txt'))
```

**Comment by teamoo** [comment]
Thanks, I will try that!

**Comment by teamoo** [comment]
Sorry, you we‘re totally right.
