### ISSUE TITLE
Token Validity

### ISSUE THREAD

**Issue by TheSanjo** [O365/python-o365#342]
Hi there

I have a working flask site which successfully completes the OAuth authentication and stores the token in a database.  However, it seems to only receive a token for 1 hour.  

I think my scopes are correct.  See below.  Is there anyway of getting a token that lasts longer?

```
def auth_step_1(user):
    # callback = 'my absolute url to auth_step_two_callback'
    callback = config.callbackurl
    protocol = MSGraphProtocol(api_version='beta')  # MSGraphProtocol defaults to v1.0 api version
    account = Account(credentials, protocol=protocol)
    # my_scopes = ['basic', 'message_all', 'calendar']
    # scopes_graph = [protocol.get_scopes_for('basic'), protocol.get_scopes_for('message_all')]
    basicscope = 'https://graph.microsoft.com/offline_access'
    userscope = 'https://graph.microsoft.com/User.Read'
    emailscope1 = 'https://graph.microsoft.com/Mail.Send'
    emailscope2 = 'https://graph.microsoft.com/Mail.ReadWrite'

    scopes_graph = [basicscope, userscope, emailscope1, emailscope2]
    tokenbackend = SqliteTokenBackend(user_id=user)
    url, state = account.con.get_authorization_url(requested_scopes=scopes_graph,
                                                   redirect_uri=callback,
                                                   token_backend=tokenbackend)
    # Saving the state ...
    Temp.delete().execute()
    Temp.create(username=user, state=state)

    return url
```

**Comment by janscas** [comment]
Yes, the token is only valid for 1 hour. If you added the scope_helper 'basic' then you will add the scope 'offline_access' also. Which will add a refresh token that will allow you ro request another access token when the current one expires.

So, every hour there will be a new access token and therefore a save to the database.

This is done automatically by the library.

This is all explained in the readme.

**Comment by TheSanjo** [comment]
Thank you.  Does the refresh require the user to login again?  I have it setup at the moment that if the account is not authenticated, I redirect to the first authentication url.  If the user is already logged into Office 365 , they just click their account and it all works.  I am not sure if this is correct design.

**Comment by janscas** [comment]
No, the refresh is done automatically.
In your script just set the account object and then check the is_authenticated property.
```python
if not account.is_authenticated:
    return redirect('authentication_endpoint')
# ...
```

**Comment by TheSanjo** [comment]
Thanks Jancas. The authentication check is always False if requested after an hour which suggests that the refresh token is not being stored.  

I cannot seem to use the scope helpers with get_authorization_url method.  Instead I have created a list of the scope urls manually and used that (As above).

I tried using protocol.get_scopes_for('basic') but this says the format of the scope is not correct on the microsoft site.

**Comment by TheSanjo** [comment]
Thanks Jancas, sorry I don't understand how not to prefix the offline access.  I am using the following to define the scopes. 

basicscope = 'https://graph.microsoft.com/offline_access'
userscope = 'https://graph.microsoft.com/User.Read'
emailscope1 = 'https://graph.microsoft.com/Mail.Send'
emailscope2 = 'https://graph.microsoft.com/Mail.ReadWrite'

scopes_graph = [basicscope, userscope, emailscope1, emailscope2]

**Comment by janscas** [comment]
Remove all but 'offline_access'

**Comment by janscas** [comment]
Closing this as there's no answer

**Comment by mohanrkrishna** [comment]
Hi @TheSanjo  - Is database backend used to store state as well like the way token is stored in sqlite? Please let me know. Thanks!

```
    Temp.delete().execute()
    Temp.create(username=user, state=state)
```
