### ISSUE TITLE
Don't hardcode Connection class in Account constructor

### ISSUE THREAD

**Issue by matthewgdv** [O365/python-o365#347]
Hiya, I was wondering if you could have `Account.__init__()` use a class attribute such as `Account.connection_constructor` to construct its `Connection` object, rather than using `Connection` directly. This would be similar to how classes like `Contact` have a `Contact.message_constructor` class attribute.

That way, implementing a subclass of `Connection` would be as easy as:

```
class MyAmazingConnection(Connection):
    # some code here

class MyAmazingAccount(Account):
    connection_constructor = MyAmazingConnection
```

Because the `Connection` gets passed around pretty much everywhere in this library it's a super useful class to piggyback off when subclassing, since if you want utility methods or persistent states that are accessible from literally everywhere (like say, a personal HTML signature for use in emails, events, etc.) you can save them in the `Connection` and just access them from the current object's `con` attribute.

**Comment by janscas** [comment]
Done!
