### ISSUE TITLE
Calendar functionality returns 400 error

### ISSUE THREAD

**Issue by JeffChuSBX** [O365/python-o365#348]
Steps to reproduce:

```
account = Account(credentials, auth_flow_type='credentials', tenant_id=dirID)
if account.authenticate():
   print('Authenticated!')

schedule = account.schedule()
calendar = schedule.get_default_calendar()
```

Returns: 
`Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/calendar | Error Message: Resource not found for the segment 'calendar'.`

Using Ms Graph explorer:
The rest API looks like `https://graph.microsoft.com/v1.0/me/calendars` so the above URL is missing "me" resource?

**Comment by janscas** [comment]
You are using the credentials auth flow type. With this auth flow type you arre logged in as the application. So you (the 'app') has no calendars nor a default user.

With this auth flow type you have to set the resource from which retrieve the calendars.

Such as:
```python
# ...
schedule = account.schedule(resource='user_i_want_calendars_from@domain.com')
calendar = schedule.get_default_calendar()
```

**Comment by JeffChuSBX** [comment]
That makes sense.  Thanks
