### ISSUE TITLE
Working with Calendar instances. AttributeError: 'NoneType' object has no attribute 'name'.

### ISSUE THREAD

**Issue by isaactorres13** [O365/python-o365#349]
Hello,
I am trying to create an event in another calendar (not the default one, but like the one of "Birthday") that I have in my Outlook account, but when replicating the tutorial to implement that type of events, it sends me the error:

calendar.name = 'Name_Calendar'
AttributeError: 'NoneType' object has no attribute 'name'.

Can you help me please? I already have the token stored and the consent permissions of my account, only this time I want to generate events in another calendar that they request. Thank you.

**Comment by janscas** [comment]
Paste the code you are using to achieve that

**Comment by isaactorres13** [comment]
Of course, this is the code I am using.

```
from O365 import Account

credentials = ('client_idXX', 'client_secretXX')
account = Account(credentials)
import datetime as dt

schedule = account.schedule()
calendar = schedule.get_calendar(calendar_name='My `Calendars')`
calendar_name = 'Project Managers'
calendar.update()

q = calendar.new_query('start').greater_equal(dt.datetime(2019, 11, 3))
q.chain('and').on_attribute('end').less_equal(dt.datetime(2019, 11, 3))

pms= calendar.get_events(query=q, include_recurring=True) 

for event in pms:
    if event.subject == 'Test for PMs':
        event.accept("I'll attend!")  # send a response accepting
    else:
        event.decline("No way I'm comming", send_response=False)  
```

**Comment by janscas** [comment]
> calendar.name = 'Name_Calendar'
> AttributeError: 'NoneType' object has no attribute 'name'.

This is because when retrieving the calendar with 'get_calendar' the calendar was not found.

Try to 'list' the calendars so you can check the available ones.

```python
schedule.list_calendars()
```

**Comment by isaactorres13** [comment]
It works and lists my calendars as follows:

```
Calendar: Calendar from Antonio Mendez
Calendar: Mexico Holidays from Antonio Mendez
Calendar: Birthday from Antonio Mendez
Calendar: Billing from Antonio Mendez
Calendar: Project Managers from Antonio Mendez
```

But now I try to change the name of the calendar in the code as it appears above and it sends me the following:

`Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/calendars/%7Bid%7D | Error Message: Id is malformed.`

**Comment by janscas** [comment]
Maybe you are setting the id or name wrong.

### Testing get_calendar with name:
The following code results in 'test passed' printed.

```python
schedule = account.schedule()

for cal in schedule.list_calendars():
    # ncal holds the same calendar as cal.
    ncal = schedule.get_calendar(calendar_name=cal.name)
    assert ncal.calendar_id == cal.calendar_id

print('test passed')
```

### Testing get_calendar with id:
The following code results in 'test passed' printed.

```python
schedule = account.schedule()

for cal in schedule.list_calendars():
    # ncal holds the same calendar as cal.
    ncal = schedule.get_calendar(calendar_id=cal.calendar_id)
    assert ncal.calendar_id == cal.calendar_id

print('test passed')
```

**Comment by isaactorres13** [comment]
Works!
In the same way I printed "lime" to know what calendar you are working on.
The other thing is how the event is now created with the tutorial parameter to send invitations to those in the "Project Managers" Calendar.

schedule = account.schedule()

```
for cal in schedule.list_calendars():
    # ncal holds the same calendar as cal.
    ncal = schedule.get_calendar(calendar_name=cal.name)
    assert ncal.calendar_id == cal.calendar_id

print('test passed')
print(cal)
```
Print:
```
test passed
Calendar: Project Managers from Antonio Mendez
```

**Comment by janscas** [comment]
just choose the calendar and call the `new_event` method.

**Comment by isaactorres13** [comment]
I am trying to implement the `"new_event"` method but I can't find where to call the calendar name.

**Comment by janscas** [comment]
> I am trying to implement the `"new_event"` method but I can't find where to call the calendar name.

I don't understand.

```python
schedule = account.schedule()

for cal in schedule.list_calendars():
   print(cal.name)

# this prints the calendar names...
# just grab the name of the calendar you want and ... :

cal = schedule.get_calendar(calendar_name='the correct name of the calendar I want as noted in the previous cal.name print')
new_event_from_the_calendar_I_want = cal.new_event()
new_event_from_the_calendar_I_want.subject = 'my subject'
# ... set other event properties...
new_event_from_the_calendar_I_want.save()
```

**Comment by isaactorres13** [comment]
It works perfect!

Thank you very much for the support, janscas.
Regards!
