### ISSUE TITLE
Question:  Trying to access tasks for a given project plan

### ISSUE THREAD

**Issue by JeffChuSBX** [O365/python-o365#351]
I'm trying to access all the tasks for a given plan id.  I have the route properly formed and believe I have all the permissions set properly (I've verified the route and access via MS Graph Explorer).  I'm authenticating with my own identity.  I'm guessing that since permissions only exist for Delegate Type, I can't access this route using the device authentication?  Just wanted to verify.

**Error**
401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/planner/plans/{group_id}/tasks

**Permissions**
![image](https://user-images.githubusercontent.com/57374701/68352340-1e525380-00d4-11ea-8dd0-cfca574cbd9c.png)

**Comment by janscas** [comment]
You have to read: 

https://github.com/O365/python-o365#authentication

You will find the answers there

**Comment by JeffChuSBX** [comment]
I should've been a little more clear.  I tried using "on behalf of user authentication" which hangs after I paste the response URL from the browser after this line in my console window **Paste the authenticated url here:** which is why I switched to the other approach.  I have to restart the kernel to get things working again.  I'm using spyder 3.3.6

Can I simply extract the code from the URL parameter into a token file to get past this?  Do I need to also add the session_state to the JSON token?

**Comment by janscas** [comment]
ok

1. I don't know why it hangs. It doesn't hang for me... So I can't help here. Sometimes depending on the OS and the console app you are using it is difficult to input large strings like the ones needed here. 

1. The two authentication flows are different and require different scopes (again you will see this in the docs). For example you can't use delegated permissions with "with your own identity" auth flow.

1.You can manually retrieve the code and generate a token but this is out of the scope of this library. You will have to figure this somewhere else. It is not so hard but oauth can be complicated sometimes.

1. Finally you can configure your own [authentication interface](https://github.com/O365/python-o365#different-authentication-interfaces). So you are not limited to the console to input the authorization code.

**Comment by janscas** [comment]
Closing this as there's no answer from the user
