### ISSUE TITLE
Error Message: Some users in the request cannot be invited securely.

### ISSUE THREAD

**Issue by weasteam** [O365/python-o365#355]
When I do this:
```
file.share_with_invite(recipients=viewers, send_email=False, share_type='view')
```

For some of the emails, I got the above error. Other email works well. Not sure why. Please advise.

**Comment by janscas** [comment]
This message comes from microsoft. Maybe ask the graph developers about this.

**Comment by weasteam** [comment]
Thanks @janscas ,

How do you reach out to graph developers? I found Microsoft has very bad API documentation and a very limited community. The same issue could not be found on google.

**Comment by janscas** [comment]
Maybe in SO or graph api docs
