### ISSUE TITLE
Create event in Group Calendars. 

### ISSUE THREAD

**Issue by isaactorres13** [O365/python-o365#358]
I am trying to create events in different groups of calendars such as "shared", "other" or "rooms" calendars but I have not found a way to get a list of them. All those names of Calendar Groups I have in my account.
I hope there is a way to do it, thanks.

**Comment by janscas** [comment]
`schedule.list_calendars` doesn't work for you?

**Comment by isaactorres13** [comment]
Yes, it worked in the previous case but this time the account has Groups of Calendars where there are calendars that do not appear to me when running the script.
I don't know if it's because those calendars are managed by a Room List. I hope you can help me.

**Comment by janscas** [comment]
What are "Groups of Calendars". Do you mean calendars owned by a Office 365 Group?

**Comment by janscas** [comment]
> I don't know if it's because those calendars are managed by a Room List. I hope you can help me.

I don't know.
Why don't you check this info into de Graph Api docs?

https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

**Comment by isaactorres13** [comment]
> What are "Groups of Calendars". Do you mean calendars owned by a Office 365 Group?

Yeah that's right.

**Comment by isaactorres13** [comment]
> Why don't you check this info into de Graph Api docs?
> https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

I have reviewed that documentation before when I started the project but found nothing concrete.

**Comment by janscas** [comment]
> Yeah that's right.

Then you have to "resource" that!

Check [resources ](https://github.com/O365/python-o365#resources)on the readme.

```python
schedule = account.schedule(resource='group:my_group_id')
group_calendars = schedule.list_calendars()
```

**Comment by isaactorres13** [comment]
> > Yeah that's right.
> 
> Then you have to "resource" that!
> 
> Check [resources ](https://github.com/O365/python-o365#resources)on the readme.
> 
> ```python
> schedule = account.schedule(resource='group:my_group_id')
> group_calendars = schedule.list_calendars()
> ```

Very well, I will review the article and try to execute the command hoping it works.
