### ISSUE TITLE
[Question] o365 limits number of emails you can process?

### ISSUE THREAD

**Issue by lia-cha-avalara** [O365/python-o365#360]
I'm not quite sure how to ask this question but I wrote a script that scrapes an inbox, writes the email subject, received date, sender, attachment names, and flag status depending on whatever parameters are passed in from jenkins.

It's been working well for 3-4 weeks but noticed recently it started reporting a HTTP 500 Internal Server error whenever it tried running the message.send() method. I can confirm the csv file it writes to has all the correct data, it just won't send the email.

The only thing I can think of is o365 is somehow throttling the number of calls you can make? If i enforce a limit on the number of messages it can retrieve to 500 to 3k, everything works as normal. The inbox previously had 16-18k messages while it was running okay. This week its hovering over 19k messages and I am now getting failures when attempting to send the report in an email. Any thoughts? helpful hints on how to work around this?

**Comment by janscas** [comment]
Check the article about throttling in the microsoft graph api docs

**Comment by lia-cha-avalara** [comment]
hmm their doc says for outlook the limit is 10k calls in 10min period (not sure if this covers o365 as well). Guess I don't get it because the docs telling me if im being throttled, i should be getting a http 429 code but I'm getting a http 500 code. Also if the 10k calls limit was being enforced, not sure why my script was working fine at 16-18k calls.

Would using the batch parameter in the get_messages() help with this at all or should I just increase the requests_delay value?

**Comment by janscas** [comment]
See:
https://docs.microsoft.com/en-us/graph/throttling?view=graph-rest-1.0

And:

https://docs.microsoft.com/en-us/graph/best-practices-concept?context=graph%2Fapi%2F1.0&view=graph-rest-1.0#handling-expected-errors

503 server error: You should employ a back-off strategy similar to 429

Also note in case a 429 response is received and you activate auto-retry (activated by default) the O365 library will auto retry after the Retry-After header time.

**Comment by Muthukrishna17** [comment]
can we manually set retry_after variable through O365 lib in python?

**Comment by janscas** [comment]
no, the retry after is set by the server
