### ISSUE TITLE
application password support?

### ISSUE THREAD

**Issue by segalion** [O365/python-o365#363]
Some companies dont let external apps access to tenant at all, but let users create passwords for some legacy applications:

https://docs.microsoft.com/es-es/azure/active-directory/user-help/multi-factor-authentication-end-user-app-passwords

Do you know if python-o365 could use this kind of authentication?
Sure it works similar to basic-auth, because "old apps" works fine login with "o365_user" and "legacy_app_password"

Thanks in advance.

**Comment by janscas** [comment]
Both Microsoft Graph and Microsoft Office 365 Rest Api only allow oauth authentication (no user and password).

Sorry

**Comment by segalion** [comment]
Microsoft say outlook.office.com/api and graph.microsoft.com/api only accept oauth authenticatión.
But I suspect we can use outlook.office365.com/api with application password (as basic auth method for legacy apps).

**Comment by janscas** [comment]
The office 365 rest api docs only talk abou oauth authentication:

https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/use-outlook-rest-api#register-and-authenticate-your-app

**Comment by janscas** [comment]
Further info:

> All Outlook REST API requests use the following new root URL format:
> 
> https://outlook.office.com/api/{version}/{user_context}
> 
> With the appropriate user authorization, the REST API in this root URL provides access to mailbox data on Office 365 and Outlook.com. The rest of this article describes REST API in this endpoint.
> 
> If you have code that uses the pre-existing root URL https://outlook.office365.com/api/{version}/{user_context}, your code will continue to work for a while for Office 365, but you should plan to switch to the new root URL.

**Comment by segalion** [comment]
Thanks jancas. 

Seems I was wrong: the application password in O365 only works for old APIs (exchange EWS), not for API REST.
You can close the isue.
