### ISSUE TITLE
Access to the Global Address List

### ISSUE THREAD

**Issue by nishizawa-jpn** [O365/python-o365#365]
I tried the sample. 
```
 address_book=account.address_book()
 global_address_list = account.address_book(address_book='gal')
 q=global_address_list.new_query('display_name')
 q.startswith('George Best')
 print(global_address_list.get_contacts(query=q))
```
>>AttributeError: 'Directory' object has no attribute 'get_contacts'

  This sample is wrong?
  I succeeded the following code.
```
 print(global_address_list.get_current_user())
```
>>TestUser

but I cloud not get users list.
```
lists=global_address_list.get_users()
lists.__next__()
```
>>StopIteration

how do i get users list?
i'm sorry for my poor English.

**Comment by janscas** [comment]
I'm so sorry... the Readme was not updated.
I've commited a change to reflect the las changes to the api.

You should:

```python
directory = account.directory()
q = directory.q().on_attribute('display_name').startswith('George Best')
for user in directory.get_users(query=q):
    print(user)

# or get just one user:
user = directory.get_user('user_email@domain.com')
```

**Comment by nishizawa-jpn** [comment]
Thank you for updating Readme! I cloud get users list.
I have one more question.
Is there a way to get a calendar from user information obtained from "directory.get_user()"?
I want to get the user's calendar from the global address list.

**Comment by janscas** [comment]
Provided that you have access to the user calendars, then you simply:

```python
user_schedule = account.schedule(resource='the_user_email')
# etc.
```

**Comment by nishizawa-jpn** [comment]
I cloud get the user's calendar from the global address list.
Thank you for your help!
