### ISSUE TITLE
Question about Mailbox Feature

### ISSUE THREAD

**Issue by rootsid** [O365/python-o365#366]
From mailbox we can get the emails but it gives email subjects only, how can we get the body of the email ?

**Comment by janscas** [comment]
You should review the readme.

Try: message.body

**Comment by rootsid** [comment]
I did but it was mentioned for sending emails out, it will be wicked if you can put some samples for mail.read including message.body as well.

**Comment by rootsid** [comment]
to be exact like get a body of selected subject and selected sender.

**Comment by janscas** [comment]
Are you trying to filter messages from a specific sender?

**Comment by rootsid** [comment]
Yeah I'm trying to filter messages from specific sender if sender is this then get the body of that message or if there is any attachment then get that as well and save that in current directory.

**Comment by janscas** [comment]
> query = inbox.q().on_attribute('sender').contains('view')

This should be:

```python
query = inbox.q().on_attribute('from').contains('view')
```

Although consider that Odata query "Contains" is restricted to some fields and could not work. Try it and see...

**Comment by janscas** [comment]
> Yeah I'm trying to filter messages from specific sender if sender is this then get the body of that message or if there is any attachment then get that as well and save that in current directory.

```python
mailbox = account.mailbox()
inbox = mailbox.inbox_folder()
query = inbox.q().on_attribute('from').startswith('view')  # startswith is usually less restrictive, although contains could work  
for message in inbox.get_messages(query=query, download_attachments=True):
    print(message)
    body = message.get_body_text()
    clean_body = body.replace('\n\n\n\xa0', '').replace('\n\n', '').replace('n\xa0', '')
    print(clean_body)
    if message.has_attachments:
        for att in message.attachments:
            att.save('my_path')
    print("*************************************")
```

**Comment by rootsid** [comment]
Gotcha worked like a charm. Just one more quick question can you give me a query sample of multiple queries 
like from startswith && subject contains && orderby recievedtime

That will be wicked.

**Comment by janscas** [comment]
Don't have time right now...

Try to look into the code. Some combinations of Odata filters could not work. You can try them on the [graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer)

**Comment by rootsid** [comment]
got it thanks for help Jans.
