### ISSUE TITLE
No module named Account

### ISSUE THREAD

**Issue by umrashrf** [O365/python-o365#367]
Fresh install O365 using pip but the README seems to be wrong. There is no Account module.

```
$ pip freeze | grep O365
O365==0.9.16
```

**Comment by janscas** [comment]
Upgrade to last version

**Comment by umrashrf** [comment]
The latest version is not Python 2 compatible but I guess its me who needs to move my project to Python 3.

**Comment by janscas** [comment]
Yep. Version 1 and above is not compatible with py2
