### ISSUE TITLE
Documentation: step 3 of the flask example?

### ISSUE THREAD

**Issue by johanovic** [O365/python-o365#369]
The README provides a Flask authentication logic, but it does not provide a step 3. Does a third view, for instance, one which shows the top 10 messages of the inbox, simply do the following?

    account = Account(credentials = ('bla', 'bla'),
        scopes=['offline_access', 'Mail.Read'])
    mb = account.mailbox()
    messages = mb.get_messages()

If it's the case that you don't need to authenticate explicitly (it happens automagically) that's lovely, but it might be worthwhile adding it to the docs.

**Comment by janscas** [comment]
The example only provides the authentication logic.

It lacks _"operational logic"_ and _"logout"_ because it's really easy.

For the former just needs to instantiate an account, check if the account is authenticated and then use the api.

Something like that (i'm writing this fast so sorry for any error)...

```python
@route('/getmessages')
def get_messages():
    account = Account(credentials)  # the scopes are only needed for authentication not to operate with the api.
    if not account.is_authenticated:
        # redirect to authentication endpoint
        return redirect('authenticate')
    inbox = account.mailbox().inbox_folder()
    messages = inbox.get_messages()
    # process the messages ...
    return render_template('messages_list.html', messages=messages)
```

The logout is simply to delete the stored token...

**Comment by johanovic** [comment]
Your answer is really helpful. Maybe add it to the README?

**Comment by janscas** [comment]
On my post I said this:

> ```python
> # the scopes are only needed for authentication not to operate with the api.
> ```

This is only True  when using the "on behalf of a user" auth flow.
If you use the "with your own identity" auth flow, then you will need the scopes to be able to refresh the access token.
