### ISSUE TITLE
Django example?

### ISSUE THREAD

**Issue by johanovic** [O365/python-o365#370]
I am trying to convert the Flask example to a django one, but I am running into an issue.

I am running https://github.com/teddziuba/django-sslserver to get this working. Three separate views handle the process. In the second step, I do **not** get a result. Not sure why that is the case. Any insight? 

    from django.shortcuts import render, redirect, HttpResponseRedirect
    from django.contrib.auth.decorators import user_passes_test

    from O365 import Account, MSGraphProtocol

    @user_passes_test(lambda u: u.is_superuser)
    def authenticate_graph_step1(request):
        print('Start the first view')

        callback = 'https://localhost:8000/graph/step2/'
        account = Account(credentials = ('bla', 'bla'),
            scopes=['offline_access', 'Mail.Read'])
        url, state = account.con.get_authorization_url(requested_scopes=['offline_access', 'Mail.Read'],
                                                    redirect_uri=callback)
        with open('state.txt', 'w') as statefile:
            statefile.write(state)
        return redirect(url)

    def authenticate_graph_step2(request):
        print('Start the second view')

        with open('state.txt') as statefile:
            state = statefile.read()
        callback = 'https://localhost:8000/graph/step2/'
        account = Account(credentials = (credentials = ('bla', 'bla'),
            scopes=['offline_access', 'Mail.Read'])
        request_uri = request.get_full_path()
        result = account.con.request_token(request_uri, 
                                        state=state,
                                        redirect_uri=callback)
        if result:
            return redirect('messages')
        else:
            print("George Best all the way")

    @user_passes_test(lambda u: u.is_superuser)
    def messages(request):
        print('Now handling the messages')

        account = Account(credentials = (credentials = ('bla', 'bla'),
            scopes=['offline_access', 'Mail.Read'])
        mb = account.mailbox()
        messages = mb.get_messages()
        return render(request, 'connects/graph_george_best.html', {'messages':messages})

The error I get is `No auth token found. Authentication Flow needed`

**Comment by johanovic** [comment]
Actually I found the error

This line 

     request_uri = request.get_full_path()

should be

    request_uri = request.build_absolute_uri()

Maybe a django example could be added? Or, people might just google this one.

**Comment by janscas** [comment]
> Maybe a django example could be added? Or, people might just google this one.

It's quite the same logic. You just have to define two endpoints one to initiate the process and the other to act as a callback.
