### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by johanovic** [O365/python-o365#371]
I am a bit confused by the amount of 'automagical' things that take place. For instance, the way the token backend saves tokens, it is just insufficiently unclear to me. I have to read almost all the code to understand what is going on. Do you maybe want to add some more detail? And a number of examples? 

I'll give a usecase. I want to store connections based on a user_principal_name. I want to store user_principal_name + token. To get that user_principal_name I first need to request the token, but I can't store it yet because I first have to get user_principal_name. So the automatic parts (storing a token, refreshing it, etc.) could really do with more documentation, I think.

Thanks

**Comment by janscas** [comment]
In the beginning the library was storing the tokens in the file system without other options. Then we allowed to pass a TokenBackend that will abstract the notion of the backend who stores the token info.

So, the library only knows that the token backend can "load" or "save" a token. Where and how it's done is not important for the library.

If you want to store the token in Redis, for example, you just subclass the [BaseTokenBackend](https://github.com/O365/python-o365/blob/master/O365/utils/token.py#L66) and implement the abstract methods `load_token` and `save_token` along with your needed initialisation (__init__ method).

The library will call this methods when the token is needed (at initialisation or save the token after a refresh action for example).

**It is not obscure.** Just look the [token backends implementation](https://github.com/O365/python-o365/blob/master/O365/utils/token.py)... and read [the readme](https://github.com/O365/python-o365#token-storage) file.


> I'll give a usecase. I want to store connections based on a user_principal_name. I want to store user_principal_name + token. To get that user_principal_name I first need to request the token, but I can't store it yet because I first have to get user_principal_name. So the automatic parts (storing a token, refreshing it, etc.) could really do with more documentation, I think.

Well this will hit you on the load stage of the token.
**How are you going to find the already saved token in the first place if you don't know the user principal name?**
You need somehow to know in advance "who" is the user accessing you api.


The library **by default** will store the token in the backend when it first retrieve's the token (just in the authentication phase). If you follow the default of course you will run into this "chicken/egg" problem.
You can change this by writing your own authentication interface (see [how to design your own authentication interface](https://github.com/O365/python-o365#different-authentication-interfaces))

So, you will need to modify the call to `request_token` to pass `store_token=False`. Then retrieve the user principal name and manually call `token_backend.save_token()`
This can be done manually, but as all the kwargs passed to `account.authenticate` are also passed to `request_token` you can do it without modifying anything.

```python
from O365.utils import BaseTokenBackend

class MyTokenBackend(BaseTokenBackend):
    def __init__(user_principal_name=None):  # at the initialisation maybe user_principal_name it's unknown...
        super().__init__()
        self.user_principal_name = user_principal_name  
        # define any other attributes you need for the load_token and save_token to work

    def load_token():
        # here implement the call that retrieves the token using the self.user_principal_name
        if self.user_principal_name is None:
            return None
        # ...
        pass

    def save_token():
        # here implement the call that stores the token using the self.user_principal_name
        if self.user_principal_name is None:
            return False
        # ...
        pass

# if you know who is the user using your api pass his user principal name here.
account = Account(credentials, token_backend=MyTokenBackend(user_principal_name=None))

# this call will try to load the token from the backend.
# If the user principal name is not set, then the load_token will return None (see token backend implementation) and there for the user is NOT authenticated...
if not account.is_authenticated:
    # design your authentication process...
    # using the default for this example only...
    account.authenticate(scopes=scopes, store_token=False)  # the token backend will NOT store the token.

    # here I have a token so I can retrieve the user:
    user = account.get_current_user()

    account.con.token_backend.user_principal_name = user.user_principal_name
    
    # now the token_backend knows the user_principal_name so we can call save_token...
    account.con.token_backend.save_token()  # save the token in the backend

# here the token is loaded and ready to go...
```

You can look in the `connection.py` for the following keywords to see what methods load or store the token: 

- `self.token_backend.save_token`
- `self.token_backend.get_token`

**Comment by johanovic** [comment]
This is a great answer to my question. It brings several concepts together that I found hard to understand. Thanks! Maybe this could be added to the docs?

**Comment by johanovic** [comment]
Does the token backend have access to the connection and/or the account?

**Comment by janscas** [comment]
> Maybe this could be added to the docs?

I'll try to add more info to the readme



> Does the token backend have access to the connection and/or the account?

No. There is a method that can access the connection called [should_refresh_token](https://github.com/O365/python-o365/blob/master/O365/utils/token.py#L110) that have access to the connection. But this a very specific method that is used to avoid parallel connections request tokens at the same time (discussed on #350).

**Comment by janscas** [comment]
Just asking... Why do you think the token backend needs to know about the account or connection?

**Comment by johanovic** [comment]
If I the token backend has access to the connection, I could simply add a few lines to save_token that force getting the user_principal_name *before* saving.

**Comment by johanovic** [comment]
If ever someone is reading this in the future, my solution was the following:

- In a first view: store a model instance with the state, but without token
- In a second view: get that model instance based on the state that is part of the request get parameters. In this view: pass the instance to a dedicated custom backend. Save the token in there. Then get the instance back again in the view (you have to hit the db again, but it has been changed) and update any info you want.
- In any other view, use the custom backend.

**Comment by janscas** [comment]
Great @johanovic. Just to let you now, I've updated a bit the readme with the info from this issue as requested.

**Comment by johanovic** [comment]
Thanks!

**Comment by mohanrkrishna** [comment]
Hi @johanovic - Thanks for sharing summary of how you implemented. I am building Flask/Python web app , looking to implement similar solution 
1) User logs in. App determines principal id and checks if valid token exists from backend
2) If not get token using request_token and store in backend
3) If token is present, load it and proceed

I am going through sample given by tool author @janscas in above comments. Can you please share any reference code (if feasible) which i can also piggy back to implement the solution.  Thanks very much!
