### ISSUE TITLE
User Properties

### ISSUE THREAD

**Issue by nishizawa-jpn** [O365/python-o365#372]
The following code, i could get user properties.
```
directory=account.directory()
user_query=directory.q().on_attribute('display_name').startswith("TestUser")
users=directory.get_users(query=user_query)
for user in users:
    print(user.display_name)
    print(user.given_name)
    print(user.surname)
    print(user.mail) 
    print(user.business_phones)
    print(user.office_location)
```

> TestUser
> Test
> User
> test01@domain.com
> ['+1 1111111111']
> office
> ja-JP

but I could not get detail properties.Is there anything missing from this code?
```
for user in users:
    print(user.preferred_language)
    print(user.city)
    print(user.company_name)
    print(user.country)
    print(user.department)
```

> None
> None
> None
> None
> None

**Comment by janscas** [comment]
Are you using scope User.ReadBasic.All?

**Comment by nishizawa-jpn** [comment]
I'm using scope User.Read.All and have admin consent.

**Comment by janscas** [comment]
Ok, that’s an application permission. It has been approved by an admin?

**Comment by nishizawa-jpn** [comment]
Yes,it has been approved by an admin

**Comment by janscas** [comment]
Mmmm....

Then I don’t know if it’s a bug of this librwry or something else.

Can you try to request the same query in the microsoft graph explorer and see if all the fields appear?

**Comment by nishizawa-jpn** [comment]
OK,I'll try it.Thank you!

**Comment by nishizawa-jpn** [comment]
```
import requests
import pprint
headers={'Authorization': 'Bearer eyJ0e....'}
req=requests.get("https://graph.microsoft.com/v1.0/users",headers=headers)
pprint.pprint(req.json())
```

> 'value' :
>{'businessPhones': ['+1 1111111111'],
>'displayName': 'TestUser',
>             'givenName': 'Test',
>             'id': '***',
>             'jobTitle': 'job',
>             'mail': 'test01@domain.com',
>             'mobilePhone': '+1 2222222222',
>             'officeLocation': 'office',
>             'preferredLanguage': 'ja-JP',
>             'surname': 'User',
>             'userPrincipalName': 'test01@domain.com'},

I could get detail properties
```
req=requests.get("https://graph.microsoft.com/v1.0/users$select=city,country,department,postalCode",headers=headers)
pprint.pprint(req.json())
```

>  'value': [{'city': 'city',
>             'country': jp,
>             'department': department,
>             'postalCode': '111-1111'},

**Comment by janscas** [comment]
Hi @nickyspag check [this](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#optional-query-parameters):

> By default, only a limited set of properties are returned (businessPhones, displayName, givenName, id, jobTitle, mail, mobilePhone, officeLocation, preferredLanguage, surname, and userPrincipalName).
> 
> To return an alternative property set, specify the desired set of user properties using the OData $select query parameter. For example, to return displayName, givenName, and postalCode, add the following to your query $select=displayName,givenName,postalCode.
> 
> Certain properties cannot be returned within a user collection. The following properties are only supported when retrieving an single user: aboutMe, birthday, hireDate, interests, mySite, pastProjects, preferredName, responsibilities, schools, skills, mailboxSettings.

So, as the second paragraph said, you have to select those properties:

```python
directory = account.directory()
user_query = directory.q().on_attribute('display_name').startswith("TestUser")

# select properties:
user_query = user_query.select('country', 'city')  # etc.

for user in directory.get_users(query=user_query):
    print(user.country)
    print(user.city)
 ```

**Comment by nishizawa-jpn** [comment]
I could get properties!
Thank you for your help!
