### ISSUE TITLE
With own identity auth 400 error

### ISSUE THREAD

**Issue by davidwynter** [O365/python-o365#373]
This is the debug output:

    DEBUG:requests_oauthlib.oauth2_session:Requesting url https://login.microsoftonline.com/<tenant_id>/oauth2/v2.0/token using method POST.
	DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'client_credentials', 'client_id': '<client_id>', 'client_secret': '<client_secret>', 'scope': 'https://graph.microsoft.com/.default', 'redirect_uri': 'https://login.microsoftonline.com/common/oauth2/nativeclient'}
    DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {'json': None, 'timeout': None, 'auth': None, 'verify': True, 'proxies': None}.
     DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): login.microsoftonline.com:443
     DEBUG:urllib3.connectionpool:https://login.microsoftonline.com:443 "POST /<tenant_id>/oauth2/v2.0/token HTTP/1.1" 200 1427
     DEBUG:requests_oauthlib.oauth2_session:Prepared fetch token request body grant_type=client_credentials&client_id=<client_id>&client_secret=<client_secret>%3F&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fnativeclient
     DEBUG:requests_oauthlib.oauth2_session:Request to fetch token completed with status 200.
     DEBUG:requests_oauthlib.oauth2_session:Request headers were {'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '266'}
     DEBUG:requests_oauthlib.oauth2_session:Request body was grant_type=client_credentials&client_id=<client_id>&client_secret=<client_secret>%3F&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fnativeclient
     DEBUG:requests_oauthlib.oauth2_session:Response headers were {'Cache-Control': 'no-cache, no-store', 'Pragma': 'no-cache', 'Content-Type': 'application/json; charset=utf-8', 'Expires': '-1', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains', 'X-Content-Type-Options': 'nosniff', 'x-ms-request-id': '044d2fc4-2672-457e-bc4d-79c8083d1000', 'x-ms-ests-server': '2.1.9767.22 - DUB2 ProdSlices', 'P3P': 'CP="DSP CUR OTPi IND OTRi ONL FIN"', 'Set-Cookie': 'fpc=AsdJ1jwimFFJhCftFhf5OpqRjr2_AQAAAHQ4jdUOAAAA; expires=Sat, 18-Jan-2020 09:23:00 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=prod; path=/; SameSite=None; secure; HttpOnly, stsservicecookie=ests; path=/; SameSite=None; secure; HttpOnly', 'Date': 'Thu, 19 Dec 2019 09:23:00 GMT', 'Content-Length': '1427'} and content {"token_type":"Bearer","expires_in":3599,"ext_expires_in":3599,"access_token":"<snip>"}.
     DEBUG:requests_oauthlib.oauth2_session:Invoking 0 token response hooks.
     DEBUG:requests_oauthlib.oauth2_session:Obtained token {'token_type': 'Bearer', 'expires_in': 3599, 'ext_expires_in': 3599, 'access_token': '<snip>', 'expires_at': 1576750979.7527802}.
     INFO:O365.connection:Requesting (POST) URL: https://graph.microsoft.com/v1.0/sendMail
     INFO:O365.connection:Request parameters: {'data': '{"message": {"subject": "Error file for client - test_managedlist yaml_group Values added to the list test are in the attached file named core_added_test.csv. Values removed from the list test are in the attached file named core_removed_test.csv", "body": {"contentType": "HTML", "content": "No message body set for this message, check store_error_msg has been called prior to sending"}, "importance": "normal", "flag": {"flagStatus": "notFlagged"}, "isReadReceiptRequested": false, "isDeliveryReceiptRequested": false, "toRecipients": [{"emailAddress": {"address": "david<snip>"}}], "attachments": [{"@odata.type": "#microsoft.graph.fileAttachment", "name": ",test\\n0,test1\\n1,test2\\n", "contentBytes": null}, {"@odata.type": "#microsoft.graph.fileAttachment", "name": ",test\\n0,test3\\n1,test4\\n", "contentBytes": null}]}}', 'headers': {'Content-type': 'application/json'}}
     DEBUG:requests_oauthlib.oauth2_session:Invoking 0 protected resource request hooks.
     DEBUG:requests_oauthlib.oauth2_session:Adding token {'token_type': 'Bearer', 'expires_in': 3599, 'ext_expires_in': 3599, 'access_token': '<snip>', 'expires_at': 1576750979.7527802} to request.
     DEBUG:requests_oauthlib.oauth2_session:Requesting url https://graph.microsoft.com/v1.0/sendMail using method post.
     DEBUG:requests_oauthlib.oauth2_session:Supplying headers {'Content-type': 'application/json', 'Authorization': 'Bearer <snip>'} and data {"message": {"subject": "Error file for client - test_managedlist yaml_group Values added to the list test are in the attached file named core_added_test.csv. Values removed from the list test are in the attached file named core_removed_test.csv", "body": {"contentType": "HTML", "content": "No message body set for this message, check store_error_msg has been called prior to sending"}, "importance": "normal", "flag": {"flagStatus": "notFlagged"}, "isReadReceiptRequested": false, "isDeliveryReceiptRequested": false, "toRecipients": [{"emailAddress": {"address": "david<snip>"}}], "attachments": [{"@odata.type": "#microsoft.graph.fileAttachment", "name": ",test\n0,test1\n1,test2\n", "contentBytes": null}, {"@odata.type": "#microsoft.graph.fileAttachment", "name": ",test\n0,test3\n1,test4\n", "contentBytes": null}]}}
     DEBUG:requests_oauthlib.oauth2_session:Passing through key word arguments {}.
     DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): graph.microsoft.com:443
     DEBUG:urllib3.connectionpool:https://graph.microsoft.com:443 "POST /v1.0/sendMail HTTP/1.1" 400 242
     ERROR:O365.connection:Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/sendMail | Error Message: Resource not found for the segment 'sendMail'.

Here is the code:

        credentials = (tuple(self.credentials365))
        account = Account(credentials, auth_flow_type='credentials', tenant_id=self.tenant_id)
        if not account.is_authenticated:  # will check if there is a token and has not expired
            # ask for a login
            # console based authentication See Authentication for other flows
            account.authenticate()

        m = account.new_message()
        for to in self.to:
            m.to.add(to)
        m.subject = self.subject_prefix + caller + ' yaml_group ' + yaml_grp
        if hasattr(self, 'errormsg'):
            m.body = self.errormsg[caller]
        else:
            m.body = 'No message body set for this message, check store_error_msg has been called prior to sending'

        for filename in filenames:
            m.attachments.add(filename)

        m.send()

I have a o365token.txt file in the same directory as the code above is placed. 

I have an additional question. If we are going to deploy to > 1 servers can we just distribute the same o365token.txt across multiple servers that run our web application (where the emails are sent from)

**Comment by janscas** [comment]
Hi, what version are you using?
are you pulling from github?

**Comment by davidwynter** [comment]
I have 2.0.5 in my requirements.txt file. Not pulling from github.
