### ISSUE TITLE
Can we add Message Attachments using StringIO?

### ISSUE THREAD

**Issue by davidwynter** [O365/python-o365#374]
I have a couple of Pandas dataframes I want to attach to an email. Do I have to save them to a physical file before attaching or can I pass something like this

        removed = self.export_csv(df_removed)
        added = self.export_csv(df_added)
        for filename in [removed, added]:
            m.attachments.add(filename)

**Comment by janscas** [comment]
Yes sure. You can attach a BytesIO object so you don’t have to save anything to disk.

**Comment by davidwynter** [comment]
I read the BaseAttachment code and saw you pass in a tuple with the (StringIO, 'filename'), line 131 of Attachment.py, But on running it the constructor seems to strip the 'filename' and thus it does not work. 

Can you give an example of how this is supposed to be called?

I have this:

    attachments = [(io.StringIO(removed), managed_list+'_removed'),
                                                 (io.StringIO(added), managed_list+'_added')]

    ...
    for attachment in attachments:
        if isinstance(attachment, tuple):
                m.attachments.add(attachment)

    m.send

This produces this error:

      File "/Users/david/PycharmProjects/etl/app/etl/senderror.py", line 140, in send_0365
    m.send()
      File "/Users/david/miniconda3/envs/frontendnewgen/lib/python3.7/site-packages/O365/message.py", line 676, in send
    response = self.con.post(url, data=data)
      File "/Users/david/miniconda3/envs/frontendnewgen/lib/python3.7/site-packages/O365/connection.py", line 725, in post
    return self.oauth_request(url, 'post', data=data, **kwargs)
      File "/Users/david/miniconda3/envs/frontendnewgen/lib/python3.7/site-packages/O365/connection.py", line 703, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
      File "/Users/david/miniconda3/envs/frontendnewgen/lib/python3.7/site- 
    packages/O365/connection.py", line 665, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) 
    from None
    requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: 
    https://graph.microsoft.com/v1.0/users/etlerror@fairxchange.co.uk/sendMail | Error Message: 
    Required property is missing.

**Comment by janscas** [comment]
You need to pass a name. It's required.

Also, when passing tuples (file object, name), you need to enclose them in a list.

This works:

```python
from io import BytesIO

# sample data
data= BytesIO()
data.write(b"Hello World")


in_memory_attachment = (data, 'sample_text.txt')

msg = account.new_message()  # type: Message
msg.subject = 'test bytes io'
msg.to.add('email@email.com')
msg.attachments.add([in_memory_attachment])
msg.send()
```

**Comment by davidwynter** [comment]
I am attaching 2 files as StringIO but am getting an error message "Required property is missing." but it does not identify which one is missing?

Here is the message being sent:

    {"message": {"subject": "Values added to the list test are in the attached file named core_added_test.csv. Values removed from the list test are in the attached file named core_removed_test.csv", "body": {"contentType": "HTML", "content": "No message body set for this message, check store_error_msg has been called prior to sending"}, "importance": "normal", "flag": {"flagStatus": "notFlagged"}, "isReadReceiptRequested": false, "isDeliveryReceiptRequested": false, "toRecipients": [{"emailAddress": {"address": "david.wynter@fairxchange.co.uk"}}], "attachments": [{"@odata.type": "#microsoft.graph.fileAttachment", "name": null, "contentBytes": null}, {"@odata.type": "#microsoft.graph.fileAttachment", "name": "test_removed", "contentBytes": null}, {"@odata.type": "#microsoft.graph.fileAttachment", "name": null, "contentBytes": null}, {"@odata.type": "#microsoft.graph.fileAttachment", "name": "test_added", "contentBytes": null}]}}

Here is the code:

        credentials = (tuple(self.credentials365))
        logging.getLogger("O365").setLevel(logging.WARNING)
        account = O365.Account(credentials, auth_flow_type='credentials', tenant_id=self.tenant_id)
        if not account.is_authenticated:  # will check if there is a token and has not expired
            # ask for a login
            # console based authentication See Authentication for other flows
            account.authenticate()

        mailbox = account.mailbox(self.from_address)
        m = mailbox.new_message()
        for to in self.to:
            m.to.add(to)

        m.subject = subject
        if hasattr(self, 'errormsg'):
            m.body = self.errormsg[caller]

        else:
            m.body = 'No message body set for this message, check store_error_msg has been called prior to sending'

        i = 0
        for attachment in attachments:
            if isinstance(attachment, tuple):
                m.attachments.add(attachment)
            else:
                m.attachments.add(attachment, 'name' + str(i))
                i = i+1

        m.send()
