### ISSUE TITLE
EventRecurrence end_date property in calendar

### ISSUE THREAD

**Issue by lindera-steffen** [O365/python-o365#376]
The Getter doesn't seem right:

    @property
    def end_date(self):
        """ End date of repetition
        :getter: get the end date
        :setter: set the end date
        :type: date
        """
        return self.__start_date

**Comment by janscas** [comment]
Thanks!!

**Comment by lindera-steffen** [comment]
no problem. when will it be on pypi? (Or I guess in the auto_deploy branch)

I don't really want to directly get it from git when I deploy my project, when I could just install it via pip...

**Comment by janscas** [comment]
there's a release each month more or less...
