### ISSUE TITLE
Getting the response after sending a msg

### ISSUE THREAD

**Issue by johanovic** [O365/python-o365#377]
I want to access the web_link for a message that I have sent. 

According to the graph docs, this is part of the response (https://docs.microsoft.com/en-us/graph/api/user-post-messages?view=graph-rest-1.0&tabs=http), but the property is not updated on the instance of a messages created via account.mailbox().new_message().

A) is it possible to access the actual response given by graph
B) can the web_link attribute be updated after sending the message?

Thanks

**Comment by johanovic** [comment]
It would feel natural to me that msg.send() would return the JSON response from the server.

**Comment by janscas** [comment]
> A) is it possible to access the actual response given by graph
> B) can the web_link attribute be updated after sending the message?

The answer is:
A) No for the moment but the library should update any relevant data into the instance.
B) Yes! I'll change that.

**Comment by janscas** [comment]
Hi, when a message is created the response includes a weblink. This is now updated on the message instance when you call 'save_message' or 'save_draft'. 

It is not posible to update this value when you send it as you will notice [here](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http).

However, you can create the message instance, save the draft, and grab the weblink.
What I don't know is if this weblink is still valid when you send the message.

As a workaround, you can retrieve the sent message just after send it and grab the weblink from there.
