### ISSUE TITLE
Reasons a setup could fail on production?

### ISSUE THREAD

**Issue by johanovic** [O365/python-o365#381]
I slightly different question.

I have a full setup that works in development (with a localhost callback, custom token backend, and credentials and scopes, etc.), but when I deploy it on a server it does not work anymore. What is the best way to debug this? The server runs nginx.

Thanks

**Comment by janscas** [comment]
I don't know...
It should work.

To debug set:

```python
import logging

logger = logging.getLogger('O365')
logger.setLevel(level=logging.DEBUG)
```

**Comment by johanovic** [comment]
Where would you set the debugging and where would it log?

**Comment by janscas** [comment]
At the beginning of the script. To the stdout.

**Comment by johanovic** [comment]
Thank you so much, this has helped me debug the issue. After seven days :( but hey, happy to have it fixed. Maybe a good idea to add this to the docs? Or did I miss it?

**Comment by janscas** [comment]
This is not about O365 but about python logging basics.
