### ISSUE TITLE
File Referencing on onedrive

### ISSUE THREAD

**Issue by rtusa7** [O365/python-o365#383]
This may be a simple question.  I am using the O365 package to read an excel file.  I can log-in to my OneDrive, and see my file system.  However, I am unable to reference my file.

I have followed the tutorial, authenticated and referenced my drives successfully using these commands.  
from O365 import Account
credentials = (my_client_id, my_client_secret)
scopes = ['basic','onedrive']
account = Account(credentials, scopes=scopes)
account.authenticate()
storage=account.storage()
my_drive=storage.get_default_drive()
docfolder=my_drive.get_special_folder('Documents')

I can see the .xlsx file in the Documents directory, but I do not know how to reference it.  For example:
file=<need the syntax here>filename.xlsx

Help would be greatly appreciated.  I could not see an example staement in the documentation or anywhere online.

**Comment by janscas** [comment]
You can use `search` or `get_items`.

Look in the code base

For example:

```python
files = docfolder.search('filename.xlxs')
if len(files) == 1:
   print(files[0])
```

**Comment by rtusa7** [comment]
Thank you.  That is what I needed.
