### ISSUE TITLE
Token refresh seems to work but get an error saying the access_token is empty

### ISSUE THREAD

**Issue by davidwynter** [O365/python-o365#385]
When I run under debug and inspect the account.con.token_backend.token.access_token object being used it is there. `{'token_type': 'Bearer', 'expires_in': 3599, 'ext_expires_in': 3599, 'access_token': 'eyJ0e...493Sp_Q', 'expires_at': 1578586873.5086055}`

expiration_datetime  is 

    2020-01-09 16:20:13.508605

But I get this error response:

    error |  
    code | "InvalidAuthenticationToken"
    message | "Access token is empty."
    innerError |  
    request-id | "b999e9f5-0c1b-4191-9bc8-6d271c89228b"
    date | "2020-01-09T16:04:13"

Any ideas?

UPDATE: Code used

    def send_0365(self, caller, subject, attachments):
        credentials = (tuple(self.credentials365))
        logging.getLogger("O365").setLevel(logging.WARNING)
        account = O365.Account(credentials, auth_flow_type='credentials', tenant_id=self.tenant_id)
        if not account.is_authenticated:  # will check if there is a token and has not expired
            # ask for a login
            # console based authentication See Authentication for other flows
            account.authenticate()

        mailbox = account.mailbox(self.from_address)
        m = mailbox.new_message()
        for to in self.to:
            m.to.add(to)

        m.subject = subject
        if hasattr(self, 'errormsg'):
            m.body = self.errormsg[caller]

        else:
            m.body = 'No message body set for this message, check store_error_msg has been called prior to sending'

        i = 0
        for attachment in attachments:
            if isinstance(attachment, tuple):
                m.attachments.add(attachment)
            else:
                m.attachments.add(attachment, 'name' + str(i))
                i = i+1

        m.send()

Minimum case for the code above is where attachments == [] and it produces the same error

**Comment by janscas** [comment]
which authentication flow method are you using?

Can you post the code used?

Thanks

**Comment by davidwynter** [comment]
This is only occurring on my development PC locally, I deployed to my AWS instance and it is sending emails just fine. Very strange. I suppress sending emails for CI. Wondering if I should close this. What do you think?

**Comment by janscas** [comment]
Strange!
For me it works both on development and on production.
