### ISSUE TITLE
upload file to onedrive failed for file name invalid

### ISSUE THREAD

**Issue by mengyyy** [O365/python-o365#387]
Hello:
   I have a file wich name is `5 - More Smiles\x81, More Happiness.mp3` in os.listdir 
   But in `ls` cmd it show `5 - More Smiles'$'\302\201'', More Happiness.mp3`
   I try to set item_name in upload_file but also get 
```HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/drive/items/0XXXXXXXXXXXXXXXXXXXXXXXXX:/5%20-%20More%20Smiles%C2%81%2C%20More%20Happiness.mp3:/createUploadSession```
   Could any one tell me how to rename this file?
Thank you

**Comment by janscas** [comment]
Can you paste the code used?
What version of O365 are you using?

**Comment by mengyyy** [comment]
O365 info
Name: O365
Version: 2.0.7
Python 3.8.1 Ubuntu 18.04 x64

example  code like this 
```python
storge = account.storage()
drive = storge.get_default_drive()
root_item = drive.get_root_folder()
# now touch a new file  named test and rename it 
error_name = b'\xc2\x81.txt'
os.rename('test', error_name )
root_item.upload(error_name)
```
Then will get this
HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/drive/items/XXXXXXXXXXXXXXXXXX:/%C2%81.txt:/content

I get this error when i try upload some music files which contain strange code in their name,
Usually they are in b'\xc2\x80' ~ b'\xc2\x90'

**Comment by mengyyy** [comment]
use base64 encode file name
