### ISSUE TITLE
Ability to interact with WorkbookApplications

### ISSUE THREAD

**Issue by icgranger9** [O365/python-o365#390]
Hey,

Is there any plan to add the functionality to get / interact with [workbookApplications](https://docs.microsoft.com/en-us/graph/api/resources/workbookapplication?view=graph-rest-1.0). This would enable us to see the calculation status of a workbook, and run calculations in a workbook.

**Comment by janscas** [comment]
Done. Check the excel module

**Comment by icgranger9** [comment]
Sorry to bother you, but could you give me an idea where? I see the workbook module, but nothing about workbookApplications. When I search for 'application' or 'calculation' nothing relevant pops up

**Comment by janscas** [comment]
Oh sorry I don’t know what a workbook application is. Can you share the relevant ms graph api docs regarding workbook applications?

**Comment by icgranger9** [comment]
No problem, here you go: [https://docs.microsoft.com/en-us/graph/api/resources/workbookapplication?view=graph-rest-1.0](https://docs.microsoft.com/en-us/graph/api/resources/workbookapplication?view=graph-rest-1.0)

**Comment by janscas** [comment]
Merged in #395
