### ISSUE TITLE
CheckOut a SharePoint file?

### ISSUE THREAD

**Issue by Vincethevince** [O365/python-o365#392]
Hi
Last days I tried to CheckOut a SharePoint file and now I found this package. Is it possible to do this with the API?

**Comment by janscas** [comment]
I don't now what's a checkout... 

with O365 you can upload and download files.

**Comment by Vincethevince** [comment]
A checkout is like locking the file so nobody can edit them. But I assume that this isn´t possible then.

**Comment by janscas** [comment]
If it's posible via microsoft graph it's posible also in O365

check https://docs.microsoft.com/en-us/graph/overview?view=graph-rest-1.0
