### ISSUE TITLE
Filtering SharePoint lists

### ISSUE THREAD

**Issue by jrmatchett** [O365/python-o365#393]
I'm needing to filter items when querying a SharePoint list. I first tried defining a query like this
```
query = my_list.q().expand('fields').select('Field1', 'Field2', 'Field3')
query.chain().on_attribute('Field3').equals(0)   # Field3 is a boolean value
items = my_list.get_items(query=query)
```
That produces `Error Message: Invalid filter clause`.  Looking through the Microsoft Graph API documentation, it indicates that `fields/` should come before the attribute and, in my testing, the field name is case sensitive. So in my example the filter expression should evaluate to `fields/Field3 eq 0` , whereas `on_attribute` produces `fields3 eq 0`. So, I added a method named `on_list_field` to the `Query` class, defined as:
```
@fluent
def on_list_field(self, field):
    """ Apply query on a list field, to be used along with chain()
    :param str field: field name (note: name is case sensitive)
    :rtype: Query
    """
    self._attribute = 'fields/' + field
    return self
```
Does that seem reasonable, or am I overlooking something in the package's existing functionality?

**Comment by janscas** [comment]
The sharepoint api is not feature complete.
But please take a look at the code and see if it does what you want.

**Comment by jrmatchett** [comment]
Thanks. Added my solution to pull request #397 if you think it's useful.

**Comment by janscas** [comment]
Merged
