### ISSUE TITLE
MFA authentication

### ISSUE THREAD

**Issue by mrh610** [O365/python-o365#398]
I have been using O365 for ~1 year with oauth2 authentication.  Yesterday my company switched our outlook to MFA authentication and now I receive the error:  oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access.  I've researched ways of resolving this but I'm unable to find any.  I have also checked on the Azure portal to attempt to authenticate again.  It is entirely possible that I am missing something simple, but I am hoping that someone can point me in the right direction.

**Comment by janscas** [comment]
Do you find any reference in the Microsoft Graph Api docs regarding MFA?

Thanks

**Comment by janscas** [comment]
Closing this as there's no answer
