### ISSUE TITLE
Cannot send mail to own tenant?

### ISSUE THREAD

**Issue by johanovic** [O365/python-o365#399]
I have an error with sendMail. I can send emails to anyone outside of the tenant (someone@somewhereelse.com) from an email address within the tenant (so someone@tenant.com), but any emails to other accounts in the tenant fail to arrive (someoneelse@tenant.com). 

Although they are successfully send and end up in the someone@tenants sent emails, they do not appear in the someoneelse@tenant.com mailbox. Any ideas what could be causing this?

**Comment by janscas** [comment]
I'm in a corporate environment with multiple tenants and I can send emails anywhere without problems. Maybe this is a configuration problem with your Office 365 account on your company.
I don't know.
