### ISSUE TITLE
Identify event invitation messages

### ISSUE THREAD

**Issue by RandomNameUser** [O365/python-o365#401]
Whenever I get an event invitation, I get an empty message in the API, and I can't find any way to identify it as an invitation, nor can I get a reference to the event that is being invited to.

Is there a way to identify a message as an invitation, and to find the event that the invitation is for? 

Thanks!

**Comment by RandomNameUser** [comment]
Digging through the MS Graph [docu ](https://docs.microsoft.com/en-us/graph/api/resources/eventmessage?view=graph-rest-1.0)I found that this is done through eventMessage messages (derived from `message`), which have a `meetingMessageType` field plus some ancillary fields (the most interesting obviously the `event` associated with the message). 

Is there a way to get these through O365? If not, can somebody give me a rough pointer where I would have to poke to add this?

Thanks!

**Comment by janscas** [comment]
Yes check message property “is_event_message”. Then you can check property “meeting_message_type” and to get the event: “message.get_event()”

**Comment by RandomNameUser** [comment]
Hm, that doesn't seem to work, I never get a message that has `is_event_message` true. :(

My suspicion is that it is related to the fact that I'm using `.select()` to get specific fields for the message (mainly to add the `internet_message_headers`), and that something that's needed for event message is not included. Is that possible? If so, what do I need to include?

Thanks!

**Comment by janscas** [comment]
Yes! It should be this. 

First get the message, identify the event message and then mater get the same message only with the internet message headers.

**Comment by RandomNameUser** [comment]
The problem is that I need to get the internet message headers for every message to reconstruct the conversation tree. I was trying to do that with the minimum amount of API calls to avoid running into API call limitations, so I'm trying to do as much in one query as I can. 

But given that I'm also downloading attachments I'm probably blowing that out of the water anyway.  Plus I probably need to switch to a subscription approach to keep the polling down. Sorry, rambling. 

But the main part is: to get the `event` message info I need to get the messages without `select()`, otherwise that field is not set correctly. Thanks!

**Comment by janscas** [comment]
Maybe you can include in the select, the fields required to get the event data.

Check the microsoft graph page on messages and try to include in the "select" that properties.

Let me know if it works.

**Comment by RandomNameUser** [comment]
Hm, there doesn't seem to be one. At least looking at https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0 there doesn't seem to be any properties that relate to the event messages. :(

I'll need to rethink everything anyway, I'm not seeing my own messages and that breaks the conversation trees. Thanks for your help!
