### ISSUE TITLE
authentication issue when authenticating on behalf of a user

### ISSUE THREAD

**Issue by billchen8888** [O365/python-o365#407]
Probably what I am running into is not an issue of O365 itself. But I really don't know what causes it -

I am using "authenticate on behalf of a user".  The following is the code:

`from O365 import Account

credentials = ('my_client_id_data', 'my_secret')

scopes=['https://graph.microsoft.com/Mail.Read']
account = Account(credentials,scopes=scopes)
if account.authenticate():
   print('Authenticated!')
`

and I run it, on the terminal console, I get:

Visit the following url to give consent:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=##############&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fnativeclient&scope=https%3A%2F%2Fgraph.microsoft.com%2FMail.Read&state=###########&access_type=offline

(I replace the client ID info  with ##### for privacy)

So I go to the URL in a browser, I got a login page, then I signed in, I get 
https://login.microsoftonline.com/common/oauth2/nativeclient?error=invalid_request&error_description=AADSTS50194%3a+Application+%2########$+is+not+configured+as+a+multi-tenant+application.+Usage+of+the+%2fcommon+endpoint+is+not+supported+for+such+applications+created+after+%2710%2f15%2f2018%27.+Use+a+tenant-specific+endpoint+or+configure+the+application+to+be+multi-tenant-#######

So it seems complaining the Account type(?).    "the registered application is not configured as a multi-tenant+application. Usage of he common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant"

Since this is a company's Off365, I am told to use 
Accounts in this organizational directory only (YOURCOMPANY only - Single tenant)
We are not allowed to use multi-tenant account type

Additional info:  When I access the Azure portal from the company's laptop, the browser uses some sort of federation for SSO), not sure whether this causes my problem.

Thanks for any hint or info.

**Comment by janscas** [comment]
I think you have to pass a tenant_id param to the account instantiation.

**Comment by billchen8888** [comment]
Thanks. That explains it.

**Comment by ruckc** [comment]
It would be nice if this was documented somewhere...

**Comment by janscas** [comment]
> It would be nice if this was documented somewhere...

Read the readme

https://github.com/O365/python-o365#oauth-authentication
