### ISSUE TITLE
Turn off logging

### ISSUE THREAD

**Issue by ChrisMellor68** [O365/python-o365#408]
Hi

How can I turn off logging (except for HTTP Errors) from the API?

I keep getting lots of lines like:
INFO:O365.connection:Request parameters: {'params': {'$top': 100}, 'allow_redirects': True}
INFO:O365.connection:Received response (200) from URL https://graph.microsoft.com/v1.0/users/xxxxxxxxxxxxxx/mailFolders/Inbox/messages?%24top=100

(xxxxxxxxxxxxxx was mailbox)

I've tried setting raise_http_errors=False but that doesn't do what I want.

I've also looked into source for connection but I'm not much the wiser from that.

Any ideas?

Many thanks

Chris

**Comment by janscas** [comment]
This is not something related to this library but to the python logging library.

You have to set the level on the logger.

```python
import logging
o365_logger = logging.getLogger('O365')
o365_logger .setLevel(logging.ERROR)
```
