### ISSUE TITLE
Microsoft To Do integration 

### ISSUE THREAD

**Issue by alxhslm** [O365/python-o365#412]
Similarly to #378 , I was wondering whether there were plans to add support for Microsoft To-Do?

I've made an initial implementation using the Graph API here (currently only in beta), based on the architecture in `calendar.py`:

`https://graph.microsoft.com/beta/me/outlook/tasks` 

I don't mind tidying up my implementation and submitting a pull request, but I thought I should check if something is already in the works because I don't want to duplicate effort.

**Comment by janscas** [comment]
Hi!

Nothing is planned for outlook tasks.

PR are welcome!

Thanks

**Comment by Nitschi** [comment]
Hello! Is there anything new about this?
Are there plans to add the Check-List fields for Tasks as well?

![grafik](https://user-images.githubusercontent.com/5908114/147081656-b33a445b-75d6-41fc-926b-e8b81efcba03.png)

**Comment by janscas** [comment]
@Nitschi no plans. PR are very welcome

**Comment by alxhslm** [comment]
Sorry, I forgot to close this after #524.
