### ISSUE TITLE
DeprecationWarning importing from collections instead of from collections.abc

### ISSUE THREAD

**Issue by omac777** [O365/python-o365#414]
On Archlinux, I did the following:
```
pacman -S extra/python-pip
pip install O365
```

Then I ran the example a tweak a bit with basic and message_all scopes.
```
from O365 import Account
credentials = ('client_id', 'client_secret')
account = Account(credentials)

if account.authenticate(scopes=['basic', 'message_all']):
   print('Authenticated!')

m = account.new_message()
m.to.add('to_example@example.com')
m.subject = 'Testing!'
m.body = "George Best quote: I've stopped drinking, but only while I'm asleep."
m.send()
```

It sent the message successfully after supplying the authenticated url.

BUT it did give the following error/warning output:
```
Authentication Flow Completed. 
Oauth Access Token Stored. You can now use the API.
Authenticated!
/usr/lib/python3.8/site-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working from collections import Mapping
```

Thank you for listening.

**Comment by janscas** [comment]
> usr/lib/python3.8/site-packages/html5lib/_trie/_base.py:3: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working from collections import Mapping

This warning is not from O365 it comes from htm5lib

**Comment by tirkarthi** [comment]
The html5lib issue is fixed in master but needs a release . See https://github.com/html5lib/html5lib-python/issues/419

**Comment by janscas** [comment]
Closing this as it's not related to this library

**Comment by omac777** [comment]
I'm just dropping by to say the python-o365 package has been very useful.  Thank you for maintaining it.  There is a great deal of complexity within office365 and your python package succeeds in simplifying it to an extent that mere mortals can use it within minutes.  The python-o365 team are masters of python, office 365, and software design.

**Comment by janscas** [comment]
Thank you! Your comment is greatly appreciated
