### ISSUE TITLE
Confused newbie

### ISSUE THREAD

**Issue by cgarmstr** [O365/python-o365#415]
I have taken your onedrive_example.py and substituted my own client_id and secret_id. When I run is I get a request for a url to give consent, to which I pasted in https://login.microsoftonline.com/common/oauth2/nativeclient
The complete dialogue is below.

PS E:\users\cecil\OneDrive\Cecil\My Documents\Software\python\OneDrive\OneDrive\examples> python onedrive_example.py    Visit the following url to give consent:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=d20c656c-9b97-425f-8206-34f20d6765f4&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fnativeclient&scope=https%3A%2F%2Fgraph.microsoft.com%2FFiles.ReadWrite.All+offline_access+https%3A%2F%2Fgraph.microsoft.com%2FUser.Read&state=QCV8kYQsKP9L3QwdzlRdFVZ64Xb3RL&access_type=offline
Paste the authenticated url here:
https://login.microsoftonline.com/common/oauth2/nativeclient
Unable to fetch auth token. Error: (missing_code) Missing code parameter in response.
Something go wrong. Please try again.
Client Error: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/me/drives?%24top=999 | Error Message: Access token is empty.

This is a screen shot of my app permission settings
![image](https://user-images.githubusercontent.com/7409913/77847721-23b15700-71b7-11ea-98bf-ccbe3e986fbb.png)

Apologies for wasting your time with this.

Cecil

**Comment by cgarmstr** [comment]
After leaving this for a while I generated a new app, client_id and secret_id. 

I hadn't read the screen instructions carefully enough, in that you have to paste the url printed out by the console in a browser and then paste back on the console the url that the browser window transforms into.

So, now I have an app which authenticates but I have issue #234 with onedrive_example.py HTTPError: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/drives?%24top=999 | Error Message: The query specified in the URI is not valid. Query option 'Top' is not allowed. To allow it, set the 'AllowedQueryOptions' property on EnableQueryAttribute or QueryValidationSettings.

**Comment by janscas** [comment]
Yep the issue #234 is now fixed. Expect a new release in a few days
