### ISSUE TITLE
Can O365 be used with an Azure Function app?

### ISSUE THREAD

**Issue by khibma** [O365/python-o365#420]
When creating an Azure Function app, and debugging, it runs in its own environment that needs to be activated. Once you're in this environment, you seemingly cannot interact with prompts, such as the prompt 

> [2020-04-08 6:20:43 PM] Visit the following url to give consent:
> [2020-04-08 6:20:43 PM] https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&..........

Besides working in this environment, once the app has been posted to Azure, it'll be impossible to provide the authenticated URL.

Does this mean, I need to authenticate using the `"with your own identity"` mechanism? If that's the case, I'll need to setup permissions and find/request an administrator to allow this (which seems unlikely for me)

OR... if because each of the above scenarios will not work for their own reasons..., I'll need to perform the steps under **DIFFERENT AUTHENTICATION INTERFACES** -- having my application handle the callback? If this becomes the only workable situation for me, can you explain how I need to store the token? Is this connection/callback something that everytime the app runs it must do? Or do I need to look into a storage mechanism for Azure Function apps to save the token into?

**Comment by janscas** [comment]
With the authorization auth flow you need a user who will need to give consent in order for the api to work.
If you are the user who will give consent, you can generate the auth token in your computer and then upload or paste the auth token (it's just json) into your code. This way it will work with functions.

But, the ideal scenario for an azure function is the credentials auth flow. But this requires admin consent.

The authentication flow needs the user input to generate the auth token. I think you can't apply the technics described under different authentication interfaces with azure function.

**Comment by khibma** [comment]
Thanks for the response. 
So your suggestion is to locally run `token_backend = FileSystemTokenBackend(token_path='my_folder', token_filename='my_token.txt')` to get the JSON for the auth token. Then essentially hardcode that JSON into my function app?
Will the refresh workflows continue to work with this approach, or would that create a problem after 90 days?

**Comment by janscas** [comment]
No, just proceed with the auth flow described in the readme (add offline_access permission). After receiving the “auth flow complete” message you will have the token stored.

Then you should set this token somewhere from where the azure function can retrieve and also set this token.

As long as the app contacts the server once in 90 days you won’t need to do authentication anymore. The O365 lib will retrieve new access and refresh tokens for you.

**Comment by khibma** [comment]
Ahhh, now I see, it did save a **o365_token.txt** file with my access token in it from attempts _outside the azure function code_

Sorry for being slow on this, but with that file/token - do I need to explicitly load it up? My understanding of the doc says it should just be found? I placed the file in the same directory as the .py making the o365 call, but it still prompts to do the URL copy/paste authorization when debugging my azure function.

Reference:
```
	credentials = (api_key, secret)
	scopes = ['message_send']

	account = Account(credentials)
	if account.authenticate(scopes=['message_send']):
		print('Authenticated!')

	example_mailbox = account.mailbox(resource=from_email)
	m = example_mailbox.new_message()
	m.to.add(to_email)
	m.subject = subject
	m.body = email_body
	m.send()
```

**Comment by khibma** [comment]
Ahhhhh I think I got it. I had reset the permission on the token, so I needed to actually do the re-authorization step. Thank you so much for your guidance.

My steps for anyone who comes across this:

1. Very basic script/function like:
```
from O365 import Account, FileSystemTokenBackend
from pathlib import Path
appID = "", c_secret = ""
credentials = (appID, c_secret)
scopes = ['message_send']

token_backend = FileSystemTokenBackend(token_path=Path(__file__).parent, token_filename='mytoken.txt')
account = Account(credentials, token_backend=token_backend)
if account.authenticate(scopes=['message_send']):
   print('Authenticated!')

example_mailbox = account.mailbox(resource='email@me.com')
m = example_mailbox.new_message()
m.to.add('email@me.com')
m.subject = 'Testing!'
m.body = "George Best quote: I've stopped drinking, but only while I'm asleep."
m.send()
```

2.  Copy the mytoken.txt into my azure function app, in the same folder as the email .py file
3. Email function implemented exactly as above
4. Just works.

**Comment by BillingtonRWG** [comment]
I've been wrestling with this one for a bit and think I'm super close.  It's got to be something little.  I have offline code now working with the token 'o365_token.txt'   I put that file in the same shared_code directory of my azure function.  I believe the path library puts it in the right place.   I am not sure if it isn't loading it/finding it. Is the **o365_token.txt** the same file as the **mytoken.txt** you call out?  I pretty much have the same code, but am still getting prompted to authenticate.   Do I perhaps need to copy the token file to a tmp directory first?   This is in an Azure linux function.  The only other code difference is that I have a tenant id included with credentials and back end.

**Comment by alejcas** [comment]
> **o365_token.txt** the same file as the **mytoken.txt** you call out?

o365_token.txt is the default name for the FileSystemTockenBackend. You can specify another name like in the example above (token_filename='mytoken.txt')

The token only lasts for 1 hour. After that the library will request another token using the refresh token. So This token needs to be saved somewhere in order for the library to work.

So the azure function needs a safe place where a token file can be stored. A temp folder will not work as multiple instances won't have access to the same temp folder.

Or you can use another token backend and give the azure function access to it.
