### ISSUE TITLE
Can't get file from a shared OneDrive folder

### ISSUE THREAD

**Issue by blanning19** [O365/python-o365#421]
Hello, I am trying to pull and push files into and Shared folder but get a 404 error.
Code snippet:
account = O365.Account(credentials)
storage = account.storage() 
my_drive = storage.get_default_drive()
shared_folder = my_drive.get_shared_with_me()

for item in shared_folder:

    if str(item) == "File: JasonEcarTest.xlsx":
        onedrive_file = my_drive.get_item(item.object_id)

This will return an error:
HTTPError: 404 Client Error: Not Found for url: https://graph.microsoft.com/v1.0/me/drive/items/017WW2JUGHVHU6BYOV7ZB2YZP6BTEWKU5P | Error Message: The resource could not be found.

I think this is because get_item() looks at my drives not my shared.

**Comment by janscas** [comment]
Item is already the file. I don't know why you try to get it another time. Just use item.

Also user item.name instead of str(item).

**Comment by blanning19** [comment]
First, thank you for such a quick response! I really appreciate that.
I modified to use item but still get error.
for item in shared_folder:
    if item.is_file:
        print(item, item.object_id)
        if item.name == "JasonEcarTest.xlsx":
            print('found it')
            item.download(to_path ='files/')

Error Message: The provided item ID is not valid for the requested drive
Error downloading driveitem JasonEcarTest.xlsx. Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/me/drive/items/017WW2JUGHVHU6BYOV7ZB2YZP6BTEWKU5P/content | Error Message: The provided item ID is not valid for the requested drive

I think it is still looking at my drive rather than shared drive?

**Comment by janscas** [comment]
I know what it's happening. It's a bug on the library.
Let me investigate this issue.

**Comment by blanning19** [comment]
Thank you for looking into this.

Had another question about download and copies.
Is there any flags that allow to overwrite if the files exists or, in the
case where the file is opened in the destination directory ?
Currently if the files is already in the destination folder, it doesn't
update.

Our goal is to create a Python tool where we can sync files on a network
share with files in a Shared OneDrive folder.
Users can collaborate their work in the Shared OneDrive folder and that
will be pushed to a network resource to be consumed by an app on a web
server. This app also outputs a result file to the network that we want to
also be pushed back up to the Shared OneDrive folder for review.
We have a good amount of apps/tools that were using Google Drive but my
company is moving from Google to Microsoft products and this gap is a
concern as we do not have a solution as of yet.

**Comment by blanning19** [comment]
Hello.
I just wanted to see if you had time to look at this bug?
I was able to manipulate parts of the drive.py code to make it download a
file from a Shared folder to my network drive, however it is not a hardened
solution. Just wanted to see if the pieces were in fact there and they are,
just needed to find the ones to use.
By using the URL
https://graph.microsoft.com/v1.0/drives/{item*.parentReference.driveId*
}/items/{item.*id*}/content

Brad

**Comment by janscas** [comment]
> Is there any flags that allow to overwrite if the files exists or, in the case where the file is opened in the destination directory ?

I'm not sure. You can check: https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

If you find something let me know!



> I just wanted to see if you had time to look at this bug?

I've to change the drive id to match the original drive id. But I didn't have time to change the code.

**Comment by janscas** [comment]
This issue is now fixed

**Comment by blanning19** [comment]
Thank you. I confirmed this fixed our issue!!
Great tool!

**Comment by StephanieMak** [comment]
I'm wondering if I need special api permission or scope to download the file in shared drive, I followed the second approach above and found the file (object id was printed out as `DB21E210CAF7E***!264`), but when I was trying to download the file, `404` was returned. 
The scope I was using is `['basic', 'onedrive_all']`

> found it File: `xxx.xlsx` `DB21E210CAF7E***!264`
Client Error: 404 Client Error: Not Found for url: https://graph.microsoft.com/beta/drives/1ce2981cb9782***/items/DB21E210CAF7E***!264/content | Error Message: Item does not exist
Error downloading driveitem xxx.xlsx. Error: 404 Client Error: Not Found for url: https://graph.microsoft.com/beta/drives/1ce2981cb9782***/items/DB21E210CAF7E***!264/content | Error Message: Item does not exist
Client Error: 404 Client Error: Not Found for url: https://graph.microsoft.com/beta/drives/1ce2981cb9782***/items/DB21E210CAF7E***!264/copy | Error Message: Item does not exist
Traceback (most recent call last):
  File "app/main.py", line 47, in <module>
    main()
  File "app/main.py", line 36, in main
    onedrive.get_latest()
  File "***load/onedrive.py", line 31, in get_latest
    operation = item.copy(target=documents_folder)  # operation here is an instance of CopyOperation
  File "***drive.py", line 770, in copy
    response = self.con.post(url, data=data)
  File "***connection.py", line 811, in post
    return self.oauth_request(url, 'post', data=data, **kwargs)
  File "***connection.py", line 789, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "***connection.py", line 751, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://graph.microsoft.com/beta/drives/1ce2981cb9782***/items/DB21E210CAF7E***!264/copy | Error Message: Item does not exist

Thanks!
