### ISSUE TITLE
Create Permanent/90 Day Token and access it

### ISSUE THREAD

**Issue by Zeakles** [O365/python-o365#423]
Hello i have currently the following code:

`from O365 import Account
from O365.excel import WorkBook

credentials = ('****', '****')
scopes = ['Files.ReadWrite.All','Files.ReadWrite','Files.Read.All','Files.Read','onedrive','basic'] 

account = Account(credentials)

account.authenticate(scopes=scopes) 

storage = account.storage()

my_drive = storage.get_default_drive()

root_folder = my_drive.get_root_folder()

for item in root_folder.get_items(limit=25):
    if item.is_file:
        file = item
        print(file)
        break
excel_file = WorkBook(file)`

Now i want that this code works automatically without any user input every day. What do i have to change or configure to make this feature possible?

The manuell authentification is currently the biggest problem for my automation.

**Comment by janscas** [comment]
If you read the readme of this library you will find the answer. Add offline_access scope and authenticate.

**Comment by Zeakles** [comment]
adding offline_access scope, offline permissisions zu azure app and adding the following lines to my code solved the problem:

account = Account(credentials)

```
if not account.is_authenticated:  # will check if there is a token and has not expired
    # ask for a login
    # console based authentication See Authentication for other flows
    account.authenticate(scopes=scopes)
```
