### ISSUE TITLE
Question: Event Unique ID?

### ISSUE THREAD

**Issue by yanicakj** [O365/python-o365#431]
Hi Alejandro,

Do events returned from `calendar.get_events(...)` have a unique ID?

For example, if there are 3 different programs using `get_events(...)`, is there some unique ID for each event that can always be used to identify the events uniquely (globally) on calendar?

Looking at the `event.to_api_data()` function returns a lot of useful data but can't find unique ID (most likely managed by MSFT?)

Was experimenting with `event.ical_uid` and `event.object_id` but not sure if these will always be the same across all programs using the API?

Thank you for the great library,
Jacob

**Comment by janscas** [comment]
Yes: `event.object_id`

Thanks
