### ISSUE TITLE
Message Protection - send encrypted email

### ISSUE THREAD

**Issue by Jaguar25** [O365/python-o365#435]
Is this capable of sending o365 email using Message Protection functionality.

E.g. now, using simple Outlook O365, i can simply send email with subject line containing word "(encrypt)" and that would enable o365 to use Message Protection. 
I tried that with this library/python and it did not work for me.

Is this in functionality (maybe i'm missing something) or in dev pipeline?

Thanks

**Comment by janscas** [comment]
I don't know what's Message Protection.

Is an office365 feature?

Can you point me to the api docs?

**Comment by Jaguar25** [comment]
https://support.office.com/en-us/article/learn-about-protected-messages-in-microsoft-365-2baf3ac7-12db-40a4-8af7-1852204b4b67
here is a service description. 

i will look for api docs.

Thanks for your response.

**Comment by janscas** [comment]
I don't know.

It should be somewhere here: https://docs.microsoft.com/en-us/graph/api/overview?view=graph-rest-1.0

**Comment by Jaguar25** [comment]
Ok, i figured it out.

Need to add this: 

Microsoft Graph (4) |   |   |   |   |  
-- | -- | -- | -- | -- | --
  | InformationProtectionPolicy.Read

to your permissions for registered App.

Then, and only then, you can use: (encrypt) in subject line and it will work.

**Comment by janscas** [comment]
Great!
