### ISSUE TITLE
PersonalNotes support in Contacts

### ISSUE THREAD

**Issue by jgrigera** [O365/python-o365#437]
Could I request to have PersonalNotes retrieved and written in address_book/Contacts? They are called 'notes' in OWA and PersonalNotes in the API call. I could try a pull request but I am not familiar with the code yet.

**Comment by janscas** [comment]
Please could you post the link to the api ms graph docs regarding personal notes?

**Comment by jgrigera** [comment]
Thanks, yes this should be it:
https://docs.microsoft.com/en-us/graph/api/resources/contact?view=graph-rest-1.0

See personalNotes (String)
