### ISSUE TITLE
Delete expired token?

### ISSUE THREAD

**Issue by jdejoode** [O365/python-o365#440]
Hi

I have a case where a token was expired (I didn't renew it within 90 days). When I try to redo the authentication process for that user, however, graph keeps on giving me that exact expired token. I go through the authentication steps 1 and 2 but I get the same token.

Is there a way to delete a token that is expired so that a new token (meaning a new auth connection) can be received?

Thanks

**Comment by janscas** [comment]
Strange.

If you are using the default token backend:

`account.con.token_backend. delete_token()`

**Comment by jdejoode** [comment]
Ok my mistake. This was a mistake in my code. Apologies.
