### ISSUE TITLE
Authenticate Web : Store state question

### ISSUE THREAD

**Issue by mohanrkrishna** [O365/python-o365#447]
Hi - Following Web authentication schemes, trying flask code. Have below question, please assist. 
After getting state in step#1 , it is mentioned to store the state (below code.store_state). Please elaborate how to use FileSystemTokenBackend and implement ".store_state"  & ".get_state()" functions. Thanks very much!   

my_db.store_state(state)

FileSystemTokenBackend ===>
token_backend = FileSystemTokenBackend(token_path='my_folder', token_filename='my_token.txt')
account = Account(credentials, token_backend=token_backend)

**Comment by mohanrkrishna** [comment]
Please ignore. As state and tokens are different , my question is not accurate. Sorry

**Comment by mjuliefr** [comment]
Hi mohanrkrishna,

I am actually trying to implement the web authentification using the the file storage back end. However, I am a hard time to understand how to do it even with the example in the read me. Could you please share your code, please ? I am overwhelmed by the store state concept and the absolute url mentioned in step one and two. I am not sure what they should be and if they are supposed to be the same. I would really appreciate your help. Thank in advance !
