### ISSUE TITLE
delete email from the inbox

### ISSUE THREAD

**Issue by sergeyr87** [O365/python-o365#45]
i didnt see any function that delete a single email 
i be happy to have this cool option

**Comment by ylxi123** [comment]
loop,filter,delete emails is also what i want.
any suggestion on how to achieve that?

**Comment by sergeyr87** [comment]
any one?

**Comment by Narcolapser** [comment]
Sorry for the delay. Had a very busy December. General answer: No, there is no way of deleting an email. I've added it as a feature request.

**Comment by HeadJar** [comment]
Is the deletion method implemented or is there a way to move messages into other folders?

**Comment by Narcolapser** [comment]
Sorry no, this project hasn't been high on my priority list as of late so I've not gotten around to adding these things.

**Comment by Narcolapser** [comment]
Actually this would be the correct link: https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-1.0/mail-rest-operations-v1#DeleteMessages

Using version 2 of the api is still in work but very important as version 1 is to be deprecated soon.

**Comment by roycem90** [comment]
available in 1.0

**Comment by tpain400** [comment]
I cannot find the documentation for this operation. Has this been implemented in the lib using the graph api?

Please help I need this for my current project.

**Comment by janscas** [comment]
> I cannot find the documentation for this operation. Has this been implemented in the lib using the graph api?
> 
> Please help I need this for my current project.


look into the code: 
https://github.com/O365/python-o365/blob/master/O365/message.py#L758
