### ISSUE TITLE
Bug? Save_to_sent_folder after storing a draft?

### ISSUE THREAD

**Issue by johanovic** [O365/python-o365#451]
Ok, I might be missing something, but I think this might be a bug.

Scenario: 
- store a message as a draft
- send it with the option `save_to_sent_folder=False`

Result:
- message is stored in sent_folder

Reason:
- This if clause is taken into account and not the else part that follows: https://github.com/O365/python-o365/blob/master/O365/message.py#L680

- Code with the error:

    def send(self, save_to_sent_folder=True):
        """ Sends this message

        :param bool save_to_sent_folder: whether or not to save it to
         sent folder
        :return: Success / Failure
        :rtype: bool
        """

        if self.object_id and not self.__is_draft:
            return RuntimeError('Not possible to send a message that is not '
                                'new or a draft. Use Reply or Forward instead.')

        if self.__is_draft and self.object_id:  # IN OUR SCENARIO AN EMAIL IS A DRAFT
            url = self.build_url(
                self._endpoints.get('send_draft').format(id=self.object_id))
            if self._track_changes:
                # there are pending changes to be committed
                self.save_draft()
            data = None

        else:
            url = self.build_url(self._endpoints.get('send_mail'))
            data = {self._cc('message'): self.to_api_data()}
            if save_to_sent_folder is False:  # THIS IS NEVER EXECUTED... HENCE saveToSentItems = True
                data[self._cc('saveToSentItems')] = False

**Comment by janscas** [comment]
Thanks! that's definitely bug.

**Comment by janscas** [comment]
Ok, not so sure now...

So, when [sending a new email](https://docs.microsoft.com/en-us/graph/api/user-sendmail?view=graph-rest-1.0&tabs=http) that did not exist as draft, the graph api provides a saveToSentItems parameter you can set to false.

But...

When [sending a draft](https://docs.microsoft.com/en-us/graph/api/message-send?view=graph-rest-1.0&tabs=http), the graph api doesn't provide such paramter, so the email will always be stored in the sent folder.

**Comment by johanovic** [comment]
Oh very good catch and a good solution (to use .delete() after sending it). Maybe an inline comment in the code could refer to this issue?

Thanks
