### ISSUE TITLE
Multi user application (Question)

### ISSUE THREAD

**Issue by mohanrkrishna** [O365/python-o365#453]
Hi 
Curious to know how FileSystemTokenBackend works with multi users accessing Flask/Python web app using this package. 

To be able to have token file based on each user , have to find principal id or email first. But principal id can be retrieved only after request_token method is called.  I am planning to implement SQL server based TokenBackend in future, even for that need to know principal id first to check token exists or not before requesting new token. 

Can you please share best way to implement multi-users scenario. Thanks!

**Comment by janscas** [comment]
The answer is simple. It doesn't work...
You have to implement another token backend. Like the [FireStoreTokenBackend](https://github.com/O365/python-o365/blob/master/O365/utils/token.py#L229)

You can store the token in a database using the user_id of the user connected.
It's quite simple.

**Comment by mohanrkrishna** [comment]
Thanks @janscas
