### ISSUE TITLE
Improvement: useful links in Readme.md

### ISSUE THREAD

**Issue by stardust85** [O365/python-o365#454]
Something easy to start with :)

I like the quick links and status information some projects have in Readme.md like link to PYPI, python versions, build status, coverage etc. Gonna start w/ link to PYPI if you don't mind :)

Basically I'm gonna steal it from https://github.com/vgrem/Office365-REST-Python-Client/blob/master/README.md from paragraph Status :-D

**Comment by stardust85** [comment]
PR: https://github.com/O365/python-o365/pull/455

**Comment by stardust85** [comment]
That was a super-quick turnaround! :) From idea to merging about 30 minutes :D Looking forward to next cooperation (as time permits....)

**Comment by janscas** [comment]
Thanks! great!
