### ISSUE TITLE
Exception when creatin an Attendee

### ISSUE THREAD

**Issue by waldo2188** [O365/python-o365#464]
I'm trying to create an Attendee to add it to a new event, like the code bellow :

` schedule = account.schedule()

calendar = schedule.get_default_calendar()
new_event= calendar.new_event()

from O365.calendar import Attendee
new_attendee = Attendee('example@example.com',  attendee_type='required')
new_event.attendees.add(new_attendee )`

But this raise an exception : 
`Traceback (most recent call last):
  File "O365\calendar.py", line 562, in __init__
    self.attendee_type = attendee_type
  File "O365\calendar.py", line 634, in attendee_type
    self._track_changes()
  File "O365\calendar.py", line 608, in _track_changes
    self._event._track_changes.add('attendees')
AttributeError: 'NoneType' object has no attribute '_track_changes'`

I'm pretty new with python, so maybe i'm missing something.

By the way, It's an awesome project 👍

**Comment by janscas** [comment]
Thanks! error solved.
I'll release a new version to pypi soon
