### ISSUE TITLE
Find API properties

### ISSUE THREAD

**Issue by riload35** [O365/python-o365#470]
Hello,
I am a beginner in programming and I want to know where we can find the list of properties ('on_attributes' like 'created_date_time' for emails for example) of the Microsoft APIs in order to create filters. I searched unsuccessfully and I am currently working blind.
Thank you very much for your work !

**Comment by janscas** [comment]
The list of properties filterable or searchable is on the internet (i don't remember where but if you search for it you will find it).

The problem however comes with the filter combinations, This is something that is not well documented by microsoft so you will have to find by yourself. Most of the answers are on stackoverflow by looking under ms graph tags.

**Comment by riload35** [comment]
Okay thank you for this informations @janscas , I will expand my research

**Comment by janscas** [comment]
I’m sorry I can’t help you more right now
