### ISSUE TITLE
Upload files greater than 4MB on api v1.0

### ISSUE THREAD

**Issue by icamposrivera** [O365/python-o365#476]
Hi @janscas, is the following feature implemented?

https://docs.microsoft.com/en-us/graph/api/attachment-createuploadsession?view=graph-rest-1.0&tabs=http

I know the beta version of MSGraph allows you to upload files greater than 4MB, but I have just seen this feature on 1.0 api version.

Thanks in advance!

**Comment by janscas** [comment]
It is not! But it’s a must to have this. I’m now switching between protocols to send big files.

**Comment by janscas** [comment]
The upload sessions mechanics is however implemented in the drive.py file to upload files to onedrive or sharepoint. I think the mail upload sessions work the same way so it should be really easy to implement that based on the drive.py code.

**Comment by imaayush** [comment]
Hi @janscas Any plans to implement this feature ? or can you guide me to make related changes

Thanks in advance

**Comment by janscas** [comment]
I do plan to get this up and running soon. You can find the main docs about this on the ms graph api reference docs

**Comment by janscas** [comment]
Fixed in #663 thanks to @Naxest
