### ISSUE TITLE
Multiple tokens for same app id, app secret

### ISSUE THREAD

**Issue by Muthukrishna17** [O365/python-o365#479]
Hi @janscas 

One (silly) question,

Can we use one app id, app secret and generate multiple no. of tokens? Like say, if I have Dev environment and Production of the same application, can I use the same secret and two different redirect_uris (or same Uris)?

**Comment by janscas** [comment]
If the redirect urls are different I think you can’t use the same token. I use the same token for multiple environments but both have the same redirect url.

But try it...
