### ISSUE TITLE
Disable Cert Verify at Account level

### ISSUE THREAD

**Issue by metalshanked** [O365/python-o365#481]
Is there a way to pass in "verify=False" at the account level ?   I get the below errors at connection setup itselfCaused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

Thanks in advance!

**Comment by janscas** [comment]
I don’t the it’s posible. If you can paste here the link to the ms graph docs where says this I’ll be grateful.

**Comment by metalshanked** [comment]
Apologies, I mean I am looking for a way to just set the verify=False flag at initial Auth steps which generates the Access token. 
i.e. nothing specifically related to Microsoft Graph API but a way to set the generic verify=False supported by the requests library. 
Currently, my workaround is to generate the access token separate from the O365 library so that I have flexibility to the underlying requests library call.

`def manual_token_generate_refresh(self):
    http_proxy = "<MY_HTTP_PROXY>"
    https_proxy = "<MY_HTTPS_PROXY>"
    proxyDict = {"http": http_proxy, "https": https_proxy}
   
    url = f'https://login.microsoftonline.com/{self.tenant_id}/oauth2/v2.0/token'

    payload = {'client_id': self.client_id,
               'client_secret': self.client_secret,
               'scope': ['https://graph.microsoft.com/.default'], 
               'grant_type': 'client_credentials'}
    response = requests.post(url, data=payload, verify=False, proxies=proxyDict)
    with open(self.token_file_path, 'w') as ft:
        ft.write(response.text)`

**Comment by Tzahi12345** [comment]
+1, this would be extremely helpful.

@metalshanked Once you generated the token, how did you use that with the O365 library? I'm stuck at this point, any help would be appreciated. Thanks!

**Comment by metalshanked** [comment]
@Tzahi12345 - Sure, I write the access token details to the same file (file name should be same) which is used by the FileSystemTokenBackend of the O365 library.  So as long as the File is present with the same name and a valid token, O365 library will auto pick it up.  Note that, since O365 cannot generate tokens, after the token has expired, you will have to have a logic to run the above "manual_token_generate_refresh" function again.  I use a simple try/except RuntimeError to catch when O365 throws a "token expired" error and execute the "manual_token_generate_refresh" function.

**Comment by janscas** [comment]
Done!, just pass `verify_ssl=False` to either the account init or the connection init

```python
account = Account(credentials, verify_ssl=False)
# ...
```

**Comment by metalshanked** [comment]
@janscas - Really appreciate it.  Would a new version with this change be available via PyPi as well?  I am behind a proxy and cannot access GitHub.

**Comment by janscas** [comment]
Yes sure

**Comment by metalshanked** [comment]
@janscas - Wanted to check on when the new version with verify flag will be available on PyPi ?

**Comment by janscas** [comment]
@metalshanked Uploading it just now.
