### ISSUE TITLE
Recommended e-mail client to use with python-o365 integration?

### ISSUE THREAD

**Issue by maitra** [O365/python-o365#483]
Hello, I am very new to this and was wondering what e-mail client I should use that makes it easy for me to integrate it with python-o365?

**Comment by janscas** [comment]
None. Email clients and this package are completely independent.

**Comment by maitra** [comment]
I understand that, but is there an example on how to use/integrate an email client.

**Comment by janscas** [comment]
No, none... and I don't think it's possible

**Comment by maitra** [comment]
So, then without the ability to read e-mail, I don't see what I can do with this tool. Is this not tool also about accessing and downloading e-mail from O365 using MS Graph/REST?

**Comment by janscas** [comment]
This tool is about using ms graph resources with python. Thats it
