### ISSUE TITLE
Oauth Token Not Persisting

### ISSUE THREAD

**Issue by jeffreybox** [O365/python-o365#484]
Hello! 

I'm having an issue with my **oauth token persisting**. A few notes: 

- I have an enterprise service email that has been setup appropriately with an Azure Application ID
- The app scopes contain read, write, and send
- The access token is successfully created into a 'o365_token.txt' file that lives in the same directory as the code
- The code below authenticates and returns "True" but the read and send sections return a 401 error

```
# LIBRARIES
from O365 import Account, Connection, FileSystemTokenBackend
from credentials import username, password, email, server, tenantid, clientid, secret

# VARS
receiver = 'fake@email.com'
mypath = '/fake/path/root'

# SETUP
credentials = (clientid, secret)
token_backend = FileSystemTokenBackend(token_path=mypath, token_filename ='o365_token.txt')
account = Account(credentials, auth_flow_type='credentials', tenant_id=tenantid, token_backend=token_backend)
account.authenticate()

# READ MAIL
mailbox = account.mailbox()
inbox = mailbox.inbox_folder()
for message in inbox.get_messages():
    print(message)

# SEND MAIL
m = account.new_message()
m.to.add(receiver)
m.subject = 'Testing python o365!'
m.body = "Test - This message was sent via Python's o365 library!"
m.send()
```

Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/mailFolders/Inbox/messages?%24top=25 | Error Message: Resource not found for the segment 'mailFolders'.

```
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token is empty.",
    "innerError": {
      "date": "2020-07-16T21:10:20",
      "request-id": "f5975517-b17f-4b28-b0ff-02a20f7bc2cd"
    }
  }
}
```

Client Error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/sendMail | Error Message: Resource not found for the segment 'sendMail'.

```
{
  "error": {
    "code": "InvalidAuthenticationToken",
    "message": "Access token is empty.",
    "innerError": {
      "date": "2020-07-16T21:14:19",
      "request-id": "37129587-beee-4091-9adb-368736c94f5d"
    }
  }
}
```
_**Example Jupyter output attached**_

[o365-oauth-token-error.pdf](https://github.com/O365/python-o365/files/4934197/o365-oauth-token-error.pdf)

**Comment by janscas** [comment]
When using credentials auth flow you must specify the resource like:

```python
mailbox = account.mailbox(resource='thismeail@corp.com')
inbox = mailbox.inbox_folder()
for message in inbox.get_messages():
    print(message)
```

**Comment by jeffreybox** [comment]
@janscas thanks for the reply! When I enter in the resource arg, I still get the same 401 Client Error that shows the access token being empty

**Comment by janscas** [comment]
401 means unauthorised...
So you don’t have access to that email it seems

**Comment by jeffreybox** [comment]
I do have access. I have the un, password, id, tenant, secret, etc stored in a credentials.py file that I read in. These two lines successfully generate and store a token which validates my access:

`token_backend = FileSystemTokenBackend(token_path=mypath, token_filename ='o365_token.txt')
account = Account(credentials, auth_flow_type='credentials', tenant_id=tenantid, token_backend=token_backend)`

Yet when I try to retrieve anything, I now get:

HTTPError: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/users/a1podintake@cox.com/mailFolders/Inbox/messages?%24top=25 | Error Message: The token contains no permissions, or permissions can not be understood.

**Comment by janscas** [comment]
Yep, you have access to the app on azure, but not to the email account? Does it make sense?

Another possibility.. did you added application permissions or delegated permissions?

**Comment by jeffreybox** [comment]
Ah interesting. Let me take that back to the team... I figured those permissions were the same for the purposes of this code. Let me ask about the application vs delegated permissions

**Comment by janscas** [comment]
Check the readme again, as all this is explain there

**Comment by jeffreybox** [comment]
I understand that the authentication specs are in the readme, but I assumed if the authentication function returned 'true' (per the readme), that the credentials were working properly. I'll ask the azure admins, since they told me I had full permissions.

**Comment by janscas** [comment]
The authencation returns true, but that means the credentials are ok, the permissions are a different matter
