### ISSUE TITLE
Attaching Files to Messages

### ISSUE THREAD

**Issue by Lukehi** [O365/python-o365#488]
I am trying to attach a csv and pdf to a new_message. The documentation and code don't make it obvious is this is possible with O365. If it is an example would be appreciated.

**Comment by pseudozach** [comment]
can you please share example if you found a way?

**Comment by Lukehi** [comment]
from O365 import Account

def send_email(send_to, email_title, email_body, attachments, APP_CLIENT_ID, APP_CLIENT_SECRET, TENANT_ID, scopes):
    print('Starting send_email function')
    credentials = (APP_CLIENT_ID, APP_CLIENT_SECRET)
    account = Account(credentials, tenant_id=TENANT_ID)
    if account.is_authenticated:
        print('Authenticated')
    else:
        print('Please Provide Authentication')
        account.authenticate(scopes=scopes)
    m = account.new_message()
    m.to.add(send_to)
    m.attachments.add(attachments=attachments)
    m.subject = email_title
    m.body = email_body
    m.send()
    return print('Email Successful')


APP_CLIENT_ID = ''
APP_CLIENT_SECRET = ''
TENANT_ID = ''
scopes = ['basic', 'message_all', 'users']
email_title = 'Test O365 API Email'
email_body = 'This message is using the Office 365 API to send emails.'
attachments = ['test.xlsx', 'test.pdf']
send_to = ''
send_email(send_to, email_title, email_body, attachments, APP_CLIENT_ID, APP_CLIENT_SECRET, TENANT_ID, scopes)

**Comment by Lukehi** [comment]
See the attached code. Turned out to be straight forward.
[o365_email.txt](https://github.com/O365/python-o365/files/5141089/o365_email.txt)
