### ISSUE TITLE
An error occurred while retrieving the body of the email

### ISSUE THREAD

**Issue by xiaocao162020** [O365/python-o365#489]
I'm going to use this method to get the full text of the message.I want to get the body of an email given a subject, but I don't know how to write the code.Is our method wrong?Should I use the get_body_text method of message.py?But then it shows 

**Traceback (most recent call last):
  File "C:/PyJobs/O365-Client/Client.py", line 52, in <module>
    start.mail_or_calendar()
  File "C:/PyJobs/O365-Client/Client.py", line 38, in mail_or_calendar
    MailboxActions().read_email()
  File "C:\PyJobs\O365-Client\mailboxactions.py", line 60, in read_email
    message.Message().get_body_text()
  File "C:\Users\77933\AppData\Local\Programs\Python\Python38\lib\site-packages\O365\message.py", line 247, in __init__
    super().__init__(
  File "C:\Users\77933\AppData\Local\Programs\Python\Python38\lib\site-packages\O365\utils\utils.py", line 331, in __init__
    raise ValueError('Protocol not provided to Api Component')
ValueError: Protocol not provided to Api Component**

How do I get the Object ID and pass the get_message method from query to mailbox.py.

Here's the code we've written:

**if readbox == '1':
    readbox = mailbox.inbox_folder()
    message.Message().get_body_text()**

**Comment by Micraow** [comment]
I have the same problem too.How can I solve it?

@janscas

**Comment by janscas** [comment]
Please paste the complete code

**Comment by Micraow** [comment]
Here is the link
https://github.com/Dreams-builder/O365-Client/blob/master/Client.py

https://github.com/Dreams-builder/O365-Client/blob/master/mailboxactions.py

And here is our code
# coding=utf-8

#  O365-Client -- A client to connect O365
#  Copyright (C) 2020  Micraow
#
#  This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

from mailboxactions import *

credentials = ('74424fcf-55d7-4e15-99d7-1663c0ba2e94',)
account = Account(credentials, auth_flow_type='public')


class Start:
    """这里是应用入口"""

    def __init__(self, choice=None):
        self.choice = choice

    def mail_or_calendar(self):
        MailboxActions().check_if_authenticated()
        self.choice = input('进入邮箱还是日历？(E/C)')
        if self.choice == 'E':
            self.choice = input('看邮件还是写邮件？(R/W)')
            if self.choice == 'R':
                MailboxActions().read_email()
            elif self.choice == 'W':
                MailboxActions().get_full_mail_info()
                MailboxActions().send_email()
            else:
                Start().mail_or_calendar()
        elif self.choice == 'C':
            print('开发中，敬请期待')
            os.system("pause")
        else:
            Start().mail_or_calendar()


start = Start()
start.mail_or_calendar()






--------

from O365 import Account, message
import os
import re

credentials = ('74424fcf-55d7-4e15-99d7-1663c0ba2e94',)
account = Account(credentials, auth_flow_type='public')


class MailboxActions:
    """用来对邮箱进行操作"""

    def __init__(self):

        # 已实现公共客户端流
        self.account = account
        self.credentials = credentials
        self.scopes = ['basic', 'message_all']  # 请求权限

    def check_if_authenticated(self):
        """检查是否有用户登录，若无，则请求登录"""
        if not self.account.is_authenticated:  # 检查是否登录
            # 请求登录
            self.account.authenticate(scopes=self.scopes)

    def read_email(self):
        """遍历邮件
        limit 表示加载多少个，微软官方一次API调用只返回999个，
        而O365模块默认25个，只有limit>25时utils分页功能才生效
        batch批处理表示加载多少次，就是往后加载
        limit=2000, batch=10 = limit=2000
        但是分为10次加载。"""

        mailbox = self.account.mailbox()
        print('''
        你要进入哪个文件夹？
        1.收件箱
        2.已发送
        3.垃圾邮件
        4.已删除\n
        ''')  # 选择进入哪个文件夹
        readbox = input('请输入对应数字')

        if readbox == '1':
            readbox = mailbox.inbox_folder()
        elif readbox == '2':
            readbox = mailbox.sent_folder()
        elif readbox == '3':
            readbox = mailbox.junk_folder()
        else:
            readbox = mailbox.deleted_folder()
        for messages in readbox.get_messages(limit=150, batch=2000):
            print(messages)
        os.system('pause')

    def send_email(self):
        global to_who
        global subj
        global text
        m = account.new_message()
        m.to.add(to_who)
        m.subject = subj
        m.body = text
        m.send()
        print('\n邮件已发送\n')
        os.system('pause')

    def get_full_mail_info(self):
        global to_who
        global subj
        global text
        new_people = input('\n收件人是谁？如有多个，每个都以;结尾，最后一个除外。\n')
        result1 = re.split(r'[;]', new_people)  # 匹配正则式，感谢@xiaocao162020
        print('请确认这些收件人。')
        print(result1)
        os.system('pause')
        to_who = result1
        subj = input('\n主题是什么？\n')
        text = input('\n 正文是什么？\n')

**Comment by xiaocao162020** [comment]
It might be difficult to read our code because it's in Chinese. If you would like to have the English translated version, just let us know, @janscas , thank you very much!

**Comment by Micraow** [comment]
Thank you for helping us. If you are free maybe you can join us，we often meet all kinds of problems and they often takes us a lot of time. If you are willing，you can email me

pengbo@pengbo0708.onmicrosoft.com 

Best wishes 
MS

**Comment by janscas** [comment]
> message.Message().get_body_text()

The links provided didn't execute the `get_body_text()` that was failing...

I can't help you

**Comment by Micraow** [comment]
I'm sorry.I gave you a wrong link.
Here is the right one 

https://github.com/Dreams-builder/O365-Client/blob/Get_body_text_MS/mailboxactions.py
