### ISSUE TITLE
Pagination support - '@odata.nextLink'

### ISSUE THREAD

**Issue by emican86** [O365/python-o365#49]
Hello friend,

I noticed the Inbox class does not check the json returned for the key '@odata.nextLink'.  Line 56 starts looping over the returned values, without pagination the maximum collection size is 10.  Also I think the Contacts class behaves the same way.

What do you think of adding a loop for pages to the existing classes to process the complete collection?  
Hopefully you can benefit from these findings:
If total collection contains <= 10 items, the key @odata.nextLink is not present in the json response.
Json module will raise a KeyError if we try and reference a key that is not present.
The last json response in the collection does not have the @odata.nextLink key.
Right now, I think the most performant way to get a total count prior to retrieving the complete collection is to use a query expression ($select) to a paginate a sliced collection.  I don't think there is a $count query expression.

I will try and budget some time this week to play around with this :)

Nice project !

**Comment by Narcolapser** [comment]
We just had a merge request for something like this, how does it compare to your proposal?

https://github.com/Narcolapser/python-o365/pull/48

**Comment by emican86** [comment]
Updates:
#48 helps because we can now retrieve up to 50 results.  Here is the source
"
By default, 10 entries are returned, a maximum of 50 entries can be return from a request on: [Messages, ChildFolders property, a collection,  CalendarView].
"
https://msdn.microsoft.com/en-us/office/office365/api/complex-types-for-mail-contacts-calendar#TopSkip

What is the best option for retrieving more than 50 entries? I can think of two choices:
    1) complete an option then re-run script:
            a. move items to sub folders (< 50 items per folder)
            b. delete items until < 50 items in folder
    2) add pagination to [Inbox.getMessages, Schedule.getCalendars, Calendar.getEvents].
        to retain the ability to process all, some, or one:
            a. use $count and determine how many pages are required
            b. adjust $top request parameter to result in fewest amount of requests

**Comment by Narcolapser** [comment]
Hmmm. Choice one isn't really a very good one. It wouldn't allow for things like two scripts running at once since we actually making changes to the files by moving them to sub folders (or so I understand). So yes, pagination will be necessary. Have you done any work this direction already?

**Comment by emican86** [comment]
Yes I've gotten started and will share on 2/1.

**Comment by roycem90** [comment]
available on 1.0
