### ISSUE TITLE
[Question] Is it possible to rename an attachment in a message?

### ISSUE THREAD

**Issue by lcvriend** [O365/python-o365#494]
First of all, thank you for this very useful library!

I am trying to create a simple script that will let me forward emails. However I am having a hard time manipulating the attachments connected to the message. One of my goals is to rename the attachment of a message before forwarding it. I have -- somewhat simplistically -- tried the following (there is one test message in the inbox and it has one attachment): 

```Python
for msg in inbox.get_messages():
    fwd = msg.forward()
    fwd.attachments.download_attachments()
    for attachment in fwd.attachments:
        attachment.name = 'bleep.bloop'
    fwd.save_draft()
```

This will create a forward that has the attachment. But it will not rename the attachment. I have also tried to remove the attachment (`fwd.attachments.clear()` and `fwd.attachments.remove(attachment.attachment_id`) in the hopes of re-adding it under a different name but even though I get no errors, the original attachment does not get deleted from the forward.

Is it possible to achieve this task with this library? If so, could anyone give me some pointers on how I would do this?

**Comment by lcvriend** [comment]
I actually got it to work!

```Python
from io import BytesIO
import base64

for msg in inbox.get_messages():
    fwd = msg.forward()
    fwd.attachments.download_attachments()
    for attachment in fwd.attachments:
        content = BytesIO(base64.b64decode(attachment.content))
    fwd.attachments.remove(attachment)
    fwd.attachments.add([(content, 'bleep.bloop')])
    fwd.save_draft()
```

However, I do not really understand why setting  `attachment.name` does nothing. Why is that?

**Comment by janscas** [comment]
Modifying attachment name does actually work (or should work) if the attachment is recently attached. Modifying the name when you are just forwarding will not work.

**Comment by lcvriend** [comment]
Thank you! I will keep that in mind.
