### ISSUE TITLE
How do I get a list of a users emails?

### ISSUE THREAD

**Issue by pkrtaylor** [O365/python-o365#498]
I want to get a list of a users inbox emails. I want the subject, date and time of each email. So far what I have only outputs the subject. I also want the date and time of the email. 

```
mailbox = account.mailbox()

inbox = mailbox.inbox_folder()

for message in inbox.get_messages(10):
    print(message)
```

**Comment by Harshitg10** [comment]
`
for message in inbox.get_messages(query=mailbox.q().select('internet_message_headers')):
   for msg in message.message_headers:
      if msg["name"] == "Subject":
         print("Subject: {}".format(msg["value"]))
      if msg["name"] == "Date":
         print("Date: {}".format(msg["value"]))
`

**Comment by kwilsonmg** [comment]
@janscas I believe that this issue can be closed?

**Comment by janscas** [comment]
you're right
