### ISSUE TITLE
integrate with thunderbird, neomutt, email clients

### ISSUE THREAD

**Issue by maitra** [O365/python-o365#499]
I am trying to see if I can integrate this package with an e-mail client such as thunderbird, neomutt, etc. Any examples on how it is to be done? TIA.

**Comment by janscas** [comment]
It is impossible

**Comment by maitra** [comment]
How about an example on how to use it with something like postfix? I am trying to understand how to use python-o365 in a practical setting to send e-mail. Any suggestions?
