### ISSUE TITLE
Throttle error

### ISSUE THREAD

**Issue by Muthukrishna17** [O365/python-o365#500]
I'm receiving this throttling error and there is no mention anywhere regarding why this error occurs. 

Error Message: Application is over its IncomingBytes limit.

**Comment by Muthukrishna17** [comment]
@janscas Can you please advise?

**Comment by arturaugusto** [comment]
Maybe Microsoft Graph is throttling your app:

https://docs.microsoft.com/en-us/graph/throttling

**Comment by Muthukrishna17** [comment]
I certainly understand that because what specifically is causing that error? What should I be doing instead to prevent it? How do I increase the limit?

**Comment by arturaugusto** [comment]
From the article:

* Reduce the number of operations per request.
* Reduce the frequency of calls.
* Avoid immediate retries, because all requests accrue against your usage limits.

**Comment by janscas** [comment]
@arturaugusto is right! that was a throttling error.
