### ISSUE TITLE
How to retrieve immutable ids for outlook items

### ISSUE THREAD

**Issue by sbealer** [O365/python-o365#503]
Sorry to make this an issue guys, but I wasn't sure the best way to contact you. In my use of your module i'll need to do some message sorting into various folders but will still need to work with the id of the message. As is noted in the provided link, the id of the message will/can change once moved. As such, i'd like to be able to retrieve the messages immutable_id but it appears we'd need to manipulate the actual headers of the graph post/get requests. Please advise - is there a way to do this using your module?

https://docs.microsoft.com/en-us/graph/outlook-immutable-id

**Comment by janscas** [comment]
The library actually updates the object_id once it has been moved.

But This prefer header should be definitively an option.

**Comment by AndreasDL** [comment]
+1

Would be nice to have as I am using this library to load mails from a shared mailbox into a database.
It becomes a bit tricky to keep everything in sync if the default ids change when you move mails.
Even more so because the mails are always moved to subfolders.

Is there a way to get immutable
