### ISSUE TITLE
is it possible to create/modify/delete mailbox rules ?

### ISSUE THREAD

**Issue by mjuliefr** [O365/python-o365#506]
Hi, 

I read the read me and search in the issue database but I have not find any information related to the possibility to create and manage outlook mailbox rules,

Is it possible, please?

Thanks Julie

**Comment by janscas** [comment]
The underlying ms graph api allows that but this library does not provide the functions to do so.
Pull requests are very welcome ....

**Comment by mjuliefr** [comment]
Noted! Thanks for the reply. 👍
