### ISSUE TITLE
include userPrincipalName or the Id in the account.get_current_user() please

### ISSUE THREAD

**Issue by mjuliefr** [O365/python-o365#508]
Hi,

I have created an outlook.com account and the mail info is equal to null
Is it possible to include either the id or userPrincipalName or the Id in the account.get_current_user() , please?
I am trying to make sure that my user is identified uniquely and the surname and first name is not enough. I would have use the email but I can not retrieved it easily since the mail property is null.

Thanks again for the library, it is great !

From MS Graph explorer :
{
    "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#users/$entity",
    "displayName": "Julie HM",
    "surname": "HM",
    "givenName": "Julie",
    "id": "1d0fddbd1dab94fe",
    "userPrincipalName": "julie.h.m@outlook.com",
    "businessPhones": [],
    "jobTitle": null,
    "mail": null,
    "mobilePhone": null,
    "officeLocation": null,
    "preferredLanguage": null
}

**Comment by janscas** [comment]
That method returns a User object. The User object has all those properties

**Comment by mjuliefr** [comment]
thanks indeed 👍 user.user_principal_name              
Thank again for the super library !
