### ISSUE TITLE
Attachments more than 4 mb

### ISSUE THREAD

**Issue by northernclimat** [O365/python-o365#509]
Hello,

while i'm trying to attach such files to my message, getting an error requests.exceptions.HTTPError: 413 Client Error: Request Entity Too Large for url: https://graph.microsoft.com/v1.0/me/sendMail

How to handle?

**Comment by janscas** [comment]
For the moment is not posible, use the outlook protocol to send big attachments

**Comment by aefruswg** [comment]
Any update to this? I'm have my protocol set as MSGraphProtocol(api_version='beta') per the instructions in the readme for files above 4mb and am still receiving an error

**Comment by BlueSideStrongSide** [comment]
https://docs.microsoft.com/en-us/graph/api/attachment-createuploadsession?view=graph-rest-1.0&tabs=http

https://docs.microsoft.com/en-us/graph/outlook-large-attachments?tabs=http

https://docs.microsoft.com/en-us/graph/known-issues#attaching-large-files-to-messages


I do not think sendMail is the endpoint you want to hit for large files.

**Comment by nachiketrss** [comment]
I have got this working by calling `.save_message()` prior to adding the attachment and it looks like it is working. You might want to give this a try. I have also raised an issue asking whether this is the correct approach to send mails with large attachment size here: https://github.com/O365/python-o365/issues/841

**Comment by kwilsonmg** [comment]
@janscas hopefully that wording is good enough, otherwise I can revise. Should allow this issue and related ones to be closed?

**Comment by janscas** [comment]
> @janscas hopefully that wording is good enough, otherwise I can revise. Should allow this issue and related ones to be closed?

sure
