### ISSUE TITLE
getting excel file from OneDrive

### ISSUE THREAD

**Issue by thehamzam** [O365/python-o365#512]
Hello,

Fairly new to O365, and I followed the tutorials here: https://pypi.org/project/O365/#sharepoint. 

I am trying to get an Excel File from my OneDrive, and then, "Format as Table" the existing data.

What I have so far does not get the contents of the folder (it gets back my OneNote files which aren't even in that folder):

```
# here we get the storage instance that handles all the storage options.
storage = account.storage()
drives = storage.get_drives()

# get the default drive
my_drive = storage.get_default_drive()  # or get_drive('drive-id')
root_folder = my_drive.get_root_folder()

a = root_folder.search('changes')

print(a)

for aa in a: ## NOTE: aa is of type File - this is what we need to feed into the Excel
    print('file', aa) # this does not give me back my EXCEL files in the 'changes' folder
```

How do I get the excel files from my onedrive folder named "changes" above?
Really appreciate your help.

**Comment by janscas** [comment]
you just have to locate the excel file use search and check for the name and is_folder properties or get a parent folder and then go through the tree looking for the excel file.

**Comment by thehamzam** [comment]
nice, I had to replace the search parameter with the name of the excel file, and it works now!
