### ISSUE TITLE
refresh_token not used?

### ISSUE THREAD

**Issue by trideeindhoven** [O365/python-o365#518]
Hi all,

I am trying to use the refresh_token, so that i can use the API for 90 days. I have added 'offline_access' to the scopes by adding 'basic'. I check the scopes by print()ing them to stdout and offline_access is in there.
I have also added delegated permissions for the app for the scopes i am requesting.

My (test-)code:

```
#!/usr/bin/python3
# -*- coding: utf-8 -*-

from O365 import Account, MSGraphProtocol, FileSystemTokenBackend
import config

protocol_graph = MSGraphProtocol()
scopes_graph = protocol_graph.get_scopes_for(['basic', 'address_book'])
print(scopes_graph)

credentials = ('*********@domain.com', '****************')
token_backend = FileSystemTokenBackend(token_path='tokens', token_filename='test.token')
account = Account(credentials, token_backend=token_backend)

if not account.is_authenticated:  # will check if there is a token and has not expired
  account.authenticate(scopes=scopes_graph)

address_book = account.address_book()
contacts = address_book.get_contacts(limit=None)  # get all the contacts in the Personal Contacts root folder
for c in contacts:
  print(c.display_name)

```
The output looks like:
```
~/bin$ ./test.py 
['offline_access', 'https://graph.microsoft.com/User.Read', 'https://graph.microsoft.com/Contacts.Read']
Visit the following url to give consent:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?response_type=code&client_id=*********************&redirect_uri=https%3A%2F%2Flogin.microsoftonline.com%2Fcommon%2Foauth2%2Fnativeclient&scope=offline_access+https%3A%2F%2Fgraph.microsoft.com%2FUser.Read+https%3A%2F%2Fgraph.microsoft.com%2FContacts.Read&state=************&access_type=offline
Paste the authenticated url here:
https://login.microsoftonline.com/common/oauth2/nativeclient?code=***************&state=******&session_state=********
Authentication Flow Completed. Oauth Access Token Stored. You can now use the API.
Name1
Name2
Name3
...etc
```

Perfect! I can read the addressbook and this stays during 60 minutes. The token:

```
~/bin$ cat tokens/test.token 
{
 "scope": [
  "profile",
  "openid",
  "email",
  "https://graph.microsoft.com/Contacts.Read",
  "https://graph.microsoft.com/User.Read"
 ],
 "access_token": "********",
 "token_type": "Bearer",
 "expires_at": 1600432322.8103461,
 "expires_in": 3599,
 "ext_expires_in": 3599,
 "refresh_token": "*******"
```
Two things stand out here: the expires_in is only 1 hour (maybe this is correct?) and the list of scopes does not correspond to the list of requested scopes. Most importantly: offline_access is not in there.

One hour later:

```
~/bin$ ./test.py 
['offline_access', 'https://graph.microsoft.com/User.Read', 'https://graph.microsoft.com/Contacts.Read']
Traceback (most recent call last):
  File "/home/2200123456/.local/lib/python3.5/site-packages/O365/connection.py", line 701, in _internal_request
    response = request_obj.request(method, url, **kwargs)
  File "/home/2200123456/.local/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 478, in request
    url, http_method=method, body=data, headers=headers
  File "/home/2200123456/.local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 198, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 61, in <module>
    contacts = address_book.get_contacts(limit=None)  # get all the contacts in the Personal Contacts root folder
  File "/home/2200123456/.local/lib/python3.5/site-packages/O365/address_book.py", line 712, in get_contacts
    response = self.con.get(url, params=params)
  File "/home/2200123456/.local/lib/python3.5/site-packages/O365/connection.py", line 805, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/home/2200123456/.local/lib/python3.5/site-packages/O365/connection.py", line 794, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/home/2200123456/.local/lib/python3.5/site-packages/O365/connection.py", line 718, in _internal_request
    if self.refresh_token() is False:
  File "/home/2200123456/.local/lib/python3.5/site-packages/O365/connection.py", line 630, in refresh_token
    client_secret=client_secret)
  File "/home/2200123456/.local/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 446, in refresh_token
    self.token = self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/home/2200123456/.local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 421, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/home/2200123456/.local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 431, in parse_token_response
    validate_token_parameters(params)
  File "/home/2200123456/.local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 438, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/home/2200123456/.local/lib/python3.5/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) AADSTS70000: Provided grant is invalid or malformed.
Trace ID: *************
Correlation ID: ********************
Timestamp: 2020-09-18 10:55:56Z
```

I am kind of struggling here. I feel like i am 99% there, but i cannot get this working in any way. All issues here regarding the 90 days token are suggesting to use either basic (which includes offline_access) or just offline_access, but i am requesting that scope and i have added it in the delegated permissions in the app.
What am i doing wrong here? Thank you so much!

**Comment by janscas** [comment]
You don't have to call get_scopes_for. Just pass the scopes to authenticate and it will do that for you:

`account.authenticate(scopes=['basic', 'address_book'])`


> Two things stand out here: the expires_in is only 1 hour (maybe this is correct?) and the list of scopes does not correspond to the list of requested scopes. Most importantly: offline_access is not in there.

Yes, all access tokens expire in 1 hour. 
The scopes are correct. Those are the basic ones + Contacts.Read. The offline_access used to appear, but not anymore. The fact that you get a refresh_token denotes you have offline_access enabled. Try to authenticate without the offline_access scope and you will see that there's not a refresh_token there.

I've never see that problem. You got the refresh token and it should work... Maybe there's something with the permission? or maybe some configuration that your admin could have done?

Can you paste an image of the azure permission section? (blur private sensitive info)

**Comment by trideeindhoven** [comment]
Hi janscas,

Thank you for your reply.

redirect URL:
![image](https://user-images.githubusercontent.com/9008122/93600681-50089c00-f9c0-11ea-91ef-8e36464921f6.png)

Permissions:
![image](https://user-images.githubusercontent.com/9008122/93600756-73334b80-f9c0-11ea-8525-2c738f159fc9.png)

**Comment by trideeindhoven** [comment]
Not sure what that is. This is very new to me. How would i do that?

**Comment by trideeindhoven** [comment]
So... This took me a long time to figure out, but it is solved. I was using an application_id like: longuuid@domain.com
Apparently that works for getting a token en logging in for the first time, but for refreshing the token this is a not supported format. I simply removed "@domain.com" from the application_id so it was just the long hex uuid and it immediately worked.
Please don't ask me why i added the "@domain.com" because i cannot remember. I must have read it somewhere. The error: "AADSTS70000: Provided grant is invalid or malformed." is now gone!

**Comment by janscas** [comment]
Great! Well I hope this knowledge will serve someone in the future
