### ISSUE TITLE
How to query email by recipients?

### ISSUE THREAD

**Issue by chrisspen** [O365/python-o365#521]
How do you query emails, filtering by recipients to find emails sent to a specific address?

Based  on the docs, I thought it would be something like:

    mailbox = account.mailbox()
    query = mailbox.new_query().on_attribute('to_recipients').contains('somename@domain.com')
    messages = mailbox.sent_folder().get_messages(query=query)

However, this gives me the error:

    Error Message: Invalid filter clause

I've tried the attribute name "toRecipients" as well, but get the same error.

Is `.contains()` not the proper filter for this type of search?

**Comment by janscas** [comment]
Microsoft is very obscure about the filters you can do.
There are literally no docs on what combinations work...

The only thing I can recommend you is to first try the filter combinations on [ms graph explorer](https://developer.microsoft.com/en-us/graph/graph-explorer). If they fail there... that's on microsoft.

**Comment by chrisspen** [comment]
Yeah, I found `.search("to:somename@domain.com")` works. Thanks.
