### ISSUE TITLE
Using your own defined scopes - Presence.Read.All

### ISSUE THREAD

**Issue by SiboneloJunior** [O365/python-o365#522]
Thanks for such an amazing and useful library 💯 

I want to get the presence of all users using the scope 'https://graph.microsoft.com/Presence.Read.All' which is already provided to the Account instance upon authentication.

Now i'm not sure how to proceed to getting the user presence... I've tried :

protocol = MSGraphProtocol('https://graph.microsoft.com/Presence.Read.All')
account = Account(credentials=credentials, protocol=protocol)

And not sure what method to use on 'account' after this step ( i.e. If this is indeed the correct way to do it )

Thanks in advance.

**Comment by janscas** [comment]
I don't know what "Presence.Read" does, but I can tell you O365 library is not ready for that.
There's no implementations right now to handle user presence or to work with the api provided by Presence.
PR are welcome

**Comment by SiboneloJunior** [comment]
Thanks for the swift response

So in summary the library is only limited to the scopes outlined in the documentation ( e.g. 'Mail.Read.Shared' etc.) 

My assumption was that the library can work with any Microsoft Graph API as long as you implement the protocol needed

**Comment by janscas** [comment]
Correct
