### ISSUE TITLE
Querying multiple mailboxes at the same time?

### ISSUE THREAD

**Issue by chrisspen** [O365/python-o365#523]
How do you search across all mailboxes for an Exchange account simultaneously?

I'm using this code to successfully retrieve email:

    from O365 import Account, MSGraphProtocol

    credentials = ('xxxxxxxxxxxxxxx', 'xxxxxxxxxxxxxxxxxxxxxxx')
    tenant_id = 'xxxxxxxxxxxxxxxxxxxxxxx'
    scopes_office = ['https://graph.microsoft.com/.default']

    protocol = MSGraphProtocol(default_resource='admin@mydomain.onmicrosoft.com')
    #protocol = MSGraphProtocol(default_resource='someuser@mydomain.onmicrosoft.com')

    account = Account(credentials, auth_flow_type='credentials', tenant_id=tenant_id, scopes=scopes_office, protocol=protocol)

    if account.authenticate():
        print('Authenticated!')
        mailbox = account.mailbox()
        inbox = mailbox.inbox_folder()
        messages = mailbox.get_messages()
        for message in messages:
            print(message, message.sender, [_ for _ in message.to])

but it only seems to work for the account defined in the MSGraphProtocol instance, even if it's the admin account. I can search a different mailbox by changing the email address used in MSGraphProtocol, but I can't do both at once.

Is there a special MSGraphProtocol to use to search all mailboxes? My app's using it's own identity, and the docs say for resources it should be able to retrieve "All Azure AD users the app has access to".

If I omit protocol completely, then I get the error:

    Error Message: Resource not found for the segment 'messages'.

**Comment by janscas** [comment]
You can't.

You just have to iterate over... like:

We don't define the resource at the protocol level for ease right here.
The resource can be specified at different levels for convenience.

```python
# ... account init...

accounts = ['email1@example.com', 'email2@example.com']
for email in accounts:
    mailbox = account.mailbox(resource=email)
    emails = mailbox.get_messages()
    # do what you want
```

**Comment by chrisspen** [comment]
I see. That's unfortunate. I'm trying to find a way to lookup everyone in an organization who communicated with a specific client. The reason I wanted a global way to search was because I don't know the target mailbox, meaning I'd have to potentially search over hundreds of mailboxes.
