### ISSUE TITLE
How to specify $skip for message retrieval offset?

### ISSUE THREAD

**Issue by chrisspen** [O365/python-o365#526]
How do you pass in a custom value for `$skip` when querying messages from Outlook?

I'm trying to paginate results and [according to the docs](https://github.com/Microsoft/api-guidelines/blob/master/Guidelines.md#982-client-driven-paging) I'd use `$top` to limit the page size, and `$skip` to specify the offset.

From your own pagination docs, you state the `limit` parameter maps to `$top`. However, I don't see any option for specifying `$skip`.

**Comment by janscas** [comment]
Yep, skip is not implemented

**Comment by chrisspen** [comment]
It's not documented, but it looks like the `search()` method support comparison operators on date fields.

So I can implement a de facto "skip" by tracking the last received date of an email, and then using that to filter search results.
