### ISSUE TITLE
Excel : unable to work with ranges over sheets with name containing either '.' or '-'

### ISSUE THREAD

**Issue by KorriGnu** [O365/python-o365#548]
Hi,

I'm currently working with a O365 Excel worksheet containing around 60 sheets. There is a semantic on the sheets names and I may not change them. I need to retrieve some cell ranges over these sheets. If the sheet name contains only letters or figures, its ok, the following code works:

`name = "Sheet1"`
``ws = excel_file.get_worksheet(name)``
``cell1 = ws.get_cell(1, 0) ``
``cell2 = ws.get_cell(1, 10)``
``range_name = "{}:{}".format(cell1.address, cell2.address)``
``cellrange = ws.get_range(range_name)``

However, if I set `name = "1.1"` or `name = "1 - stuff"` I've got the following error:
``requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: [...] Error Message: Syntax error at position 20 in 'address=``

Any ideas ?

**Comment by janscas** [comment]
Hi, this is abug, the provided address (range_name) is never url encoded. and that's causing the error.

See [this line](https://github.com/O365/python-o365/blob/master/O365/excel.py#L1609).

**Comment by KorriGnu** [comment]
Thank you, but I think there is still a bug, related to quotes.

With "complex" sheets name, like `1.1`, `word-other` or `1 - stuff`, Excel quotes these names, which gives a range like `'1.1'!A1:'1.1'!K1` which creates some troubles with `address='{}'` at the given line...

**Comment by janscas** [comment]
What's the error message?

**Comment by KorriGnu** [comment]
HTTP error: 400 Client Error: Bad Request for url: https://graph.microsoft.com/v1.0/drives...worksheets('...')/range(address='%271%20-%20%C3%89valuations%27%21A2%3A%271%20-%20%C3%89valuations%27%21K2') | Error Message: Syntax error at position 11 in 'address=''1 - Évaluations'!A2:'1 - Évaluations'!K2''.

**Comment by janscas** [comment]
ok, when calling Worksheet.get_range you don't need to pass the sheetname in-front of the range cells.

Why are you passing "1.1'!A2:'1.1'!K2" instead of "A2:K2"?

**Comment by KorriGnu** [comment]
true, but this is not me, my code does :
`name = "Sheet1"
ws = excel_file.get_worksheet(name)
cell1 = ws.get_cell(1, 0)
cell2 = ws.get_cell(1, 10)
range_name = "{}:{}".format(cell1.address, cell2.address)
cellrange = ws.get_range(range_name)`

Maybe there is another way to create the range...

**Comment by janscas** [comment]
ok, I see. 
The address property is just what the Graph Api returns.
I'll just remove the sheet name from the given address as a safe check.

**Comment by janscas** [comment]
can you try now?

**Comment by KorriGnu** [comment]
I've just
`pip3 uninstall O365`
`git clone https://github.com/O365/python-o365.git`
`cd python-o365`
`sudo python3 setup.py install`
and re-run my script.
Same issue...
