### ISSUE TITLE
auth_flow_type='credentials' Issues

### ISSUE THREAD

**Issue by bhain7** [O365/python-o365#550]
```
from O365 import Account

credentials=("xxxxxx", "xxxxxx")

# the default protocol will be Microsoft Graph

account = Account(credentials, auth_flow_type='credentials', tenant_id='xxxx')

account.authenticate()
if account.authenticate():
   print('Authenticated!')

```
I've switched my application to be self authenticating and tried to run the basic code to ensure authentication is working and the code runs for a very long period of time then errors with the following.

> Unable to fetch auth token. Error: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /xxxxxx/oauth2/v2.0/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fc2bcd9c048>: Failed to establish a new connection: [Errno 110] Connection timed out',))'

Any idea what is going on here? Prior I was user authentication and atleast getting a URL to authenticate.

Edit: Could this have anything to do with being stuck behind a company proxy server?

**Comment by janscas** [comment]
> Edit: Could this have anything to do with being stuck behind a company proxy server?

Sure it does!

**Comment by bhain7** [comment]
I apologize! I'm a relatively new developer. Any example code of how I might pass the proxy configuration on init? 
I've done it on a per request basis when using the requests library but lost when it comes to setting the configuration overall.

**Comment by janscas** [comment]
```python
account = Account(credentials, proxy_server='myserver', proxy_port=8080)  # etc.
```

**Comment by bhain7** [comment]
This worked perfectly! Thank you so so much!
