### ISSUE TITLE
Scope User

### ISSUE THREAD

**Issue by whoo** [O365/python-o365#568]
Hi Guys,

```
credentials = (id,key)
token_backend = FileSystemTokenBackend()
account = Account(credentials, token_backend=token_backend)

if (not account.is_authenticated):
  if account.authenticate(scopes=['basic', 'users']):
     print('Authenticated!')

global_address_list = account.directory()
# for backwards compatibilty only this also works and returns a Directory object:
# global_address_list = account.address_book(address_book='gal')
# start a new query:
q = global_address_list.new_query('display_name')
q.startswith('George Best')

for user in global_address_list.get_users(query=q):
    print(user)

```

I follow readme.txt .
User.ReadBasic.All is not supposed to ask admin to approve application.
But authentication process ask for admin approval.

Thanks for your help.

![image](https://user-images.githubusercontent.com/1499543/105565680-104b1b80-5cf6-11eb-883b-6c0c67b4be91.png)

**Comment by janscas** [comment]
Can you paste the error?

**Comment by whoo** [comment]
There is no error just:
"Approbation administrateur requise"

**Comment by janscas** [comment]
I don't know then... in theory does not require admin approval

**Comment by whoo** [comment]
Corporate rules could override default parameter.
(That's why)
I close this ticket.

**Comment by janscas** [comment]
That's the reason! ok
