### ISSUE TITLE
CC function that works like reply-to.add()?

### ISSUE THREAD

**Issue by mr-alord** [O365/python-o365#574]
Hi,

Is there currently any way to add a cc-to in a similar way to how reply-to.add() works?

Ideally, I'd like to be able to forward an email on from one inbox to another where it preserves the original CC recipients in without it actually emailing them as part of the forward.  Then the recipient of the forward can simply press reply and respond to the original recipients (much like reply-to.add() works for the sender).

Thanks.

**Comment by janscas** [comment]
I don't think so... 'reply-to' is something that "exists" on the ms graph side. "cc-to" does not.

**Comment by mr-alord** [comment]
.
