### ISSUE TITLE
[QUESTION] Unable to generate token file anymore

### ISSUE THREAD

**Issue by liab25** [O365/python-o365#575]
I've been running a script using this module for over a year and it's been working well but recently there's been multiple failures when trying to pull messages from specific inboxes. I'm not exactly sure what's going on but it looks like the script is unable to pull messages from the inboxes. When I run the script locally, I was getting the HTTP error "too many 504 responses".

I tried registering a new test app in azure AD and using the same code below, it runs without error but I am never able to authenticate because the token file isn't created.
```
credentials = (CLIENT_ID, CLIENT_SECRET)
token_path = "C:\\Users\\me\\Documents\\Projects\\test\\"
token_backend = FileSystemTokenBackend(token_path=token_path, token_filename="new_token.txt")
protocol = MSGraphProtocol()
logger.info("Attempting to authenticate with MS Graph API")
try:
     account = Account(credentials, token_backend=token_backend, protocol=protocol, auth_flow_type='credentials', tenant_id=TENANT_ID)
except Exception as e:
     logger.error(e)
     sys.exit(1)

if account.authenticate():
    print("Authenticated!")
```

**Comment by janscas** [comment]
What's the error message when trying to authenticate?

**Comment by liab25** [comment]
> What's the error message when trying to authenticate?

That’s the odd thing. There is no error it just doesn’t seem to write the token to the file

**Comment by liab25** [comment]
Ahh - it's been a while since i looked at this. Looks like the problem was i was using the client ID of the secret instead of the app registration client ID. Once i changed it to the client ID for the app, it worked.

**Comment by janscas** [comment]
Great!
