### ISSUE TITLE
[QUESTION] Changing non-draft subject/body of messages and the meaning of __is_draft

### ISSUE THREAD

**Issue by JoelWiesmann** [O365/python-o365#576]
Dear all

For an automation we have to manipulate messages in the inbox folder. save_message() does not allow us to save changed subject/body. So I was curious and forcibly set __is_draft to True and used save_draft() to write the message back. With success - I was able to change the subject / body of a message in the inbox folder.

So I wanted to ask whether there is a **technical** reason why we shouldn't manipulate messages?

```python
mail = next(
    inbox.get_messages(query=inbox.new_query().on_attribute("subject").equals("Test Message"))
)

mail.subject = "This is a changed subject."
mail.__setattr__('_Message__is_draft', True)
mail.save_draft()
```

Regards
Joel

**Comment by janscas** [comment]
Wow! I didn't know you can modify messages... I think's that's a security risk anyway.
Well ideally you can't modify a message on the inbox. 
To modify a message you need it to be a draft.

That's the whole reason behind...

**Comment by JoelWiesmann** [comment]
You can modify messages using Outlook as a client as well, so I would say it's works as designed.

Double-click the mail you want to modify so it opens in a separate window - now you can change the subject. Click "actions" in the move group and click edit message - now you can edit the body.

It's a bit odd but for building mail robots it's a great feature ;-).
