### ISSUE TITLE
404 error when getting calendar API

### ISSUE THREAD

**Issue by int-72h** [O365/python-o365#588]
I've been trying to get the calendar to work, but I keep getting an odd error:
`requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://graph.microsoft.com/beta/me/calendar | Error Message: REST API is not yet supported for this mailbox.
`
I've tried using the beta graph API and the office365 APIs, but the same error (with a different URL).
Code snippet:

```
credentials = ('clientid','clientsecret')
account = Account(credentials, tenant_id='tenantid',protocol=MSGraphProtocol(api_version="beta"))
if account.authenticate(scopes=['calendar_all']):
   print('Authenticated!')

schedule = account.schedule()
```
(IDs and secrets redacted)

**Comment by janscas** [comment]
I don’t know what account you have but the error is pretty descriptive...

> REST API is not yet supported for this mailbox.

**Comment by int-72h** [comment]
I've just followed the tutorial - what is this supposed to mean anyway?

**Comment by int-72h** [comment]
well why does the account type matter? I have a school account for reference, I don't see any reason why it shouldn't work.

**Comment by janscas** [comment]
I don’t know. Ma graph is returning that message... maybe you can ask your account admin

**Comment by int-72h** [comment]
OK, for future reference the issue was that it was an exchange account and REST wasn't enabled. That's not an issue for here so I'll close this, sorry for misreading the error
