### ISSUE TITLE
Error: 'backports.zoneinfo.ZoneInfo' object has no attribute 'zone'

### ISSUE THREAD

**Issue by topcats** [O365/python-o365#591]
I'm getting an error message when trying to iterate though the calendar events.
it then breaks out and give me no data.

Python Version: Python 3.7.3
Installed Version: O365-2.0.14
Host System: Raspberry Pi (Buster)

Calling Code:
```
     o365_mycalendar = Account.schedule().get_default_calendar()
     o365_mycalendarEvents = o365_calendar.get_events(limit=20, query=o365_calendarQuery, include_recurring=True)
     for o365_event in o365_mycalendarEvents:
          print('E  ', o365_event.start, o365_event.end, o365_event.subject)
```

Stack Trace
```
  File "/home/pi/dashdisplay/app_calendar.py", line 214, in process
    for o365_event in o365_mycalendarEvents:
  File "/usr/local/lib/python3.7/dist-packages/O365/calendar.py", line 1740, in <genexpr>
    for event in data.get('value', []))
  File "/usr/local/lib/python3.7/dist-packages/O365/calendar.py", line 897, in __init__
    cc('recurrence'), None))
  File "/usr/local/lib/python3.7/dist-packages/O365/calendar.py", line 137, in __init__
    get_windows_tz(self.protocol.timezone))
  File "/usr/local/lib/python3.7/dist-packages/O365/utils/windows_tz.py", line 639, in get_windows_tz
    iana_tz.zone if isinstance(iana_tz, tzinfo) else iana_tz)
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'zone'
```

I'm guessing I have a problem somewhere else (ie a system dependency that is not installed), but can't track down.

**Comment by janscas** [comment]
I have no clue for your problem. For me it works perfectly as expected.

**Comment by mw-deb** [comment]
Same issue here.

However, the error occurred with me after an update of the pip packages on 15.08. The only difference I found is a new version of the package "tzlocal" (from v2.1 to v3.0) and that after the update additionally the package "backports.zoneinfo" was installed (v0.2.1).

pip freeze:
`
autopep8==1.5.7
beautifulsoup4==4.9.3    
boto3==1.18.21
botocore==1.21.21        
certifi==2021.5.30       
charset-normalizer==2.0.4
idna==3.2
Jinja2==2.11.3
jmespath==0.10.0
MarkupSafe==2.0.1
O365==2.0.15
oauthlib==3.1.1
pycodestyle==2.7.0
python-dateutil==2.8.2
pytz==2021.1
requests==2.26.0
requests-oauthlib==1.3.0
s3transfer==0.5.0
SAPLaMa==0.0.6
six==1.16.0
soupsieve==2.2.1
stringcase==1.2.0
toml==0.10.2
tzdata==2021.1
tzlocal==3.0
urllib3==1.26.6
`

Calling Code:
`
o365_mycalendar = schedule.get_calendar(calendar_name=calendar_name)
o365_mycalendarEvents = patch_events = calendar.get_events(200, include_recurring=False)
for event in o365_mycalendarEvents: **# error occurs here**
    ...
`

**Comment by mw-deb** [comment]
Workaround:
It helped me to manually install tzlocal on version 2.1.

**Comment by RogerSelwyn** [comment]
I suspect the breaking change to tzlocal which has been reported against that module is going to break all sorts of things - https://github.com/regebro/tzlocal/issues/112

Also causing problems on O365 module for Home Assistant. 

I suspect this module needs updating to deal with new version of tzlocal, or constraing to v2.1 as suggest above

**Comment by hmkim** [comment]
I also solved issue after tzlocal downgrade

`pip install tzlocal==2.1`

**Comment by janscas** [comment]
I'll pin tzlocal 2.1 as a requirement so this will be solved.
