### ISSUE TITLE
Plaintext body message

### ISSUE THREAD

**Issue by lukastribus** [O365/python-o365#594]
I feel like I'm missing something, there is probably an easier way that I overlooked ... but I just want to set the body of a message to a plain text string that doesn't get overwritten by a HTML conversion.

`message.body` assumes HTML and tires to extract plaintext from it.

I just want to send an email in plaintext, not a MIME multi-part with plaintext and HTML, just normal plaintext, and more importantly without automatic plain-text -> HTML -> plain-text transformations behind the scenes.

Currently I need to strange workaround `replace("\n", '<br>')` so that the HTML conversion forth and back doesn't eat newlines.

```
body = """Hey Bob!

This is the first paragraph.
This is the second line of the first paragraph.

And this is an entire new paragraph.

Keep it up
"""
message.body = body.replace("\n", '<br>')
```

This doesn't fulfill my requirement (which is to just send a plaintext string), but it's what I need to do, to be able to send a text that doesn't look garbled.

Is there any easier way?

**Comment by janscas** [comment]
message.body_type

**Comment by lukastribus** [comment]
`message.body_type = 'text'` does the job indeed.

Unsure why gmail now clips the message (`[Message clipped]  View entire message`), but this certainly works, thanks.
