### ISSUE TITLE
Signing key is invalid

### ISSUE THREAD

**Issue by gboeing** [O365/python-o365#597]
I had an automated workflow with O365 working well for months, but suddenly this morning I started getting "Signing key is invalid" errors. When I manually run the script, it prompts me to "Visit the following url to give consent". When I do so and log in, I paste in the resulting URL, and it says:
```
Client Error: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/me/calendar | Error Message: Signing key is invalid.
Traceback (most recent call last):
  File "outlook_to_google.py", line 204, in <module>
    outlook_cal = outlook_acct.schedule().get_default_calendar()
  File "/home/geoff/miniconda3/lib/python3.8/site-packages/O365/calendar.py", line 1948, in get_default_calendar
    response = self.con.get(url)
  File "/home/geoff/miniconda3/lib/python3.8/site-packages/O365/connection.py", line 808, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/home/geoff/miniconda3/lib/python3.8/site-packages/O365/connection.py", line 797, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/home/geoff/miniconda3/lib/python3.8/site-packages/O365/connection.py", line 759, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/me/calendar | Error Message: Signing key is invalid.
```
Why would the signing key suddenly be invalid? This script had been working for months.

**Comment by jesusjbr** [comment]
Hi, I've also experienced this problem around the same time. From what I've checked its seems the reason is an outage in Microsoft's services. It should be solved now.

**Comment by janscas** [comment]
That's odd. I'm also running a script every day multiple times and I haven't see this error.
Check if it is solved now. 

It could also be a change in some policy by the sys admin... don't know...

**Comment by gboeing** [comment]
Thanks @jesusjbr and @janscas. Looks like it's working again. Probably an outage on Microsoft's end!
