### ISSUE TITLE
Extracting access_token for use with fetchmail-7.0.0-alpha7

### ISSUE THREAD

**Issue by dthompson-uw** [O365/python-o365#605]
I'm using the o365 module with the FileSystemTokenBackend. I'm extracting the text of the access_token from the token to use with the PasswordFile parameter of fetchmail-7.0.0-alpha7 in "auth oauthbearer" mode to pull mail from an o365 account, but the authentication is failing. Is there some kind of format conversation that I need to do, or should this be working? Thx,
David

Apr 08 13:29:51 fetchmail: POP3< +OK The Microsoft Exchange POP3 service is ready. [QwBIADIAUABSADIAMABDAEEAMAAwADIANQAuAG4AYQBtAHAAcgBkADIAMAAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
Apr 08 13:29:51 fetchmail: POP3> CAPA
Apr 08 13:29:51 fetchmail: POP3< +OK
Apr 08 13:29:51 fetchmail: POP3< TOP
Apr 08 13:29:51 fetchmail: POP3< UIDL
Apr 08 13:29:51 fetchmail: POP3< SASL PLAIN XOAUTH2
Apr 08 13:29:51 fetchmail: POP3< USER
Apr 08 13:29:51 fetchmail: POP3< .
Apr 08 13:29:51 fetchmail: POP3> AUTH XOAUTH2
Apr 08 13:29:51 fetchmail: POP3< + 
Apr 08 13:29:51 fetchmail: POP3> [SHROUDED]
Apr 08 13:29:51 fetchmail: POP3< -ERR Authentication failure: unknown user name or bad password.
Apr 08 13:29:51 fetchmail: Authentication failure: unknown user name or bad password.

**Comment by janscas** [comment]
I have no clue
