### ISSUE TITLE
How go get manager / direct reports

### ISSUE THREAD

**Issue by Timmmm** [O365/python-o365#608]
Is there any way to get a user's manager or direct reports so I can build an org chart? It seems like I can get all the users using `account.directory().get_users()` but that doesn't include manager or reports. According to [this comment](https://github.com/O365/python-o365/issues/298#issuecomment-532629943) the `manager` is in the `Contact` object, but unfortunately it seems like you can't access the global address book so there's no way to get any of the users as contacts.

I found [this thread about it](https://stackoverflow.com/questions/43328466/how-to-get-manager-property-from-a-users-request) which seems to suggest you can get a manager from a `User`. Maybe.

**Comment by janscas** [comment]
Maybe, I don't know. You can check the docs and see it by yourself.

**Comment by Timmmm** [comment]
It turns out you need admin approval to get managers/reports so I had to do [a bit of a hack](https://stackoverflow.com/a/67116623/265521) for authentication and then it was easy enough just to do the queries myself.
