### ISSUE TITLE
Get mail url?

### ISSUE THREAD

**Issue by biggytruck** [O365/python-o365#612]
Let's say I use the `get_message` method to search for a particular email with a query. Instead of getting the message body or attachments or whatever is in the email, I want to get the email url so that I can view the original email on Outlook. Is this doable?

**Comment by janscas** [comment]
Sure.

Just pass a [Query ](https://github.com/O365/python-o365#the-query-helper)object with the selected properties you want to be pulled:

```python
query = mailbox.new_query()

quer = query.select('subject', 'web_link', 'etc...')

for message in mailbox.get_messages(query=Query):
    print(message)
```
