### ISSUE TITLE
Python 3.4 & 3.5 not supported

### ISSUE THREAD

**Issue by ATPmtimmerman** [O365/python-o365#614]
PyPi lists this project as supporting Python 3.4 & 3.5, however when I try to run it from a 3.5 install I get errors when it encounters an f-string.  ex: f"hello {name}"

My googling says this feature was added in [PEP498](https://www.python.org/dev/peps/pep-0498/) which was introduced in Python 3.6

Thoughts?

**Comment by janscas** [comment]
Let me fix it! Sorry

**Comment by janscas** [comment]
It should be fixed now in 6df9fb1c79f465f22d621cf024a15f01caa02943

**Comment by ATPmtimmerman** [comment]
Works :)
Thank you!!!
