### ISSUE TITLE
storing token in `Web app based authentication interface`

### ISSUE THREAD

**Issue by Anupam02** [O365/python-o365#615]
Hi ,
   based on the documentation page for `Web app based authentication interface` , 
the first step that is mentioned is :
 `1. First ensure you are using an appropiate TokenBackend to store the auth tokens (See Token storage below).`

 Can someone please help me with where to put the `account.authenticate(credentials, scopes=scopes)` in this case ,
 I tried using `FileSystemTokenBackend` in `/stepone` route , but its not working as expected.
PFB some excerpt from [doc](https://pypi.org/project/O365/)
```
You can authenticate your users in a web environment by following this steps:

First ensure you are using an appropiate TokenBackend to store the auth tokens (See Token storage below).
From a handler redirect the user to the Microsoft login url. Provide a callback. Store the state.
From the callback handler complete the authentication with the state and other data.
```
```
@route('/stepone')
def auth_step_one():

    callback = 'my absolute url to auth_step_two_callback'
    account = Account(credentials)
    url, state = account.con.get_authorization_url(requested_scopes=my_scopes,
                                                   redirect_uri=callback)

    # the state must be saved somewhere as it will be needed later
    my_db.store_state(state) # example...

    return redirect(url)
```

**Comment by janscas** [comment]
For web app authentication using auth_flow_type 'authorization' you don't need to call `account.authenticate`.
The user will authenticate using the url you just provide in step one.

In step two, you will receive the call when the user submit his credentials.

The token backend to use is up to you, but you don't usually want to use a token stored as a file in the filesystem in a production envirenment where multiple instances of your app can run from different machines.

**Comment by Anupam02** [comment]
Hi @janscas , the issue was from my side, the `callback` url was not set to proper `https` , got the issue resolved , thanks for your suggestions.
