### ISSUE TITLE
Connection closed by remote host 

### ISSUE THREAD

**Issue by codifyer** [O365/python-o365#625]
I'm using the O365 package to send emails within a for loop. Inevitably in the 17th iteration I get the following error

`('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))`

The error persists even if I retry msg.send() after couple of seconds.
Strangely, the 18th iteration and the ones after that work fine. (I have around 20-25 elements in the array)
Note:  I have set a 1 sec sleep between each iteration. I even tried 5 sec sleep between iterations but still see the same error. 

Wondering if anyone know why this is happening and whats the way to work around it? I'm guessing it is something to do with rate limits.  Some forums suggest resetting the connection but wasn't sure how to do that in O365 package.

**Comment by janscas** [comment]
No clue, that doesn’t happen to me

**Comment by codifyer** [comment]
Ok, I'm closing this, maybe it was a one off thing. Not happening now.
