### ISSUE TITLE
Get photo from contact

### ISSUE THREAD

**Issue by LarsK1** [O365/python-o365#626]
Hey there,
i saw that it is possible to get a photo from the MS-Graph-API (https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0). But how can I get this data from your awesome library - or isn't that supported yet?
Thanks for your help,
Lars

**Comment by superot** [comment]
For example

get_directory = account.directory()
    get_picture = get_directory.get_user("mail@contonso.com").get_profile_photo()

If you examine the project in detail, many modules are active.

**Comment by LarsK1** [comment]
Thanks for your help. What I was looking for is: contact._get_profile_photo(). But your hint was great!
