### ISSUE TITLE
F-strings in utils/token.py break compatibility with Python >= 3.4

### ISSUE THREAD

**Issue by karl-dv** [O365/python-o365#634]
The O365 package states that it runs on Python >= 3.4.
However, in v2.0.14, a few f-strings have made their way into the source of "utils/token.py", which are not supported prior to Python 3.6.

I wanted to make it easy by forking the project her on GitHub, and issuing a PR for the patch, but then I stumbled on another problem. The GitHub source in the 'master' branch seems to be for v2.0, released on 29 Jul 2019, while pipy.org shows v2.0.14 with a release date of 28 Jan 2021, consistent with what 'pip' installed on my system.

**Comment by lukastribus** [comment]
See:

https://github.com/O365/python-o365/issues/614 https://github.com/O365/python-o365/commit/6df9fb1c79f465f22d621cf024a15f01caa02943


I think on github you have all the commits and code, what's missing is git tags and releases, but the uptodate code is here.

**Comment by janscas** [comment]
I will release a new version this week

**Comment by karl-dv** [comment]
Oh wow. I apologise for having overlooked that.
Thank you both for the quick and swift response. Wishing you all the best...
