### ISSUE TITLE
Token Authentication link does not load

### ISSUE THREAD

**Issue by The-Loud** [O365/python-o365#652]
I have registered my app in the App Registration and have given it the basic auth
Mail.ReadWrite
Mail.Send
User.Read

I've also used delegated access. Basically I've recreated the example app in the README to a T.

I then took the generated client ID and client secret and used the following code:

`credentials = ('code1', 'code2')
account = Account(credentials)
if account.authenticate(scopes=['basic', 'message_all']):
   print('Authenticated!')`

Which then opens up a link. The link will ask me to select a login (I have several for Azure) and I select the one where I registered the app. However, the link does not load. It just ends up at a white screen and never progresses or provides a token.
If I paste the link I get the following response:

```
Something go wrong. Please try again.
Unable to fetch auth token. Error: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/v2.0/token (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))
```

Is this something with the link generation? Perhaps user error? I have tried several browsers (Chrome, Edge, MS Explorer) with no change in behavior.

Thanks.

**Comment by janscas** [comment]
The basic and default flow asks you to visit a link and authenticate. After authenticating the console will wait for a response. Just copy the link after authenticating ( the link on the blank page) and paste it on the console. then hit enter.

**Comment by The-Loud** [comment]
@janscas Thanks for the reply. Upon trying that I get the following error in Python:
Something go wrong. Please try again.
`Unable to fetch auth token. Error: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/v2.0/token (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))`

are there any SSL considerations that I must pass?

**Comment by janscas** [comment]
Are you sure you pasted the complete url? Its something like: 

https://login.microsoftonline.com/common/oauth2/nativeclient?code=Xxxxxxxxx

if you have the “code” part the url is correct.

Are you on mac?

**Comment by The-Loud** [comment]
Yes, it's like that plus a super long code and a state and session state values.

No, I'm not on a Mac. Just plain Win 10

**Comment by janscas** [comment]
I’m also using pycharm and when you paste the url before hitting enter go first to the begining of the line.  Otherwise you will submit just a partial url.

**Comment by nwold** [comment]
I've had this issue in Pycharm. When I paste the URL back into pycharm i get an error or nothing happens...may be because i was submitting a partial URL. When I use the IDLE (Python 3.9 64-bit) it works fine.

**Comment by The-Loud** [comment]
Thanks for the replies. Unfortunately using IDLE did not change the behavior. I continue to receive SSL errors. I did confirm that I was pasting the entire URL. Is there anything else that I can try?

**Comment by The-Loud** [comment]
Upon running this again with an updated Python library, I got this error:

`Unable to fetch auth token. Error: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /common/oauth2/v2.0/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)')))
Something go wrong. Please try again.`

Since there is a self-signed certificate in the chain, is there an option to turn off SSL verify?

**Comment by janscas** [comment]
We use requests behind the scenes so maybe you find something about this searching for the same issue about requests

**Comment by The-Loud** [comment]
@janscas Thanks for the reply. Closing this ticket because the SSL issue is on my side and nothing to do with the O365 library.
