### ISSUE TITLE
Cant get One Drive folder items with client credentials

### ISSUE THREAD

**Issue by Scylla2020** [O365/python-o365#656]
I have set up both application and delegated permissions for `File.ReadWriteAl`l, granted permission, and also exposed the scopes in Azure but cant get my code to list files. My code works if I use the auth flow but not credentials. I thought both need the same permissions.

My code is shown below. How can I get it working?
```
from O365 import Account

credentials = (client,secret)
account = Account(credentials, auth_flow_type='credentials', tenant_id=tenant)
storage = account.storage()

if account.authenticate():
    print('Authenticated!')
    
my_drive = storage.get_default_drive() 
root_folder = my_drive.get_root_folder()

# iterate over the first 25 items on the root folder
for item in root_folder.get_items(limit=25):
    if item.is_folder:
        print(list(item.get_items(2))) # print the first two element on this folder.
```

Everything works if I use this other code below but then it requires user interaction at first, and even when I saved the token file and used `FileSystemTokenBackend` it expired after 90 days. I had thought the token backend takes care of token refreshes since my app was running daily. 

```
from O365 import Account

credentials = (client,secret)
account = Account(credentials)
storage = account.storage()

if account.authenticate(scopes=['onedrive_all',('offline_access')]): #Once u get the token file with refresh token u can remove the if statement to avoid always asking user input
    print('Authenticated!')
    
my_drive = storage.get_default_drive() 
root_folder = my_drive.get_root_folder()

# iterate over the first 25 items on the root folder
for item in root_folder.get_items(limit=25):
    if item.is_folder:
        print(list(item.get_items(2))) # print the first two element on this folder.
```

**Comment by janscas** [comment]
Follow the readme as there are a lot of different setups on the credentials auth flow.
 When using credentials you have to specify a resource: `storage = account.storage(“user@company.com”)`

of course you need to have access to that account…

**Comment by Scylla2020** [comment]
Thanks for the advice. I had more of a read and solved by specifying the email  in `account = Account(credentials, auth_flow_type='credentials', tenant_id=tenant,main_resource=myemail)`

I left `storage = account.storage()` as is because `storage = account.storage(myemail)`  gave an error `TypeError: storage() takes 1 positional argument but 2 were given`
