### ISSUE TITLE
Bug introduced in latest release of tzlocal dependency package

### ISSUE THREAD

**Issue by rena2damas** [O365/python-o365#677]
I believe the latest release for tzlocal (3.0.0) has introduced the error below:

```bash
  File "/usr/local/lib/python3.8/site-packages/O365/message.py", line 690, in send
    self.save_draft()
  File "/usr/local/lib/python3.8/site-packages/O365/message.py", line 1000, in save_draft
    self.__modified = self.protocol.timezone.localize(dt.datetime.now())
AttributeError: 'backports.zoneinfo.ZoneInfo' object has no attribute 'localize'
```

It's a breaking change so it requires a fix as soon as possible.

**Comment by rena2damas** [comment]
Yep there you go, [Replaced pytz with zoneinfo](https://github.com/regebro/tzlocal/commit/ee1354ff97a70e9b0f1649d32010f64133b88aed#diff-32fe862e398ce86af1897d655d00e028f918b7f3c1e1cc079f03eb954637065e).

So ```localize``` is no longer a valid attribute for ```self.protocol.timezone```.

**Comment by janscas** [comment]
PR #671 already merged solved this

**Comment by rena2damas** [comment]
> PR #671 already merged solved this

I see . However, the presented solution does not seem to be working for me since I end up with version ```3.0```.

**Comment by rena2damas** [comment]
Ok nevermind, the solution works, now it makes sense. However the ```pipy``` needs a new release. Therefore the current release still introduces the issue.
