### ISSUE TITLE
HTTPS/SSL For OneDrive

### ISSUE THREAD

**Issue by infosisio** [O365/python-o365#705]
From what I am able to tell, https/ssl are used by default for secure onedrive uploads.

I would like however to ask for a confirmation about this. Thank you.

**Comment by janscas** [comment]
The underlaying lib is requests and nothing is touch regarding the defaults.

**Comment by infosisio** [comment]
I saw the "verify_ssl" option set to True and also the fact that all links around the code are https and not http.

**Comment by janscas** [comment]
True …You have your answer then

**Comment by infosisio** [comment]
Yeah, thanks!
