### ISSUE TITLE
'NoneType' object has no attribute 'get_events'

### ISSUE THREAD

**Issue by stig3** [O365/python-o365#711]
I have used O365 in my project and it works well until few days ago then the follow error raise:
 ```python
events = calendar.get_events(include_recurring=False)
AttributeError: 'NoneType' object has no attribute 'get_events'
```
And I have not change any code, so how can i fix this?

**Comment by janscas** [comment]
As you may notice I haven't got any context from you so I can't help...
The code works for me.

**Comment by stig3** [comment]
Sorry. This error is weird since my old code works well for a long time.
and I have located this problem.
the error code was
```
calendar = schedule.get_calendar(calendar_name='Calendar')
events = calendar.get_events(include_recurring=False)
```
and I replace them with
```
calendar = schedule.get_default_calendar()
events = calendar.get_events(include_recurring=False)
```
then it works again.
still do not know why, but works now.

**Comment by janscas** [comment]
If calendar_name is incorrect somehow, then it will return Null. Try just to get the calendar by id.
