### ISSUE TITLE
Please do not enable DeprecationWarnings by default

### ISSUE THREAD

**Issue by sergei-maertens** [O365/python-o365#713]
The offending code is this one:

https://github.com/O365/python-o365/blob/696f338c5321aae6143386bd2d59f6f9f4493b60/O365/__init__.py#L15

As library consumer, we have `DeprecationWarning` that are emited from other, unrelated libraries that clutter our log output (application + logs). Please follow the pattern from the Python documentation to only emit warnings if end-user have opted in to this:

https://docs.python.org/3.8/library/warnings.html#overriding-the-default-filter

```
import sys

if sys.warnoptions:
    import warnings
    warnings.simplefilter("always", DeprecationWarning)
```

**Comment by janscas** [comment]
Done. thanks for letting me know

**Comment by sergei-maertens** [comment]
Much appreciated! :heart:
