### ISSUE TITLE
'O365.drive.Drive.get_shared_with_me' returns collection of drive items with mime_type None

### ISSUE THREAD

**Issue by MartyX98** [O365/python-o365#715]
Hello!

I'm trying to access an Excel file shared with me with the goal of being able to read and write into it. 

I have no problem accessing .xlsx files stored on my onedrive but when I try to do the same with 'drive.get_shared_with_me' I get files with mime_type None and therefore 'ValueError: This file is not a valid Excel xlsx file.' when trying to open the item as WorkBook. 

I would expect the type to be 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' as it is with files on my own drive. Is that an expected behaviour/output?

My code:
```
from O365 import Account
from O365.excel import WorkBook
import O365

def main():
    with open('data.txt', 'r') as f:
        registered_app_name, registered_app_secret = f.readline(), f.readline()

    account = Account(credentials=(registered_app_name, registered_app_secret),
                      scopes=['files.readwrite.all', 'sites.readwrite.all', 'user.read', 'offline_access'])
    if not account.is_authenticated:
        account = Account((registered_app_name, registered_app_secret))
        account.authenticate(scopes=['files.readwrite.all', 'sites.readwrite.all', 'user.read', 'offline_access'])

    storage = account.storage()  # here we get the storage instance that handles all the storage options.
    my_drive = storage.get_default_drive()
    shared_folder = my_drive.get_shared_with_me(allow_external=True)
    my_folder = my_drive.get_root_folder()

    for item in shared_folder:
        print(item.name)
        if '.xlsx' in item.name:
            print(item.mime_type)
            excel_file = WorkBook(item)

            ws = excel_file.get_worksheets()
            cell = ws[0].get_range('C717')
            print(cell.text)

if __name__ == '__main__':
    main()
```

**Comment by MartyX98** [comment]
After some debugging, it seems I'm unable to interact with any shared file/folder besides listing them using 'my_drive.get_shared_with_me()'. I tried tinkering with correcting mime_type, changing web_url, main_resource, _base_url of the shared_file but nothing helps. Is that intentional?

**Comment by janscas** [comment]
It is not intentional.

**Comment by MartyX98** [comment]
Is there anything I can do to make it work?

**Comment by MartyX98** [comment]
Actually, it was my mistake. I'm closing this issue. Sorry.
