### ISSUE TITLE
How do you remove or clear TO and CC from the message?

### ISSUE THREAD

**Issue by vinhta916** [O365/python-o365#719]
Is there a way to clear or remove To and Cc emails from a reply to or forward message that has been created with those functions?

**Comment by janscas** [comment]
From draft messages yes

**Comment by vinhta916** [comment]
![image](https://user-images.githubusercontent.com/52723156/143292187-d248d2a3-48d6-4902-a5cd-22db333a33e9.png)

Is it in this section? Is there an example on how to remove users from the draft?

**Comment by janscas** [comment]
Message.to.clear()

**Comment by vinhta916** [comment]
> 

I've tried that but the TO and CC emails are still in the reply message when I use the clear() method

**Comment by vinhta916** [comment]
I figured it out with reply.save_draft() after using those methods worked. Then reply.send() will send out the draft
