### ISSUE TITLE
Is it possible to access SharePoint sites pages from this library?

### ISSUE THREAD

**Issue by gjabouley-invn** [O365/python-o365#720]
Hello

we would need to access SharePoint sites pages, to be able to modify page contents. It is possible using this library?
https://docs.microsoft.com/en-us/graph/api/resources/sitepage?view=graph-rest-beta

We could provide an implementation to support this feature in case it is not available, but would need some guidance how to start the development.

**Comment by janscas** [comment]
Not implemented in the library
