### ISSUE TITLE
Update this to tzlocal 4.1 

### ISSUE THREAD

**Issue by R-LIBIN** [O365/python-o365#742]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency co
nflicts.
o365 2.0.16 requires tzlocal<3.*,>=1.5.0, but you have tzlocal 4.1 which is incompatible.

**Comment by janscas** [comment]
Can you test if O365 works as expected with tzlocal 4.1?

**Comment by cfinnberg** [comment]
At least from the tzlocal changes log, it doesn't seem it should affect anything: https://pypi.org/project/tzlocal/#changes
How is the best way to test this?

**Comment by R-LIBIN** [comment]
It works, just would be on works, if updated. Just, to put a note.

**Comment by janscas** [comment]
I'll updated that then.

thanks

**Comment by R-LIBIN** [comment]
I see lot of functions getting deprecated in the current standard. So, to
keep up with the  standards.

**Comment by R-LIBIN** [comment]
++updated

**Comment by janscas** [comment]
Done in cd6cef99148dd13fc91d43aae3fa23041439ba72
