### ISSUE TITLE
Working with groups

### ISSUE THREAD

**Issue by compukab** [O365/python-o365#744]
I noticed that the repo contains some functionality related to groups. But it doesn't seems to be incorporated yet when I run pip install O365.
How would I interact with O365 groups and members of those groups?

**Comment by janscas** [comment]
I'll release a new version to pypi with this funcionality

**Comment by compukab** [comment]
Great!

Thanks

Marc Hoogerwerf

**Comment by janscas** [comment]
Relase done!

**Comment by compukab** [comment]
Super!

Marc Hoogerwerf
