### ISSUE TITLE
Authenticate every time I run script?

### ISSUE THREAD

**Issue by Seanofdead** [O365/python-o365#762]
Hello, I'm constantly having to authenticate each time I run my script as I'm testing is this normal? Or is there any workaround to make the authentication last longer than just 1 time running the script?

`credentials = (CLIENT_ID, SECRET_ID)

protocol = MSGraphProtocol() 

scopes = ['https://graph.microsoft.com/.default'] 
account = Account(credentials, protocol=protocol)

if account.authenticate(scopes=scopes):
   print('Authenticated!')

schedule = account.schedule()
calendar = schedule.get_default_calendar()
events = calendar.get_events(include_recurring=False) 

for event in events:
    print(event)`

This is just the sample code I'm running but it requires me to copy the authentication link each time paste and then paste the new link to move forward.

**Comment by rtpm** [comment]
Probably there' s o365_token.txt file in your directory created once authenticated.

Use it then, so you don't need to reauthenticate.

`token_backend = FileSystemTokenBackend(token_path='', token_filename='o365_token.txt')
account = Account(credentials, token_backend=token_backend)`

**Comment by janscas** [comment]
You need to add offline_access permission in order to have some time between authentications. See the docs

**Comment by agn-7** [comment]
@janscas How can I set the `offline_access`? Is it enabled by appending `basic` to the scopes?!

**Comment by janscas** [comment]
> @janscas How can I set the `offline_access`? Is it enabled by appending `basic` to the scopes?!

By adding that keyword to the scopes. Yes ‘basic’ adds that as well.
