### ISSUE TITLE
Resource Channels is being replaced with Users

### ISSUE THREAD

**Issue by Krukosz** [O365/python-o365#774]
Found bug in utils.py, created pull request 

https://github.com/O365/python-o365/pull/773

When accessing channel's messages, library replaces "channels" endpoint with "users". I commented out these problematic lines, but i don't know where this elif was used, so it has to be reviewed.

**Comment by hcallen** [comment]
Your pull request seems like it would break the ability to access Channel threads, Chat messages, and shared mailbox access.

Please describe what you are trying to accomplish and the resource that has an '@' symbol in it.

**Comment by hcallen** [comment]
Fixed with [776](https://github.com/O365/python-o365/pull/776)
