### ISSUE TITLE
python's input cannot handle long (longer than 1024?) authenticated URL.

### ISSUE THREAD

**Issue by nakatamaho** [O365/python-o365#786]
When authenticating, python-o365 prints "visit the following url to give consent:"
When I visit the URL and then I get the authenticated URL and paste it to the terminal,
then I cannot do anything.

It is because the authenticated URL is longer than 1024 (?) chars, which is too long to handle by input().
https://github.com/O365/python-o365/blob/master/O365/utils/consent.py
----
def consent_input_token(consent_url):
    print('Visit the following url to give consent:')
    print(consent_url)

    return input('Paste the authenticated url here:\n')
-----
Unfortunately, input('Paste the authenticated url here:\n') cannot handle the URL longer than 1024 or so.

A naive workaround is to paste the authenticated URL to a file, then ask the user to input the file name as follows;
-----------
import sys
def consent_input_token(consent_url):
    print('Visit the following url to give consent:')
    print(consent_url)

    _file=input('Paste input the file including authentified url:\n')
    with open(_file) as f:
        for line in f:
            a=line
            break
    return a
----------------
at least it worked for me, but not a solution.

**Comment by janscas** [comment]
Python input does not have a 1024 char limit.

Maybe is something related to the place where you are submitting the input. For example if you are using the pycharm terminal, then you need to move the cursor to the first char before hitting enter in order to input the url.

Also if you are on Mac check this: https://github.com/O365/python-o365/issues/268

**Comment by nakatamaho** [comment]
You're right. Thanks. On Linux, I could proceed, and on Mac, I cannot paste as described in #268.
