### ISSUE TITLE
Getting a SyntaxError when trying to get Token

### ISSUE THREAD

**Issue by olaor** [O365/python-o365#79]
I have followed the Connection howto, and this is what happens.

Code:
#!/usr/bin/env python
from O365 import Connection, FluentInbox
Connection.oauth2("lots of numbers with - in there as well", "very long password with special characters", store_token=True)

Runtime:

$ python fetchcal.py 
Please open https://login.microsoftonline.com/common/oauth2/v2.0/authorize
Enter the full result url: https://outlook.office.com/owa/?code=looooong_string&state=redacted&session_state=redacted
Traceback (most recent call last):
  File "fetchcal.py", line 7, in <module>
    Connection.oauth2("redacted", "redacted", store_token=True)
  File "/usr/local/lib/python2.7/dist-packages/O365/connection.py", line 153, in oauth2
    auth_resp = input('Enter the full result url: ')
  File "<string>", line 1
The URL
         ^
SyntaxError: invalid syntax

This happens because python 2.7 input() and Python 3 input is not the same... I changed it to raw_input and it worked like a charm.

**Comment by Narcolapser** [comment]
Hey @roycem90 can you give this a look? I've never managed to get OAuth to work. ^^;

**Comment by roycem90** [comment]
Thanks @olaor, i will update the it to work on both versions :)

**Comment by roycem90** [comment]
this is fixed on the pre 1.0 version

and O365 v1.0 used python 3.4+
