### ISSUE TITLE
How can I get an event by its object_id and then delete it?

### ISSUE THREAD

**Issue by agn-7** [O365/python-o365#802]
Actually, I want to create and save an event in ms-calendar and then I want to delete it. Thus, I can store the event_id using `object_id` via the `event.object_id`. Now, I am going to delete that event using its `object_id`. My question is how I can find an event using its ID or object_id by `.get_events()` method? I expected it could be a possibility to get an event for example by a query and `object_id` and then delete the event.

Thank you in advance.

**Comment by janscas** [comment]
you can pass the event object_id to get_event to retrieve the event.
