### ISSUE TITLE
get_item_by_path not working ''Resource not found for the segment 'root:General'."

### ISSUE THREAD

**Issue by jeroenvermunt** [O365/python-o365#842]
The issue is strange, it should be simple but for some reason it is not working.

I want to use the following method to open a file instance:

````
my_drive =  storage.get_drive(drive_id)

file = my_drive.get_item_by_path('General/SomeFolder/SomeFile.xlsx')

400 Client Error: Bad Request for url: https://graph.microsoft.com/beta/users/{account}/drives/{drive_id}/root:General/SomeFolder/SomeFile.xlsx | Error Message: Resource not found for the segment 'root:General'
````

However, I got the following workaround:

````
def get_folder_by_name(folder, name):
    for child in folder.get_child_folders():
        if child.name == name:
            return child
        
def get_item_by_name(folder, name):
    for child in folder.get_items():
        if child.name == name:
            return child
        
general_folder = get_folder_by_name(marketing_sales, 'General')
child_folder = get_folder_by_name(general_folder, 'SomeFolder')
file = get_item_by_name(child_folder, 'SomeFile.xlsx')
````

The workaround works perfectly fine. And gives the expected outcome of using `my_drive.get_item_by_path` directly.

Any idea how this is not working?

**Comment by janscas** [comment]
I don't really know and I currently have no time to investigate any further

**Comment by alejcas** [comment]
Maybe the "root;" thing doesn't need to be into that request. I'm not sure however

**Comment by dekiesel** [comment]
The issue is that the path needs to start with a slash.

This doesn't work
`drive.get_item_by_path("folder1/folder2")`

This works:
`drive.get_item_by_path("/folder1/folder2")`

o365 could prepend a slash if the path doesn't start with a slash. Let me know if you want a pr.

**Comment by alejcas** [comment]
Are you sure this is true for all cases? If its the root path? 

If this is the case, PR is very welvome

**Comment by dekiesel** [comment]
https://learn.microsoft.com/en-us/graph/api/driveitem-get?view=graph-rest-1.0&tabs=http

```
GET /drives/{drive-id}/items/{item-id}
GET /drives/{drive-id}/root:/{item-path}
GET /groups/{group-id}/drive/items/{item-id}
GET /groups/{group-id}/drive/root:/{item-path}
GET /me/drive/items/{item-id}
GET /me/drive/root:/{item-path}
GET /sites/{site-id}/drive/items/{item-id}
GET /sites/{site-id}/drive/root:/{item-path}
GET /sites/{site-id}/lists/{list-id}/items/{item-id}/driveItem
GET /users/{user-id}/drive/items/{item-id}
GET /users/{user-id}/drive/root:/{item-path}
```

It seems to be the case. I'll create a PR
