### ISSUE TITLE
Delegated mailbox

### ISSUE THREAD

**Issue by darryllane** [O365/python-o365#85]
Does the lib support the use of delegated mailboxes? I cant seem to find anything that suggests it does.

**Comment by Narcolapser** [comment]
I don't believe so. When I first created this library that feature wasn't available. Now it is. If you interested you could try implementing it yourself, the doc to read is here: https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference

I can't make any promises on when I'd be able to get to it.

**Comment by hellbe** [comment]
@darryllane not sure exactly what the distinction between shared and delegated mailboxes is, but I've added some some support for shared mailboxes: see latest commits on master and https://github.com/O365/python-o365#support-for-shared-mailboxes

**Comment by darryllane** [comment]
Great @hellbe , just for ref. A shared mailbox is a mailbox that allows multiple users to use the mailbox aswell as monitor it. Delegated boxes are boxes that someone has granted permission to access from your own account.

**Comment by janscas** [comment]
Shared mailboxes and delegated maiboxes are both available in 1.0
