### ISSUE TITLE
HTTPError: 403 Client Error: Forbidden for url: Error Message: Access is denied. Check credentials and try again.

### ISSUE THREAD

**Issue by yogansh-zestl** [O365/python-o365#855]
Hi @janscas 

I'm using "credentials" auth_flow_type. I get authenticated and I'm also able to connect to the Inbox using mailbox = account.mailbox(resource='myemail'). But when i try to call the mailbox.get_messages(). I get the following error -- requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/users/sniffthis@zvolv.com/mailFolders/Inbox/messages?%24top=25 | Error Message: Access is denied. Check credentials and try again.
I Also verified I have enabled Mail.Read and Mail.Send in App Permissions
I have checked my credentials are correct also I'm getting authenticated. But still can't access my mails. Can you please help me out on this if you have any idea why this might be happening.

Thank You

**Comment by griseau** [comment]
Hey @yogansh-zestl , I'm having the same error, how did you manage to fix it ? 
thanks

**Comment by rathishkumar** [comment]
I am facing similar issue. Could you please share how did you fixed? @griseau @yogansh-zestl

**Comment by HendrikZe** [comment]
Any updates on this? Just faced the same error today and not yet sure how to fix it.

**Comment by alejcas** [comment]
> I just figured that i had the wrong permissions set in the Azure Portal. As i am using `auth_flow_type='credentials'` I need to set _**Application Permissions**_ instead of Delegated permissions, as also stated correctly in the docs.
> 
> After changing my permissions to Application permissions everything worked fine. So in case your facing a similar error message, double check your choosing permission correctly for the way you're accessing the api.
> 
> <img alt="image" width="1485" src="https://private-user-images.githubusercontent.com/27962057/303280586-fd9ae474-a430-4046-8ae4-03e66e06553f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDA0MDIsIm5iZiI6MTcwNzQwMDEwMiwicGF0aCI6Ii8yNzk2MjA1Ny8zMDMyODA1ODYtZmQ5YWU0NzQtYTQzMC00MDQ2LThhZTQtMDNlNjZlMDY1NTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA4VDEzNDgyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZWFhMDM0ZGI4OWMzNThjNmFkZjc1ZjhlNTZmZWJlMTQzZjg3YWUwYjFjNDQ0YWY2ODFlNWE2NTgxNzA0OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.twpaiwdCQhw45VFh35-OE6DgUsQp4DxNbeVbIiU16H4">

Great that you figure it out!
