### ISSUE TITLE
Error Message: The tenant for tenant guid .. does not exist.

### ISSUE THREAD

**Issue by dsuch** [O365/python-o365#859]
Hello,

I am using o365 v. 2.0.21.

I would like to discuss once more the issues from tickets #542, #757 and #765.

@janscas - in all of these cases you are, essentially, saying that the message from Azure is clear, the tenant does not exist.

I understand what the message says but I am not sure how to reconcile it with the fact that the self-contained code below does obtain a token and this token is valid.

Yet, when it comes to using this token in the context of a specific resource, the "tenant for tenant guid .. does not exist" error still occurs.

What I observe is this:

* If I use an obviously invalid tenant ID, I do not get a token at all
* Regardless of whether I use a tenant ID as a GUID or as a domain name (as below), I get the same message pointing to a GUID

The second point is curious because Azure can apparently resolve hello.onmicrosoft to a GUID but then it says that a tenant does not exist for this GUID.

This makes me wonder what is actually meant by "the tenant" in the error message.

* Is that the name of the directory that I am using? If yes, then I am not sure how to interpret this message at all.
* Is that the name of the resource that "the tenant" means?

Thank you for your library and for your insights on how to approach this case.

```python
from O365 import Account

scopes = ['https://graph.microsoft.com/.default']

client_id = 'my-client-id'
secret_value = 'my-secret-value'
tenant_id = 'hello.onmicrosoft.com' # I also tried to use a GUID here
resource = 'hello@example.com'

credentials = (client_id, secret_value)

account = Account(credentials, auth_flow_type='credentials', tenant_id=tenant_id)
account.authenticate(scopes=scopes)

# At this point the token backend has a token so the tenant ID must have be valid above

mailbox = account.mailbox(resource=resource)
messages = mailbox.get_messages()
```

```
Traceback (most recent call last):
  File "hello.py", line 18, in <module>
    messages = mailbox.get_messages()
  File "/home/dsuch/projects/zatosource-zato/3.2/code/lib/python3.8/site-packages/O365/mailbox.py", line 212, in get_messages
    response = self.con.get(url, params=params)
  File "/home/dsuch/projects/zatosource-zato/3.2/code/lib/python3.8/site-packages/O365/connection.py", line 847, in get
    return self.oauth_request(url, 'get', params=params, **kwargs)
  File "/home/dsuch/projects/zatosource-zato/3.2/code/lib/python3.8/site-packages/O365/connection.py", line 836, in oauth_request
    return self._internal_request(self.session, url, method, **kwargs)
  File "/home/dsuch/projects/zatosource-zato/3.2/code/lib/python3.8/site-packages/O365/connection.py", line 798, in _internal_request
    raise HTTPError('{} | Error Message: {}'.format(e.args[0], error_message), response=response) from None
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://graph.microsoft.com/v1.0/users/hello@example.com/messages?%24top=25 | Error Message: The tenant for tenant guid '1111-2222-333-444' does not exist.
```

**Comment by janscas** [comment]
Yeah, I thing you are right, unfortunately I don't think I can help here.

Error messages from MS Graph api are (in my experience) too generic and sometimes misleading.

The problem is that I can't tell where's the issue. I mean O365 is just calling the MS Graph endpoints and returning that message from the graph api, also, as noted in the many issues you pointed that seems to fail on every endpoint so ... I sincerely don't know what's going on here.

Furthermore I only use authorization auth flow type and that never fails with that kind of errors.

So (just speculating here) maybe some permission is missing from the azure app, or maybe some admin configuration prevents this usage or else. The fact is this calls to MS Graph should work or fail whether you use O365 or not.

**Comment by janscas** [comment]
> Other than that, I just do not have any idea what was going on as the message from Azure was really difficult to comprehend.

Yeah, they tend to deliver bad error messages
