### ISSUE TITLE
Issue using O365 in Azure: Result: Failure Exception: OSError: [Errno 30] Read-only file system: 'o365_token.txt' 

### ISSUE THREAD

**Issue by jeroenvermunt** [O365/python-o365#869]
Hi there, I am running a script using O365 locally. However, I have now deployed it to the cloud.

It seems like the authentication method does not immediately work in the cloud. I am not really experienced with these type of issues, so I am posting it here in the hopes that anyone can help. It likely has to something to do with the permissions regarding the o365_token.txt file.

This is the full traceback, any suggestions to try?

````
Result: Failure Exception: OSError: [Errno 30] Read-only file system: 'o365_token.txt' Stack: File "/azure-functions-
host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 448, in _handle__invocation_request call_result = 
await self._loop.run_in_executor( File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, 
**self.kwargs) File "/azure-functions-host/workers/python/3.9/LINUX/X64/azure_functions_worker/dispatcher.py", line 691, in 
_run_sync_func return ExtensionManager.get_sync_invocation_wrapper(context, File "/azure-functions-
host/workers/python/3.9/LINUX/X64/azure_functions_worker/extension.py", line 215, in _raw_invocation_wrapper result = 
function(**args) File "/home/site/wwwroot/process-log/__init__.py", line 14, in main main_database_entries(test=False) File 
"/home/site/wwwroot/.python_packages/lib/site-packages/hph_functions/database_entries.py", line 915, in main MS_graph_v2 = 
MSGraphAPI_v2('my_account.nl') File "/home/site/wwwroot/.python_packages/lib/site-
packages/hph_functions/resources/onedrive_api.py", line 1005, in __init__ self.account.authenticate(scopes=self.config['scope']) File 
"/home/site/wwwroot/.python_packages/lib/site-packages/O365/account.py", line 121, in authenticate return 
self.con.request_token(None, requested_scopes=scopes) File "/home/site/wwwroot/.python_packages/lib/site-
packages/O365/connection.py", line 561, in request_token self.token_backend.save_token() File 
"/home/site/wwwroot/.python_packages/lib/site-packages/O365/utils/token.py", line 258, in save_token with self.token_path.open('w') 
as token_file: File "/usr/local/lib/python3.9/pathlib.py", line 1252, in open return io.open(self, mode, buffering, encoding, errors, 
newline, File "/usr/local/lib/python3.9/pathlib.py", line 1120, in _opener return self._accessor.open(self, flags, mode)
````

**Comment by janscas** [comment]
The default token backend writes a file to the disk. If you don’t have that, use another token backend.

**Comment by jeroenvermunt** [comment]
Thanks for pointing me in the right direction. I created a simple TokenBackend like so:

````
class SimpleTokenBackend(BaseTokenBackend):

    def load_token(self):
        return self.token

    def save_token(self):
        pass
````

This works. What's yet unclear to me is are the security or practical implications of this type of implementation.

**Comment by janscas** [comment]
At some point yes…. But it’s completely up to you. If you deployed the app somewhere where there’s no filesystem available, then you have to set the appropriate token backend: like EnvTokenBackend to store the token in an environment variable, or a database token backend, etc…

**Comment by lakshmipython** [comment]
**How to use refresh token in Get request once actual token expired in python**

I have a scenario where i need to connect onedrive and get all folders and inside files information, so for that i registered app in azure to get tenat id and client id etc...

i'm successfully login and able to get folders and files information, but i have have around 8k+ folders and inside files so i'm getting token expire time after 1 to 2 hours getting that error, i have refresh token also but not sure how can i use that token in GET request

here i'm pasting the code can anyone please suggest how to use that, in my code i'm creating bin file in that have both access_token and refresh_token

`TENANT_ID = '111*********f5d4'
CLIENT_ID = '7c0*************5517'

AUTHORITY = 'https://login.microsoftonline.com/' + TENANT_ID
ENDPOINT = 'https://graph.microsoft.com/v1.0'
base_url = 'https://graph.microsoft.com/v1.0/'
SCOPES = [
    'Files.ReadWrite.All',
    'Sites.ReadWrite.All',
    'User.Read',
    'User.ReadBasic.All'
]

cache = msal.SerializableTokenCache()

if os.path.exists('token_cache.bin'):
    cache.deserialize(open('token_cache.bin', 'r').read())

atexit.register(lambda: open('token_cache.bin', 'w').write(cache.serialize()) if cache.has_state_changed else None)

app = msal.PublicClientApplication(CLIENT_ID, authority=AUTHORITY, token_cache=cache)

accounts = app.get_accounts()
result = None
if len(accounts) > 0:
    result = app.acquire_token_silent(SCOPES, account=accounts[0])

if result is None:
    flow = app.initiate_device_flow(scopes=SCOPES)
    if 'user_code' not in flow:
        raise Exception('Failed to create device flow')

    print(flow['message'])

    result = app.acquire_token_by_device_flow(flow)

if 'access_token' in result:
    parent = base_url +'/drives/!FJ9b********************BnEOcC-mq/root:/Box_Migration/Product Images - SHARE'
    link = parent+":/children"
    while True:
        rGetCh = requests.get(link, headers={'Authorization': 'Bearer ' + result['access_token']})
        data=rGetCh.json()['value']
        for itemm in data:
            file_id =itemm['name']
            print(file_id)
            endpoint=base_url + f'/drives/b!FJ9b********************BnEOcC-mq/root:/Box_Migration/****uct I888ages - SHARE/{file_id}:/children'
            response_data= requests.get(endpoint,headers={'Authorization': 'Bearer ' + result['access_token']})
            print(response_data)
            json_data =response_data.json()
            #print(json_data)
       
            with open('new_Refresh_token.json', 'a+') as fout:
                fout.write(json.dumps(json_data,indent = 4,default=str))
                fout.write(',\n')
                fout.close()       
        for ch in rGetCh.json()["value"]:
            # Looping through the current list of children
            chName = urllib.parse.quote(ch["name"].encode('utf8'))
            chPath = parent + "/" + chName

        if "@odata.nextLink" in rGetCh.json():  # if this is in the response, there are more children
            link =  rGetCh.json()["@odata.nextLink"]
        else:
           break

else:
    raise Exception('no access token in result')`

here we have 2 GET request one for to get folders information and other for file information

please it is very high priority can any one suggest/help/idea
