### ISSUE TITLE
Question - PR for tasks/todo on MS Graph

### ISSUE THREAD

**Issue by RogerSelwyn** [O365/python-o365#873]
I'm interested to know if you would accept a PR for a partial addition of tasks/todo on MS Graph api. The end points look quite different from the O365 api, so I think it will need new classes based on if someone is using Graph.

I need to be able to enumerate and get details of todo lists and the items on them, plus create new tasks. This is the minimum I would intend to create.

**Comment by janscas** [comment]
Don't know what you really mean by that.
The graph endpoints are what we are targeting in O365 so it should be the same endpoints.

There is already a a Task - Todo implementation:

https://github.com/O365/python-o365/blob/master/O365/tasks.py

**Comment by RogerSelwyn** [comment]
Thanks for getting back to me.

For Tasks/Todo in account.tasks, there is a specific exclusion for Graph. It only does O365. 

As far as I can see account.tasks points at tasks.ToDo. Todo.list_folders() uses a url ending in `/taskfolders`.  If I use this query in graph explorer `https://graph.microsoft.com/v1.0/me/taskfolders` I get the following response:

```
{
    "error": {
        "code": "Request_ResourceNotFound",
        "message": "Resource 'taskfolders' does not exist or one of its queried reference-property objects are not present.",
        "innerError": {
            "date": "2022-11-11T11:29:55",
            "request-id": "238aec15-28b0-4ecc-8c47-69d7d6ed8920",
            "client-request-id": "296b1fff-661f-60ca-7647-9fb75b2a2184"
        }
    }
}
```

I think the right query is `https://graph.microsoft.com/v1.0/me/todo/lists`.

I'm not 100% familiar with your code, so it maybe I have constructed the url wrong.

**Comment by janscas** [comment]
Ok I know now what you mean:

```python
# inside account.py
def tasks(self, *, resource=''):
        """ Get an instance to read information from Microsoft ToDo """

        if not isinstance(self.protocol, MSOffice365Protocol):
            raise RuntimeError(
                'todo api only works on Microsoft Office 365 API')

        from .tasks import ToDo
        return ToDo(parent=self, main_resource=resource)
```

**Comment by janscas** [comment]
Yes, you can implement that and even return a different object from this `tasks` method if the protocol is `MSGraphProtocol`.

Thanks

**Comment by RogerSelwyn** [comment]
I'd propose to use a new set of classes within tasks.py, that can then be built on. No idea how complex this is, but I'll probably give it a go next week.

**Comment by RogerSelwyn** [comment]
PR here - https://github.com/O365/python-o365/pull/874

**Comment by RogerSelwyn** [comment]
Closed when the PR was merged.
