### ISSUE TITLE
Authentication fail at step two

### ISSUE THREAD

**Issue by AmoghSilaparasetti** [O365/python-o365#878]
I am using flask example to see if authentication works but the error on log returns the error shown on the log pic.
![image](https://user-images.githubusercontent.com/106341282/202510097-cef03eb4-31cb-4f9f-bf46-04be17afe0df.png)
![image](https://user-images.githubusercontent.com/106341282/202510194-0dc7c723-c423-4219-b175-38e16b99aee5.png)

Authstepone end point gives a valid url

**Comment by janscas** [comment]
The error says you are using http instead of https. This has nothing to do with O365

**Comment by AmoghSilaparasetti** [comment]
I'm relatively new to to this but I tried https in the endpoint and it gives me 'This site can’t provide a secure connection' error. 

![image](https://user-images.githubusercontent.com/106341282/202727123-65b88d17-830d-44a3-8ece-79da6edfd9f6.png)

The verified link is https
![image](https://user-images.githubusercontent.com/106341282/202727241-000020dc-48d6-4df4-ac10-8dfe27ff0029.png)

**Comment by AmoghSilaparasetti** [comment]
Update:- I have copied the authorized link and pasted in code to see if it works for step_two endpoint. The step_two endpoiint works succesfully. But I want to take the url from step_one response and save it as a variable, which is an issue as I can't save it when I enter the step_two endpoint.

**Comment by janscas** [comment]
use a database or something like that

**Comment by AmoghSilaparasetti** [comment]
Currently I have found an alternative. I have been using global list variable to store values and user interaction to enter authorized link without changing code. For now it's fine. Thanks for your help though.
