### ISSUE TITLE
Can't send a message with OAuth2 enabled

### ISSUE THREAD

**Issue by jrpvt** [O365/python-o365#89]
First off, this repository is absolutely brilliant.  The basic Message and Inbox classes work perfectly with basic auth.  This saved me so much time working between Python and the O365 API so thank you!

A question about OAuth2.  How is the OAuth2 authentication (Connection object now) handled in the Message class?

With OAuth2 setup (following the readme steps), I'm able to retrieve a message and its contents using FluentInbox.  However, I can't get the Message class to actually send a message.  No errors are displayed but no message is ever sent from the O365 account.  Any help would be awesome.

**Comment by roycem90** [comment]
You can use `FluentMessage.send` to send message, it is working now
