### ISSUE TITLE
error in getting calanders

### ISSUE THREAD

**Issue by nauman-pucit** [O365/python-o365#90]
schedule = Schedule(self.office_email, self.office_password)
result = schedule.getCalendars()

Error: 'str' object is not callable

**Comment by nauman-pucit** [comment]
@Narcolapser  Thanks for response. I have tried this but when I call  schedule.getCalendars()
it on line 33 of schedule.py it gives error "Authentication For this account must be using OAuth"

**Comment by nauman-pucit** [comment]
Is there anyone who can help me here?

**Comment by roycem90** [comment]
no more relevent as non OAuth is no longer support

please use OAuth with v1.0 of the library
