### ISSUE TITLE
[Bug] can not update Table show_headers and show_totals of Table

### ISSUE THREAD

**Issue by bfcs** [O365/python-o365#937]
in excel.py -> Table -> update(), if show_headers or show_totals is False, then it won't be added into request, suppose to change to 
```python
  if show_headers is not None:
      ...
```

<img width="793" alt="image" src="https://user-images.githubusercontent.com/52602045/219908136-206f5983-6f57-4a4f-91f4-b7d166f0cb59.png">

**Comment by janscas** [comment]
Can you make a PR fixing it? Thanks

**Comment by bfcs** [comment]
I am glad to

**Comment by janscas** [comment]
Thanks!
