### ISSUE TITLE
Resulting eml file generated via message.save_as_eml() not readable by macOS Outlook client

### ISSUE THREAD

**Issue by fruiti-lewis** [O365/python-o365#940]
Hello, great work on the library btw - I'm having the following issue:

Saving a message that contains a PDF attachment via the message.save_as_eml() creates a file that is readable by the macOS Mail client / macOS Preview but not by the macOS Outlook client (version 16.70)

When the eml file is opened with Outlook it won't display the attachments and shows the following at the top of the message:

`ml>`

and the bottom of the message:

`--_000_17C8B936F6054ED690A5A44D9AB162DBfruitiapp_-- --_004_17C8B936F6054ED690A5A44D9AB162DBfruitiapp_ Content-Type: `

Almost looks like the header / html tags are being cut off?

I suspect this is to do with macOS Outlook more than anything but to double check my code:

`
inbox.get_messages()
  for m in messages:
    m.save_as_eml("some-file.eml")
`

**Comment by janscas** [comment]
The eml contents are set by ms graph. So nothing to do with this library

**Comment by fruiti-lewis** [comment]
thanks for this quick response @janscas after a bit more digging looks like this is do with line endings. So yup nothing on the library/api side, keep up the good work 👍🏻
