### ISSUE TITLE
Remove __init__.py from tests directory

### ISSUE THREAD

**Issue by owenlamont** [O365/python-o365#966]
Can we remove the ```__init__.py``` from the tests directory so it isn't a module? Usually that isn't necessary and it is the one error I get when I try to convert the PyPi package to a conda package which I'd love to get on conda-forge.

**Comment by kwilsonmg** [comment]
@janscas if you're okay with this, I could do a PR easily enough to help out.

**Comment by kwilsonmg** [comment]
@janscas PR filed. :)

**Comment by owenlamont** [comment]
Thanks @kwilsonmg !
