### ISSUE TITLE
Cant import O365

### ISSUE THREAD

**Issue by bitcoinbrisbane** [O365/python-o365#969]
Ive got troubles getting started with a basic read email from the example.  It doesnt like my import.

```bash
pip3 install O365
```

```python
from O365 import Account

app_id = 'test'
secret = 'test'
credentials = (app_id, secret)

account = Account(credentials)
m = account.new_message()
m.to.add('lucas@example.org')
m.subject = 'Testing!'
m.body = "George Best quote: I've stopped drinking, but only while I'm asleep."
m.send()
```

![image](https://github.com/O365/python-o365/assets/8411406/185ea4b5-053c-467c-a3e2-73ff483f823e)

**Comment by janscas** [comment]
It should work, maybe you are running from other venv where the package is installed?

**Comment by kwilsonmg** [comment]
I do believe that this is most likely what janscas wrote about, @bitcoinbrisbane . Please check your local config. If this is resolved, please do close the issue.

**Comment by janscas** [comment]
Yeah, closing this... it's too old.
