### ISSUE TITLE
Issue with zoneinfo.ZoneInfo

### ISSUE THREAD

**Issue by Dawwee27** [O365/python-o365#972]
Hi, I use o365 lib in three projects. In first two I don't have issue with reply. But in the third I have issue with reply. My app check the mailbox every 5 min and its searches for something in the message via regex and if doesnt find anything, it should reply to the message. But I get error:  'zoneinfo.ZoneInfo' object has no attribute 'localize'.
It also does it when forwarding.
Have any of you dealt with a similar problem?

thank you

**Comment by DavidDobrovolny** [comment]
Had the same issue. Fixed it by downgrading `tzlocal` from 5.x to 4.x.

**Comment by Dawwee27** [comment]
Thank you it works for me :)

**Comment by sebastianmanger** [comment]
This probably relates to https://github.com/O365/python-o365/commit/6c379aaaccc07da9cf554ac97719c4e1b87035ff
