### ISSUE TITLE
How to get mailboxSettings values?

### ISSUE THREAD

**Issue by sdelgadoc** [O365/python-o365#975]
I have searched all over the code, and couldn't find a way to get the timeZone property on the mailboxSettings, which you can get with the following call:

`GET /me/mailboxSettings/timeZone`

You can find the documentation for the mailboxSettings here.
https://learn.microsoft.com/en-us/graph/api/resources/mailboxsettings?view=graph-rest-1.0

Any input on how to pull the information would be much appreciated.

**Comment by janscas** [comment]
It's possible but not yet implemented

**Comment by sdelgadoc** [comment]
Thank you, @janscas. Is another property implemented in a similar way that I could refer to in order to create a pull request (PR) for adding the timeZone property?

**Comment by janscas** [comment]
Sorry there's already a MailboxSettings class in https://github.com/O365/python-o365/blob/master/O365/mailbox.py

See there what you want to add or change
