### ISSUE TITLE
Instead of using object_id maybe use ical_uid for Calendar.get_event()

### ISSUE THREAD

**Issue by yegorsb** [O365/python-o365#976]
I am working a project at work to synchronize several calendars that we are using.
One thing that I found out from working with Microsoft Calendar Event Objects is that the object_id isn't unique if there are multiple events overlapping the same day and time frame.
I had to adjust my code to run a for loop to be able to find the right event based on ical_uid instead of the object_id. 

Thoughts about including a search option for get_event based on ical_uid or object_id in a future release?

**Comment by janscas** [comment]
I don't know if this is possible but anyway don't expect anything unless someone sends a PR with this changes
