### ISSUE TITLE
Use python-0365 with an existing access token (oauth is delegated to another component)

### ISSUE THREAD

**Issue by lionpeloux** [O365/python-o365#983]
Hello,

I am building a small streamlit app to help agents send complex templated emails.

I've set-up my streamlit app with the [msal-streamlit-authentication](https://github.com/mstaal/msal_streamlit_authentication) widget so users from my organization can log with their account.

When a user logs, I got its access token from the `msal-streamlit-authentication` widget.
From there, I did not find a way to use the capabilities of `python-0365` to read/write/send emails for the user's account.

Can some one point me how to start ? Is there a way to define an `Account `with a `client_id `and an existing token ?

Thanks !

**Comment by janscas** [comment]
Yes of course, just set the token backend to point where the token data is.

Also instance the account with the client_id , etc...

**Comment by lionpeloux** [comment]
Ok. 
My problem now is that I don't know what needs to be in the token object that is requiered by the TokenBakend.

Do you have a json schema for this ? For instance, do I need to specify the `refresh_token` ? Is it optional ? What about the `expires_in` or `ext_expires_in` ?

This is the informations I get back from the `msal-streamlit-authentication` widget inside my `streamlit` app after successfully logged-in :
```json
{
"authority":"https://login.microsoftonline.com/1e71a412-cdf9-.../"
"uniqueId":"f809778d-598b-..."
"tenantId":"1e71a412-cdf9-f36df6e5c428"
"scopes":[...]
"account":{...}
"idToken":"eyJ0eXAiOiJKV1QiL..."
"idTokenClaims":{...}
"accessToken":"eyJ0eXAiOiJKV1QiLCJub..."
"fromCache":false
"expiresOn":"2023-06-28T10:20:45.000Z"
"correlationId":"ab4a1746-..."
"requestId":"2f5bd415-..."
"extExpiresOn":"2023-06-28T11:29:05.000Z"
"familyId":""
"tokenType":"Bearer"
"state":""
"cloudGraphHostName":""
"msGraphHost":""
"fromNativeBroker":false
}
```
And this is the persisted token I got when I use oauth from `python-O365` within a console project :
```json
{
 "token_type": "Bearer",
 "scope": [
  "profile",
  "openid",
  "email",
  "https://graph.microsoft.com/Calendars.ReadWrite",
  "https://graph.microsoft.com/Calendars.ReadWrite.Shared",
  "https://graph.microsoft.com/Contacts.ReadWrite",
  "https://graph.microsoft.com/Contacts.ReadWrite.Shared",
  "https://graph.microsoft.com/Mail.ReadWrite",
  "https://graph.microsoft.com/Mail.ReadWrite.Shared",
  "https://graph.microsoft.com/Mail.Send",
  "https://graph.microsoft.com/Mail.Send.Shared",
  "https://graph.microsoft.com/User.Read"
 ],
 "expires_in": 3724,
 "ext_expires_in": 3724,
 "access_token": "eyJ0eXAiOiJKV1...",
 "refresh_token": "0.AS8AEqRxHvnN9k...",
 "expires_at": 1687728646.671638
}
```

**Comment by lionpeloux** [comment]
Ok, I suppose you get an [authenticationresult](https://learn.microsoft.com/en-us/dotnet/api/microsoft.identity.client.authenticationresult?view=msal-dotnet-latest) object in the bakckground.

But that still does not tell me what you expect exactly from the token file ?

**Comment by janscas** [comment]
Check ma graph docs

**Comment by lionpeloux** [comment]
Ok, I finally made it by providing a token with an empty refresh token string :

``` python
token = {
        "token_type": login_token["tokenType"],
        "scope": login_token["scopes"],
        "access_token": login_token["accessToken"],
        "refresh_token": "", # requiered by python-O365
    }
```

**Comment by janscas** [comment]
closing this
